/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RootRouteImport } from './routes/root'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ItemsTreeRouteImport } from './routes/items.tree'
import { Route as ItemsTableRouteImport } from './routes/items.table'
import { Route as ItemsKanbanRouteImport } from './routes/items.kanban'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ProjectsProjectIdTemporalRouteImport } from './routes/projects.$projectId.temporal'
import { Route as ProjectsProjectIdSpecificationsRouteImport } from './routes/projects.$projectId.specifications'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as ProjectsProjectIdScenarioActivityRouteImport } from './routes/projects.$projectId.scenario-activity'
import { Route as ProjectsProjectIdFeaturesRouteImport } from './routes/projects.$projectId.features'
import { Route as ProjectsProjectIdEquivalenceRouteImport } from './routes/projects.$projectId.equivalence'
import { Route as ProjectsProjectIdContractsRouteImport } from './routes/projects.$projectId.contracts'
import { Route as ProjectsProjectIdComplianceRouteImport } from './routes/projects.$projectId.compliance'
import { Route as ProjectsProjectIdAgentsRouteImport } from './routes/projects.$projectId.agents'
import { Route as ProjectsProjectIdAdrsRouteImport } from './routes/projects.$projectId.adrs'
import { Route as ProjectsProjectIdViewsWireframeRouteImport } from './routes/projects.$projectId.views.wireframe'
import { Route as ProjectsProjectIdViewsWebhooksRouteImport } from './routes/projects.$projectId.views.webhooks'
import { Route as ProjectsProjectIdViewsTestSuitesRouteImport } from './routes/projects.$projectId.views.test-suites'
import { Route as ProjectsProjectIdViewsTestRunsRouteImport } from './routes/projects.$projectId.views.test-runs'
import { Route as ProjectsProjectIdViewsTestCasesRouteImport } from './routes/projects.$projectId.views.test-cases'
import { Route as ProjectsProjectIdViewsTestRouteImport } from './routes/projects.$projectId.views.test'
import { Route as ProjectsProjectIdViewsSecurityRouteImport } from './routes/projects.$projectId.views.security'
import { Route as ProjectsProjectIdViewsQaDashboardRouteImport } from './routes/projects.$projectId.views.qa-dashboard'
import { Route as ProjectsProjectIdViewsProcessRouteImport } from './routes/projects.$projectId.views.process'
import { Route as ProjectsProjectIdViewsProblemRouteImport } from './routes/projects.$projectId.views.problem'
import { Route as ProjectsProjectIdViewsPerformanceRouteImport } from './routes/projects.$projectId.views.performance'
import { Route as ProjectsProjectIdViewsMonitoringRouteImport } from './routes/projects.$projectId.views.monitoring'
import { Route as ProjectsProjectIdViewsJourneyRouteImport } from './routes/projects.$projectId.views.journey'
import { Route as ProjectsProjectIdViewsIntegrationsRouteImport } from './routes/projects.$projectId.views.integrations'
import { Route as ProjectsProjectIdViewsInfrastructureRouteImport } from './routes/projects.$projectId.views.infrastructure'
import { Route as ProjectsProjectIdViewsFeatureRouteImport } from './routes/projects.$projectId.views.feature'
import { Route as ProjectsProjectIdViewsDomainRouteImport } from './routes/projects.$projectId.views.domain'
import { Route as ProjectsProjectIdViewsDependencyRouteImport } from './routes/projects.$projectId.views.dependency'
import { Route as ProjectsProjectIdViewsDataflowRouteImport } from './routes/projects.$projectId.views.dataflow'
import { Route as ProjectsProjectIdViewsDatabaseRouteImport } from './routes/projects.$projectId.views.database'
import { Route as ProjectsProjectIdViewsCoverageRouteImport } from './routes/projects.$projectId.views.coverage'
import { Route as ProjectsProjectIdViewsConfigurationRouteImport } from './routes/projects.$projectId.views.configuration'
import { Route as ProjectsProjectIdViewsCodeRouteImport } from './routes/projects.$projectId.views.code'
import { Route as ProjectsProjectIdViewsArchitectureRouteImport } from './routes/projects.$projectId.views.architecture'
import { Route as ProjectsProjectIdViewsApiRouteImport } from './routes/projects.$projectId.views.api'
import { Route as ProjectsProjectIdViewsViewTypeRouteImport } from './routes/projects.$projectId.views.$viewType'
import { Route as ProjectsProjectIdFeaturesFeatureIdRouteImport } from './routes/projects.$projectId.features.$featureId'
import { Route as ProjectsProjectIdContractsContractIdRouteImport } from './routes/projects.$projectId.contracts.$contractId'
import { Route as ProjectsProjectIdAdrsAdrIdRouteImport } from './routes/projects.$projectId.adrs.$adrId'
import { Route as ProjectsProjectIdViewsViewTypeItemIdRouteImport } from './routes/projects.$projectId.views.$viewType.$itemId'
import { Route as ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRouteImport } from './routes/projects.$projectId.features.$featureId.scenarios.$scenarioId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RootRoute = RootRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ItemsTreeRoute = ItemsTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsTableRoute = ItemsTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsKanbanRoute = ItemsKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => ItemsRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdTemporalRoute =
  ProjectsProjectIdTemporalRouteImport.update({
    id: '/temporal',
    path: '/temporal',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSpecificationsRoute =
  ProjectsProjectIdSpecificationsRouteImport.update({
    id: '/specifications',
    path: '/specifications',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdScenarioActivityRoute =
  ProjectsProjectIdScenarioActivityRouteImport.update({
    id: '/scenario-activity',
    path: '/scenario-activity',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdFeaturesRoute =
  ProjectsProjectIdFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdEquivalenceRoute =
  ProjectsProjectIdEquivalenceRouteImport.update({
    id: '/equivalence',
    path: '/equivalence',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdContractsRoute =
  ProjectsProjectIdContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdComplianceRoute =
  ProjectsProjectIdComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdAgentsRoute = ProjectsProjectIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdAdrsRoute = ProjectsProjectIdAdrsRouteImport.update({
  id: '/adrs',
  path: '/adrs',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdViewsWireframeRoute =
  ProjectsProjectIdViewsWireframeRouteImport.update({
    id: '/views/wireframe',
    path: '/views/wireframe',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsWebhooksRoute =
  ProjectsProjectIdViewsWebhooksRouteImport.update({
    id: '/views/webhooks',
    path: '/views/webhooks',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsTestSuitesRoute =
  ProjectsProjectIdViewsTestSuitesRouteImport.update({
    id: '/views/test-suites',
    path: '/views/test-suites',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsTestRunsRoute =
  ProjectsProjectIdViewsTestRunsRouteImport.update({
    id: '/views/test-runs',
    path: '/views/test-runs',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsTestCasesRoute =
  ProjectsProjectIdViewsTestCasesRouteImport.update({
    id: '/views/test-cases',
    path: '/views/test-cases',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsTestRoute =
  ProjectsProjectIdViewsTestRouteImport.update({
    id: '/views/test',
    path: '/views/test',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsSecurityRoute =
  ProjectsProjectIdViewsSecurityRouteImport.update({
    id: '/views/security',
    path: '/views/security',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsQaDashboardRoute =
  ProjectsProjectIdViewsQaDashboardRouteImport.update({
    id: '/views/qa-dashboard',
    path: '/views/qa-dashboard',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsProcessRoute =
  ProjectsProjectIdViewsProcessRouteImport.update({
    id: '/views/process',
    path: '/views/process',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsProblemRoute =
  ProjectsProjectIdViewsProblemRouteImport.update({
    id: '/views/problem',
    path: '/views/problem',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsPerformanceRoute =
  ProjectsProjectIdViewsPerformanceRouteImport.update({
    id: '/views/performance',
    path: '/views/performance',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsMonitoringRoute =
  ProjectsProjectIdViewsMonitoringRouteImport.update({
    id: '/views/monitoring',
    path: '/views/monitoring',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsJourneyRoute =
  ProjectsProjectIdViewsJourneyRouteImport.update({
    id: '/views/journey',
    path: '/views/journey',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsIntegrationsRoute =
  ProjectsProjectIdViewsIntegrationsRouteImport.update({
    id: '/views/integrations',
    path: '/views/integrations',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsInfrastructureRoute =
  ProjectsProjectIdViewsInfrastructureRouteImport.update({
    id: '/views/infrastructure',
    path: '/views/infrastructure',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsFeatureRoute =
  ProjectsProjectIdViewsFeatureRouteImport.update({
    id: '/views/feature',
    path: '/views/feature',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsDomainRoute =
  ProjectsProjectIdViewsDomainRouteImport.update({
    id: '/views/domain',
    path: '/views/domain',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsDependencyRoute =
  ProjectsProjectIdViewsDependencyRouteImport.update({
    id: '/views/dependency',
    path: '/views/dependency',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsDataflowRoute =
  ProjectsProjectIdViewsDataflowRouteImport.update({
    id: '/views/dataflow',
    path: '/views/dataflow',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsDatabaseRoute =
  ProjectsProjectIdViewsDatabaseRouteImport.update({
    id: '/views/database',
    path: '/views/database',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsCoverageRoute =
  ProjectsProjectIdViewsCoverageRouteImport.update({
    id: '/views/coverage',
    path: '/views/coverage',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsConfigurationRoute =
  ProjectsProjectIdViewsConfigurationRouteImport.update({
    id: '/views/configuration',
    path: '/views/configuration',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsCodeRoute =
  ProjectsProjectIdViewsCodeRouteImport.update({
    id: '/views/code',
    path: '/views/code',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsArchitectureRoute =
  ProjectsProjectIdViewsArchitectureRouteImport.update({
    id: '/views/architecture',
    path: '/views/architecture',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsApiRoute =
  ProjectsProjectIdViewsApiRouteImport.update({
    id: '/views/api',
    path: '/views/api',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsViewTypeRoute =
  ProjectsProjectIdViewsViewTypeRouteImport.update({
    id: '/views/$viewType',
    path: '/views/$viewType',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdFeaturesFeatureIdRoute =
  ProjectsProjectIdFeaturesFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => ProjectsProjectIdFeaturesRoute,
  } as any)
const ProjectsProjectIdContractsContractIdRoute =
  ProjectsProjectIdContractsContractIdRouteImport.update({
    id: '/$contractId',
    path: '/$contractId',
    getParentRoute: () => ProjectsProjectIdContractsRoute,
  } as any)
const ProjectsProjectIdAdrsAdrIdRoute =
  ProjectsProjectIdAdrsAdrIdRouteImport.update({
    id: '/$adrId',
    path: '/$adrId',
    getParentRoute: () => ProjectsProjectIdAdrsRoute,
  } as any)
const ProjectsProjectIdViewsViewTypeItemIdRoute =
  ProjectsProjectIdViewsViewTypeItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => ProjectsProjectIdViewsViewTypeRoute,
  } as any)
const ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRoute =
  ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRouteImport.update({
    id: '/scenarios/$scenarioId',
    path: '/scenarios/$scenarioId',
    getParentRoute: () => ProjectsProjectIdFeaturesFeatureIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof RootRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/home': typeof HomeRoute
  '/index': typeof IndexRoute
  '/items': typeof ItemsRouteWithChildren
  '/landing': typeof LandingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/items/kanban': typeof ItemsKanbanRoute
  '/items/table': typeof ItemsTableRoute
  '/items/tree': typeof ItemsTreeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/adrs': typeof ProjectsProjectIdAdrsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/compliance': typeof ProjectsProjectIdComplianceRoute
  '/projects/$projectId/contracts': typeof ProjectsProjectIdContractsRouteWithChildren
  '/projects/$projectId/equivalence': typeof ProjectsProjectIdEquivalenceRoute
  '/projects/$projectId/features': typeof ProjectsProjectIdFeaturesRouteWithChildren
  '/projects/$projectId/scenario-activity': typeof ProjectsProjectIdScenarioActivityRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/specifications': typeof ProjectsProjectIdSpecificationsRoute
  '/projects/$projectId/temporal': typeof ProjectsProjectIdTemporalRoute
  '/projects/$projectId/adrs/$adrId': typeof ProjectsProjectIdAdrsAdrIdRoute
  '/projects/$projectId/contracts/$contractId': typeof ProjectsProjectIdContractsContractIdRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRouteWithChildren
  '/projects/$projectId/views/$viewType': typeof ProjectsProjectIdViewsViewTypeRouteWithChildren
  '/projects/$projectId/views/api': typeof ProjectsProjectIdViewsApiRoute
  '/projects/$projectId/views/architecture': typeof ProjectsProjectIdViewsArchitectureRoute
  '/projects/$projectId/views/code': typeof ProjectsProjectIdViewsCodeRoute
  '/projects/$projectId/views/configuration': typeof ProjectsProjectIdViewsConfigurationRoute
  '/projects/$projectId/views/coverage': typeof ProjectsProjectIdViewsCoverageRoute
  '/projects/$projectId/views/database': typeof ProjectsProjectIdViewsDatabaseRoute
  '/projects/$projectId/views/dataflow': typeof ProjectsProjectIdViewsDataflowRoute
  '/projects/$projectId/views/dependency': typeof ProjectsProjectIdViewsDependencyRoute
  '/projects/$projectId/views/domain': typeof ProjectsProjectIdViewsDomainRoute
  '/projects/$projectId/views/feature': typeof ProjectsProjectIdViewsFeatureRoute
  '/projects/$projectId/views/infrastructure': typeof ProjectsProjectIdViewsInfrastructureRoute
  '/projects/$projectId/views/integrations': typeof ProjectsProjectIdViewsIntegrationsRoute
  '/projects/$projectId/views/journey': typeof ProjectsProjectIdViewsJourneyRoute
  '/projects/$projectId/views/monitoring': typeof ProjectsProjectIdViewsMonitoringRoute
  '/projects/$projectId/views/performance': typeof ProjectsProjectIdViewsPerformanceRoute
  '/projects/$projectId/views/problem': typeof ProjectsProjectIdViewsProblemRoute
  '/projects/$projectId/views/process': typeof ProjectsProjectIdViewsProcessRoute
  '/projects/$projectId/views/qa-dashboard': typeof ProjectsProjectIdViewsQaDashboardRoute
  '/projects/$projectId/views/security': typeof ProjectsProjectIdViewsSecurityRoute
  '/projects/$projectId/views/test': typeof ProjectsProjectIdViewsTestRoute
  '/projects/$projectId/views/test-cases': typeof ProjectsProjectIdViewsTestCasesRoute
  '/projects/$projectId/views/test-runs': typeof ProjectsProjectIdViewsTestRunsRoute
  '/projects/$projectId/views/test-suites': typeof ProjectsProjectIdViewsTestSuitesRoute
  '/projects/$projectId/views/webhooks': typeof ProjectsProjectIdViewsWebhooksRoute
  '/projects/$projectId/views/wireframe': typeof ProjectsProjectIdViewsWireframeRoute
  '/projects/$projectId/views/$viewType/$itemId': typeof ProjectsProjectIdViewsViewTypeItemIdRoute
  '/projects/$projectId/features/$featureId/scenarios/$scenarioId': typeof ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof RootRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/home': typeof HomeRoute
  '/index': typeof IndexRoute
  '/items': typeof ItemsRouteWithChildren
  '/landing': typeof LandingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/items/kanban': typeof ItemsKanbanRoute
  '/items/table': typeof ItemsTableRoute
  '/items/tree': typeof ItemsTreeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/adrs': typeof ProjectsProjectIdAdrsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/compliance': typeof ProjectsProjectIdComplianceRoute
  '/projects/$projectId/contracts': typeof ProjectsProjectIdContractsRouteWithChildren
  '/projects/$projectId/equivalence': typeof ProjectsProjectIdEquivalenceRoute
  '/projects/$projectId/features': typeof ProjectsProjectIdFeaturesRouteWithChildren
  '/projects/$projectId/scenario-activity': typeof ProjectsProjectIdScenarioActivityRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/specifications': typeof ProjectsProjectIdSpecificationsRoute
  '/projects/$projectId/temporal': typeof ProjectsProjectIdTemporalRoute
  '/projects/$projectId/adrs/$adrId': typeof ProjectsProjectIdAdrsAdrIdRoute
  '/projects/$projectId/contracts/$contractId': typeof ProjectsProjectIdContractsContractIdRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRouteWithChildren
  '/projects/$projectId/views/$viewType': typeof ProjectsProjectIdViewsViewTypeRouteWithChildren
  '/projects/$projectId/views/api': typeof ProjectsProjectIdViewsApiRoute
  '/projects/$projectId/views/architecture': typeof ProjectsProjectIdViewsArchitectureRoute
  '/projects/$projectId/views/code': typeof ProjectsProjectIdViewsCodeRoute
  '/projects/$projectId/views/configuration': typeof ProjectsProjectIdViewsConfigurationRoute
  '/projects/$projectId/views/coverage': typeof ProjectsProjectIdViewsCoverageRoute
  '/projects/$projectId/views/database': typeof ProjectsProjectIdViewsDatabaseRoute
  '/projects/$projectId/views/dataflow': typeof ProjectsProjectIdViewsDataflowRoute
  '/projects/$projectId/views/dependency': typeof ProjectsProjectIdViewsDependencyRoute
  '/projects/$projectId/views/domain': typeof ProjectsProjectIdViewsDomainRoute
  '/projects/$projectId/views/feature': typeof ProjectsProjectIdViewsFeatureRoute
  '/projects/$projectId/views/infrastructure': typeof ProjectsProjectIdViewsInfrastructureRoute
  '/projects/$projectId/views/integrations': typeof ProjectsProjectIdViewsIntegrationsRoute
  '/projects/$projectId/views/journey': typeof ProjectsProjectIdViewsJourneyRoute
  '/projects/$projectId/views/monitoring': typeof ProjectsProjectIdViewsMonitoringRoute
  '/projects/$projectId/views/performance': typeof ProjectsProjectIdViewsPerformanceRoute
  '/projects/$projectId/views/problem': typeof ProjectsProjectIdViewsProblemRoute
  '/projects/$projectId/views/process': typeof ProjectsProjectIdViewsProcessRoute
  '/projects/$projectId/views/qa-dashboard': typeof ProjectsProjectIdViewsQaDashboardRoute
  '/projects/$projectId/views/security': typeof ProjectsProjectIdViewsSecurityRoute
  '/projects/$projectId/views/test': typeof ProjectsProjectIdViewsTestRoute
  '/projects/$projectId/views/test-cases': typeof ProjectsProjectIdViewsTestCasesRoute
  '/projects/$projectId/views/test-runs': typeof ProjectsProjectIdViewsTestRunsRoute
  '/projects/$projectId/views/test-suites': typeof ProjectsProjectIdViewsTestSuitesRoute
  '/projects/$projectId/views/webhooks': typeof ProjectsProjectIdViewsWebhooksRoute
  '/projects/$projectId/views/wireframe': typeof ProjectsProjectIdViewsWireframeRoute
  '/projects/$projectId/views/$viewType/$itemId': typeof ProjectsProjectIdViewsViewTypeItemIdRoute
  '/projects/$projectId/features/$featureId/scenarios/$scenarioId': typeof ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RootRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/home': typeof HomeRoute
  '/index': typeof IndexRoute
  '/items': typeof ItemsRouteWithChildren
  '/landing': typeof LandingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/items/kanban': typeof ItemsKanbanRoute
  '/items/table': typeof ItemsTableRoute
  '/items/tree': typeof ItemsTreeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/adrs': typeof ProjectsProjectIdAdrsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/compliance': typeof ProjectsProjectIdComplianceRoute
  '/projects/$projectId/contracts': typeof ProjectsProjectIdContractsRouteWithChildren
  '/projects/$projectId/equivalence': typeof ProjectsProjectIdEquivalenceRoute
  '/projects/$projectId/features': typeof ProjectsProjectIdFeaturesRouteWithChildren
  '/projects/$projectId/scenario-activity': typeof ProjectsProjectIdScenarioActivityRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/specifications': typeof ProjectsProjectIdSpecificationsRoute
  '/projects/$projectId/temporal': typeof ProjectsProjectIdTemporalRoute
  '/projects/$projectId/adrs/$adrId': typeof ProjectsProjectIdAdrsAdrIdRoute
  '/projects/$projectId/contracts/$contractId': typeof ProjectsProjectIdContractsContractIdRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRouteWithChildren
  '/projects/$projectId/views/$viewType': typeof ProjectsProjectIdViewsViewTypeRouteWithChildren
  '/projects/$projectId/views/api': typeof ProjectsProjectIdViewsApiRoute
  '/projects/$projectId/views/architecture': typeof ProjectsProjectIdViewsArchitectureRoute
  '/projects/$projectId/views/code': typeof ProjectsProjectIdViewsCodeRoute
  '/projects/$projectId/views/configuration': typeof ProjectsProjectIdViewsConfigurationRoute
  '/projects/$projectId/views/coverage': typeof ProjectsProjectIdViewsCoverageRoute
  '/projects/$projectId/views/database': typeof ProjectsProjectIdViewsDatabaseRoute
  '/projects/$projectId/views/dataflow': typeof ProjectsProjectIdViewsDataflowRoute
  '/projects/$projectId/views/dependency': typeof ProjectsProjectIdViewsDependencyRoute
  '/projects/$projectId/views/domain': typeof ProjectsProjectIdViewsDomainRoute
  '/projects/$projectId/views/feature': typeof ProjectsProjectIdViewsFeatureRoute
  '/projects/$projectId/views/infrastructure': typeof ProjectsProjectIdViewsInfrastructureRoute
  '/projects/$projectId/views/integrations': typeof ProjectsProjectIdViewsIntegrationsRoute
  '/projects/$projectId/views/journey': typeof ProjectsProjectIdViewsJourneyRoute
  '/projects/$projectId/views/monitoring': typeof ProjectsProjectIdViewsMonitoringRoute
  '/projects/$projectId/views/performance': typeof ProjectsProjectIdViewsPerformanceRoute
  '/projects/$projectId/views/problem': typeof ProjectsProjectIdViewsProblemRoute
  '/projects/$projectId/views/process': typeof ProjectsProjectIdViewsProcessRoute
  '/projects/$projectId/views/qa-dashboard': typeof ProjectsProjectIdViewsQaDashboardRoute
  '/projects/$projectId/views/security': typeof ProjectsProjectIdViewsSecurityRoute
  '/projects/$projectId/views/test': typeof ProjectsProjectIdViewsTestRoute
  '/projects/$projectId/views/test-cases': typeof ProjectsProjectIdViewsTestCasesRoute
  '/projects/$projectId/views/test-runs': typeof ProjectsProjectIdViewsTestRunsRoute
  '/projects/$projectId/views/test-suites': typeof ProjectsProjectIdViewsTestSuitesRoute
  '/projects/$projectId/views/webhooks': typeof ProjectsProjectIdViewsWebhooksRoute
  '/projects/$projectId/views/wireframe': typeof ProjectsProjectIdViewsWireframeRoute
  '/projects/$projectId/views/$viewType/$itemId': typeof ProjectsProjectIdViewsViewTypeItemIdRoute
  '/projects/$projectId/features/$featureId/scenarios/$scenarioId': typeof ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/dashboard'
    | '/graph'
    | '/home'
    | '/index'
    | '/items'
    | '/landing'
    | '/projects'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/items/$itemId'
    | '/items/kanban'
    | '/items/table'
    | '/items/tree'
    | '/projects/$projectId'
    | '/projects/$projectId/adrs'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/compliance'
    | '/projects/$projectId/contracts'
    | '/projects/$projectId/equivalence'
    | '/projects/$projectId/features'
    | '/projects/$projectId/scenario-activity'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/specifications'
    | '/projects/$projectId/temporal'
    | '/projects/$projectId/adrs/$adrId'
    | '/projects/$projectId/contracts/$contractId'
    | '/projects/$projectId/features/$featureId'
    | '/projects/$projectId/views/$viewType'
    | '/projects/$projectId/views/api'
    | '/projects/$projectId/views/architecture'
    | '/projects/$projectId/views/code'
    | '/projects/$projectId/views/configuration'
    | '/projects/$projectId/views/coverage'
    | '/projects/$projectId/views/database'
    | '/projects/$projectId/views/dataflow'
    | '/projects/$projectId/views/dependency'
    | '/projects/$projectId/views/domain'
    | '/projects/$projectId/views/feature'
    | '/projects/$projectId/views/infrastructure'
    | '/projects/$projectId/views/integrations'
    | '/projects/$projectId/views/journey'
    | '/projects/$projectId/views/monitoring'
    | '/projects/$projectId/views/performance'
    | '/projects/$projectId/views/problem'
    | '/projects/$projectId/views/process'
    | '/projects/$projectId/views/qa-dashboard'
    | '/projects/$projectId/views/security'
    | '/projects/$projectId/views/test'
    | '/projects/$projectId/views/test-cases'
    | '/projects/$projectId/views/test-runs'
    | '/projects/$projectId/views/test-suites'
    | '/projects/$projectId/views/webhooks'
    | '/projects/$projectId/views/wireframe'
    | '/projects/$projectId/views/$viewType/$itemId'
    | '/projects/$projectId/features/$featureId/scenarios/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/dashboard'
    | '/graph'
    | '/home'
    | '/index'
    | '/items'
    | '/landing'
    | '/projects'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/items/$itemId'
    | '/items/kanban'
    | '/items/table'
    | '/items/tree'
    | '/projects/$projectId'
    | '/projects/$projectId/adrs'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/compliance'
    | '/projects/$projectId/contracts'
    | '/projects/$projectId/equivalence'
    | '/projects/$projectId/features'
    | '/projects/$projectId/scenario-activity'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/specifications'
    | '/projects/$projectId/temporal'
    | '/projects/$projectId/adrs/$adrId'
    | '/projects/$projectId/contracts/$contractId'
    | '/projects/$projectId/features/$featureId'
    | '/projects/$projectId/views/$viewType'
    | '/projects/$projectId/views/api'
    | '/projects/$projectId/views/architecture'
    | '/projects/$projectId/views/code'
    | '/projects/$projectId/views/configuration'
    | '/projects/$projectId/views/coverage'
    | '/projects/$projectId/views/database'
    | '/projects/$projectId/views/dataflow'
    | '/projects/$projectId/views/dependency'
    | '/projects/$projectId/views/domain'
    | '/projects/$projectId/views/feature'
    | '/projects/$projectId/views/infrastructure'
    | '/projects/$projectId/views/integrations'
    | '/projects/$projectId/views/journey'
    | '/projects/$projectId/views/monitoring'
    | '/projects/$projectId/views/performance'
    | '/projects/$projectId/views/problem'
    | '/projects/$projectId/views/process'
    | '/projects/$projectId/views/qa-dashboard'
    | '/projects/$projectId/views/security'
    | '/projects/$projectId/views/test'
    | '/projects/$projectId/views/test-cases'
    | '/projects/$projectId/views/test-runs'
    | '/projects/$projectId/views/test-suites'
    | '/projects/$projectId/views/webhooks'
    | '/projects/$projectId/views/wireframe'
    | '/projects/$projectId/views/$viewType/$itemId'
    | '/projects/$projectId/features/$featureId/scenarios/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/dashboard'
    | '/graph'
    | '/home'
    | '/index'
    | '/items'
    | '/landing'
    | '/projects'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/items/$itemId'
    | '/items/kanban'
    | '/items/table'
    | '/items/tree'
    | '/projects/$projectId'
    | '/projects/$projectId/adrs'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/compliance'
    | '/projects/$projectId/contracts'
    | '/projects/$projectId/equivalence'
    | '/projects/$projectId/features'
    | '/projects/$projectId/scenario-activity'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/specifications'
    | '/projects/$projectId/temporal'
    | '/projects/$projectId/adrs/$adrId'
    | '/projects/$projectId/contracts/$contractId'
    | '/projects/$projectId/features/$featureId'
    | '/projects/$projectId/views/$viewType'
    | '/projects/$projectId/views/api'
    | '/projects/$projectId/views/architecture'
    | '/projects/$projectId/views/code'
    | '/projects/$projectId/views/configuration'
    | '/projects/$projectId/views/coverage'
    | '/projects/$projectId/views/database'
    | '/projects/$projectId/views/dataflow'
    | '/projects/$projectId/views/dependency'
    | '/projects/$projectId/views/domain'
    | '/projects/$projectId/views/feature'
    | '/projects/$projectId/views/infrastructure'
    | '/projects/$projectId/views/integrations'
    | '/projects/$projectId/views/journey'
    | '/projects/$projectId/views/monitoring'
    | '/projects/$projectId/views/performance'
    | '/projects/$projectId/views/problem'
    | '/projects/$projectId/views/process'
    | '/projects/$projectId/views/qa-dashboard'
    | '/projects/$projectId/views/security'
    | '/projects/$projectId/views/test'
    | '/projects/$projectId/views/test-cases'
    | '/projects/$projectId/views/test-runs'
    | '/projects/$projectId/views/test-suites'
    | '/projects/$projectId/views/webhooks'
    | '/projects/$projectId/views/wireframe'
    | '/projects/$projectId/views/$viewType/$itemId'
    | '/projects/$projectId/features/$featureId/scenarios/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RootRoute: typeof RootRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  DashboardRoute: typeof DashboardRoute
  GraphRoute: typeof GraphRoute
  HomeRoute: typeof HomeRoute
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  LandingRoute: typeof LandingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/items/tree': {
      id: '/items/tree'
      path: '/tree'
      fullPath: '/items/tree'
      preLoaderRoute: typeof ItemsTreeRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/table': {
      id: '/items/table'
      path: '/table'
      fullPath: '/items/table'
      preLoaderRoute: typeof ItemsTableRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/kanban': {
      id: '/items/kanban'
      path: '/kanban'
      fullPath: '/items/kanban'
      preLoaderRoute: typeof ItemsKanbanRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/temporal': {
      id: '/projects/$projectId/temporal'
      path: '/temporal'
      fullPath: '/projects/$projectId/temporal'
      preLoaderRoute: typeof ProjectsProjectIdTemporalRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/specifications': {
      id: '/projects/$projectId/specifications'
      path: '/specifications'
      fullPath: '/projects/$projectId/specifications'
      preLoaderRoute: typeof ProjectsProjectIdSpecificationsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/scenario-activity': {
      id: '/projects/$projectId/scenario-activity'
      path: '/scenario-activity'
      fullPath: '/projects/$projectId/scenario-activity'
      preLoaderRoute: typeof ProjectsProjectIdScenarioActivityRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/features': {
      id: '/projects/$projectId/features'
      path: '/features'
      fullPath: '/projects/$projectId/features'
      preLoaderRoute: typeof ProjectsProjectIdFeaturesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/equivalence': {
      id: '/projects/$projectId/equivalence'
      path: '/equivalence'
      fullPath: '/projects/$projectId/equivalence'
      preLoaderRoute: typeof ProjectsProjectIdEquivalenceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/contracts': {
      id: '/projects/$projectId/contracts'
      path: '/contracts'
      fullPath: '/projects/$projectId/contracts'
      preLoaderRoute: typeof ProjectsProjectIdContractsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/compliance': {
      id: '/projects/$projectId/compliance'
      path: '/compliance'
      fullPath: '/projects/$projectId/compliance'
      preLoaderRoute: typeof ProjectsProjectIdComplianceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/agents': {
      id: '/projects/$projectId/agents'
      path: '/agents'
      fullPath: '/projects/$projectId/agents'
      preLoaderRoute: typeof ProjectsProjectIdAgentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/adrs': {
      id: '/projects/$projectId/adrs'
      path: '/adrs'
      fullPath: '/projects/$projectId/adrs'
      preLoaderRoute: typeof ProjectsProjectIdAdrsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/wireframe': {
      id: '/projects/$projectId/views/wireframe'
      path: '/views/wireframe'
      fullPath: '/projects/$projectId/views/wireframe'
      preLoaderRoute: typeof ProjectsProjectIdViewsWireframeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/webhooks': {
      id: '/projects/$projectId/views/webhooks'
      path: '/views/webhooks'
      fullPath: '/projects/$projectId/views/webhooks'
      preLoaderRoute: typeof ProjectsProjectIdViewsWebhooksRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/test-suites': {
      id: '/projects/$projectId/views/test-suites'
      path: '/views/test-suites'
      fullPath: '/projects/$projectId/views/test-suites'
      preLoaderRoute: typeof ProjectsProjectIdViewsTestSuitesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/test-runs': {
      id: '/projects/$projectId/views/test-runs'
      path: '/views/test-runs'
      fullPath: '/projects/$projectId/views/test-runs'
      preLoaderRoute: typeof ProjectsProjectIdViewsTestRunsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/test-cases': {
      id: '/projects/$projectId/views/test-cases'
      path: '/views/test-cases'
      fullPath: '/projects/$projectId/views/test-cases'
      preLoaderRoute: typeof ProjectsProjectIdViewsTestCasesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/test': {
      id: '/projects/$projectId/views/test'
      path: '/views/test'
      fullPath: '/projects/$projectId/views/test'
      preLoaderRoute: typeof ProjectsProjectIdViewsTestRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/security': {
      id: '/projects/$projectId/views/security'
      path: '/views/security'
      fullPath: '/projects/$projectId/views/security'
      preLoaderRoute: typeof ProjectsProjectIdViewsSecurityRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/qa-dashboard': {
      id: '/projects/$projectId/views/qa-dashboard'
      path: '/views/qa-dashboard'
      fullPath: '/projects/$projectId/views/qa-dashboard'
      preLoaderRoute: typeof ProjectsProjectIdViewsQaDashboardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/process': {
      id: '/projects/$projectId/views/process'
      path: '/views/process'
      fullPath: '/projects/$projectId/views/process'
      preLoaderRoute: typeof ProjectsProjectIdViewsProcessRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/problem': {
      id: '/projects/$projectId/views/problem'
      path: '/views/problem'
      fullPath: '/projects/$projectId/views/problem'
      preLoaderRoute: typeof ProjectsProjectIdViewsProblemRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/performance': {
      id: '/projects/$projectId/views/performance'
      path: '/views/performance'
      fullPath: '/projects/$projectId/views/performance'
      preLoaderRoute: typeof ProjectsProjectIdViewsPerformanceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/monitoring': {
      id: '/projects/$projectId/views/monitoring'
      path: '/views/monitoring'
      fullPath: '/projects/$projectId/views/monitoring'
      preLoaderRoute: typeof ProjectsProjectIdViewsMonitoringRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/journey': {
      id: '/projects/$projectId/views/journey'
      path: '/views/journey'
      fullPath: '/projects/$projectId/views/journey'
      preLoaderRoute: typeof ProjectsProjectIdViewsJourneyRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/integrations': {
      id: '/projects/$projectId/views/integrations'
      path: '/views/integrations'
      fullPath: '/projects/$projectId/views/integrations'
      preLoaderRoute: typeof ProjectsProjectIdViewsIntegrationsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/infrastructure': {
      id: '/projects/$projectId/views/infrastructure'
      path: '/views/infrastructure'
      fullPath: '/projects/$projectId/views/infrastructure'
      preLoaderRoute: typeof ProjectsProjectIdViewsInfrastructureRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/feature': {
      id: '/projects/$projectId/views/feature'
      path: '/views/feature'
      fullPath: '/projects/$projectId/views/feature'
      preLoaderRoute: typeof ProjectsProjectIdViewsFeatureRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/domain': {
      id: '/projects/$projectId/views/domain'
      path: '/views/domain'
      fullPath: '/projects/$projectId/views/domain'
      preLoaderRoute: typeof ProjectsProjectIdViewsDomainRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/dependency': {
      id: '/projects/$projectId/views/dependency'
      path: '/views/dependency'
      fullPath: '/projects/$projectId/views/dependency'
      preLoaderRoute: typeof ProjectsProjectIdViewsDependencyRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/dataflow': {
      id: '/projects/$projectId/views/dataflow'
      path: '/views/dataflow'
      fullPath: '/projects/$projectId/views/dataflow'
      preLoaderRoute: typeof ProjectsProjectIdViewsDataflowRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/database': {
      id: '/projects/$projectId/views/database'
      path: '/views/database'
      fullPath: '/projects/$projectId/views/database'
      preLoaderRoute: typeof ProjectsProjectIdViewsDatabaseRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/coverage': {
      id: '/projects/$projectId/views/coverage'
      path: '/views/coverage'
      fullPath: '/projects/$projectId/views/coverage'
      preLoaderRoute: typeof ProjectsProjectIdViewsCoverageRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/configuration': {
      id: '/projects/$projectId/views/configuration'
      path: '/views/configuration'
      fullPath: '/projects/$projectId/views/configuration'
      preLoaderRoute: typeof ProjectsProjectIdViewsConfigurationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/code': {
      id: '/projects/$projectId/views/code'
      path: '/views/code'
      fullPath: '/projects/$projectId/views/code'
      preLoaderRoute: typeof ProjectsProjectIdViewsCodeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/architecture': {
      id: '/projects/$projectId/views/architecture'
      path: '/views/architecture'
      fullPath: '/projects/$projectId/views/architecture'
      preLoaderRoute: typeof ProjectsProjectIdViewsArchitectureRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/api': {
      id: '/projects/$projectId/views/api'
      path: '/views/api'
      fullPath: '/projects/$projectId/views/api'
      preLoaderRoute: typeof ProjectsProjectIdViewsApiRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/$viewType': {
      id: '/projects/$projectId/views/$viewType'
      path: '/views/$viewType'
      fullPath: '/projects/$projectId/views/$viewType'
      preLoaderRoute: typeof ProjectsProjectIdViewsViewTypeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/features/$featureId': {
      id: '/projects/$projectId/features/$featureId'
      path: '/$featureId'
      fullPath: '/projects/$projectId/features/$featureId'
      preLoaderRoute: typeof ProjectsProjectIdFeaturesFeatureIdRouteImport
      parentRoute: typeof ProjectsProjectIdFeaturesRoute
    }
    '/projects/$projectId/contracts/$contractId': {
      id: '/projects/$projectId/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/projects/$projectId/contracts/$contractId'
      preLoaderRoute: typeof ProjectsProjectIdContractsContractIdRouteImport
      parentRoute: typeof ProjectsProjectIdContractsRoute
    }
    '/projects/$projectId/adrs/$adrId': {
      id: '/projects/$projectId/adrs/$adrId'
      path: '/$adrId'
      fullPath: '/projects/$projectId/adrs/$adrId'
      preLoaderRoute: typeof ProjectsProjectIdAdrsAdrIdRouteImport
      parentRoute: typeof ProjectsProjectIdAdrsRoute
    }
    '/projects/$projectId/views/$viewType/$itemId': {
      id: '/projects/$projectId/views/$viewType/$itemId'
      path: '/$itemId'
      fullPath: '/projects/$projectId/views/$viewType/$itemId'
      preLoaderRoute: typeof ProjectsProjectIdViewsViewTypeItemIdRouteImport
      parentRoute: typeof ProjectsProjectIdViewsViewTypeRoute
    }
    '/projects/$projectId/features/$featureId/scenarios/$scenarioId': {
      id: '/projects/$projectId/features/$featureId/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/projects/$projectId/features/$featureId/scenarios/$scenarioId'
      preLoaderRoute: typeof ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRouteImport
      parentRoute: typeof ProjectsProjectIdFeaturesFeatureIdRoute
    }
  }
}

interface ItemsRouteChildren {
  ItemsItemIdRoute: typeof ItemsItemIdRoute
  ItemsKanbanRoute: typeof ItemsKanbanRoute
  ItemsTableRoute: typeof ItemsTableRoute
  ItemsTreeRoute: typeof ItemsTreeRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsItemIdRoute: ItemsItemIdRoute,
  ItemsKanbanRoute: ItemsKanbanRoute,
  ItemsTableRoute: ItemsTableRoute,
  ItemsTreeRoute: ItemsTreeRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

interface ProjectsProjectIdAdrsRouteChildren {
  ProjectsProjectIdAdrsAdrIdRoute: typeof ProjectsProjectIdAdrsAdrIdRoute
}

const ProjectsProjectIdAdrsRouteChildren: ProjectsProjectIdAdrsRouteChildren = {
  ProjectsProjectIdAdrsAdrIdRoute: ProjectsProjectIdAdrsAdrIdRoute,
}

const ProjectsProjectIdAdrsRouteWithChildren =
  ProjectsProjectIdAdrsRoute._addFileChildren(
    ProjectsProjectIdAdrsRouteChildren,
  )

interface ProjectsProjectIdContractsRouteChildren {
  ProjectsProjectIdContractsContractIdRoute: typeof ProjectsProjectIdContractsContractIdRoute
}

const ProjectsProjectIdContractsRouteChildren: ProjectsProjectIdContractsRouteChildren =
  {
    ProjectsProjectIdContractsContractIdRoute:
      ProjectsProjectIdContractsContractIdRoute,
  }

const ProjectsProjectIdContractsRouteWithChildren =
  ProjectsProjectIdContractsRoute._addFileChildren(
    ProjectsProjectIdContractsRouteChildren,
  )

interface ProjectsProjectIdFeaturesFeatureIdRouteChildren {
  ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRoute: typeof ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRoute
}

const ProjectsProjectIdFeaturesFeatureIdRouteChildren: ProjectsProjectIdFeaturesFeatureIdRouteChildren =
  {
    ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRoute:
      ProjectsProjectIdFeaturesFeatureIdScenariosScenarioIdRoute,
  }

const ProjectsProjectIdFeaturesFeatureIdRouteWithChildren =
  ProjectsProjectIdFeaturesFeatureIdRoute._addFileChildren(
    ProjectsProjectIdFeaturesFeatureIdRouteChildren,
  )

interface ProjectsProjectIdFeaturesRouteChildren {
  ProjectsProjectIdFeaturesFeatureIdRoute: typeof ProjectsProjectIdFeaturesFeatureIdRouteWithChildren
}

const ProjectsProjectIdFeaturesRouteChildren: ProjectsProjectIdFeaturesRouteChildren =
  {
    ProjectsProjectIdFeaturesFeatureIdRoute:
      ProjectsProjectIdFeaturesFeatureIdRouteWithChildren,
  }

const ProjectsProjectIdFeaturesRouteWithChildren =
  ProjectsProjectIdFeaturesRoute._addFileChildren(
    ProjectsProjectIdFeaturesRouteChildren,
  )

interface ProjectsProjectIdViewsViewTypeRouteChildren {
  ProjectsProjectIdViewsViewTypeItemIdRoute: typeof ProjectsProjectIdViewsViewTypeItemIdRoute
}

const ProjectsProjectIdViewsViewTypeRouteChildren: ProjectsProjectIdViewsViewTypeRouteChildren =
  {
    ProjectsProjectIdViewsViewTypeItemIdRoute:
      ProjectsProjectIdViewsViewTypeItemIdRoute,
  }

const ProjectsProjectIdViewsViewTypeRouteWithChildren =
  ProjectsProjectIdViewsViewTypeRoute._addFileChildren(
    ProjectsProjectIdViewsViewTypeRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAdrsRoute: typeof ProjectsProjectIdAdrsRouteWithChildren
  ProjectsProjectIdAgentsRoute: typeof ProjectsProjectIdAgentsRoute
  ProjectsProjectIdComplianceRoute: typeof ProjectsProjectIdComplianceRoute
  ProjectsProjectIdContractsRoute: typeof ProjectsProjectIdContractsRouteWithChildren
  ProjectsProjectIdEquivalenceRoute: typeof ProjectsProjectIdEquivalenceRoute
  ProjectsProjectIdFeaturesRoute: typeof ProjectsProjectIdFeaturesRouteWithChildren
  ProjectsProjectIdScenarioActivityRoute: typeof ProjectsProjectIdScenarioActivityRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdSpecificationsRoute: typeof ProjectsProjectIdSpecificationsRoute
  ProjectsProjectIdTemporalRoute: typeof ProjectsProjectIdTemporalRoute
  ProjectsProjectIdViewsViewTypeRoute: typeof ProjectsProjectIdViewsViewTypeRouteWithChildren
  ProjectsProjectIdViewsApiRoute: typeof ProjectsProjectIdViewsApiRoute
  ProjectsProjectIdViewsArchitectureRoute: typeof ProjectsProjectIdViewsArchitectureRoute
  ProjectsProjectIdViewsCodeRoute: typeof ProjectsProjectIdViewsCodeRoute
  ProjectsProjectIdViewsConfigurationRoute: typeof ProjectsProjectIdViewsConfigurationRoute
  ProjectsProjectIdViewsCoverageRoute: typeof ProjectsProjectIdViewsCoverageRoute
  ProjectsProjectIdViewsDatabaseRoute: typeof ProjectsProjectIdViewsDatabaseRoute
  ProjectsProjectIdViewsDataflowRoute: typeof ProjectsProjectIdViewsDataflowRoute
  ProjectsProjectIdViewsDependencyRoute: typeof ProjectsProjectIdViewsDependencyRoute
  ProjectsProjectIdViewsDomainRoute: typeof ProjectsProjectIdViewsDomainRoute
  ProjectsProjectIdViewsFeatureRoute: typeof ProjectsProjectIdViewsFeatureRoute
  ProjectsProjectIdViewsInfrastructureRoute: typeof ProjectsProjectIdViewsInfrastructureRoute
  ProjectsProjectIdViewsIntegrationsRoute: typeof ProjectsProjectIdViewsIntegrationsRoute
  ProjectsProjectIdViewsJourneyRoute: typeof ProjectsProjectIdViewsJourneyRoute
  ProjectsProjectIdViewsMonitoringRoute: typeof ProjectsProjectIdViewsMonitoringRoute
  ProjectsProjectIdViewsPerformanceRoute: typeof ProjectsProjectIdViewsPerformanceRoute
  ProjectsProjectIdViewsProblemRoute: typeof ProjectsProjectIdViewsProblemRoute
  ProjectsProjectIdViewsProcessRoute: typeof ProjectsProjectIdViewsProcessRoute
  ProjectsProjectIdViewsQaDashboardRoute: typeof ProjectsProjectIdViewsQaDashboardRoute
  ProjectsProjectIdViewsSecurityRoute: typeof ProjectsProjectIdViewsSecurityRoute
  ProjectsProjectIdViewsTestRoute: typeof ProjectsProjectIdViewsTestRoute
  ProjectsProjectIdViewsTestCasesRoute: typeof ProjectsProjectIdViewsTestCasesRoute
  ProjectsProjectIdViewsTestRunsRoute: typeof ProjectsProjectIdViewsTestRunsRoute
  ProjectsProjectIdViewsTestSuitesRoute: typeof ProjectsProjectIdViewsTestSuitesRoute
  ProjectsProjectIdViewsWebhooksRoute: typeof ProjectsProjectIdViewsWebhooksRoute
  ProjectsProjectIdViewsWireframeRoute: typeof ProjectsProjectIdViewsWireframeRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAdrsRoute: ProjectsProjectIdAdrsRouteWithChildren,
  ProjectsProjectIdAgentsRoute: ProjectsProjectIdAgentsRoute,
  ProjectsProjectIdComplianceRoute: ProjectsProjectIdComplianceRoute,
  ProjectsProjectIdContractsRoute: ProjectsProjectIdContractsRouteWithChildren,
  ProjectsProjectIdEquivalenceRoute: ProjectsProjectIdEquivalenceRoute,
  ProjectsProjectIdFeaturesRoute: ProjectsProjectIdFeaturesRouteWithChildren,
  ProjectsProjectIdScenarioActivityRoute:
    ProjectsProjectIdScenarioActivityRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdSpecificationsRoute: ProjectsProjectIdSpecificationsRoute,
  ProjectsProjectIdTemporalRoute: ProjectsProjectIdTemporalRoute,
  ProjectsProjectIdViewsViewTypeRoute:
    ProjectsProjectIdViewsViewTypeRouteWithChildren,
  ProjectsProjectIdViewsApiRoute: ProjectsProjectIdViewsApiRoute,
  ProjectsProjectIdViewsArchitectureRoute:
    ProjectsProjectIdViewsArchitectureRoute,
  ProjectsProjectIdViewsCodeRoute: ProjectsProjectIdViewsCodeRoute,
  ProjectsProjectIdViewsConfigurationRoute:
    ProjectsProjectIdViewsConfigurationRoute,
  ProjectsProjectIdViewsCoverageRoute: ProjectsProjectIdViewsCoverageRoute,
  ProjectsProjectIdViewsDatabaseRoute: ProjectsProjectIdViewsDatabaseRoute,
  ProjectsProjectIdViewsDataflowRoute: ProjectsProjectIdViewsDataflowRoute,
  ProjectsProjectIdViewsDependencyRoute: ProjectsProjectIdViewsDependencyRoute,
  ProjectsProjectIdViewsDomainRoute: ProjectsProjectIdViewsDomainRoute,
  ProjectsProjectIdViewsFeatureRoute: ProjectsProjectIdViewsFeatureRoute,
  ProjectsProjectIdViewsInfrastructureRoute:
    ProjectsProjectIdViewsInfrastructureRoute,
  ProjectsProjectIdViewsIntegrationsRoute:
    ProjectsProjectIdViewsIntegrationsRoute,
  ProjectsProjectIdViewsJourneyRoute: ProjectsProjectIdViewsJourneyRoute,
  ProjectsProjectIdViewsMonitoringRoute: ProjectsProjectIdViewsMonitoringRoute,
  ProjectsProjectIdViewsPerformanceRoute:
    ProjectsProjectIdViewsPerformanceRoute,
  ProjectsProjectIdViewsProblemRoute: ProjectsProjectIdViewsProblemRoute,
  ProjectsProjectIdViewsProcessRoute: ProjectsProjectIdViewsProcessRoute,
  ProjectsProjectIdViewsQaDashboardRoute:
    ProjectsProjectIdViewsQaDashboardRoute,
  ProjectsProjectIdViewsSecurityRoute: ProjectsProjectIdViewsSecurityRoute,
  ProjectsProjectIdViewsTestRoute: ProjectsProjectIdViewsTestRoute,
  ProjectsProjectIdViewsTestCasesRoute: ProjectsProjectIdViewsTestCasesRoute,
  ProjectsProjectIdViewsTestRunsRoute: ProjectsProjectIdViewsTestRunsRoute,
  ProjectsProjectIdViewsTestSuitesRoute: ProjectsProjectIdViewsTestSuitesRoute,
  ProjectsProjectIdViewsWebhooksRoute: ProjectsProjectIdViewsWebhooksRoute,
  ProjectsProjectIdViewsWireframeRoute: ProjectsProjectIdViewsWireframeRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RootRoute: RootRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  DashboardRoute: DashboardRoute,
  GraphRoute: GraphRoute,
  HomeRoute: HomeRoute,
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRouteWithChildren,
  LandingRoute: LandingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
