/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as LinksIndexRouteImport } from './routes/links.index'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as GraphIndexRouteImport } from './routes/graph.index'
import { Route as ApiDocsIndexRouteImport } from './routes/api-docs.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ItemsTreeRouteImport } from './routes/items.tree'
import { Route as ItemsKanbanRouteImport } from './routes/items.kanban'
import { Route as ApiSwaggerConfigRouteImport } from './routes/api/swagger-config'
import { Route as ApiSpecRouteImport } from './routes/api/spec'
import { Route as ApiAuthTestRouteImport } from './routes/api/auth-test'
import { Route as ApiDocsSwaggerRouteImport } from './routes/api-docs.swagger'
import { Route as ApiDocsRedocRouteImport } from './routes/api-docs.redoc'
import { Route as MatrixTraceabilityIndexRouteImport } from './routes/matrix.traceability.index'
import { Route as ImpactAnalysisIndexRouteImport } from './routes/impact.analysis.index'
import { Route as EventsTimelineIndexRouteImport } from './routes/events.timeline.index'
import { Route as ProjectsProjectIdViewsWireframeRouteImport } from './routes/projects.$projectId.views.wireframe'
import { Route as ProjectsProjectIdViewsTestRouteImport } from './routes/projects.$projectId.views.test'
import { Route as ProjectsProjectIdViewsFeatureRouteImport } from './routes/projects.$projectId.views.feature'
import { Route as ProjectsProjectIdViewsDatabaseRouteImport } from './routes/projects.$projectId.views.database'
import { Route as ProjectsProjectIdViewsCodeRouteImport } from './routes/projects.$projectId.views.code'
import { Route as ProjectsProjectIdViewsApiRouteImport } from './routes/projects.$projectId.views.api'
import { Route as ProjectsProjectIdViewsViewTypeRouteImport } from './routes/projects.$projectId.views.$viewType'
import { Route as ProjectsProjectIdViewsViewTypeItemIdRouteImport } from './routes/projects.$projectId.views.$viewType.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksIndexRoute = LinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsIndexRoute = ApiDocsIndexRouteImport.update({
  id: '/api-docs/',
  path: '/api-docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsTreeRoute = ItemsTreeRouteImport.update({
  id: '/items/tree',
  path: '/items/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsKanbanRoute = ItemsKanbanRouteImport.update({
  id: '/items/kanban',
  path: '/items/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwaggerConfigRoute = ApiSwaggerConfigRouteImport.update({
  id: '/api/swagger-config',
  path: '/api/swagger-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpecRoute = ApiSpecRouteImport.update({
  id: '/api/spec',
  path: '/api/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTestRoute = ApiAuthTestRouteImport.update({
  id: '/api/auth-test',
  path: '/api/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsSwaggerRoute = ApiDocsSwaggerRouteImport.update({
  id: '/api-docs/swagger',
  path: '/api-docs/swagger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRedocRoute = ApiDocsRedocRouteImport.update({
  id: '/api-docs/redoc',
  path: '/api-docs/redoc',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixTraceabilityIndexRoute = MatrixTraceabilityIndexRouteImport.update({
  id: '/matrix/traceability/',
  path: '/matrix/traceability/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactAnalysisIndexRoute = ImpactAnalysisIndexRouteImport.update({
  id: '/impact/analysis/',
  path: '/impact/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsTimelineIndexRoute = EventsTimelineIndexRouteImport.update({
  id: '/events/timeline/',
  path: '/events/timeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdViewsWireframeRoute =
  ProjectsProjectIdViewsWireframeRouteImport.update({
    id: '/views/wireframe',
    path: '/views/wireframe',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsTestRoute =
  ProjectsProjectIdViewsTestRouteImport.update({
    id: '/views/test',
    path: '/views/test',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsFeatureRoute =
  ProjectsProjectIdViewsFeatureRouteImport.update({
    id: '/views/feature',
    path: '/views/feature',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsDatabaseRoute =
  ProjectsProjectIdViewsDatabaseRouteImport.update({
    id: '/views/database',
    path: '/views/database',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsCodeRoute =
  ProjectsProjectIdViewsCodeRouteImport.update({
    id: '/views/code',
    path: '/views/code',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsApiRoute =
  ProjectsProjectIdViewsApiRouteImport.update({
    id: '/views/api',
    path: '/views/api',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsViewTypeRoute =
  ProjectsProjectIdViewsViewTypeRouteImport.update({
    id: '/views/$viewType',
    path: '/views/$viewType',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdViewsViewTypeItemIdRoute =
  ProjectsProjectIdViewsViewTypeItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => ProjectsProjectIdViewsViewTypeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs/redoc': typeof ApiDocsRedocRoute
  '/api-docs/swagger': typeof ApiDocsSwaggerRoute
  '/api/auth-test': typeof ApiAuthTestRoute
  '/api/spec': typeof ApiSpecRoute
  '/api/swagger-config': typeof ApiSwaggerConfigRoute
  '/items/kanban': typeof ItemsKanbanRoute
  '/items/tree': typeof ItemsTreeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/agents': typeof AgentsIndexRoute
  '/api-docs': typeof ApiDocsIndexRoute
  '/graph': typeof GraphIndexRoute
  '/items': typeof ItemsIndexRoute
  '/links': typeof LinksIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/events/timeline': typeof EventsTimelineIndexRoute
  '/impact/analysis': typeof ImpactAnalysisIndexRoute
  '/matrix/traceability': typeof MatrixTraceabilityIndexRoute
  '/projects/$projectId/views/$viewType': typeof ProjectsProjectIdViewsViewTypeRouteWithChildren
  '/projects/$projectId/views/api': typeof ProjectsProjectIdViewsApiRoute
  '/projects/$projectId/views/code': typeof ProjectsProjectIdViewsCodeRoute
  '/projects/$projectId/views/database': typeof ProjectsProjectIdViewsDatabaseRoute
  '/projects/$projectId/views/feature': typeof ProjectsProjectIdViewsFeatureRoute
  '/projects/$projectId/views/test': typeof ProjectsProjectIdViewsTestRoute
  '/projects/$projectId/views/wireframe': typeof ProjectsProjectIdViewsWireframeRoute
  '/projects/$projectId/views/$viewType/$itemId': typeof ProjectsProjectIdViewsViewTypeItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs/redoc': typeof ApiDocsRedocRoute
  '/api-docs/swagger': typeof ApiDocsSwaggerRoute
  '/api/auth-test': typeof ApiAuthTestRoute
  '/api/spec': typeof ApiSpecRoute
  '/api/swagger-config': typeof ApiSwaggerConfigRoute
  '/items/kanban': typeof ItemsKanbanRoute
  '/items/tree': typeof ItemsTreeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/agents': typeof AgentsIndexRoute
  '/api-docs': typeof ApiDocsIndexRoute
  '/graph': typeof GraphIndexRoute
  '/items': typeof ItemsIndexRoute
  '/links': typeof LinksIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/events/timeline': typeof EventsTimelineIndexRoute
  '/impact/analysis': typeof ImpactAnalysisIndexRoute
  '/matrix/traceability': typeof MatrixTraceabilityIndexRoute
  '/projects/$projectId/views/$viewType': typeof ProjectsProjectIdViewsViewTypeRouteWithChildren
  '/projects/$projectId/views/api': typeof ProjectsProjectIdViewsApiRoute
  '/projects/$projectId/views/code': typeof ProjectsProjectIdViewsCodeRoute
  '/projects/$projectId/views/database': typeof ProjectsProjectIdViewsDatabaseRoute
  '/projects/$projectId/views/feature': typeof ProjectsProjectIdViewsFeatureRoute
  '/projects/$projectId/views/test': typeof ProjectsProjectIdViewsTestRoute
  '/projects/$projectId/views/wireframe': typeof ProjectsProjectIdViewsWireframeRoute
  '/projects/$projectId/views/$viewType/$itemId': typeof ProjectsProjectIdViewsViewTypeItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs/redoc': typeof ApiDocsRedocRoute
  '/api-docs/swagger': typeof ApiDocsSwaggerRoute
  '/api/auth-test': typeof ApiAuthTestRoute
  '/api/spec': typeof ApiSpecRoute
  '/api/swagger-config': typeof ApiSwaggerConfigRoute
  '/items/kanban': typeof ItemsKanbanRoute
  '/items/tree': typeof ItemsTreeRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/api-docs/': typeof ApiDocsIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/links/': typeof LinksIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/events/timeline/': typeof EventsTimelineIndexRoute
  '/impact/analysis/': typeof ImpactAnalysisIndexRoute
  '/matrix/traceability/': typeof MatrixTraceabilityIndexRoute
  '/projects/$projectId/views/$viewType': typeof ProjectsProjectIdViewsViewTypeRouteWithChildren
  '/projects/$projectId/views/api': typeof ProjectsProjectIdViewsApiRoute
  '/projects/$projectId/views/code': typeof ProjectsProjectIdViewsCodeRoute
  '/projects/$projectId/views/database': typeof ProjectsProjectIdViewsDatabaseRoute
  '/projects/$projectId/views/feature': typeof ProjectsProjectIdViewsFeatureRoute
  '/projects/$projectId/views/test': typeof ProjectsProjectIdViewsTestRoute
  '/projects/$projectId/views/wireframe': typeof ProjectsProjectIdViewsWireframeRoute
  '/projects/$projectId/views/$viewType/$itemId': typeof ProjectsProjectIdViewsViewTypeItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs/redoc'
    | '/api-docs/swagger'
    | '/api/auth-test'
    | '/api/spec'
    | '/api/swagger-config'
    | '/items/kanban'
    | '/items/tree'
    | '/projects/$projectId'
    | '/agents'
    | '/api-docs'
    | '/graph'
    | '/items'
    | '/links'
    | '/projects'
    | '/reports'
    | '/search'
    | '/settings'
    | '/events/timeline'
    | '/impact/analysis'
    | '/matrix/traceability'
    | '/projects/$projectId/views/$viewType'
    | '/projects/$projectId/views/api'
    | '/projects/$projectId/views/code'
    | '/projects/$projectId/views/database'
    | '/projects/$projectId/views/feature'
    | '/projects/$projectId/views/test'
    | '/projects/$projectId/views/wireframe'
    | '/projects/$projectId/views/$viewType/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs/redoc'
    | '/api-docs/swagger'
    | '/api/auth-test'
    | '/api/spec'
    | '/api/swagger-config'
    | '/items/kanban'
    | '/items/tree'
    | '/projects/$projectId'
    | '/agents'
    | '/api-docs'
    | '/graph'
    | '/items'
    | '/links'
    | '/projects'
    | '/reports'
    | '/search'
    | '/settings'
    | '/events/timeline'
    | '/impact/analysis'
    | '/matrix/traceability'
    | '/projects/$projectId/views/$viewType'
    | '/projects/$projectId/views/api'
    | '/projects/$projectId/views/code'
    | '/projects/$projectId/views/database'
    | '/projects/$projectId/views/feature'
    | '/projects/$projectId/views/test'
    | '/projects/$projectId/views/wireframe'
    | '/projects/$projectId/views/$viewType/$itemId'
  id:
    | '__root__'
    | '/'
    | '/api-docs/redoc'
    | '/api-docs/swagger'
    | '/api/auth-test'
    | '/api/spec'
    | '/api/swagger-config'
    | '/items/kanban'
    | '/items/tree'
    | '/projects/$projectId'
    | '/agents/'
    | '/api-docs/'
    | '/graph/'
    | '/items/'
    | '/links/'
    | '/projects/'
    | '/reports/'
    | '/search/'
    | '/settings/'
    | '/events/timeline/'
    | '/impact/analysis/'
    | '/matrix/traceability/'
    | '/projects/$projectId/views/$viewType'
    | '/projects/$projectId/views/api'
    | '/projects/$projectId/views/code'
    | '/projects/$projectId/views/database'
    | '/projects/$projectId/views/feature'
    | '/projects/$projectId/views/test'
    | '/projects/$projectId/views/wireframe'
    | '/projects/$projectId/views/$viewType/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRedocRoute: typeof ApiDocsRedocRoute
  ApiDocsSwaggerRoute: typeof ApiDocsSwaggerRoute
  ApiAuthTestRoute: typeof ApiAuthTestRoute
  ApiSpecRoute: typeof ApiSpecRoute
  ApiSwaggerConfigRoute: typeof ApiSwaggerConfigRoute
  ItemsKanbanRoute: typeof ItemsKanbanRoute
  ItemsTreeRoute: typeof ItemsTreeRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  AgentsIndexRoute: typeof AgentsIndexRoute
  ApiDocsIndexRoute: typeof ApiDocsIndexRoute
  GraphIndexRoute: typeof GraphIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  LinksIndexRoute: typeof LinksIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  EventsTimelineIndexRoute: typeof EventsTimelineIndexRoute
  ImpactAnalysisIndexRoute: typeof ImpactAnalysisIndexRoute
  MatrixTraceabilityIndexRoute: typeof MatrixTraceabilityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/': {
      id: '/links/'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs/': {
      id: '/api-docs/'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/tree': {
      id: '/items/tree'
      path: '/items/tree'
      fullPath: '/items/tree'
      preLoaderRoute: typeof ItemsTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/kanban': {
      id: '/items/kanban'
      path: '/items/kanban'
      fullPath: '/items/kanban'
      preLoaderRoute: typeof ItemsKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swagger-config': {
      id: '/api/swagger-config'
      path: '/api/swagger-config'
      fullPath: '/api/swagger-config'
      preLoaderRoute: typeof ApiSwaggerConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spec': {
      id: '/api/spec'
      path: '/api/spec'
      fullPath: '/api/spec'
      preLoaderRoute: typeof ApiSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-test': {
      id: '/api/auth-test'
      path: '/api/auth-test'
      fullPath: '/api/auth-test'
      preLoaderRoute: typeof ApiAuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs/swagger': {
      id: '/api-docs/swagger'
      path: '/api-docs/swagger'
      fullPath: '/api-docs/swagger'
      preLoaderRoute: typeof ApiDocsSwaggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs/redoc': {
      id: '/api-docs/redoc'
      path: '/api-docs/redoc'
      fullPath: '/api-docs/redoc'
      preLoaderRoute: typeof ApiDocsRedocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix/traceability/': {
      id: '/matrix/traceability/'
      path: '/matrix/traceability'
      fullPath: '/matrix/traceability'
      preLoaderRoute: typeof MatrixTraceabilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact/analysis/': {
      id: '/impact/analysis/'
      path: '/impact/analysis'
      fullPath: '/impact/analysis'
      preLoaderRoute: typeof ImpactAnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/timeline/': {
      id: '/events/timeline/'
      path: '/events/timeline'
      fullPath: '/events/timeline'
      preLoaderRoute: typeof EventsTimelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/views/wireframe': {
      id: '/projects/$projectId/views/wireframe'
      path: '/views/wireframe'
      fullPath: '/projects/$projectId/views/wireframe'
      preLoaderRoute: typeof ProjectsProjectIdViewsWireframeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/test': {
      id: '/projects/$projectId/views/test'
      path: '/views/test'
      fullPath: '/projects/$projectId/views/test'
      preLoaderRoute: typeof ProjectsProjectIdViewsTestRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/feature': {
      id: '/projects/$projectId/views/feature'
      path: '/views/feature'
      fullPath: '/projects/$projectId/views/feature'
      preLoaderRoute: typeof ProjectsProjectIdViewsFeatureRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/database': {
      id: '/projects/$projectId/views/database'
      path: '/views/database'
      fullPath: '/projects/$projectId/views/database'
      preLoaderRoute: typeof ProjectsProjectIdViewsDatabaseRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/code': {
      id: '/projects/$projectId/views/code'
      path: '/views/code'
      fullPath: '/projects/$projectId/views/code'
      preLoaderRoute: typeof ProjectsProjectIdViewsCodeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/api': {
      id: '/projects/$projectId/views/api'
      path: '/views/api'
      fullPath: '/projects/$projectId/views/api'
      preLoaderRoute: typeof ProjectsProjectIdViewsApiRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/$viewType': {
      id: '/projects/$projectId/views/$viewType'
      path: '/views/$viewType'
      fullPath: '/projects/$projectId/views/$viewType'
      preLoaderRoute: typeof ProjectsProjectIdViewsViewTypeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/views/$viewType/$itemId': {
      id: '/projects/$projectId/views/$viewType/$itemId'
      path: '/$itemId'
      fullPath: '/projects/$projectId/views/$viewType/$itemId'
      preLoaderRoute: typeof ProjectsProjectIdViewsViewTypeItemIdRouteImport
      parentRoute: typeof ProjectsProjectIdViewsViewTypeRoute
    }
  }
}

interface ProjectsProjectIdViewsViewTypeRouteChildren {
  ProjectsProjectIdViewsViewTypeItemIdRoute: typeof ProjectsProjectIdViewsViewTypeItemIdRoute
}

const ProjectsProjectIdViewsViewTypeRouteChildren: ProjectsProjectIdViewsViewTypeRouteChildren =
  {
    ProjectsProjectIdViewsViewTypeItemIdRoute:
      ProjectsProjectIdViewsViewTypeItemIdRoute,
  }

const ProjectsProjectIdViewsViewTypeRouteWithChildren =
  ProjectsProjectIdViewsViewTypeRoute._addFileChildren(
    ProjectsProjectIdViewsViewTypeRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdViewsViewTypeRoute: typeof ProjectsProjectIdViewsViewTypeRouteWithChildren
  ProjectsProjectIdViewsApiRoute: typeof ProjectsProjectIdViewsApiRoute
  ProjectsProjectIdViewsCodeRoute: typeof ProjectsProjectIdViewsCodeRoute
  ProjectsProjectIdViewsDatabaseRoute: typeof ProjectsProjectIdViewsDatabaseRoute
  ProjectsProjectIdViewsFeatureRoute: typeof ProjectsProjectIdViewsFeatureRoute
  ProjectsProjectIdViewsTestRoute: typeof ProjectsProjectIdViewsTestRoute
  ProjectsProjectIdViewsWireframeRoute: typeof ProjectsProjectIdViewsWireframeRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdViewsViewTypeRoute:
    ProjectsProjectIdViewsViewTypeRouteWithChildren,
  ProjectsProjectIdViewsApiRoute: ProjectsProjectIdViewsApiRoute,
  ProjectsProjectIdViewsCodeRoute: ProjectsProjectIdViewsCodeRoute,
  ProjectsProjectIdViewsDatabaseRoute: ProjectsProjectIdViewsDatabaseRoute,
  ProjectsProjectIdViewsFeatureRoute: ProjectsProjectIdViewsFeatureRoute,
  ProjectsProjectIdViewsTestRoute: ProjectsProjectIdViewsTestRoute,
  ProjectsProjectIdViewsWireframeRoute: ProjectsProjectIdViewsWireframeRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRedocRoute: ApiDocsRedocRoute,
  ApiDocsSwaggerRoute: ApiDocsSwaggerRoute,
  ApiAuthTestRoute: ApiAuthTestRoute,
  ApiSpecRoute: ApiSpecRoute,
  ApiSwaggerConfigRoute: ApiSwaggerConfigRoute,
  ItemsKanbanRoute: ItemsKanbanRoute,
  ItemsTreeRoute: ItemsTreeRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  AgentsIndexRoute: AgentsIndexRoute,
  ApiDocsIndexRoute: ApiDocsIndexRoute,
  GraphIndexRoute: GraphIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  LinksIndexRoute: LinksIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  EventsTimelineIndexRoute: EventsTimelineIndexRoute,
  ImpactAnalysisIndexRoute: ImpactAnalysisIndexRoute,
  MatrixTraceabilityIndexRoute: MatrixTraceabilityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
