-- SoundWave - Music Streaming Service
-- Comprehensive test data for music streaming platform

DELETE FROM links WHERE project_id IN (SELECT id FROM projects WHERE name = 'SoundWave - Music Streaming Service');
DELETE FROM items WHERE project_id IN (SELECT id FROM projects WHERE name = 'SoundWave - Music Streaming Service');
DELETE FROM projects WHERE name = 'SoundWave - Music Streaming Service';

-- Insert Project with explicit ID
INSERT INTO projects (id, name, project_metadata, created_at, updated_at)
VALUES (
  'proj_soundwave_001',
  'SoundWave - Music Streaming Service',
  '{"description": "Next-generation music streaming platform with AI-powered recommendations, offline playback, podcasts, and social features"}'::jsonb,
  NOW(),
  NOW()
);

-- REQUIREMENTS (001-030)
INSERT INTO items (id, project_id, title, description, view, item_type, status, priority, owner, parent_id, item_metadata, version, created_at, updated_at)
VALUES
('req_sw_001', 'proj_soundwave_001', 'Audio Playback Engine', 'Implement high-fidelity audio playback with support for FLAC, MP3, AAC, and Opus formats', 'requirements', 'requirement', 'done', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "Supports all major formats with lossless streaming", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_002', 'proj_soundwave_001', 'User Authentication & Authorization', 'Secure OAuth2.0 authentication with JWT tokens and role-based access control', 'requirements', 'requirement', 'done', 'critical', 'David Park', NULL, '{"acceptance": "Zero-knowledge authentication, session management", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_003', 'proj_soundwave_001', 'Playlist Management System', 'Create, edit, delete, and share playlists with collaborative editing', 'requirements', 'requirement', 'done', 'critical', 'Emma Thompson', NULL, '{"acceptance": "Real-time sync across devices, playlist versioning", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_004', 'proj_soundwave_001', 'Music Library Integration', 'Sync with user''s local music library and cloud storage services', 'requirements', 'requirement', 'done', 'high', 'James Chen', NULL, '{"acceptance": "Support 1M+ tracks, automatic metadata enrichment", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_005', 'proj_soundwave_001', 'Recommendation Engine', 'AI-powered personalized music recommendations using collaborative filtering', 'requirements', 'requirement', 'in_progress', 'critical', 'Sarah Williams', NULL, '{"acceptance": ">80% relevance score, <100ms latency", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_006', 'proj_soundwave_001', 'Offline Playback Mode', 'Download tracks for offline listening with automatic cache management', 'requirements', 'requirement', 'in_progress', 'high', 'Maya Rodriguez', NULL, '{"acceptance": "50GB cache, background sync", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_007', 'proj_soundwave_001', 'Podcast Integration', 'Full podcast support with episode management and subscriptions', 'requirements', 'requirement', 'in_progress', 'high', 'David Park', NULL, '{"acceptance": "Auto-download, playback position sync", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_008', 'proj_soundwave_001', 'Social Features', 'Friend connections, follow artists, and social sharing', 'requirements', 'requirement', 'todo', 'high', 'Emma Thompson', NULL, '{"acceptance": "Activity feed, social notifications", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_009', 'proj_soundwave_001', 'Lyrics Display System', 'Real-time synchronized lyrics with karaoke mode support', 'requirements', 'requirement', 'todo', 'high', 'James Chen', NULL, '{"acceptance": "Sync ±100ms accuracy, multiple languages", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_010', 'proj_soundwave_001', 'Queue Management', 'Advanced queue with shuffle, repeat, and drag-to-reorder', 'requirements', 'requirement', 'done', 'critical', 'Sarah Williams', NULL, '{"acceptance": "Persistent queue, history tracking", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_011', 'proj_soundwave_001', 'Search & Filtering', 'Fast full-text search with advanced filters and faceted navigation', 'requirements', 'requirement', 'done', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "<50ms response time, typo tolerance", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_012', 'proj_soundwave_001', 'Audio Quality Settings', 'User-configurable audio quality with adaptive bitrate streaming', 'requirements', 'requirement', 'in_progress', 'high', 'David Park', NULL, '{"acceptance": "Low/Normal/High/Lossless options", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_013', 'proj_soundwave_001', 'Equalizer & Sound Effects', 'Customizable equalizer with preset profiles and effects', 'requirements', 'requirement', 'todo', 'medium', 'Emma Thompson', NULL, '{"acceptance": "10-band EQ, 20+ presets", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_014', 'proj_soundwave_001', 'Sleep Timer', 'Audio fade-out with sleep timer for nighttime listening', 'requirements', 'requirement', 'todo', 'medium', 'James Chen', NULL, '{"acceptance": "30-min increment intervals", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_015', 'proj_soundwave_001', 'Loved Tracks System', 'Save favorite tracks with automatic playlist generation', 'requirements', 'requirement', 'done', 'critical', 'Sarah Williams', NULL, '{"acceptance": "Heart icon, loved playlist sync", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_016', 'proj_soundwave_001', 'Album Grouping', 'Intelligent album/EP/compilation detection and grouping', 'requirements', 'requirement', 'in_progress', 'high', 'Maya Rodriguez', NULL, '{"acceptance": "96% accuracy on metadata match", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_017', 'proj_soundwave_001', 'Artist Pages', 'Rich artist profiles with discography, bio, and social links', 'requirements', 'requirement', 'todo', 'high', 'David Park', NULL, '{"acceptance": "Real-time follower count, verified badges", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_018', 'proj_soundwave_001', 'Genre-based Curation', 'Discover playlists and stations by genre with expert curation', 'requirements', 'requirement', 'todo', 'medium', 'Emma Thompson', NULL, '{"acceptance": "50+ genre categories, weekly updates", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_019', 'proj_soundwave_001', 'Mood-based Playlists', 'Algorithmic playlists based on mood and activity', 'requirements', 'requirement', 'todo', 'high', 'James Chen', NULL, '{"acceptance": "15+ mood categories, real-time generation", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_020', 'proj_soundwave_001', 'Time-based Playlists', 'Curated playlists for different times of day', 'requirements', 'requirement', 'todo', 'medium', 'Sarah Williams', NULL, '{"acceptance": "Morning/Work/Evening/Night playlists", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_021', 'proj_soundwave_001', 'Radio Stations', 'Create and play continuous radio stations based on seed', 'requirements', 'requirement', 'in_progress', 'high', 'Maya Rodriguez', NULL, '{"acceptance": "No repeats for 100+ tracks", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_022', 'proj_soundwave_001', 'User Profiles', 'Customizable user profiles with avatar, bio, and listening stats', 'requirements', 'requirement', 'done', 'high', 'David Park', NULL, '{"acceptance": "Public/private profile settings", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_023', 'proj_soundwave_001', 'Listening Statistics', 'Track and display user listening history and statistics', 'requirements', 'requirement', 'in_progress', 'high', 'Emma Thompson', NULL, '{"acceptance": "Top tracks/artists by period, time spent", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_024', 'proj_soundwave_001', 'Year in Review', 'Annual summary of listening habits and top tracks', 'requirements', 'requirement', 'todo', 'medium', 'James Chen', NULL, '{"acceptance": "Wrapped-style analytics, shareable", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_025', 'proj_soundwave_001', 'Notifications System', 'Real-time notifications for follows, releases, and messages', 'requirements', 'requirement', 'in_progress', 'high', 'Sarah Williams', NULL, '{"acceptance": "Push, in-app, email notifications", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_026', 'proj_soundwave_001', 'Premium Features', 'Tiered subscription system with ad-free and high-quality audio', 'requirements', 'requirement', 'done', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "Free/Premium/Premium+ tiers", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_027', 'proj_soundwave_001', 'Payment Processing', 'Secure payment processing with multiple methods', 'requirements', 'requirement', 'in_progress', 'critical', 'David Park', NULL, '{"acceptance": "Stripe/PayPal integration, recurring billing", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_028', 'proj_soundwave_001', 'Analytics Dashboard', 'Admin dashboard for platform metrics and user insights', 'requirements', 'requirement', 'todo', 'high', 'Emma Thompson', NULL, '{"acceptance": "Real-time metrics, 30-day history", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_029', 'proj_soundwave_001', 'Content Moderation', 'System for reporting and moderating user-generated content', 'requirements', 'requirement', 'in_progress', 'high', 'James Chen', NULL, '{"acceptance": "Auto-flagging, human review queue", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_030', 'proj_soundwave_001', 'Multi-language Support', 'Support for 20+ languages with localized content', 'requirements', 'requirement', 'todo', 'high', 'Sarah Williams', NULL, '{"acceptance": "Right-to-left language support", "complexity": "medium"}', 1, NOW(), NOW());

-- Additional requirements (031-060)
INSERT INTO items (id, project_id, title, description, view, item_type, status, priority, owner, parent_id, item_metadata, version, created_at, updated_at)
VALUES
('req_sw_031', 'proj_soundwave_001', 'Cross-Device Sync', 'Seamless playback sync across web, mobile, and desktop apps', 'requirements', 'requirement', 'done', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "Sub-second sync, conflict resolution", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_032', 'proj_soundwave_001', 'Duplicate Track Detection', 'Intelligent identification and deduplication of duplicate tracks', 'requirements', 'requirement', 'in_progress', 'high', 'David Park', NULL, '{"acceptance": ">99% accuracy, metadata enrichment", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_033', 'proj_soundwave_001', 'Collaborative Playlists', 'Real-time collaborative playlist editing with permission levels', 'requirements', 'requirement', 'in_progress', 'high', 'Emma Thompson', NULL, '{"acceptance": "Conflict-free updates, audit trail", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_034', 'proj_soundwave_001', 'Artist Verification', 'Verification system for artists with official badges', 'requirements', 'requirement', 'todo', 'high', 'James Chen', NULL, '{"acceptance": "KYC process, badge management", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_035', 'proj_soundwave_001', 'Fan Engagement Tools', 'Tools for artists to engage fans (polls, chats, events)', 'requirements', 'requirement', 'todo', 'medium', 'Sarah Williams', NULL, '{"acceptance": "Real-time chat, scheduled events", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_036', 'proj_soundwave_001', 'Merch Integration', 'Merch marketplace for artists with revenue sharing', 'requirements', 'requirement', 'todo', 'medium', 'Maya Rodriguez', NULL, '{"acceptance": "Payment processing, inventory management", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_037', 'proj_soundwave_001', 'Concert Ticketing', 'Integrated concert ticket discovery and purchase', 'requirements', 'requirement', 'todo', 'medium', 'David Park', NULL, '{"acceptance": "Venue integration, dynamic pricing", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_038', 'proj_soundwave_001', 'Video Content', 'Support for music videos and behind-the-scenes content', 'requirements', 'requirement', 'todo', 'medium', 'Emma Thompson', NULL, '{"acceptance": "HLS streaming, quality negotiation", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_039', 'proj_soundwave_001', 'Session Sharing', 'Share listening sessions with friends in real-time', 'requirements', 'requirement', 'todo', 'high', 'James Chen', NULL, '{"acceptance": "Sub-second sync, invitation links", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_040', 'proj_soundwave_001', 'Parental Controls', 'Age-appropriate content filtering and family accounts', 'requirements', 'requirement', 'todo', 'high', 'Sarah Williams', NULL, '{"acceptance": "Explicit content filter, time limits", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_041', 'proj_soundwave_001', 'Accessibility Features', 'Screen reader support and keyboard navigation', 'requirements', 'requirement', 'in_progress', 'high', 'Maya Rodriguez', NULL, '{"acceptance": "WCAG 2.1 AA compliance", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_042', 'proj_soundwave_001', 'Dark Mode', 'System-wide dark theme with OLED optimization', 'requirements', 'requirement', 'done', 'high', 'David Park', NULL, '{"acceptance": "Follow system preference, manual toggle", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_043', 'proj_soundwave_001', 'Performance Optimization', 'Cache optimization and lazy loading for fast load times', 'requirements', 'requirement', 'in_progress', 'critical', 'Emma Thompson', NULL, '{"acceptance": "<3s initial load, FCP <1s", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_044', 'proj_soundwave_001', 'API Rate Limiting', 'Fair rate limiting with quota management', 'requirements', 'requirement', 'done', 'high', 'James Chen', NULL, '{"acceptance": "Tier-based limits, burst handling", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_045', 'proj_soundwave_001', 'Webhook System', 'Real-time webhooks for track changes and events', 'requirements', 'requirement', 'todo', 'high', 'Sarah Williams', NULL, '{"acceptance": "Retry logic, signature verification", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_046', 'proj_soundwave_001', 'GraphQL API', 'GraphQL API for efficient client queries', 'requirements', 'requirement', 'in_progress', 'high', 'Maya Rodriguez', NULL, '{"acceptance": "Full query language, subscription support", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_047', 'proj_soundwave_001', 'REST API', 'RESTful API with comprehensive documentation', 'requirements', 'requirement', 'done', 'critical', 'David Park', NULL, '{"acceptance": "OpenAPI 3.0 spec, versioning", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_048', 'proj_soundwave_001', 'Data Export', 'User data export in standard formats (JSON, CSV)', 'requirements', 'requirement', 'todo', 'high', 'Emma Thompson', NULL, '{"acceptance": "GDPR compliance, encrypted export", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_049', 'proj_soundwave_001', 'Privacy Controls', 'Granular privacy settings and data retention policies', 'requirements', 'requirement', 'in_progress', 'critical', 'James Chen', NULL, '{"acceptance": "GDPR/CCPA compliance, clear UX", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_050', 'proj_soundwave_001', 'Security Audit Logging', 'Comprehensive audit logging for compliance', 'requirements', 'requirement', 'done', 'critical', 'Sarah Williams', NULL, '{"acceptance": "Immutable logs, retention policies", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_051', 'proj_soundwave_001', 'Two-Factor Authentication', '2FA with TOTP and hardware key support', 'requirements', 'requirement', 'in_progress', 'high', 'Maya Rodriguez', NULL, '{"acceptance": "FIDO2 support, backup codes", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_052', 'proj_soundwave_001', 'Bot Detection', 'Prevent automated abuse and bot accounts', 'requirements', 'requirement', 'todo', 'high', 'David Park', NULL, '{"acceptance": "Captcha integration, ML detection", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_053', 'proj_soundwave_001', 'DDoS Protection', 'Protection against distributed denial of service attacks', 'requirements', 'requirement', 'done', 'critical', 'Emma Thompson', NULL, '{"acceptance": "Rate limiting, IP whitelisting", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_054', 'proj_soundwave_001', 'Data Encryption', 'End-to-end encryption for sensitive data', 'requirements', 'requirement', 'in_progress', 'critical', 'James Chen', NULL, '{"acceptance": "AES-256, TLS 1.3", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_055', 'proj_soundwave_001', 'Incident Response', 'Automated incident detection and response system', 'requirements', 'requirement', 'todo', 'critical', 'Sarah Williams', NULL, '{"acceptance": "Alert system, auto-mitigation", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_056', 'proj_soundwave_001', 'Backup & Disaster Recovery', 'Automated backups with disaster recovery plan', 'requirements', 'requirement', 'done', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "5-minute RTO, 99.99% uptime SLA", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_057', 'proj_soundwave_001', 'Load Balancing', 'Intelligent load distribution across servers', 'requirements', 'requirement', 'done', 'critical', 'David Park', NULL, '{"acceptance": "Auto-scaling, health checks", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_058', 'proj_soundwave_001', 'CDN Integration', 'Global CDN for fast content delivery', 'requirements', 'requirement', 'in_progress', 'critical', 'Emma Thompson', NULL, '{"acceptance": "300ms p95 latency worldwide", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_059', 'proj_soundwave_001', 'Database Optimization', 'Query optimization and indexing strategy', 'requirements', 'requirement', 'in_progress', 'high', 'James Chen', NULL, '{"acceptance": "<50ms p99 queries, <5s full scans", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_060', 'proj_soundwave_001', 'Monitoring & Alerting', 'Real-time monitoring with alert escalation', 'requirements', 'requirement', 'done', 'critical', 'Sarah Williams', NULL, '{"acceptance": "<1 min alert latency, multi-channel", "complexity": "medium"}', 1, NOW(), NOW());

-- Additional requirements (061-090)
INSERT INTO items (id, project_id, title, description, view, item_type, status, priority, owner, parent_id, item_metadata, version, created_at, updated_at)
VALUES
('req_sw_061', 'proj_soundwave_001', 'Machine Learning Pipeline', 'ML infrastructure for recommendation and ranking models', 'requirements', 'requirement', 'in_progress', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "10M+ training samples, <100ms inference", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_062', 'proj_soundwave_001', 'A/B Testing Framework', 'Framework for running controlled experiments', 'requirements', 'requirement', 'todo', 'high', 'David Park', NULL, '{"acceptance": "Multi-variant testing, statistical analysis", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_063', 'proj_soundwave_001', 'Feature Flags', 'Feature flag system for safe deployments', 'requirements', 'requirement', 'done', 'critical', 'Emma Thompson', NULL, '{"acceptance": "Real-time updates, rollback capability", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_064', 'proj_soundwave_001', 'Blue-Green Deployments', 'Zero-downtime deployment strategy', 'requirements', 'requirement', 'in_progress', 'critical', 'James Chen', NULL, '{"acceptance": "Automated rollback, health checks", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_065', 'proj_soundwave_001', 'Container Orchestration', 'Kubernetes-based service orchestration', 'requirements', 'requirement', 'done', 'critical', 'Sarah Williams', NULL, '{"acceptance": "Auto-scaling, self-healing", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_066', 'proj_soundwave_001', 'Logging System', 'Centralized logging with structured formats', 'requirements', 'requirement', 'in_progress', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "Log aggregation, 90-day retention", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_067', 'proj_soundwave_001', 'Distributed Tracing', 'End-to-end request tracing', 'requirements', 'requirement', 'todo', 'high', 'David Park', NULL, '{"acceptance": "Trace correlation, latency analysis", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_068', 'proj_soundwave_001', 'Message Queue System', 'Asynchronous task processing with queues', 'requirements', 'requirement', 'done', 'critical', 'Emma Thompson', NULL, '{"acceptance": "Exactly-once delivery, dead letter queue", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_069', 'proj_soundwave_001', 'Cache Layer', 'Distributed caching with invalidation', 'requirements', 'requirement', 'done', 'critical', 'James Chen', NULL, '{"acceptance": "99.9% hit rate, sub-ms latency", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_070', 'proj_soundwave_001', 'Search Infrastructure', 'Full-text search with relevance ranking', 'requirements', 'requirement', 'in_progress', 'critical', 'Sarah Williams', NULL, '{"acceptance": "100M+ indexed items, <100ms", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_071', 'proj_soundwave_001', 'Streaming Backend', 'Low-latency audio streaming infrastructure', 'requirements', 'requirement', 'done', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "<1s startup delay, adaptive bitrate", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_072', 'proj_soundwave_001', 'License Management', 'Track and enforce music licensing agreements', 'requirements', 'requirement', 'in_progress', 'critical', 'David Park', NULL, '{"acceptance": "License validation, royalty tracking", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_073', 'proj_soundwave_001', 'Royalty Calculation', 'Automated royalty calculation and reporting', 'requirements', 'requirement', 'in_progress', 'critical', 'Emma Thompson', NULL, '{"acceptance": "Real-time calculations, tax compliance", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_074', 'proj_soundwave_001', 'Rights Management', 'Track song rights and splits', 'requirements', 'requirement', 'todo', 'high', 'James Chen', NULL, '{"acceptance": "Rights registry, dispute resolution", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_075', 'proj_soundwave_001', 'Quality Assurance', 'Automated QA testing and CI/CD', 'requirements', 'requirement', 'done', 'critical', 'Sarah Williams', NULL, '{"acceptance": "80%+ code coverage, <10min build", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_076', 'proj_soundwave_001', 'Load Testing', 'Capacity planning and load testing', 'requirements', 'requirement', 'in_progress', 'high', 'Maya Rodriguez', NULL, '{"acceptance": "10K concurrent users, latency benchmarks", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_077', 'proj_soundwave_001', 'Security Testing', 'Automated security vulnerability scanning', 'requirements', 'requirement', 'in_progress', 'critical', 'David Park', NULL, '{"acceptance": "OWASP Top 10 coverage, pen testing", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_078', 'proj_soundwave_001', 'Customer Support System', 'Ticketing system for customer support', 'requirements', 'requirement', 'todo', 'high', 'Emma Thompson', NULL, '{"acceptance": "Multi-channel support, SLA tracking", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_079', 'proj_soundwave_001', 'Knowledge Base', 'Self-service knowledge base and FAQs', 'requirements', 'requirement', 'todo', 'high', 'James Chen', NULL, '{"acceptance": "Searchable content, video guides", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_080', 'proj_soundwave_001', 'Feedback System', 'User feedback collection and analysis', 'requirements', 'requirement', 'todo', 'high', 'Sarah Williams', NULL, '{"acceptance": "In-app surveys, sentiment analysis", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_081', 'proj_soundwave_001', 'Email System', 'Transactional email with templates', 'requirements', 'requirement', 'done', 'critical', 'Maya Rodriguez', NULL, '{"acceptance": "95%+ delivery, template management", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_082', 'proj_soundwave_001', 'SMS Notifications', 'SMS alerts for critical events', 'requirements', 'requirement', 'todo', 'high', 'David Park', NULL, '{"acceptance": "2-way SMS, delivery confirmation", "complexity": "low"}', 1, NOW(), NOW()),
('req_sw_083', 'proj_soundwave_001', 'Push Notifications', 'Cross-platform push notifications', 'requirements', 'requirement', 'in_progress', 'critical', 'Emma Thompson', NULL, '{"acceptance": "Rich notifications, scheduling", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_084', 'proj_soundwave_001', 'In-App Messaging', 'Real-time in-app message delivery', 'requirements', 'requirement', 'in_progress', 'high', 'James Chen', NULL, '{"acceptance": "Segmentation, targeting", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_085', 'proj_soundwave_001', 'Marketing Automation', 'Automated marketing campaigns', 'requirements', 'requirement', 'todo', 'medium', 'Sarah Williams', NULL, '{"acceptance": "Email sequences, personalization", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_086', 'proj_soundwave_001', 'Referral Program', 'Viral referral system with incentives', 'requirements', 'requirement', 'todo', 'medium', 'Maya Rodriguez', NULL, '{"acceptance": "Tracking, reward distribution", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_087', 'proj_soundwave_001', 'Affiliate Program', 'Affiliate marketing program management', 'requirements', 'requirement', 'todo', 'medium', 'David Park', NULL, '{"acceptance": "Commission tracking, reporting", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_088', 'proj_soundwave_001', 'Ad Network Integration', 'Integration with ad networks for monetization', 'requirements', 'requirement', 'todo', 'high', 'Emma Thompson', NULL, '{"acceptance": "Multiple ad formats, targeting", "complexity": "medium"}', 1, NOW(), NOW()),
('req_sw_089', 'proj_soundwave_001', 'Subscription Management', 'Flexible subscription tiers and pricing', 'requirements', 'requirement', 'done', 'critical', 'James Chen', NULL, '{"acceptance": "Trial periods, cancellation, dunning", "complexity": "high"}', 1, NOW(), NOW()),
('req_sw_090', 'proj_soundwave_001', 'Gift Cards & Promotions', 'Gift card system with promotional codes', 'requirements', 'requirement', 'todo', 'high', 'Sarah Williams', NULL, '{"acceptance": "Redemption, balance tracking", "complexity": "low"}', 1, NOW(), NOW());

-- FEATURES (001-050)
INSERT INTO items (id, project_id, title, description, view, item_type, status, priority, owner, parent_id, item_metadata, version, created_at, updated_at)
VALUES
('feat_sw_001', 'proj_soundwave_001', 'Audio Format Decoding', 'Implement FLAC lossless decoding engine', 'features', 'feature', 'done', 'critical', 'Maya Rodriguez', 'req_sw_001', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_002', 'proj_soundwave_001', 'Opus Codec Support', 'Add high-quality Opus audio codec support', 'features', 'feature', 'in_progress', 'critical', 'David Park', 'req_sw_001', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_003', 'proj_soundwave_001', 'AAC Streaming', 'Optimize AAC format for streaming efficiency', 'features', 'feature', 'done', 'critical', 'Emma Thompson', 'req_sw_001', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_004', 'proj_soundwave_001', 'MP3 Legacy Support', 'Maintain compatibility with MP3 format', 'features', 'feature', 'done', 'critical', 'James Chen', 'req_sw_001', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_005', 'proj_soundwave_001', 'OAuth2 Integration', 'Implement OAuth2.0 provider integration', 'features', 'feature', 'done', 'critical', 'Sarah Williams', 'req_sw_002', '{"subtasks": 5}', 1, NOW(), NOW()),
('feat_sw_006', 'proj_soundwave_001', 'JWT Token Generation', 'Create JWT token generation and validation', 'features', 'feature', 'done', 'critical', 'Maya Rodriguez', 'req_sw_002', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_007', 'proj_soundwave_001', 'Role-Based Access Control', 'Implement RBAC system with permission matrix', 'features', 'feature', 'in_progress', 'critical', 'David Park', 'req_sw_002', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_008', 'proj_soundwave_001', 'Session Management', 'Create robust session lifecycle management', 'features', 'feature', 'done', 'critical', 'Emma Thompson', 'req_sw_002', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_009', 'proj_soundwave_001', 'Create Playlist', 'Allow users to create new playlists', 'features', 'feature', 'done', 'critical', 'James Chen', 'req_sw_003', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_010', 'proj_soundwave_001', 'Edit Playlist Metadata', 'Enable playlist title/description editing', 'features', 'feature', 'done', 'critical', 'Sarah Williams', 'req_sw_003', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_011', 'proj_soundwave_001', 'Delete Playlist', 'Implement playlist deletion with confirmation', 'features', 'feature', 'done', 'critical', 'Maya Rodriguez', 'req_sw_003', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_012', 'proj_soundwave_001', 'Playlist Sharing', 'Create shareable playlist links', 'features', 'feature', 'in_progress', 'high', 'David Park', 'req_sw_003', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_013', 'proj_soundwave_001', 'Collaborative Playlist Editor', 'Enable real-time multi-user playlist editing', 'features', 'feature', 'in_progress', 'high', 'Emma Thompson', 'req_sw_003', '{"subtasks": 5}', 1, NOW(), NOW()),
('feat_sw_014', 'proj_soundwave_001', 'Playlist Versioning', 'Track playlist change history with rollback', 'features', 'feature', 'todo', 'medium', 'James Chen', 'req_sw_003', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_015', 'proj_soundwave_001', 'Local Library Scanner', 'Scan and index user local music files', 'features', 'feature', 'done', 'high', 'Sarah Williams', 'req_sw_004', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_016', 'proj_soundwave_001', 'Cloud Storage Integration', 'Connect with Google Drive, OneDrive, iCloud', 'features', 'feature', 'in_progress', 'high', 'Maya Rodriguez', 'req_sw_004', '{"subtasks": 5}', 1, NOW(), NOW()),
('feat_sw_017', 'proj_soundwave_001', 'Metadata Auto-Enrichment', 'Auto-fetch album art and metadata', 'features', 'feature', 'in_progress', 'high', 'David Park', 'req_sw_004', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_018', 'proj_soundwave_001', 'Duplicate Detection', 'Identify and merge duplicate track entries', 'features', 'feature', 'in_progress', 'high', 'Emma Thompson', 'req_sw_004', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_019', 'proj_soundwave_001', 'Collaborative Filtering Model', 'Train user-item interaction model', 'features', 'feature', 'in_progress', 'critical', 'James Chen', 'req_sw_005', '{"subtasks": 5}', 1, NOW(), NOW()),
('feat_sw_020', 'proj_soundwave_001', 'Content-Based Recommendations', 'Use audio features for similar track finding', 'features', 'feature', 'todo', 'high', 'Sarah Williams', 'req_sw_005', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_021', 'proj_soundwave_001', 'Personalization Pipeline', 'Real-time personalization engine', 'features', 'feature', 'in_progress', 'critical', 'Maya Rodriguez', 'req_sw_005', '{"subtasks": 5}', 1, NOW(), NOW()),
('feat_sw_022', 'proj_soundwave_001', 'Discovery Mix Generation', 'Generate weekly discovery mixes', 'features', 'feature', 'todo', 'high', 'David Park', 'req_sw_005', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_023', 'proj_soundwave_001', 'Download Management UI', 'User interface for managing downloads', 'features', 'feature', 'in_progress', 'high', 'Emma Thompson', 'req_sw_006', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_024', 'proj_soundwave_001', 'Smart Cache Invalidation', 'Intelligent cache cleanup and refresh', 'features', 'feature', 'todo', 'high', 'James Chen', 'req_sw_006', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_025', 'proj_soundwave_001', 'Background Sync Engine', 'Sync downloaded content in background', 'features', 'feature', 'in_progress', 'high', 'Sarah Williams', 'req_sw_006', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_026', 'proj_soundwave_001', 'Podcast Feed Parser', 'Parse and validate RSS/Atom feeds', 'features', 'feature', 'in_progress', 'high', 'Maya Rodriguez', 'req_sw_007', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_027', 'proj_soundwave_001', 'Episode Auto-Download', 'Automatic episode download when available', 'features', 'feature', 'in_progress', 'high', 'David Park', 'req_sw_007', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_028', 'proj_soundwave_001', 'Podcast Subscription Manager', 'Manage podcast subscriptions and feeds', 'features', 'feature', 'todo', 'high', 'Emma Thompson', 'req_sw_007', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_029', 'proj_soundwave_001', 'Episode Position Sync', 'Sync playback position across devices', 'features', 'feature', 'in_progress', 'high', 'James Chen', 'req_sw_007', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_030', 'proj_soundwave_001', 'Friend Discovery', 'Find and connect with friends on platform', 'features', 'feature', 'todo', 'high', 'Sarah Williams', 'req_sw_008', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_031', 'proj_soundwave_001', 'Activity Feed', 'Display friends'' listening activity', 'features', 'feature', 'todo', 'high', 'Maya Rodriguez', 'req_sw_008', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_032', 'proj_soundwave_001', 'Artist Following', 'Allow users to follow favorite artists', 'features', 'feature', 'todo', 'high', 'David Park', 'req_sw_008', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_033', 'proj_soundwave_001', 'Share to Social Media', 'Share tracks/playlists to social networks', 'features', 'feature', 'todo', 'high', 'Emma Thompson', 'req_sw_008', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_034', 'proj_soundwave_001', 'Lyric Display Engine', 'Real-time lyric display with sync', 'features', 'feature', 'todo', 'high', 'James Chen', 'req_sw_009', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_035', 'proj_soundwave_001', 'Karaoke Mode', 'Highlight and display lyrics for karaoke', 'features', 'feature', 'todo', 'medium', 'Sarah Williams', 'req_sw_009', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_036', 'proj_soundwave_001', 'Multi-Language Lyrics', 'Support lyrics in multiple languages', 'features', 'feature', 'todo', 'medium', 'Maya Rodriguez', 'req_sw_009', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_037', 'proj_soundwave_001', 'Lyric Search', 'Search tracks by lyric content', 'features', 'feature', 'todo', 'medium', 'David Park', 'req_sw_009', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_038', 'proj_soundwave_001', 'Queue Drag-to-Reorder', 'Drag-and-drop reordering of queue', 'features', 'feature', 'done', 'critical', 'Emma Thompson', 'req_sw_010', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_039', 'proj_soundwave_001', 'Queue Persistence', 'Save queue state across sessions', 'features', 'feature', 'done', 'critical', 'James Chen', 'req_sw_010', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_040', 'proj_soundwave_001', 'Shuffle Algorithm', 'Weighted shuffle preventing repeats', 'features', 'feature', 'done', 'critical', 'Sarah Williams', 'req_sw_010', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_041', 'proj_soundwave_001', 'Repeat Modes', 'Implement repeat all/one/off modes', 'features', 'feature', 'done', 'critical', 'Maya Rodriguez', 'req_sw_010', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_042', 'proj_soundwave_001', 'Full-Text Search', 'Implement ES full-text search', 'features', 'feature', 'done', 'critical', 'David Park', 'req_sw_011', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_043', 'proj_soundwave_001', 'Advanced Filters', 'Filter by genre, year, artist, duration', 'features', 'feature', 'done', 'critical', 'Emma Thompson', 'req_sw_011', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_044', 'proj_soundwave_001', 'Typo-Tolerant Search', 'Fuzzy matching for user queries', 'features', 'feature', 'done', 'high', 'James Chen', 'req_sw_011', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_045', 'proj_soundwave_001', 'Search Autocomplete', 'Real-time search suggestions', 'features', 'feature', 'done', 'critical', 'Sarah Williams', 'req_sw_011', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_046', 'proj_soundwave_001', 'Bitrate Selection UI', 'User-friendly bitrate picker', 'features', 'feature', 'in_progress', 'high', 'Maya Rodriguez', 'req_sw_012', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_047', 'proj_soundwave_001', 'Adaptive Bitrate Algorithm', 'ABR based on network conditions', 'features', 'feature', 'in_progress', 'high', 'David Park', 'req_sw_012', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_048', 'proj_soundwave_001', 'Data Saving Mode', 'Ultra-low bitrate for data conservation', 'features', 'feature', 'todo', 'high', 'Emma Thompson', 'req_sw_012', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_049', 'proj_soundwave_001', 'Quality Monitoring', 'Monitor actual stream quality', 'features', 'feature', 'in_progress', 'high', 'James Chen', 'req_sw_012', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_050', 'proj_soundwave_001', '10-Band Equalizer', 'Implement 10-band parametric EQ', 'features', 'feature', 'todo', 'medium', 'Sarah Williams', 'req_sw_013', '{"subtasks": 3}', 1, NOW(), NOW());

-- More features (051-100)
INSERT INTO items (id, project_id, title, description, view, item_type, status, priority, owner, parent_id, item_metadata, version, created_at, updated_at)
VALUES
('feat_sw_051', 'proj_soundwave_001', 'EQ Presets Library', 'Pre-built equalizer presets for genres', 'features', 'feature', 'todo', 'medium', 'Maya Rodriguez', 'req_sw_013', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_052', 'proj_soundwave_001', 'Sleep Timer UI', 'Create sleep timer control widget', 'features', 'feature', 'todo', 'medium', 'David Park', 'req_sw_014', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_053', 'proj_soundwave_001', 'Fade Out Algorithm', 'Implement smooth audio fade-out', 'features', 'feature', 'todo', 'medium', 'Emma Thompson', 'req_sw_014', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_054', 'proj_soundwave_001', 'Timer Presets', 'Common sleep timer duration shortcuts', 'features', 'feature', 'todo', 'medium', 'James Chen', 'req_sw_014', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_055', 'proj_soundwave_001', 'Heart Icon Component', 'Implement loved tracks UI control', 'features', 'feature', 'done', 'critical', 'Sarah Williams', 'req_sw_015', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_056', 'proj_soundwave_001', 'Loved Playlist Auto-Create', 'Auto-generate loved tracks playlist', 'features', 'feature', 'done', 'critical', 'Maya Rodriguez', 'req_sw_015', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_057', 'proj_soundwave_001', 'Cross-Device Sync', 'Sync loved status across devices', 'features', 'feature', 'done', 'critical', 'David Park', 'req_sw_015', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_058', 'proj_soundwave_001', 'Album Detection Algorithm', 'ML-based album grouping logic', 'features', 'feature', 'in_progress', 'high', 'Emma Thompson', 'req_sw_016', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_059', 'proj_soundwave_001', 'Compilation Handling', 'Proper grouping of compilation albums', 'features', 'feature', 'in_progress', 'high', 'James Chen', 'req_sw_016', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_060', 'proj_soundwave_001', 'EP Detection', 'Differentiate EPs from full albums', 'features', 'feature', 'in_progress', 'high', 'Sarah Williams', 'req_sw_016', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_061', 'proj_soundwave_001', 'Artist Biography', 'Display enriched artist bios', 'features', 'feature', 'todo', 'high', 'Maya Rodriguez', 'req_sw_017', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_062', 'proj_soundwave_001', 'Discography View', 'Show all artist releases', 'features', 'feature', 'todo', 'high', 'David Park', 'req_sw_017', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_063', 'proj_soundwave_001', 'Artist Social Links', 'Display verified social media profiles', 'features', 'feature', 'todo', 'high', 'Emma Thompson', 'req_sw_017', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_064', 'proj_soundwave_001', 'Verified Badge System', 'Show artist verification status', 'features', 'feature', 'todo', 'high', 'James Chen', 'req_sw_017', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_065', 'proj_soundwave_001', 'Genre Taxonomy', 'Comprehensive genre classification', 'features', 'feature', 'todo', 'medium', 'Sarah Williams', 'req_sw_018', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_066', 'proj_soundwave_001', 'Expert Curation Pipeline', 'Editorial playlist management', 'features', 'feature', 'todo', 'medium', 'Maya Rodriguez', 'req_sw_018', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_067', 'proj_soundwave_001', 'Playlist Update Scheduler', 'Weekly playlist refresh automation', 'features', 'feature', 'todo', 'medium', 'David Park', 'req_sw_018', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_068', 'proj_soundwave_001', 'Mood Detection Model', 'ML model for mood classification', 'features', 'feature', 'todo', 'high', 'Emma Thompson', 'req_sw_019', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_069', 'proj_soundwave_001', 'Activity-Based Playlists', 'Playlists by activity type', 'features', 'feature', 'todo', 'high', 'James Chen', 'req_sw_019', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_070', 'proj_soundwave_001', 'Real-Time Generation', 'Generate playlists on-the-fly', 'features', 'feature', 'todo', 'high', 'Sarah Williams', 'req_sw_019', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_071', 'proj_soundwave_001', 'Morning Mix Playlist', 'Upbeat morning playlist generation', 'features', 'feature', 'todo', 'medium', 'Maya Rodriguez', 'req_sw_020', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_072', 'proj_soundwave_001', 'Work Focus Playlist', 'Concentration-boosting music', 'features', 'feature', 'todo', 'medium', 'David Park', 'req_sw_020', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_073', 'proj_soundwave_001', 'Evening Wind Down', 'Relaxing evening playlist', 'features', 'feature', 'todo', 'medium', 'Emma Thompson', 'req_sw_020', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_074', 'proj_soundwave_001', 'Sleep Playlist', 'Calm music for bedtime', 'features', 'feature', 'todo', 'medium', 'James Chen', 'req_sw_020', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_075', 'proj_soundwave_001', 'Radio Seed System', 'Start radio from any seed item', 'features', 'feature', 'in_progress', 'high', 'Sarah Williams', 'req_sw_021', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_076', 'proj_soundwave_001', 'Station Infinite Queue', 'Unlimited station track generation', 'features', 'feature', 'in_progress', 'high', 'Maya Rodriguez', 'req_sw_021', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_077', 'proj_soundwave_001', 'Repeat Prevention', 'Prevent duplicate tracks in radio', 'features', 'feature', 'in_progress', 'high', 'David Park', 'req_sw_021', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_078', 'proj_soundwave_001', 'Radio Customization', 'Fine-tune radio recommendations', 'features', 'feature', 'todo', 'high', 'Emma Thompson', 'req_sw_021', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_079', 'proj_soundwave_001', 'Profile Customization', 'Editable user profile settings', 'features', 'feature', 'done', 'high', 'James Chen', 'req_sw_022', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_080', 'proj_soundwave_001', 'Avatar Upload', 'User profile picture upload', 'features', 'feature', 'done', 'high', 'Sarah Williams', 'req_sw_022', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_081', 'proj_soundwave_001', 'Privacy Settings', 'Profile visibility controls', 'features', 'feature', 'done', 'high', 'Maya Rodriguez', 'req_sw_022', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_082', 'proj_soundwave_001', 'Bio Management', 'Edit user bio/description', 'features', 'feature', 'done', 'high', 'David Park', 'req_sw_022', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_083', 'proj_soundwave_001', 'All-Time Stats', 'Lifetime listening statistics', 'features', 'feature', 'in_progress', 'high', 'Emma Thompson', 'req_sw_023', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_084', 'proj_soundwave_001', 'Time Period Filter', 'Stats by week/month/year', 'features', 'feature', 'in_progress', 'high', 'James Chen', 'req_sw_023', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_085', 'proj_soundwave_001', 'Top Tracks Report', 'User''s most played tracks', 'features', 'feature', 'in_progress', 'high', 'Sarah Williams', 'req_sw_023', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_086', 'proj_soundwave_001', 'Top Artists Report', 'User''s most played artists', 'features', 'feature', 'in_progress', 'high', 'Maya Rodriguez', 'req_sw_023', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_087', 'proj_soundwave_001', 'Listening Streak', 'Track consecutive listening days', 'features', 'feature', 'todo', 'medium', 'David Park', 'req_sw_023', '{"subtasks": 1}', 1, NOW(), NOW()),
('feat_sw_088', 'proj_soundwave_001', 'Year in Review UI', 'Create shareable wrapped experience', 'features', 'feature', 'todo', 'medium', 'Emma Thompson', 'req_sw_024', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_089', 'proj_soundwave_001', 'Analytics Export', 'Export yearly analytics as image/PDF', 'features', 'feature', 'todo', 'medium', 'James Chen', 'req_sw_024', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_090', 'proj_soundwave_001', 'Wrapped Sharing', 'Social media sharing for wrapped results', 'features', 'feature', 'todo', 'medium', 'Sarah Williams', 'req_sw_024', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_091', 'proj_soundwave_001', 'Push Notification Manager', 'Centralized notification settings', 'features', 'feature', 'in_progress', 'high', 'Maya Rodriguez', 'req_sw_025', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_092', 'proj_soundwave_001', 'In-App Notification Center', 'Notification history and management', 'features', 'feature', 'todo', 'high', 'David Park', 'req_sw_025', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_093', 'proj_soundwave_001', 'Free Tier Features', 'Limited ad-supported experience', 'features', 'feature', 'done', 'critical', 'Emma Thompson', 'req_sw_026', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_094', 'proj_soundwave_001', 'Premium Features Bundle', 'Premium ad-free + high-quality', 'features', 'feature', 'done', 'critical', 'James Chen', 'req_sw_026', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_095', 'proj_soundwave_001', 'Premium+ Extra Features', 'Exclusive premium+ features', 'features', 'feature', 'in_progress', 'critical', 'Sarah Williams', 'req_sw_026', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_096', 'proj_soundwave_001', 'Subscription Management UI', 'Plan selection and management', 'features', 'feature', 'done', 'critical', 'Maya Rodriguez', 'req_sw_026', '{"subtasks": 2}', 1, NOW(), NOW()),
('feat_sw_097', 'proj_soundwave_001', 'Free Trial Logic', 'Trial period management', 'features', 'feature', 'in_progress', 'critical', 'David Park', 'req_sw_027', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_098', 'proj_soundwave_001', 'Payment Gateway Integration', 'Stripe/PayPal gateway integration', 'features', 'feature', 'done', 'critical', 'Emma Thompson', 'req_sw_027', '{"subtasks": 4}', 1, NOW(), NOW()),
('feat_sw_099', 'proj_soundwave_001', 'Billing Invoice System', 'Invoice generation and history', 'features', 'feature', 'in_progress', 'critical', 'James Chen', 'req_sw_027', '{"subtasks": 3}', 1, NOW(), NOW()),
('feat_sw_100', 'proj_soundwave_001', 'Subscription Cancellation', 'Manage subscription cancellation', 'features', 'feature', 'todo', 'high', 'Sarah Williams', 'req_sw_027', '{"subtasks": 2}', 1, NOW(), NOW());

-- TASKS (001-020)
INSERT INTO items (id, project_id, title, description, view, item_type, status, priority, owner, parent_id, item_metadata, version, created_at, updated_at)
VALUES
('task_sw_001', 'proj_soundwave_001', 'Decode FLAC audio streams', 'Implement FLAC format decoder', 'tasks', 'task', 'todo', 'critical', 'Maya Rodriguez', 'feat_sw_001', '{"hours": 4}', 1, NOW(), NOW()),
('task_sw_002', 'proj_soundwave_001', 'Optimize FLAC performance', 'Optimize decoding for streaming', 'tasks', 'task', 'todo', 'critical', 'David Park', 'feat_sw_001', '{"hours": 8}', 1, NOW(), NOW()),
('task_sw_003', 'proj_soundwave_001', 'Add Opus codec support', 'Integrate Opus audio library', 'tasks', 'task', 'todo', 'critical', 'Emma Thompson', 'feat_sw_002', '{"hours": 6}', 1, NOW(), NOW()),
('task_sw_004', 'proj_soundwave_001', 'Implement OAuth2 provider', 'OAuth2.0 provider integration', 'tasks', 'task', 'todo', 'critical', 'James Chen', 'feat_sw_005', '{"hours": 6}', 1, NOW(), NOW()),
('task_sw_005', 'proj_soundwave_001', 'Build JWT token system', 'JWT generation and validation', 'tasks', 'task', 'todo', 'critical', 'Sarah Williams', 'feat_sw_006', '{"hours": 4}', 1, NOW(), NOW()),
('task_sw_006', 'proj_soundwave_001', 'Create playlist model', 'Design playlist database schema', 'tasks', 'task', 'todo', 'critical', 'Maya Rodriguez', 'feat_sw_009', '{"hours": 4}', 1, NOW(), NOW()),
('task_sw_007', 'proj_soundwave_001', 'Build playlist API', 'Create playlist REST endpoints', 'tasks', 'task', 'todo', 'critical', 'David Park', 'feat_sw_009', '{"hours": 8}', 1, NOW(), NOW()),
('task_sw_008', 'proj_soundwave_001', 'Implement library scanner', 'Local library file scanning logic', 'tasks', 'task', 'todo', 'high', 'Emma Thompson', 'feat_sw_015', '{"hours": 8}', 1, NOW(), NOW()),
('task_sw_009', 'proj_soundwave_001', 'Build full-text search', 'Elasticsearch integration', 'tasks', 'task', 'todo', 'critical', 'James Chen', 'feat_sw_042', '{"hours": 8}', 1, NOW(), NOW()),
('task_sw_010', 'proj_soundwave_001', 'Implement search filters', 'Faceted search and filters', 'tasks', 'task', 'todo', 'critical', 'Sarah Williams', 'feat_sw_042', '{"hours": 6}', 1, NOW(), NOW()),
('task_sw_011', 'proj_soundwave_001', 'Design recommendation model', 'Collaborative filtering model', 'tasks', 'task', 'todo', 'critical', 'Maya Rodriguez', 'feat_sw_019', '{"hours": 16}', 1, NOW(), NOW()),
('task_sw_012', 'proj_soundwave_001', 'Train ML model', 'Model training pipeline', 'tasks', 'task', 'todo', 'critical', 'David Park', 'feat_sw_019', '{"hours": 12}', 1, NOW(), NOW()),
('task_sw_013', 'proj_soundwave_001', 'Implement serving layer', 'Real-time recommendation serving', 'tasks', 'task', 'todo', 'critical', 'Emma Thompson', 'feat_sw_019', '{"hours": 8}', 1, NOW(), NOW()),
('task_sw_014', 'proj_soundwave_001', 'Build download manager', 'Download queue and management', 'tasks', 'task', 'todo', 'high', 'James Chen', 'feat_sw_023', '{"hours": 6}', 1, NOW(), NOW()),
('task_sw_015', 'proj_soundwave_001', 'Implement cache cleanup', 'Smart cache invalidation', 'tasks', 'task', 'todo', 'high', 'Sarah Williams', 'feat_sw_024', '{"hours": 4}', 1, NOW(), NOW()),
('task_sw_016', 'proj_soundwave_001', 'Design sync protocol', 'Background sync architecture', 'tasks', 'task', 'todo', 'high', 'Maya Rodriguez', 'feat_sw_025', '{"hours": 8}', 1, NOW(), NOW()),
('task_sw_017', 'proj_soundwave_001', 'Implement sync engine', 'Background sync implementation', 'tasks', 'task', 'todo', 'high', 'David Park', 'feat_sw_025', '{"hours": 8}', 1, NOW(), NOW()),
('task_sw_018', 'proj_soundwave_001', 'Parse podcast feeds', 'RSS/Atom feed parser', 'tasks', 'task', 'todo', 'high', 'Emma Thompson', 'feat_sw_026', '{"hours": 4}', 1, NOW(), NOW()),
('task_sw_019', 'proj_soundwave_001', 'Build recommendation engine', 'Core recommendation algorithm', 'tasks', 'task', 'todo', 'critical', 'James Chen', 'feat_sw_021', '{"hours": 12}', 1, NOW(), NOW()),
('task_sw_020', 'proj_soundwave_001', 'Create user profile UI', 'Profile editing interface', 'tasks', 'task', 'todo', 'high', 'Sarah Williams', 'feat_sw_079', '{"hours": 6}', 1, NOW(), NOW());

-- TESTS (001-005)
INSERT INTO items (id, project_id, title, description, view, item_type, status, priority, owner, parent_id, item_metadata, version, created_at, updated_at)
VALUES
('test_sw_001', 'proj_soundwave_001', 'FLAC decoding test', 'Verify FLAC format decoding', 'tasks', 'test', 'todo', 'critical', 'Maya Rodriguez', 'task_sw_001', '{"type": "unit"}', 1, NOW(), NOW()),
('test_sw_002', 'proj_soundwave_001', 'OAuth2 integration test', 'Verify OAuth2 provider integration', 'tasks', 'test', 'todo', 'critical', 'James Chen', 'task_sw_004', '{"type": "integration"}', 1, NOW(), NOW()),
('test_sw_003', 'proj_soundwave_001', 'Playlist API test', 'Verify playlist endpoints', 'tasks', 'test', 'todo', 'critical', 'Sarah Williams', 'task_sw_007', '{"type": "integration"}', 1, NOW(), NOW()),
('test_sw_004', 'proj_soundwave_001', 'Search performance test', 'Verify search latency <50ms', 'tasks', 'test', 'todo', 'critical', 'David Park', 'task_sw_009', '{"type": "performance"}', 1, NOW(), NOW()),
('test_sw_005', 'proj_soundwave_001', 'ML recommendation test', 'Verify recommendation accuracy >80%', 'tasks', 'test', 'todo', 'critical', 'Emma Thompson', 'task_sw_012', '{"type": "ml"}', 1, NOW(), NOW());

-- LINKS (dependencies and relationships between items)
INSERT INTO links (id, project_id, source_item_id, target_item_id, link_type, link_metadata, created_at, updated_at)
VALUES
('link_sw_001', 'proj_soundwave_001', 'req_sw_001', 'feat_sw_001', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_002', 'proj_soundwave_001', 'req_sw_001', 'feat_sw_002', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_003', 'proj_soundwave_001', 'req_sw_001', 'feat_sw_003', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_004', 'proj_soundwave_001', 'req_sw_002', 'feat_sw_005', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_005', 'proj_soundwave_001', 'req_sw_002', 'feat_sw_006', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_006', 'proj_soundwave_001', 'req_sw_003', 'feat_sw_009', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_007', 'proj_soundwave_001', 'req_sw_003', 'feat_sw_012', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_008', 'proj_soundwave_001', 'req_sw_003', 'feat_sw_013', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_009', 'proj_soundwave_001', 'req_sw_005', 'feat_sw_019', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_010', 'proj_soundwave_001', 'req_sw_005', 'feat_sw_021', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_011', 'proj_soundwave_001', 'req_sw_006', 'feat_sw_023', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_012', 'proj_soundwave_001', 'req_sw_006', 'feat_sw_025', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_013', 'proj_soundwave_001', 'req_sw_007', 'feat_sw_026', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_014', 'proj_soundwave_001', 'req_sw_007', 'feat_sw_027', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_015', 'proj_soundwave_001', 'req_sw_009', 'feat_sw_034', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_016', 'proj_soundwave_001', 'req_sw_010', 'feat_sw_038', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_017', 'proj_soundwave_001', 'req_sw_010', 'feat_sw_040', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_018', 'proj_soundwave_001', 'req_sw_011', 'feat_sw_042', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_019', 'proj_soundwave_001', 'req_sw_011', 'feat_sw_045', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_020', 'proj_soundwave_001', 'req_sw_012', 'feat_sw_046', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_021', 'proj_soundwave_001', 'req_sw_012', 'feat_sw_047', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_022', 'proj_soundwave_001', 'req_sw_015', 'feat_sw_055', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_023', 'proj_soundwave_001', 'req_sw_015', 'feat_sw_057', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_024', 'proj_soundwave_001', 'req_sw_017', 'feat_sw_061', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_025', 'proj_soundwave_001', 'req_sw_017', 'feat_sw_062', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_026', 'proj_soundwave_001', 'req_sw_021', 'feat_sw_075', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_sw_027', 'proj_soundwave_001', 'req_sw_022', 'feat_sw_079', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_028', 'proj_soundwave_001', 'req_sw_023', 'feat_sw_083', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_sw_029', 'proj_soundwave_001', 'req_sw_026', 'feat_sw_094', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_030', 'proj_soundwave_001', 'req_sw_026', 'feat_sw_096', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_031', 'proj_soundwave_001', 'req_sw_027', 'feat_sw_098', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_032', 'proj_soundwave_001', 'req_sw_027', 'feat_sw_099', 'implements', '{"priority": "critical"}', NOW(), NOW()),
('link_sw_033', 'proj_soundwave_001', 'feat_sw_001', 'task_sw_001', 'breaks_down', '{"hours": 4}', NOW(), NOW()),
('link_sw_034', 'proj_soundwave_001', 'feat_sw_001', 'task_sw_002', 'breaks_down', '{"hours": 8}', NOW(), NOW()),
('link_sw_035', 'proj_soundwave_001', 'feat_sw_005', 'task_sw_004', 'breaks_down', '{"hours": 6}', NOW(), NOW()),
('link_sw_036', 'proj_soundwave_001', 'feat_sw_009', 'task_sw_006', 'breaks_down', '{"hours": 4}', NOW(), NOW()),
('link_sw_037', 'proj_soundwave_001', 'feat_sw_009', 'task_sw_007', 'breaks_down', '{"hours": 8}', NOW(), NOW()),
('link_sw_038', 'proj_soundwave_001', 'feat_sw_042', 'task_sw_009', 'breaks_down', '{"hours": 8}', NOW(), NOW()),
('link_sw_039', 'proj_soundwave_001', 'feat_sw_042', 'task_sw_010', 'breaks_down', '{"hours": 6}', NOW(), NOW()),
('link_sw_040', 'proj_soundwave_001', 'feat_sw_019', 'task_sw_012', 'breaks_down', '{"hours": 12}', NOW(), NOW()),
('link_sw_041', 'proj_soundwave_001', 'feat_sw_019', 'task_sw_013', 'breaks_down', '{"hours": 8}', NOW(), NOW()),
('link_sw_042', 'proj_soundwave_001', 'feat_sw_023', 'task_sw_016', 'breaks_down', '{"hours": 4}', NOW(), NOW()),
('link_sw_043', 'proj_soundwave_001', 'feat_sw_023', 'task_sw_017', 'breaks_down', '{"hours": 8}', NOW(), NOW()),
('link_sw_044', 'proj_soundwave_001', 'task_sw_001', 'test_sw_001', 'tests', '{"type": "unit"}', NOW(), NOW()),
('link_sw_045', 'proj_soundwave_001', 'task_sw_004', 'test_sw_002', 'tests', '{"type": "integration"}', NOW(), NOW()),
('link_sw_046', 'proj_soundwave_001', 'task_sw_006', 'test_sw_003', 'tests', '{"type": "integration"}', NOW(), NOW()),
('link_sw_047', 'proj_soundwave_001', 'task_sw_009', 'test_sw_004', 'tests', '{"type": "performance"}', NOW(), NOW()),
('link_sw_048', 'proj_soundwave_001', 'task_sw_012', 'test_sw_005', 'tests', '{"type": "ml"}', NOW(), NOW()),
('link_sw_049', 'proj_soundwave_001', 'req_sw_002', 'req_sw_001', 'depends_on', '{"reason": "auth before playback"}', NOW(), NOW()),
('link_sw_050', 'proj_soundwave_001', 'req_sw_003', 'req_sw_001', 'depends_on', '{"reason": "auth before playlists"}', NOW(), NOW()),
('link_sw_051', 'proj_soundwave_001', 'req_sw_005', 'req_sw_001', 'depends_on', '{"reason": "personalization needs user"}', NOW(), NOW()),
('link_sw_052', 'proj_soundwave_001', 'req_sw_026', 'req_sw_027', 'depends_on', '{"reason": "payment for premium"}', NOW(), NOW()),
('link_sw_053', 'proj_soundwave_001', 'req_sw_031', 'req_sw_002', 'depends_on', '{"reason": "sync needs auth"}', NOW(), NOW()),
('link_sw_054', 'proj_soundwave_001', 'req_sw_033', 'req_sw_003', 'depends_on', '{"reason": "collab needs playlists"}', NOW(), NOW());
