-- Add diverse item types to Swift Ride project (cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e)
SET search_path TO tracertm;

INSERT INTO items (id, project_id, title, description, type, status, priority, parent_id, metadata, created_at, updated_at)
VALUES
-- architecture (8)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Ride-Sharing Microservices Architecture', 'High-level service boundaries: matching, pricing, payments, notifications', 'architecture', 'done', 2, NULL, '{"view": "architecture"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Event-Driven Driver Matching', 'Architecture for real-time driver-passenger matching via events', 'architecture', 'in_progress', 2, NULL, '{"view": "architecture"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Mobile-Backend API Boundary', 'API contract and sync strategy for iOS/Android clients', 'architecture', 'done', 1, NULL, '{"view": "architecture"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Surge Pricing Service Design', 'Isolated service for dynamic pricing with minimal coupling', 'architecture', 'in_progress', 2, NULL, '{"view": "architecture"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Safety & SOS Flow Architecture', 'End-to-end flow for emergency and safety features', 'architecture', 'done', 2, NULL, '{"view": "architecture"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Payment & Wallet Service Boundary', 'Bounded context for payments and wallet operations', 'architecture', 'done', 2, NULL, '{"view": "architecture"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Geolocation & ETA Pipeline', 'Data flow for GPS, traffic, and ETA calculation', 'architecture', 'in_progress', 1, NULL, '{"view": "architecture"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Rating & Review Aggregation', 'Design for bi-directional ratings and review storage', 'architecture', 'done', 1, NULL, '{"view": "architecture"}'::jsonb, NOW(), NOW()),
-- code (10)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'DriverMatchingService', 'Core service for matching drivers to ride requests', 'code', 'in_progress', 2, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'SurgePricingEngine', 'Dynamic pricing calculation module', 'code', 'done', 2, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'PaymentGatewayAdapter', 'Adapter for payment provider integration', 'code', 'done', 2, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'NotificationDispatcher', 'Push and in-app notification dispatcher', 'code', 'in_progress', 1, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'RouteOptimizer', 'Route and ETA optimization logic', 'code', 'done', 2, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'RatingAggregator', 'Aggregates and persists driver/passenger ratings', 'code', 'done', 1, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'GeolocationService', 'GPS and location updates handler', 'code', 'in_progress', 2, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'WalletBalanceManager', 'Wallet balance and transaction logic', 'code', 'in_progress', 2, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'SOSHandler', 'Emergency SOS and safety flow handler', 'code', 'done', 2, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'FraudDetectionPipeline', 'ML pipeline for fraud signals', 'code', 'in_progress', 2, NULL, '{"view": "code"}'::jsonb, NOW(), NOW()),
-- database (8)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'rides', 'Core table for ride records and state', 'database', 'done', 2, NULL, '{"view": "database"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'drivers', 'Driver profiles and availability', 'database', 'done', 2, NULL, '{"view": "database"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'passengers', 'Passenger accounts and preferences', 'database', 'done', 2, NULL, '{"view": "database"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'payments', 'Payment and transaction ledger', 'database', 'done', 2, NULL, '{"view": "database"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'ratings', 'Driver and passenger ratings', 'database', 'done', 1, NULL, '{"view": "database"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'locations', 'GPS and geolocation history', 'database', 'in_progress', 2, NULL, '{"view": "database"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'wallets', 'User wallet balances', 'database', 'done', 2, NULL, '{"view": "database"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'notifications', 'Notification queue and delivery log', 'database', 'in_progress', 1, NULL, '{"view": "database"}'::jsonb, NOW(), NOW()),
-- wireframe (8)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Home Map & Request Ride', 'Main map and request ride CTA', 'wireframe', 'done', 2, NULL, '{"view": "wireframe"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Ride Type & Price Selection', 'Choose ride type and see price estimate', 'wireframe', 'done', 2, NULL, '{"view": "wireframe"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Driver Arrival & Trip Progress', 'Live driver location and trip progress', 'wireframe', 'in_progress', 2, NULL, '{"view": "wireframe"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Payment & Tip Screen', 'Post-ride payment and tip', 'wireframe', 'done', 2, NULL, '{"view": "wireframe"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Rating Modal', 'Rate driver and add optional review', 'wireframe', 'done', 1, NULL, '{"view": "wireframe"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'SOS & Safety Center', 'Emergency and safety entry points', 'wireframe', 'done', 2, NULL, '{"view": "wireframe"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Wallet & Payment Methods', 'Manage wallet and saved payment methods', 'wireframe', 'in_progress', 1, NULL, '{"view": "wireframe"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Ride History & Receipts', 'Past rides and receipts', 'wireframe', 'done', 1, NULL, '{"view": "wireframe"}'::jsonb, NOW(), NOW()),
-- security (8)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'PII Encryption at Rest', 'Encrypt driver/passenger PII in DB', 'security', 'done', 2, NULL, '{"view": "security"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Payment Tokenization', 'No raw card data; tokenize via provider', 'security', 'done', 2, NULL, '{"view": "security"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Auth & Session Management', 'JWT and session lifecycle', 'security', 'in_progress', 2, NULL, '{"view": "security"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Driver Background Check Integration', 'Secure integration with background check provider', 'security', 'done', 2, NULL, '{"view": "security"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Rate Limiting & Abuse Prevention', 'API and app rate limits', 'security', 'in_progress', 1, NULL, '{"view": "security"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Audit Logging', 'Audit trail for sensitive actions', 'security', 'done', 1, NULL, '{"view": "security"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'SOS Data Handling', 'Retention and access for emergency data', 'security', 'done', 2, NULL, '{"view": "security"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'GDPR Data Export & Deletion', 'User data export and right to be forgotten', 'security', 'in_progress', 2, NULL, '{"view": "security"}'::jsonb, NOW(), NOW()),
-- performance (6)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Matching Latency SLA', 'Match response under 10s p99', 'performance', 'in_progress', 2, NULL, '{"view": "performance"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Map Load & Tile Performance', 'Map and tiles load under 2s', 'performance', 'done', 1, NULL, '{"view": "performance"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Payment Confirmation Time', 'Payment confirmation under 5s', 'performance', 'done', 2, NULL, '{"view": "performance"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'API P95 Latency Targets', 'Core APIs p95 under 500ms', 'performance', 'in_progress', 2, NULL, '{"view": "performance"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Cold Start & Background Limits', 'Mobile cold start and background constraints', 'performance', 'todo', 1, NULL, '{"view": "performance"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Database Query Indexing', 'Index coverage for hot paths', 'performance', 'done', 1, NULL, '{"view": "performance"}'::jsonb, NOW(), NOW()),
-- monitoring (6)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Matching Success Rate Dashboard', 'Real-time match success and fallback metrics', 'monitoring', 'done', 2, NULL, '{"view": "monitoring"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Payment Failure Alerts', 'Alerts on payment provider errors', 'monitoring', 'done', 2, NULL, '{"view": "monitoring"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'SOS & Safety Event Logging', 'Log and alert on SOS usage', 'monitoring', 'done', 2, NULL, '{"view": "monitoring"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'API Error Rate & SLO', 'API error rate and availability SLO', 'monitoring', 'in_progress', 2, NULL, '{"view": "monitoring"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Driver Availability Heatmap', 'Geographic driver availability metrics', 'monitoring', 'todo', 1, NULL, '{"view": "monitoring"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Surge Multiplier & Demand Metrics', 'Surge and demand observability', 'monitoring', 'done', 1, NULL, '{"view": "monitoring"}'::jsonb, NOW(), NOW()),
-- domain (6)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Ride', 'Core domain: ride lifecycle and state', 'domain', 'done', 2, NULL, '{"view": "domain"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Driver', 'Driver entity and availability', 'domain', 'done', 2, NULL, '{"view": "domain"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Passenger', 'Passenger and trip request', 'domain', 'done', 2, NULL, '{"view": "domain"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Payment', 'Payment and wallet value objects', 'domain', 'done', 2, NULL, '{"view": "domain"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Location', 'Geo and ETA value objects', 'domain', 'done', 1, NULL, '{"view": "domain"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Rating', 'Rating and review aggregate', 'domain', 'done', 1, NULL, '{"view": "domain"}'::jsonb, NOW(), NOW()),
-- infrastructure (6)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Kubernetes Ride-Service Deployment', 'K8s manifests for ride and matching services', 'infrastructure', 'in_progress', 2, NULL, '{"view": "infrastructure"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'PostgreSQL & Read Replicas', 'DB and read replica setup', 'infrastructure', 'done', 2, NULL, '{"view": "infrastructure"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Redis Cache & Sessions', 'Redis for cache and session store', 'infrastructure', 'done', 1, NULL, '{"view": "infrastructure"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Message Queue for Events', 'NATS/Kafka for ride and match events', 'infrastructure', 'in_progress', 2, NULL, '{"view": "infrastructure"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'CDN for Static Assets', 'CDN for app assets and map tiles', 'infrastructure', 'done', 1, NULL, '{"view": "infrastructure"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Push Notification Infrastructure', 'FCM/APNs and delivery pipeline', 'infrastructure', 'done', 1, NULL, '{"view": "infrastructure"}'::jsonb, NOW(), NOW()),
-- dependency (5)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Stripe SDK', 'Payment provider SDK dependency', 'dependency', 'done', 2, NULL, '{"view": "dependency"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Map Provider API', 'Google Maps / Mapbox for maps and routing', 'dependency', 'done', 2, NULL, '{"view": "dependency"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Background Check Provider', 'Third-party driver background checks', 'dependency', 'done', 2, NULL, '{"view": "dependency"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Push Notification Services', 'FCM and APNs', 'dependency', 'done', 1, NULL, '{"view": "dependency"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Traffic Data Provider', 'Real-time traffic for ETA', 'dependency', 'in_progress', 1, NULL, '{"view": "dependency"}'::jsonb, NOW(), NOW()),
-- bug (5)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Surge price not updating on map refresh', 'Price sometimes stale after 30s', 'bug', 'in_progress', 2, NULL, '{"view": "feature"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Wallet balance race on concurrent rides', 'Balance can go negative under load', 'bug', 'todo', 2, NULL, '{"view": "feature"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'SOS button not visible in landscape', 'Layout issue on some devices', 'bug', 'done', 2, NULL, '{"view": "feature"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Rating modal closes on background tap', 'Accessibility and accidental dismiss', 'bug', 'in_progress', 1, NULL, '{"view": "feature"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Driver location jitter on map', 'GPS smoothing needed', 'bug', 'todo', 1, NULL, '{"view": "feature"}'::jsonb, NOW(), NOW()),
-- document (5)
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'SwiftRide API Overview', 'Public API documentation overview', 'document', 'done', 1, NULL, '{"view": "documentation"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Driver Onboarding Runbook', 'Steps for driver verification and onboarding', 'document', 'in_progress', 1, NULL, '{"view": "documentation"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Surge Pricing Policy', 'Business rules for surge pricing', 'document', 'done', 1, NULL, '{"view": "documentation"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Safety & SOS Procedures', 'Internal safety and SOS handling', 'document', 'done', 2, NULL, '{"view": "documentation"}'::jsonb, NOW(), NOW()),
(gen_random_uuid(), 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e'::uuid, 'Data Retention & Privacy', 'Retention and privacy documentation', 'document', 'in_progress', 2, NULL, '{"view": "documentation"}'::jsonb, NOW(), NOW());
