[mypy]
explicit_package_bases = True
namespace_packages = True
mypy_path = src
exclude = (frontend/disable|ARCHIVE)

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-sentence_transformers.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True
