apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://localhost:16686
    uid: jaeger
    editable: true
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
