#!/usr/bin/env python3
"""Generate comprehensive Security Layer for SwiftRide rideshare platform.

Targets:
- 80 security_vulnerability items with CVSS scores
- 100 security_control items
- 60 threat_model items
- 90 security_test items
- 50 encryption_requirement items
- 70 access_control items

Total: 450+ security items with extensive linking
"""

import os
import sys
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend"))

from dotenv import load_dotenv

load_dotenv()

# Database setup
db_url = os.getenv("DATABASE_URL", "postgresql+asyncpg://tracertm:tracertm_password@localhost:5432/tracertm")
if not db_url.startswith("postgresql+asyncpg://"):
    db_url = db_url.replace("postgresql://", "postgresql+asyncpg://")
DATABASE_URL = db_url
PROJECT_ID = "cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e"

# Item storage for linking
items_db: dict[str, list[str]] = {
    "security_vulnerability": [],
    "security_control": [],
    "threat_model": [],
    "security_test": [],
    "encryption_requirement": [],
    "access_control": [],
    "feature": [],
    "api_endpoint": [],
    "backend_service": [],
}


# === SECURITY VULNERABILITIES (80 items) ===

VULNERABILITIES = [
    # SQL Injection (10 items)
    {
        "title": "SQL Injection in Driver Search Query",
        "description": "Driver search endpoint vulnerable to SQL injection via unparameterized name filter",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "Driver Search API (/api/v1/drivers/search)",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "open",
        "mitigation": "Use parameterized queries with SQLAlchemy ORM. Avoid raw SQL with user input.",
        "remediation_effort": "Medium (2-4 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "SQL Injection in Ride History Filter",
        "description": "Ride history endpoint constructs SQL queries using string concatenation",
        "severity": "critical",
        "cvss_score": 8.9,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "Ride History API (/api/v1/rides/history)",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "in_progress",
        "mitigation": "Migrate to ORM queries, implement input validation",
        "remediation_effort": "Medium (3-5 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Blind SQL Injection in Payment Search",
        "description": "Payment transaction search vulnerable to time-based blind SQL injection",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Payment API (/api/v1/payments/search)",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "open",
        "mitigation": "Use prepared statements, implement rate limiting on search endpoints",
        "remediation_effort": "Low (1-2 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "SQL Injection in Location Query",
        "description": "Geospatial queries vulnerable to injection via latitude/longitude parameters",
        "severity": "high",
        "cvss_score": 8.2,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
        "affected_component": "Location API (/api/v1/locations/nearby)",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "open",
        "mitigation": "Validate numeric inputs, use PostGIS parameterized functions",
        "remediation_effort": "Medium (2-3 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Second-Order SQL Injection in User Profile",
        "description": "Stored user profile data later used in unsafe SQL queries",
        "severity": "high",
        "cvss_score": 7.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "User Profile Service",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "open",
        "mitigation": "Sanitize stored data, use ORM for all queries",
        "remediation_effort": "High (5-8 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "SQL Injection in Admin Dashboard Reports",
        "description": "Custom report generation uses dynamic SQL construction",
        "severity": "critical",
        "cvss_score": 9.4,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:H",
        "affected_component": "Admin Dashboard (/admin/reports)",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "open",
        "mitigation": "Use query builder, restrict admin access, implement SQL injection WAF rules",
        "remediation_effort": "High (8-12 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "NoSQL Injection in MongoDB Driver Ratings",
        "description": "MongoDB queries vulnerable to operator injection via rating filters",
        "severity": "high",
        "cvss_score": 7.2,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N",
        "affected_component": "Driver Rating Service (MongoDB)",
        "vulnerability_type": "NoSQL Injection",
        "cwe_id": "CWE-943",
        "status": "open",
        "mitigation": "Sanitize MongoDB operators, use strict schema validation",
        "remediation_effort": "Medium (3-4 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "SQL Injection in Promo Code Validation",
        "description": "Promotional code validation endpoint vulnerable to union-based injection",
        "severity": "high",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
        "affected_component": "Promo Code API (/api/v1/promos/validate)",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "open",
        "mitigation": "Use parameterized queries, implement strict input validation",
        "remediation_effort": "Low (1-2 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "SQL Injection in Ride Scheduling",
        "description": "Scheduled ride queries vulnerable to time-based injection attacks",
        "severity": "medium",
        "cvss_score": 6.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Ride Scheduling Service",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "open",
        "mitigation": "Refactor to use ORM, add query timeout limits",
        "remediation_effort": "Medium (2-4 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "SQL Injection in Driver Earnings Report",
        "description": "Earnings calculation queries vulnerable to boolean-based blind injection",
        "severity": "high",
        "cvss_score": 7.9,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N",
        "affected_component": "Driver Earnings API (/api/v1/drivers/earnings)",
        "vulnerability_type": "SQL Injection",
        "cwe_id": "CWE-89",
        "status": "resolved",
        "mitigation": "Migrated to SQLAlchemy ORM queries",
        "remediation_effort": "Medium (4 hours)",
        "exploitation_likelihood": "Medium",
    },
    # XSS Vulnerabilities (10 items)
    {
        "title": "Stored XSS in Ride Notes",
        "description": "Ride notes allow HTML input that is rendered without sanitization",
        "severity": "high",
        "cvss_score": 7.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N",
        "affected_component": "Ride Details UI",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "open",
        "mitigation": "Implement DOMPurify sanitization, use textContent instead of innerHTML",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Reflected XSS in Search Results",
        "description": "Search query parameter reflected in page without encoding",
        "severity": "medium",
        "cvss_score": 6.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        "affected_component": "Search UI (/search)",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "open",
        "mitigation": "Encode all output, implement CSP headers",
        "remediation_effort": "Low (1 hour)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "DOM-Based XSS in Route Rendering",
        "description": "Client-side route rendering vulnerable to DOM XSS via URL parameters",
        "severity": "high",
        "cvss_score": 7.4,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:H/A:N",
        "affected_component": "Map Route Renderer",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "open",
        "mitigation": "Use React safe rendering, validate all URL parameters",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Stored XSS in Driver Bio",
        "description": "Driver profile bio field stores and displays unescaped HTML",
        "severity": "high",
        "cvss_score": 7.3,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:L",
        "affected_component": "Driver Profile Page",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "open",
        "mitigation": "Sanitize bio input, implement markdown-only format",
        "remediation_effort": "Medium (2-3 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "XSS in Chat Messages",
        "description": "In-app chat allows JavaScript execution via malicious message content",
        "severity": "critical",
        "cvss_score": 8.2,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:L/A:N",
        "affected_component": "Chat Service",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "in_progress",
        "mitigation": "Implement message sanitization, use safe rendering",
        "remediation_effort": "Medium (4 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "XSS in Support Ticket System",
        "description": "Support ticket descriptions rendered without HTML encoding",
        "severity": "medium",
        "cvss_score": 6.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N",
        "affected_component": "Support Dashboard",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "open",
        "mitigation": "Encode all user-generated content, implement CSP",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "XSS via SVG Upload",
        "description": "Profile image upload allows SVG files with embedded JavaScript",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:L/A:N",
        "affected_component": "Image Upload Service",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "open",
        "mitigation": "Block SVG uploads or sanitize with DOMPurify, serve images from CDN with different origin",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "XSS in Email Notification Templates",
        "description": "Email templates render user data without HTML encoding",
        "severity": "medium",
        "cvss_score": 5.9,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:N",
        "affected_component": "Email Service",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "open",
        "mitigation": "Use email-safe templating engine with auto-escaping",
        "remediation_effort": "Medium (4 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "XSS in Admin Logs Viewer",
        "description": "Admin panel displays log entries containing unsanitized user input",
        "severity": "high",
        "cvss_score": 7.6,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:H/I:L/A:N",
        "affected_component": "Admin Logging Dashboard",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "open",
        "mitigation": "Sanitize log display, implement strict CSP for admin pages",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "XSS in Push Notification Content",
        "description": "Push notification payloads can contain malicious HTML/JavaScript",
        "severity": "medium",
        "cvss_score": 6.3,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N",
        "affected_component": "Push Notification Service",
        "vulnerability_type": "Cross-Site Scripting (XSS)",
        "cwe_id": "CWE-79",
        "status": "resolved",
        "mitigation": "Implemented strict notification content sanitization",
        "remediation_effort": "Low (1 hour)",
        "exploitation_likelihood": "Low",
    },
    # CSRF Vulnerabilities (8 items)
    {
        "title": "CSRF in Payment Method Update",
        "description": "Payment method update endpoint lacks CSRF token validation",
        "severity": "high",
        "cvss_score": 7.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        "affected_component": "Payment API (/api/v1/payment-methods)",
        "vulnerability_type": "Cross-Site Request Forgery (CSRF)",
        "cwe_id": "CWE-352",
        "status": "open",
        "mitigation": "Implement CSRF tokens, use SameSite cookie attributes",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "CSRF in Account Settings",
        "description": "Email and phone number changes vulnerable to CSRF attacks",
        "severity": "high",
        "cvss_score": 6.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        "affected_component": "Account Settings API",
        "vulnerability_type": "Cross-Site Request Forgery (CSRF)",
        "cwe_id": "CWE-352",
        "status": "open",
        "mitigation": "Add CSRF protection, require password confirmation for critical changes",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "CSRF in Ride Cancellation",
        "description": "Ride cancellation endpoint can be triggered via CSRF",
        "severity": "medium",
        "cvss_score": 5.4,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:L",
        "affected_component": "Ride Management API",
        "vulnerability_type": "Cross-Site Request Forgery (CSRF)",
        "cwe_id": "CWE-352",
        "status": "open",
        "mitigation": "Implement CSRF tokens for all state-changing operations",
        "remediation_effort": "Low (1 hour)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "CSRF in Driver Application Submission",
        "description": "Driver application form vulnerable to automated CSRF submissions",
        "severity": "medium",
        "cvss_score": 5.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        "affected_component": "Driver Onboarding",
        "vulnerability_type": "Cross-Site Request Forgery (CSRF)",
        "cwe_id": "CWE-352",
        "status": "open",
        "mitigation": "Add CSRF protection and CAPTCHA",
        "remediation_effort": "Medium (2-3 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "CSRF in Rating Submission",
        "description": "Driver/rider rating submission lacks CSRF protection",
        "severity": "medium",
        "cvss_score": 5.3,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
        "affected_component": "Rating API",
        "vulnerability_type": "Cross-Site Request Forgery (CSRF)",
        "cwe_id": "CWE-352",
        "status": "in_progress",
        "mitigation": "Implement double-submit cookie pattern",
        "remediation_effort": "Low (1-2 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "CSRF in Emergency Contact Update",
        "description": "Emergency contact modification vulnerable to CSRF",
        "severity": "high",
        "cvss_score": 6.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
        "affected_component": "Safety Settings API",
        "vulnerability_type": "Cross-Site Request Forgery (CSRF)",
        "cwe_id": "CWE-352",
        "status": "open",
        "mitigation": "Add CSRF tokens, implement critical action confirmation",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "CSRF in Promo Code Application",
        "description": "Promo code application endpoint lacks CSRF protection",
        "severity": "low",
        "cvss_score": 4.3,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
        "affected_component": "Promo Code API",
        "vulnerability_type": "Cross-Site Request Forgery (CSRF)",
        "cwe_id": "CWE-352",
        "status": "open",
        "mitigation": "Implement CSRF tokens",
        "remediation_effort": "Low (1 hour)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "CSRF in Account Deletion",
        "description": "Account deletion endpoint can be triggered via CSRF attack",
        "severity": "critical",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:H",
        "affected_component": "Account Management API",
        "vulnerability_type": "Cross-Site Request Forgery (CSRF)",
        "cwe_id": "CWE-352",
        "status": "resolved",
        "mitigation": "Added CSRF protection and mandatory email confirmation",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "Medium",
    },
    # Authentication & Session Vulnerabilities (12 items)
    {
        "title": "Session Fixation in Login Flow",
        "description": "Session ID not regenerated after successful authentication",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
        "affected_component": "Authentication Service",
        "vulnerability_type": "Session Fixation",
        "cwe_id": "CWE-384",
        "status": "open",
        "mitigation": "Regenerate session ID on login, use secure session management",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "JWT Secret Key in Source Code",
        "description": "Hard-coded JWT secret key found in authentication module",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "affected_component": "JWT Token Service",
        "vulnerability_type": "Hard-coded Credentials",
        "cwe_id": "CWE-798",
        "status": "open",
        "mitigation": "Move secret to environment variables, rotate all tokens immediately",
        "remediation_effort": "Low (1 hour)",
        "exploitation_likelihood": "Critical",
    },
    {
        "title": "Weak Password Policy",
        "description": "Password policy allows weak passwords (minimum 6 characters, no complexity)",
        "severity": "medium",
        "cvss_score": 6.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "User Registration",
        "vulnerability_type": "Weak Password Requirements",
        "cwe_id": "CWE-521",
        "status": "open",
        "mitigation": "Enforce minimum 12 characters, complexity rules, check against breach databases",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Missing Session Timeout",
        "description": "User sessions never expire, remain valid indefinitely",
        "severity": "high",
        "cvss_score": 7.2,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
        "affected_component": "Session Management",
        "vulnerability_type": "Improper Session Expiration",
        "cwe_id": "CWE-613",
        "status": "open",
        "mitigation": "Implement 30-minute idle timeout, 12-hour absolute timeout",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Insecure Password Reset Token",
        "description": "Password reset tokens predictable (sequential), no expiration",
        "severity": "critical",
        "cvss_score": 8.6,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "Password Reset Flow",
        "vulnerability_type": "Insufficient Entropy",
        "cwe_id": "CWE-330",
        "status": "open",
        "mitigation": "Use cryptographically secure random tokens, 1-hour expiration, one-time use",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "OAuth State Parameter Missing",
        "description": "OAuth flow lacks state parameter for CSRF protection",
        "severity": "high",
        "cvss_score": 7.4,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N",
        "affected_component": "Social Login (OAuth)",
        "vulnerability_type": "CSRF in OAuth",
        "cwe_id": "CWE-352",
        "status": "open",
        "mitigation": "Implement state parameter validation, PKCE for public clients",
        "remediation_effort": "Medium (4 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Concurrent Session Limit Not Enforced",
        "description": "Users can have unlimited concurrent sessions from different devices",
        "severity": "medium",
        "cvss_score": 5.9,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Session Management",
        "vulnerability_type": "Unlimited Session Creation",
        "cwe_id": "CWE-770",
        "status": "open",
        "mitigation": "Limit to 5 concurrent sessions, provide session management UI",
        "remediation_effort": "Medium (4 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "Biometric Authentication Bypass",
        "description": "Biometric authentication can be bypassed via fallback PIN",
        "severity": "medium",
        "cvss_score": 6.3,
        "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
        "affected_component": "Mobile App Authentication",
        "vulnerability_type": "Authentication Bypass",
        "cwe_id": "CWE-287",
        "status": "open",
        "mitigation": "Require re-authentication after 3 failed biometric attempts",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "JWT Algorithm Confusion",
        "description": "JWT library vulnerable to algorithm confusion attacks (HS256/RS256)",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "JWT Token Validation",
        "vulnerability_type": "Algorithm Confusion",
        "cwe_id": "CWE-347",
        "status": "in_progress",
        "mitigation": "Enforce algorithm in verification, update JWT library",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Missing Multi-Factor Authentication",
        "description": "No MFA option available for high-value accounts",
        "severity": "medium",
        "cvss_score": 6.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Account Security",
        "vulnerability_type": "Missing Authentication Factor",
        "cwe_id": "CWE-308",
        "status": "open",
        "mitigation": "Implement TOTP-based MFA, support authenticator apps",
        "remediation_effort": "High (8 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Account Enumeration via Login",
        "description": "Different error messages reveal whether email exists in system",
        "severity": "low",
        "cvss_score": 5.3,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "affected_component": "Login API",
        "vulnerability_type": "Information Disclosure",
        "cwe_id": "CWE-200",
        "status": "open",
        "mitigation": "Use generic error messages for all authentication failures",
        "remediation_effort": "Low (1 hour)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Brute Force Attack Not Rate Limited",
        "description": "Login endpoint lacks rate limiting, allows unlimited attempts",
        "severity": "high",
        "cvss_score": 7.3,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
        "affected_component": "Login API",
        "vulnerability_type": "Missing Rate Limiting",
        "cwe_id": "CWE-307",
        "status": "open",
        "mitigation": "Implement rate limiting (5 attempts/15min), CAPTCHA after failures",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "High",
    },
]

# Will continue with more categories in the next file append
