#!/usr/bin/env python3
"""
Part 2: Additional Security Vulnerabilities and Security Controls
Continuing from generate_swiftride_security.py
"""

# === MORE VULNERABILITIES (continued to reach 80 total) ===

ADDITIONAL_VULNERABILITIES = [
    # Authorization & Access Control (10 items)
    {
        "title": "IDOR in Ride Details API",
        "description": "Ride details accessible by guessing sequential ride IDs without authorization",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Ride API (/api/v1/rides/{id})",
        "vulnerability_type": "Insecure Direct Object Reference",
        "cwe_id": "CWE-639",
        "status": "open",
        "mitigation": "Implement authorization checks, use UUIDs instead of sequential IDs",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Privilege Escalation in Driver Portal",
        "description": "Regular drivers can access admin functions by modifying role parameter",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:H",
        "affected_component": "Driver Portal",
        "vulnerability_type": "Privilege Escalation",
        "cwe_id": "CWE-269",
        "status": "open",
        "mitigation": "Validate role server-side, implement proper RBAC",
        "remediation_effort": "High (6 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Missing Authorization on Payment Refund",
        "description": "Payment refund endpoint lacks authorization check",
        "severity": "critical",
        "cvss_score": 8.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H",
        "affected_component": "Payment Refund API",
        "vulnerability_type": "Missing Authorization",
        "cwe_id": "CWE-862",
        "status": "open",
        "mitigation": "Implement strict authorization and approval workflow",
        "remediation_effort": "High (5 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "IDOR in User Profile Update",
        "description": "Users can update other users profiles by changing user_id parameter",
        "severity": "high",
        "cvss_score": 8.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H",
        "affected_component": "Profile API",
        "vulnerability_type": "Insecure Direct Object Reference",
        "cwe_id": "CWE-639",
        "status": "open",
        "mitigation": "Use authenticated user context, never trust client-provided IDs",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Path Traversal in Driver Document Upload",
        "description": "Document upload allows directory traversal via filename",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:N",
        "affected_component": "Document Upload Service",
        "vulnerability_type": "Path Traversal",
        "cwe_id": "CWE-22",
        "status": "open",
        "mitigation": "Sanitize filenames, use content-based storage (S3), validate file types",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Mass Assignment in User Registration",
        "description": "User registration allows setting admin flag via JSON payload",
        "severity": "critical",
        "cvss_score": 8.6,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "Registration API",
        "vulnerability_type": "Mass Assignment",
        "cwe_id": "CWE-915",
        "status": "resolved",
        "mitigation": "Use explicit field whitelisting, implemented DTOs",
        "remediation_effort": "Medium (4 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Unauthorized Access to Admin Analytics",
        "description": "Business analytics endpoints lack role-based access control",
        "severity": "high",
        "cvss_score": 7.7,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Analytics API",
        "vulnerability_type": "Missing Authorization",
        "cwe_id": "CWE-862",
        "status": "open",
        "mitigation": "Implement role-based middleware, audit access logs",
        "remediation_effort": "Medium (4 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Horizontal Privilege Escalation in Messaging",
        "description": "Users can read messages from other rides by changing conversation ID",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Messaging Service",
        "vulnerability_type": "Broken Access Control",
        "cwe_id": "CWE-639",
        "status": "open",
        "mitigation": "Validate conversation participants before returning messages",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "API Rate Limiting Bypass",
        "description": "API rate limits can be bypassed by rotating IP addresses",
        "severity": "medium",
        "cvss_score": 6.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
        "affected_component": "API Gateway",
        "vulnerability_type": "Rate Limiting Bypass",
        "cwe_id": "CWE-770",
        "status": "open",
        "mitigation": "Implement user-based rate limiting, use CAPTCHA for suspicious patterns",
        "remediation_effort": "High (6 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "IDOR in Driver Earnings Export",
        "description": "Earnings export endpoint allows downloading any drivers financial data",
        "severity": "critical",
        "cvss_score": 8.2,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Earnings Export API",
        "vulnerability_type": "Insecure Direct Object Reference",
        "cwe_id": "CWE-639",
        "status": "open",
        "mitigation": "Enforce driver-specific authorization, audit all export requests",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "High",
    },
    # Data Exposure & Privacy (10 items)
    {
        "title": "Sensitive Data in API Response",
        "description": "User API returns full credit card numbers and SSNs",
        "severity": "critical",
        "cvss_score": 9.1,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "User API",
        "vulnerability_type": "Sensitive Data Exposure",
        "cwe_id": "CWE-200",
        "status": "open",
        "mitigation": "Mask sensitive data, return only last 4 digits",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Unencrypted Database Backups",
        "description": "Database backups stored without encryption in S3",
        "severity": "critical",
        "cvss_score": 8.9,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "Backup System",
        "vulnerability_type": "Unencrypted Data at Rest",
        "cwe_id": "CWE-311",
        "status": "open",
        "mitigation": "Enable S3 encryption (SSE-KMS), encrypt backups before upload",
        "remediation_effort": "Medium (3 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "PII in Application Logs",
        "description": "Application logs contain unredacted PII (names, phone numbers, addresses)",
        "severity": "high",
        "cvss_score": 7.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "Logging System",
        "vulnerability_type": "Sensitive Data in Logs",
        "cwe_id": "CWE-532",
        "status": "open",
        "mitigation": "Implement log scrubbing, redact PII before logging",
        "remediation_effort": "High (8 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Location History Not Anonymized",
        "description": "Historical location data retained indefinitely with user IDs",
        "severity": "high",
        "cvss_score": 7.4,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Location Tracking Service",
        "vulnerability_type": "Privacy Violation",
        "cwe_id": "CWE-359",
        "status": "open",
        "mitigation": "Anonymize after 90 days, implement data retention policy",
        "remediation_effort": "High (12 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "Inadequate Data Deletion",
        "description": "Account deletion does not remove user data from backups or logs",
        "severity": "medium",
        "cvss_score": 6.5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "affected_component": "Data Deletion Service",
        "vulnerability_type": "Incomplete Data Deletion",
        "cwe_id": "CWE-404",
        "status": "open",
        "mitigation": "Implement right to erasure, mark for deletion in backups",
        "remediation_effort": "High (10 hours)",
        "exploitation_likelihood": "Low",
    },
    {
        "title": "Cleartext Transmission of Credentials",
        "description": "Legacy mobile app versions send passwords over HTTP",
        "severity": "critical",
        "cvss_score": 9.8,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "affected_component": "Mobile App v1.x",
        "vulnerability_type": "Cleartext Transmission",
        "cwe_id": "CWE-319",
        "status": "in_progress",
        "mitigation": "Force app update, deprecate HTTP endpoints",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Driver Background Check Data Exposed",
        "description": "Background check results viewable by any authenticated user",
        "severity": "critical",
        "cvss_score": 8.7,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "Driver Verification Service",
        "vulnerability_type": "Sensitive Data Exposure",
        "cwe_id": "CWE-200",
        "status": "open",
        "mitigation": "Restrict access to HR/compliance roles only, audit access",
        "remediation_effort": "Medium (4 hours)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "Payment Card Data Stored Unencrypted",
        "description": "Full card numbers stored in database without encryption",
        "severity": "critical",
        "cvss_score": 9.4,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:N",
        "affected_component": "Payment Database",
        "vulnerability_type": "PCI-DSS Violation",
        "cwe_id": "CWE-311",
        "status": "open",
        "mitigation": "Migrate to tokenization (Stripe), never store full PANs",
        "remediation_effort": "Critical (16+ hours)",
        "exploitation_likelihood": "High",
    },
    {
        "title": "Debug Endpoints in Production",
        "description": "Debug endpoints exposing environment variables and configs accessible in production",
        "severity": "critical",
        "cvss_score": 8.6,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "affected_component": "Debug API (/debug/config)",
        "vulnerability_type": "Information Disclosure",
        "cwe_id": "CWE-215",
        "status": "resolved",
        "mitigation": "Disabled debug endpoints in production",
        "remediation_effort": "Low (1 hour)",
        "exploitation_likelihood": "Medium",
    },
    {
        "title": "User Email Addresses Publicly Searchable",
        "description": "User search API returns email addresses without authentication",
        "severity": "medium",
        "cvss_score": 5.3,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "affected_component": "User Search API",
        "vulnerability_type": "Information Disclosure",
        "cwe_id": "CWE-359",
        "status": "open",
        "mitigation": "Require authentication, filter sensitive fields from search results",
        "remediation_effort": "Low (2 hours)",
        "exploitation_likelihood": "High",
    },
]

# Continue with more categories...
