#!/usr/bin/env python3
"""Complete SwiftRide Quality & Compliance Item Generator.

Generates 570+ items across 7 types with proper metadata and relationships.
"""

PROJECT_ID = "cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e"
DATABASE_URL = "postgresql://tracertm:tracertm_password@localhost:5432/tracertm"


class QualityData:
    """All quality item data definitions."""

    @staticmethod
    def get_quality_gates() -> None:
        """60 quality gate items."""
        return [
            # Code Coverage Gates (10)
            {
                "title": "Unit Test Coverage >= 80%",
                "description": "All Python/TypeScript modules must maintain minimum 80% unit test coverage. Measured via pytest-cov and jest --coverage. Blocks merge if below threshold.",
                "priority": 1,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 80,
                    "metric": "line_coverage",
                    "tools": ["pytest-cov", "jest"],
                    "automation": "CI pipeline",
                },
                "tags": ["coverage", "unit-test", "quality-gate", "blocking", "ci"],
            },
            {
                "title": "Integration Test Coverage >= 70%",
                "description": "Integration tests must cover at least 70% of API endpoints and service-to-service interactions. Includes database, message queue, and external API integration points.",
                "priority": 1,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 70,
                    "metric": "integration_coverage",
                    "scope": "api_endpoints",
                },
                "tags": ["coverage", "integration-test", "quality-gate", "api"],
            },
            {
                "title": "E2E Test Coverage >= 60%",
                "description": "End-to-end tests must cover 60%+ of critical user journeys: ride booking, payment flow, driver matching, SOS emergency, and ride completion.",
                "priority": 2,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 60,
                    "critical_flows": ["ride_booking", "payment", "driver_matching", "sos", "completion"],
                },
                "tags": ["coverage", "e2e-test", "quality-gate", "user-journey"],
            },
            {
                "title": "Branch Coverage >= 75%",
                "description": "All conditional branches (if/else, switch, ternary) must be tested with minimum 75% coverage to ensure decision logic validation.",
                "priority": 2,
                "metadata": {"gate_type": "coverage", "threshold": 75, "metric": "branch_coverage"},
                "tags": ["coverage", "branch-coverage", "quality-gate", "logic"],
            },
            {
                "title": "Mutation Score >= 65%",
                "description": "Mutation testing score must be at least 65% to ensure test quality and effectiveness. Use mutmut for Python, Stryker for TypeScript.",
                "priority": 3,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 65,
                    "metric": "mutation_score",
                    "tools": ["mutmut", "stryker"],
                },
                "tags": ["coverage", "mutation-testing", "quality-gate", "test-quality"],
            },
            {
                "title": "Frontend Component Coverage >= 85%",
                "description": "React components must have 85%+ test coverage including user interactions, state changes, and prop validation using React Testing Library.",
                "priority": 1,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 85,
                    "framework": "react",
                    "library": "react-testing-library",
                },
                "tags": ["coverage", "frontend", "react", "quality-gate", "components"],
            },
            {
                "title": "API Contract Coverage 100%",
                "description": "All OpenAPI-documented endpoints must have corresponding contract tests validating request/response schemas and error codes.",
                "priority": 1,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 100,
                    "metric": "api_contract_coverage",
                    "standard": "OpenAPI_3.0",
                },
                "tags": ["coverage", "api", "contract-testing", "quality-gate", "openapi"],
            },
            {
                "title": "Critical Path Coverage 100%",
                "description": "All critical business paths must be 100% covered: complete ride lifecycle (request->match->pickup->dropoff->payment), safety SOS flow, surge pricing.",
                "priority": 1,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 100,
                    "paths": ["ride_lifecycle", "payment_flow", "sos_emergency", "surge_pricing"],
                },
                "tags": ["coverage", "critical-path", "quality-gate", "business-logic", "blocking"],
            },
            {
                "title": "Error Handling Coverage >= 80%",
                "description": "All error scenarios and exception handlers must be tested with 80%+ coverage including network failures, timeouts, invalid inputs, and system errors.",
                "priority": 2,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 80,
                    "focus": "error_handling",
                    "scenarios": ["network_failure", "timeout", "invalid_input", "system_error"],
                },
                "tags": ["coverage", "error-handling", "quality-gate", "resilience"],
            },
            {
                "title": "Security Test Coverage >= 90%",
                "description": "Security-critical code paths must have 90%+ coverage: authentication, authorization, payment processing, PII handling, input validation.",
                "priority": 1,
                "metadata": {
                    "gate_type": "coverage",
                    "threshold": 90,
                    "domains": ["authentication", "authorization", "payment", "pii", "validation"],
                },
                "tags": ["coverage", "security", "quality-gate", "critical", "pii"],
            },
            # Security Gates (10)
            {
                "title": "Zero Critical Security Vulnerabilities",
                "description": "No critical (CVSS 9.0-10.0) vulnerabilities allowed in dependencies or code. Scanned via Snyk, Trivy, and Safety. Blocks deployment if critical found.",
                "priority": 1,
                "metadata": {
                    "gate_type": "security",
                    "max_critical": 0,
                    "cvss_range": "9.0-10.0",
                    "tools": ["snyk", "trivy", "safety"],
                    "enforcement": "blocking",
                },
                "tags": ["security", "vulnerabilities", "quality-gate", "critical", "blocking", "cvss"],
            },
            {
                "title": "No High Severity Vulnerabilities",
                "description": "High severity vulnerabilities (CVSS 7.0-8.9) must be resolved before production release. Grace period: 48 hours for non-blocking, then blocks merge.",
                "priority": 1,
                "metadata": {"gate_type": "security", "max_high": 0, "cvss_range": "7.0-8.9", "grace_period_hours": 48},
                "tags": ["security", "vulnerabilities", "quality-gate", "high-severity"],
            },
            {
                "title": "OWASP Top 10 Compliance",
                "description": "Must pass OWASP Top 10 2021 security checks: Injection, Broken Authentication, XSS, XXE, Broken Access Control, Security Misconfiguration, Sensitive Data Exposure.",
                "priority": 1,
                "metadata": {
                    "gate_type": "security",
                    "standard": "OWASP_Top_10_2021",
                    "checks": [
                        "injection",
                        "broken_auth",
                        "xss",
                        "xxe",
                        "access_control",
                        "misconfig",
                        "data_exposure",
                    ],
                },
                "tags": ["security", "owasp", "quality-gate", "compliance", "top-10"],
            },
            {
                "title": "Dependency Audit Pass",
                "description": "All bun/pip/go dependencies must pass security audit with zero known vulnerabilities. Run bun audit, pip-audit, govulncheck daily.",
                "priority": 2,
                "metadata": {
                    "gate_type": "security",
                    "commands": {"bun": "bun audit", "python": "pip-audit", "go": "govulncheck"},
                    "frequency": "daily",
                },
                "tags": ["security", "dependencies", "quality-gate", "audit", "supply-chain"],
            },
            {
                "title": "Secrets Detection Pass",
                "description": "No secrets, API keys, credentials, or tokens in codebase. Scanned via TruffleHog, GitLeaks, and detect-secrets. Includes commit history scan.",
                "priority": 1,
                "metadata": {
                    "gate_type": "security",
                    "tools": ["trufflehog", "gitleaks", "detect-secrets"],
                    "scope": ["code", "commits", "config", "history"],
                },
                "tags": ["security", "secrets", "quality-gate", "blocking", "credentials"],
            },
            {
                "title": "Authentication Strength Validation",
                "description": "All authentication must use strong protocols: OAuth2 with PKCE, JWT with RS256 (no HS256), MFA support, session expiry <=24h.",
                "priority": 1,
                "metadata": {
                    "gate_type": "security",
                    "required": ["OAuth2_PKCE", "JWT_RS256", "MFA"],
                    "forbidden": ["basic_auth", "JWT_HS256", "md5", "sha1"],
                    "session_max_hours": 24,
                },
                "tags": ["security", "authentication", "quality-gate", "oauth2", "jwt"],
            },
            {
                "title": "PII Encryption Compliance",
                "description": "All PII (phone, email, payment info, location history) must use AES-256 encryption at rest and TLS 1.3 in transit. Regular encryption audit required.",
                "priority": 1,
                "metadata": {
                    "gate_type": "security",
                    "at_rest": "AES-256",
                    "in_transit": "TLS_1.3",
                    "pii_fields": ["phone", "email", "payment", "location", "identity"],
                    "audit_frequency": "quarterly",
                },
                "tags": ["security", "encryption", "pii", "quality-gate", "compliance", "gdpr"],
            },
            {
                "title": "SQL Injection Prevention",
                "description": "All database queries must use parameterized queries or ORM. Zero string concatenation in SQL. Enforced via semgrep and sqlmap testing.",
                "priority": 1,
                "metadata": {
                    "gate_type": "security",
                    "requirement": "parameterized_queries",
                    "forbidden": "string_concatenation",
                    "tools": ["semgrep", "sqlmap"],
                },
                "tags": ["security", "sql-injection", "quality-gate", "database", "owasp"],
            },
            {
                "title": "CSRF Protection Enabled",
                "description": "All state-changing endpoints must have CSRF token validation. Exempt only: health checks, metrics. Use double-submit cookie or synchronizer token pattern.",
                "priority": 1,
                "metadata": {
                    "gate_type": "security",
                    "protection": "csrf",
                    "pattern": ["double_submit_cookie", "synchronizer_token"],
                    "exempt": ["/health", "/metrics"],
                },
                "tags": ["security", "csrf", "quality-gate", "web-security"],
            },
            {
                "title": "Rate Limiting Configured",
                "description": "All public endpoints must have rate limiting: Auth 100/min, API 1000/min, Payment 10/min, Location 10000/min. Implement sliding window algorithm.",
                "priority": 2,
                "metadata": {
                    "gate_type": "security",
                    "limits": {"auth": "100/min", "api": "1000/min", "payment": "10/min", "location": "10000/min"},
                    "algorithm": "sliding_window",
                },
                "tags": ["security", "rate-limiting", "quality-gate", "ddos", "abuse-prevention"],
            },
            # Performance Gates (10)
            {
                "title": "API Response Time p95 < 200ms",
                "description": "95th percentile API response time must be under 200ms for all endpoints. Measured in production and load testing. Alerts at 150ms.",
                "priority": 1,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "response_time_p95",
                    "threshold": 200,
                    "unit": "ms",
                    "alert_threshold": 150,
                },
                "tags": ["performance", "api", "latency", "quality-gate", "p95"],
            },
            {
                "title": "API Response Time p99 < 500ms",
                "description": "99th percentile API response time must be under 500ms to ensure consistent user experience even at tail latencies.",
                "priority": 2,
                "metadata": {"gate_type": "performance", "metric": "response_time_p99", "threshold": 500, "unit": "ms"},
                "tags": ["performance", "api", "latency", "quality-gate", "p99", "tail-latency"],
            },
            {
                "title": "Database Query p95 < 50ms",
                "description": "95th percentile database query time must be under 50ms. Includes connection time. Optimize slow queries, add indexes.",
                "priority": 1,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "db_query_p95",
                    "threshold": 50,
                    "unit": "ms",
                    "includes": "connection_time",
                },
                "tags": ["performance", "database", "query", "quality-gate", "postgresql"],
            },
            {
                "title": "Frontend Load Time < 2s",
                "description": "Initial page load must complete in under 2 seconds on 4G connection (simulated). Measured via Lighthouse, WebPageTest.",
                "priority": 2,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "page_load_time",
                    "threshold": 2000,
                    "unit": "ms",
                    "network": "4G",
                    "tools": ["lighthouse", "webpagetest"],
                },
                "tags": ["performance", "frontend", "loading", "quality-gate", "web-vitals"],
            },
            {
                "title": "Memory Usage < 512MB per Service",
                "description": "Each microservice must use less than 512MB memory under normal load. Measured via Prometheus. Alert at 400MB.",
                "priority": 2,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "memory_usage",
                    "threshold": 512,
                    "unit": "MB",
                    "scope": "per_service",
                    "alert_threshold": 400,
                },
                "tags": ["performance", "memory", "resources", "quality-gate", "microservices"],
            },
            {
                "title": "CPU Usage < 70% per Service",
                "description": "CPU usage must stay below 70% under normal load for each service. Sustained high CPU triggers auto-scaling.",
                "priority": 2,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "cpu_usage",
                    "threshold": 70,
                    "unit": "percent",
                    "action": "auto_scale",
                },
                "tags": ["performance", "cpu", "resources", "quality-gate", "scaling"],
            },
            {
                "title": "Throughput >= 1000 req/sec",
                "description": "System must handle minimum 1000 requests per second under load with <5% error rate. Load test with K6 or Locust.",
                "priority": 1,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "throughput",
                    "threshold": 1000,
                    "unit": "req/sec",
                    "max_error_rate": 5,
                    "tools": ["k6", "locust"],
                },
                "tags": ["performance", "throughput", "scalability", "quality-gate", "load-testing"],
            },
            {
                "title": "Bundle Size < 200KB (gzipped)",
                "description": "Frontend JavaScript bundle must be under 200KB after gzip compression. Use code splitting and lazy loading.",
                "priority": 2,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "bundle_size",
                    "threshold": 200,
                    "unit": "KB",
                    "compression": "gzip",
                    "techniques": ["code_splitting", "lazy_loading"],
                },
                "tags": ["performance", "frontend", "bundle", "quality-gate", "optimization"],
            },
            {
                "title": "Time to Interactive < 3.5s",
                "description": "Page must be fully interactive (TTI) in under 3.5 seconds. All JavaScript loaded and main thread idle.",
                "priority": 2,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "time_to_interactive",
                    "threshold": 3500,
                    "unit": "ms",
                    "requirements": ["js_loaded", "main_thread_idle"],
                },
                "tags": ["performance", "frontend", "tti", "quality-gate", "web-vitals"],
            },
            {
                "title": "First Contentful Paint < 1.5s",
                "description": "First Contentful Paint must occur within 1.5 seconds to provide fast perceived performance.",
                "priority": 2,
                "metadata": {
                    "gate_type": "performance",
                    "metric": "first_contentful_paint",
                    "threshold": 1500,
                    "unit": "ms",
                },
                "tags": ["performance", "frontend", "fcp", "quality-gate", "web-vitals"],
            },
            # Build & CI/CD Gates (10)
            {
                "title": "Build Success Rate >= 95%",
                "description": "CI/CD builds must succeed at least 95% of the time over rolling 7-day window. Track build stability metrics.",
                "priority": 2,
                "metadata": {"gate_type": "cicd", "metric": "build_success_rate", "threshold": 95, "window": "7_days"},
                "tags": ["cicd", "build", "quality-gate", "stability"],
            },
            {
                "title": "Build Time < 10 minutes",
                "description": "Full CI/CD pipeline (lint, test, build, scan) must complete in under 10 minutes for fast feedback.",
                "priority": 3,
                "metadata": {
                    "gate_type": "cicd",
                    "metric": "build_time",
                    "threshold": 10,
                    "unit": "minutes",
                    "stages": ["lint", "test", "build", "scan"],
                },
                "tags": ["cicd", "build", "performance", "quality-gate", "developer-experience"],
            },
            {
                "title": "Zero Linter Errors",
                "description": "Code must pass all linter checks with zero errors. Use eslint (TypeScript), pylint/ruff (Python), golangci-lint (Go).",
                "priority": 1,
                "metadata": {
                    "gate_type": "cicd",
                    "max_errors": 0,
                    "linters": {"typescript": "eslint", "python": "pylint/ruff", "go": "golangci-lint"},
                },
                "tags": ["cicd", "linting", "code-quality", "quality-gate", "blocking"],
            },
            {
                "title": "Linter Warnings < 10",
                "description": "Maximum 10 linter warnings allowed across entire codebase. Track trend - should decrease over time.",
                "priority": 2,
                "metadata": {"gate_type": "cicd", "max_warnings": 10, "trend": "decreasing"},
                "tags": ["cicd", "linting", "quality-gate", "code-health"],
            },
            {
                "title": "Type Coverage >= 90%",
                "description": "TypeScript strict mode and Python type hints must cover 90% of code. Use mypy --strict and tsc --noImplicitAny.",
                "priority": 2,
                "metadata": {
                    "gate_type": "cicd",
                    "metric": "type_coverage",
                    "threshold": 90,
                    "tools": {"typescript": "tsc --strict", "python": "mypy --strict"},
                },
                "tags": ["cicd", "types", "quality-gate", "type-safety"],
            },
            {
                "title": "Code Complexity < 10 (Cyclomatic)",
                "description": "Maximum cyclomatic complexity of 10 for any function/method. Refactor complex functions.",
                "priority": 2,
                "metadata": {
                    "gate_type": "cicd",
                    "metric": "cyclomatic_complexity",
                    "threshold": 10,
                    "tools": {"python": "radon", "typescript": "eslint-complexity"},
                },
                "tags": ["cicd", "complexity", "maintainability", "quality-gate", "refactoring"],
            },
            {
                "title": "Code Duplication < 3%",
                "description": "No more than 3% code duplication across codebase. Use DRY principle, extract common logic.",
                "priority": 3,
                "metadata": {
                    "gate_type": "cicd",
                    "metric": "code_duplication",
                    "threshold": 3,
                    "unit": "percent",
                    "tools": ["jscpd", "pylint"],
                },
                "tags": ["cicd", "duplication", "quality-gate", "dry"],
            },
            {
                "title": "Docker Image Size < 500MB",
                "description": "Production Docker images must be under 500MB. Use multi-stage builds, alpine base images.",
                "priority": 3,
                "metadata": {
                    "gate_type": "cicd",
                    "metric": "docker_image_size",
                    "threshold": 500,
                    "unit": "MB",
                    "optimizations": ["multi_stage", "alpine"],
                },
                "tags": ["cicd", "docker", "size", "quality-gate", "optimization"],
            },
            {
                "title": "Docker Security Scan Pass",
                "description": "Docker images must pass security scan with no critical/high vulnerabilities. Use Trivy, Snyk Container.",
                "priority": 1,
                "metadata": {
                    "gate_type": "cicd",
                    "scan": "docker_security",
                    "tools": ["trivy", "snyk-container"],
                    "max_critical": 0,
                    "max_high": 0,
                },
                "tags": ["cicd", "docker", "security", "quality-gate", "container"],
            },
            {
                "title": "Deployment Rollback < 2 minutes",
                "description": "Failed deployments must be rolled back within 2 minutes automatically. Test rollback procedures monthly.",
                "priority": 1,
                "metadata": {
                    "gate_type": "cicd",
                    "metric": "rollback_time",
                    "threshold": 2,
                    "unit": "minutes",
                    "automation": "automatic",
                    "test_frequency": "monthly",
                },
                "tags": ["cicd", "deployment", "rollback", "quality-gate", "reliability"],
            },
            # Documentation Gates (10)
            {
                "title": "API Documentation Coverage 100%",
                "description": "All API endpoints must have OpenAPI 3.0 documentation with request/response examples and error codes.",
                "priority": 2,
                "metadata": {
                    "gate_type": "documentation",
                    "metric": "api_doc_coverage",
                    "threshold": 100,
                    "format": "openapi_3.0",
                    "includes": ["examples", "error_codes"],
                },
                "tags": ["documentation", "api", "quality-gate", "openapi"],
            },
            {
                "title": "Code Comment Density >= 15%",
                "description": "At least 15% of code lines should have meaningful comments explaining complex logic and business rules.",
                "priority": 3,
                "metadata": {
                    "gate_type": "documentation",
                    "metric": "comment_density",
                    "threshold": 15,
                    "unit": "percent",
                    "focus": ["complex_logic", "business_rules"],
                },
                "tags": ["documentation", "comments", "quality-gate", "readability"],
            },
            {
                "title": "README Files for All Services",
                "description": "Each microservice must have comprehensive README: setup, usage, API, configuration, troubleshooting sections.",
                "priority": 2,
                "metadata": {
                    "gate_type": "documentation",
                    "required_sections": ["setup", "usage", "api", "configuration", "troubleshooting"],
                    "scope": "per_service",
                },
                "tags": ["documentation", "readme", "quality-gate", "microservices"],
            },
            {
                "title": "Architecture Decision Records (ADRs)",
                "description": "All major architectural decisions must be documented as ADRs with context, decision, consequences.",
                "priority": 2,
                "metadata": {
                    "gate_type": "documentation",
                    "format": "ADR",
                    "template": "madr",
                    "sections": ["context", "decision", "consequences"],
                    "scope": "major_decisions",
                },
                "tags": ["documentation", "adr", "architecture", "quality-gate"],
            },
            {
                "title": "Public API Inline Documentation",
                "description": "All public functions/classes must have docstrings (Python) or JSDoc (TypeScript) with params, returns, examples.",
                "priority": 2,
                "metadata": {
                    "gate_type": "documentation",
                    "scope": "public_api",
                    "formats": {"python": "docstring", "typescript": "jsdoc"},
                    "includes": ["params", "returns", "examples"],
                },
                "tags": ["documentation", "inline", "quality-gate", "api"],
            },
            {
                "title": "Database Schema Documentation",
                "description": "All database tables and relationships must be documented with ER diagrams and table/column descriptions.",
                "priority": 3,
                "metadata": {
                    "gate_type": "documentation",
                    "scope": "database_schema",
                    "includes": ["er_diagram", "table_descriptions", "column_descriptions", "relationships"],
                },
                "tags": ["documentation", "database", "quality-gate", "schema"],
            },
            {
                "title": "Deployment Runbooks Complete",
                "description": "Deployment runbooks required for all services: deployment steps, rollback procedures, smoke tests, troubleshooting.",
                "priority": 2,
                "metadata": {
                    "gate_type": "documentation",
                    "type": "runbook",
                    "sections": ["deployment", "rollback", "smoke_tests", "troubleshooting"],
                    "scope": "per_service",
                },
                "tags": ["documentation", "runbook", "deployment", "quality-gate", "operations"],
            },
            {
                "title": "Incident Response Playbooks",
                "description": "Playbooks must exist for critical incidents: outage, security breach, data loss, payment failure with clear action steps.",
                "priority": 1,
                "metadata": {
                    "gate_type": "documentation",
                    "type": "playbook",
                    "incidents": ["outage", "security_breach", "data_loss", "payment_failure"],
                    "includes": "action_steps",
                },
                "tags": ["documentation", "incident", "playbook", "quality-gate", "critical"],
            },
            {
                "title": "Changelog Maintained",
                "description": "CHANGELOG.md must be updated for every release following Keep a Changelog format with Added, Changed, Fixed sections.",
                "priority": 3,
                "metadata": {
                    "gate_type": "documentation",
                    "file": "CHANGELOG.md",
                    "format": "keep_a_changelog",
                    "sections": ["Added", "Changed", "Fixed", "Removed"],
                },
                "tags": ["documentation", "changelog", "quality-gate", "releases"],
            },
            {
                "title": "Onboarding Documentation Current",
                "description": "New developer onboarding guide must be complete and tested quarterly: setup, architecture, workflows, tools.",
                "priority": 3,
                "metadata": {
                    "gate_type": "documentation",
                    "type": "onboarding",
                    "test_frequency": "quarterly",
                    "sections": ["setup", "architecture", "workflows", "tools"],
                },
                "tags": ["documentation", "onboarding", "quality-gate", "developer-experience"],
            },
            # Data Quality Gates (10)
            {
                "title": "Zero Data Loss on Deployment",
                "description": "Database migrations must not cause data loss. All migrations must be reversible and tested in staging first.",
                "priority": 1,
                "metadata": {
                    "gate_type": "data_quality",
                    "requirement": "zero_loss",
                    "migration_reversible": True,
                    "test_environment": "staging",
                },
                "tags": ["data", "migration", "quality-gate", "critical", "blocking"],
            },
            {
                "title": "Data Validation Pass Rate >= 99%",
                "description": "99% of input data must pass validation before database insert. Track validation failures for data quality insights.",
                "priority": 1,
                "metadata": {
                    "gate_type": "data_quality",
                    "metric": "validation_pass_rate",
                    "threshold": 99,
                    "track_failures": True,
                },
                "tags": ["data", "validation", "quality-gate", "input"],
            },
            {
                "title": "Data Consistency Checks Pass",
                "description": "Referential integrity and consistency checks must pass for critical entities: rides, payments, users, drivers.",
                "priority": 1,
                "metadata": {
                    "gate_type": "data_quality",
                    "check": "consistency",
                    "entities": ["rides", "payments", "users", "drivers"],
                    "includes": "referential_integrity",
                },
                "tags": ["data", "consistency", "quality-gate", "integrity"],
            },
            {
                "title": "Database Backup Success 100%",
                "description": "All scheduled database backups (hourly) must succeed. Alert immediately on any failure. Test restores monthly.",
                "priority": 1,
                "metadata": {
                    "gate_type": "data_quality",
                    "metric": "backup_success_rate",
                    "threshold": 100,
                    "frequency": "hourly",
                    "test_restore": "monthly",
                },
                "tags": ["data", "backup", "quality-gate", "critical", "disaster-recovery"],
            },
            {
                "title": "Backup Restore Test Monthly",
                "description": "Backup restore procedures must be tested monthly with success validation. Document restore time (target < 1 hour).",
                "priority": 1,
                "metadata": {
                    "gate_type": "data_quality",
                    "test": "backup_restore",
                    "frequency": "monthly",
                    "target_restore_time": 60,
                    "unit": "minutes",
                },
                "tags": ["data", "backup", "restore", "quality-gate", "testing"],
            },
            {
                "title": "Data Retention Policy Compliance",
                "description": "Old data must be archived/deleted per retention policy: 90 days for logs, 2 years for rides, 7 years for financial.",
                "priority": 2,
                "metadata": {
                    "gate_type": "data_quality",
                    "policy": "retention",
                    "periods": {"logs": "90_days", "rides": "2_years", "financial": "7_years"},
                },
                "tags": ["data", "retention", "compliance", "quality-gate", "gdpr"],
            },
            {
                "title": "PII Anonymization in Non-Prod",
                "description": "All PII must be anonymized in dev/staging: phone, email, name, payment info, location. Use realistic fake data.",
                "priority": 1,
                "metadata": {
                    "gate_type": "data_quality",
                    "requirement": "pii_anonymization",
                    "environments": ["dev", "staging"],
                    "fields": ["phone", "email", "name", "payment", "location"],
                    "method": "faker",
                },
                "tags": ["data", "pii", "anonymization", "quality-gate", "compliance", "gdpr"],
            },
            {
                "title": "Data Quality Score >= 95%",
                "description": "Overall data quality score (completeness, accuracy, consistency, timeliness) must be 95%+. Monitor per table.",
                "priority": 2,
                "metadata": {
                    "gate_type": "data_quality",
                    "metric": "dq_score",
                    "threshold": 95,
                    "dimensions": ["completeness", "accuracy", "consistency", "timeliness"],
                    "granularity": "per_table",
                },
                "tags": ["data", "quality-score", "quality-gate", "monitoring"],
            },
            {
                "title": "Duplicate Records < 0.1%",
                "description": "Duplicate records must be less than 0.1% of total. Implement unique constraints, deduplication jobs.",
                "priority": 2,
                "metadata": {
                    "gate_type": "data_quality",
                    "metric": "duplicate_rate",
                    "threshold": 0.1,
                    "unit": "percent",
                    "solutions": ["unique_constraints", "dedup_jobs"],
                },
                "tags": ["data", "duplicates", "quality-gate", "cleanliness"],
            },
            {
                "title": "Data Freshness < 5 minutes",
                "description": "Critical real-time data (location, ride status, driver availability) must be no older than 5 minutes.",
                "priority": 1,
                "metadata": {
                    "gate_type": "data_quality",
                    "metric": "data_freshness",
                    "threshold": 5,
                    "unit": "minutes",
                    "data_types": ["location", "ride_status", "driver_availability"],
                },
                "tags": ["data", "freshness", "real-time", "quality-gate", "critical"],
            },
        ]


# Continue with get_code_standards, get_performance_benchmarks, get_slas, get_bugs, get_technical_debt, get_refactoring_opportunities...
# Due to length, showing structure with first complete section
