export type {
	BlockerFn,
	HistoryLocation,
	HistoryState,
	ParsedPath,
	RouterHistory,
} from "@tanstack/history";
export {
	createBrowserHistory,
	createHashHistory,
	createHistory,
	createMemoryHistory,
} from "@tanstack/history";
export type {
	AbsoluteToPath,
	ActiveOptions,
	AnyContext,
	AnyPathParams,
	AnyRedirect,
	AnyRoute,
	AnyRouteMatch,
	AnyRouter,
	AnyRouterWithContext,
	AnyRouteWithContext,
	AnySchema,
	AnySerializationAdapter,
	AnyValidator,
	AnyValidatorAdapter,
	AnyValidatorFn,
	AnyValidatorObj,
	Assign,
	BaseRouteOptions,
	BeforeLoadContextOptions,
	BeforeLoadContextParameter,
	BuildLocationFn,
	BuildNextOptions,
	CommitLocationOptions,
	Constrain,
	ContextAsyncReturnType,
	ContextOptions,
	ContextReturnType,
	ControllablePromise,
	ControlledPromise,
	CreateFileRoute,
	CreateLazyFileRoute,
	DefaultValidator,
	DeferredPromise,
	DeferredPromiseState,
	ErrorComponentProps,
	ErrorRouteProps,
	Expand,
	FileBaseRouteOptions,
	FileRoutesByPath,
	FileRouteTypes,
	FullSearchSchemaOption,
	InferAllContext,
	InferAllParams,
	InferDescendantToPaths,
	InferFrom,
	InferFullSearchSchema,
	InferFullSearchSchemaInput,
	InferMaskFrom,
	InferMaskTo,
	InferSelected,
	InferShouldThrow,
	InferStrict,
	InferTo,
	InjectedHtmlEntry,
	IntersectAssign,
	LazyRouteOptions,
	LinkOptions,
	ListenerFn,
	LoaderFnContext,
	LocationRewrite,
	LocationRewriteFunction,
	LooseAsyncReturnType,
	LooseReturnType,
	MakeOptionalPathParams,
	MakeRemountDepsOptionsUnion,
	MakeRouteMatch,
	MakeRouteMatchUnion,
	Manifest,
	MatchLocation,
	MatchRouteOptions,
	MergeAll,
	MetaDescriptor,
	NavigateFn,
	NavigateOptions,
	NotFoundError,
	NotFoundRouteProps,
	ParamsOptions,
	ParsedLocation,
	ParseParamsFn,
	PathParamOptions,
	PreloadableObj,
	Redirect,
	RedirectOptions,
	Register,
	RegisteredRouter,
	RelativeToCurrentPath,
	RelativeToParentPath,
	RelativeToPath,
	RelativeToPathAutoComplete,
	RemountDepsOptions,
	RemoveLeadingSlashes,
	RemoveTrailingSlashes,
	ResolveAllContext,
	ResolveAllParamsFromParent,
	ResolvedRedirect,
	ResolveFullPath,
	ResolveFullSearchSchema,
	ResolveFullSearchSchemaInput,
	ResolveId,
	ResolveLoaderData,
	ResolveOptionalParams,
	ResolveParams,
	ResolveRelativePath,
	ResolveRequiredParams,
	ResolveRoute,
	ResolveRouteContext,
	ResolveSearchValidatorInput,
	ResolveSearchValidatorInputFn,
	ResolveValidatorInput,
	ResolveValidatorInputFn,
	ResolveValidatorOutput,
	ResolveValidatorOutputFn,
	RootRouteId,
	RootRouteOptions,
	RouteById,
	RouteConstraints,
	RouteContext,
	RouteContextFn,
	RouteContextOptions,
	RouteContextParameter,
	RouteIds,
	RouteLinkEntry,
	RouteLoaderFn,
	RouteMask,
	RouteMatch,
	RouteOptions,
	RoutePathOptions,
	RoutePathOptionsIntersection,
	RouterConstructorOptions,
	RouterContextOptions,
	RouterEvent,
	RouterEvents,
	RouterListener,
	RouterManagedTag,
	RouterOptions,
	RouterState,
	SearchFilter,
	SearchParamOptions,
	SearchParser,
	SearchSchemaInput,
	SearchSerializer,
	SerializationAdapter,
	StaticDataRouteOption,
	StringifyParamsFn,
	ToMaskOptions,
	ToOptions,
	ToPathOption,
	ToSubOptions,
	TrailingSlashOption,
	TrimPath,
	TrimPathLeft,
	TrimPathRight,
	UpdatableRouteOptions,
	UpdatableStaticRouteOption,
	UseNavigateResult,
	ValidateFromPath,
	ValidateId,
	ValidateNavigateOptions,
	ValidateNavigateOptionsArray,
	ValidateParams,
	ValidateRedirectOptions,
	ValidateRedirectOptionsArray,
	ValidateSearch,
	ValidateToPath,
	ValidateUseParamsResult,
	ValidateUseSearchResult,
	Validator,
	ValidatorAdapter,
	ValidatorFn,
	ValidatorObj,
} from "@tanstack/router-core";
export {
	cleanPath,
	componentTypes,
	composeRewrites,
	createControlledPromise,
	createRouterConfig,
	createSerializationAdapter,
	deepEqual,
	defaultParseSearch,
	defaultSerializeError,
	defaultStringifySearch,
	defer,
	functionalUpdate,
	getInitialRouterState,
	interpolatePath,
	isMatch,
	isNotFound,
	isPlainArray,
	isPlainObject,
	isRedirect,
	joinPaths,
	lazyFn,
	notFound,
	PathParamError,
	parseSearchWith,
	redirect,
	replaceEqualDeep,
	resolvePath,
	retainSearchParams,
	rootRouteId,
	SearchParamError,
	stringifySearchWith,
	stripSearchParams,
	TSR_DEFERRED_PROMISE,
	trimPath,
	trimPathLeft,
	trimPathRight,
} from "@tanstack/router-core";
export { Asset } from "./Asset";
export type { AwaitOptions } from "./awaited";
export { Await, useAwaited } from "./awaited";
export { CatchBoundary, ErrorComponent } from "./CatchBoundary";
export { ClientOnly, useHydrated } from "./ClientOnly";
export {
	createFileRoute,
	createLazyFileRoute,
	createLazyRoute,
	FileRoute,
	FileRouteLoader,
	LazyRoute,
} from "./fileRoute";
export { HeadContent } from "./HeadContent";
export * from "./history";
export { lazyRouteComponent } from "./lazyRouteComponent";
export type {
	ActiveLinkOptions,
	CreateLinkProps,
	LinkComponent,
	LinkComponentProps,
	LinkProps,
	UseLinkPropsOptions,
} from "./link";
export { createLink, Link, linkOptions, useLinkProps } from "./link";
export { Match, Outlet } from "./Match";
export type { MakeMatchRouteOptions, UseMatchRouteOptions } from "./Matches";
export {
	Matches,
	MatchRoute,
	useChildMatches,
	useMatches,
	useMatchRoute,
	useParentMatches,
} from "./Matches";
export { matchContext } from "./matchContext";
export { CatchNotFound, DefaultGlobalNotFound } from "./not-found";
export type { RouterProps } from "./RouterProvider";
export { RouterContextProvider, RouterProvider } from "./RouterProvider";
export type {
	AnyRootRoute,
	AsyncRouteComponent,
	DefaultRouteTypes,
	ErrorRouteComponent,
	NotFoundRouteComponent,
	RouteComponent,
	RouteTypes,
} from "./route";
export {
	createRootRoute,
	createRootRouteWithContext,
	createRoute,
	createRouteMask,
	getRouteApi,
	NotFoundRoute,
	RootRoute,
	Route,
	RouteApi,
	rootRouteWithContext,
} from "./route";
export { createRouter, Router } from "./router";
export {
	getRouterContext, // SSR
} from "./routerContext";
export { ScriptOnce } from "./ScriptOnce";
export { Scripts } from "./Scripts";
export {
	ScrollRestoration,
	useElementScrollRestoration,
} from "./ScrollRestoration";
export type * from "./ssr/serializer";
export type {
	InferStructuralSharing,
	ValidateLinkOptions,
	ValidateLinkOptionsArray,
	ValidateUseParamsOptions,
	ValidateUseSearchOptions,
} from "./typePrimitives";
export type { ShouldBlockFn, UseBlockerOpts } from "./useBlocker";
export { Block, useBlocker } from "./useBlocker";
export { useCanGoBack } from "./useCanGoBack";
export { useLoaderData } from "./useLoaderData";
export { useLoaderDeps } from "./useLoaderDeps";
export { useLocation } from "./useLocation";
export { useMatch } from "./useMatch";
export { Navigate, useNavigate } from "./useNavigate";
export { useParams } from "./useParams";
export { useRouteContext } from "./useRouteContext";
export { useRouter } from "./useRouter";
export { useRouterState } from "./useRouterState";
export { useSearch } from "./useSearch";
export {
	useLayoutEffect, // SSR
	useStableCallback,
} from "./utils";
