export type { DeferredPromise, DeferredPromiseState } from "./defer";

export { defer, TSR_DEFERRED_PROMISE } from "./defer";
export type {
	CreateFileRoute,
	CreateLazyFileRoute,
	FileRoutesByPath,
	FileRouteTypes,
	InferFileRouteTypes,
	LazyRoute,
	LazyRouteOptions,
} from "./fileRoute";
export * from "./global";
export type {
	AbsoluteToPath,
	ActiveOptions,
	AddLeadingSlash,
	AddTrailingSlash,
	FindDescendantToPaths,
	FromPathOption,
	InferDescendantToPaths,
	IsRequiredParams,
	LinkCurrentTargetElement,
	LinkOptions,
	LinkOptionsProps,
	MakeOptionalPathParams,
	MakeOptionalSearchParams,
	MaskOptions,
	NavigateOptions,
	PathParamOptions,
	RelativeToCurrentPath,
	RelativeToParentPath,
	RelativeToPath,
	RelativeToPathAutoComplete,
	RemoveLeadingSlashes,
	RemoveTrailingSlashes,
	RequiredToOptions,
	ResolveCurrentPath,
	ResolveParentPath,
	ResolveRelativePath,
	ResolveRoute,
	SearchParamOptions,
	ToMaskOptions,
	ToOptions,
	ToPathOption,
	ToSubOptions,
	ToSubOptionsProps,
} from "./link";
export { preloadWarning } from "./link";
export { componentTypes } from "./load-matches";
export type { ParsedLocation } from "./location";
export type {
	AnyMatchAndValue,
	AnyRouteMatch,
	CreateMatchAndValue,
	FindValueByIndex,
	FindValueByKey,
	IsMatch,
	IsMatchKeyOf,
	IsMatchParse,
	IsMatchPath,
	IsMatchResult,
	MakeRouteMatch,
	MakeRouteMatchFromRoute,
	MakeRouteMatchUnion,
	MatchRouteOptions,
	NextMatchAndValue,
	RouteMatch,
	RouteMatchExtensions,
} from "./Matches";
export { isMatch } from "./Matches";
export type { Manifest, RouterManagedTag } from "./manifest";
export type { NotFoundError } from "./not-found";
export { isNotFound, notFound } from "./not-found";
export type { Segment } from "./path";
export {
	cleanPath,
	exactPathTest,
	interpolatePath,
	joinPaths,
	matchByPath,
	matchPathname,
	parsePathname,
	removeBasepath,
	removeTrailingSlash,
	resolvePath,
	trimPath,
	trimPathLeft,
	trimPathRight,
} from "./path";
export type { ProcessRouteTreeResult } from "./process-route-tree";
export { processRouteTree } from "./process-route-tree";
export { decode, encode } from "./qss";
export type {
	BuildLocationFn,
	CommitLocationOptions,
	MatchLocation,
	NavigateFn,
} from "./RouterProvider";
export type {
	AnyRedirect,
	Redirect,
	RedirectOptions,
	ResolvedRedirect,
} from "./redirect";
export {
	isRedirect,
	isResolvedRedirect,
	parseRedirect,
	redirect,
} from "./redirect";
export type { RootRouteId } from "./root";
export { rootRouteId } from "./root";
export type {
	AnyContext,
	AnyPathParams,
	AnyRoute,
	AnyRouteWithContext,
	AnySearchValidator,
	BaseRouteOptions,
	BeforeLoadContextOptions,
	BeforeLoadContextParameter,
	BeforeLoadFn,
	ContextAsyncReturnType,
	ContextOptions,
	ContextReturnType,
	DefaultSearchValidator,
	ErrorComponentProps,
	ErrorRouteProps,
	FileBaseRouteOptions,
	FullSearchSchemaOption,
	InferAllContext,
	InferAllParams,
	InferFullSearchSchema,
	InferFullSearchSchemaInput,
	LoaderFnContext,
	MakeRemountDepsOptionsUnion,
	MetaDescriptor,
	NotFoundRouteProps,
	ParamsOptions,
	ParseParamsFn,
	PreloadableObj,
	RemountDepsOptions,
	ResolveAllContext,
	ResolveAllParamsFromParent,
	ResolveFullPath,
	ResolveFullSearchSchema,
	ResolveFullSearchSchemaInput,
	ResolveId,
	ResolveLoaderData,
	ResolveOptionalParams,
	ResolveParams,
	ResolveRequiredParams,
	ResolveRouteContext,
	ResolveSearchSchema,
	ResolveSearchSchemaFn,
	ResolveSearchSchemaFnInput,
	ResolveSearchSchemaInput,
	RootRoute,
	RootRouteOptions,
	RootRouteOptionsExtensions,
	Route,
	RouteAddChildrenFn,
	RouteAddFileChildrenFn,
	RouteAddFileTypesFn,
	RouteConstraints,
	RouteContext,
	RouteContextFn,
	RouteContextOptions,
	RouteContextParameter,
	RouteExtensions,
	RouteLazyFn,
	RouteLinkEntry,
	RouteLoaderFn,
	RouteMask,
	RouteOptions,
	RoutePathOptions,
	RoutePathOptionsIntersection,
	RoutePrefix,
	RouteTypes,
	RouteTypesById,
	SearchFilter,
	SearchMiddleware,
	SearchMiddlewareContext,
	SearchSchemaInput,
	SearchValidator,
	StaticDataRouteOption,
	StringifyParamsFn,
	TrimPath,
	TrimPathLeft,
	TrimPathRight,
	UpdatableRouteOptions,
	UpdatableRouteOptionsExtensions,
	UpdatableStaticRouteOption,
} from "./route";
export { BaseRootRoute, BaseRoute, BaseRouteApi } from "./route";
export type {
	AllContext,
	AllLoaderData,
	AllParams,
	CodeRouteToPath,
	FullSearchSchema,
	FullSearchSchemaInput,
	ParseRoute,
	RouteById,
	RouteByPath,
	RouteIds,
	RoutePaths,
	RoutesById,
	RoutesByPath,
	RouteToPath,
	TrailingSlashOptionByRouter,
} from "./routeInfo";
export type {
	AnyRouter,
	AnyRouterWithContext,
	BuildNextOptions,
	ClearCacheFn,
	CommitLocationFn,
	ControllablePromise,
	CreateRouterFn,
	DefaultRemountDepsFn,
	EmitFn,
	GetMatchFn,
	GetMatchRoutesFn,
	InjectedHtmlEntry,
	InvalidateFn,
	ListenerFn,
	LoadFn,
	LoadRouteChunkFn,
	MatchRouteFn,
	MatchRoutesFn,
	MatchRoutesOpts,
	ParseLocationFn,
	PreloadRouteFn,
	Register,
	RegisteredRouter,
	RouterConstructorOptions,
	RouterContextOptions,
	RouterEvent,
	RouterEvents,
	RouterListener,
	RouterOptions,
	RouterOptionsExtensions,
	RouterState,
	StartTransitionFn,
	SubscribeFn,
	TrailingSlashOption,
	UpdateFn,
	UpdateMatchFn,
	ViewTransitionOptions,
} from "./router";
export {
	defaultSerializeError,
	getInitialRouterState,
	getLocationChangeInfo,
	getMatchedRoutes,
	lazyFn,
	PathParamError,
	RouterCore,
	SearchParamError,
} from "./router";
export type {
	ScrollRestorationEntry,
	ScrollRestorationOptions,
} from "./scroll-restoration";
export {
	defaultGetScrollRestorationKey,
	getCssSelector,
	handleHashScroll,
	restoreScroll,
	scrollRestorationCache,
	setupScrollRestoration,
	storageKey,
} from "./scroll-restoration";
export { retainSearchParams, stripSearchParams } from "./searchMiddleware";
export type { SearchParser, SearchSerializer } from "./searchParams";
export {
	defaultParseSearch,
	defaultStringifySearch,
	parseSearchWith,
	stringifySearchWith,
} from "./searchParams";
export type { OptionalStructuralSharing } from "./structuralSharing";
export type {
	InferFrom,
	InferMaskFrom,
	InferMaskTo,
	InferSelected,
	InferShouldThrow,
	InferStrict,
	InferTo,
	ValidateFromPath,
	ValidateId,
	ValidateNavigateOptions,
	ValidateNavigateOptionsArray,
	ValidateParams,
	ValidateRedirectOptions,
	ValidateRedirectOptionsArray,
	ValidateSearch,
	ValidateToPath,
	ValidateUseParamsResult,
	ValidateUseSearchResult,
} from "./typePrimitives";
export type {
	ResolveUseLoaderData,
	UseLoaderDataResult,
} from "./useLoaderData";
export type {
	ResolveUseLoaderDeps,
	UseLoaderDepsResult,
} from "./useLoaderDeps";
export type { UseNavigateResult } from "./useNavigate";
export type { ResolveUseParams, UseParamsResult } from "./useParams";
export type {
	UseRouteContextBaseOptions,
	UseRouteContextOptions,
	UseRouteContextResult,
} from "./useRouteContext";
export type { ResolveUseSearch, UseSearchResult } from "./useSearch";
export type {
	Assign,
	Awaitable,
	Constrain,
	ConstrainLiteral,
	ControlledPromise,
	DeepPartial,
	Expand,
	ExtractObjects,
	ExtractPrimitives,
	IntersectAssign,
	IsAny,
	IsNonEmptyObject,
	IsUnion,
	LooseAsyncReturnType,
	LooseReturnType,
	MakeDifferenceOptional,
	MergeAll,
	MergeAllObjects,
	MergeAllPrimitive,
	NoInfer,
	NonNullableUpdater,
	PartialMergeAll,
	PartialMergeAllObject,
	PickAsRequired,
	PickOptional,
	PickRequired,
	StrictOrFrom,
	StringLiteral,
	ThrowConstraint,
	ThrowOrOptional,
	Timeout,
	UnionToIntersection,
	Updater,
	ValidateJSON,
	WithoutEmpty,
} from "./utils";
export {
	createControlledPromise,
	deepEqual,
	escapeJSON,
	functionalUpdate,
	isModuleNotFoundError,
	isPlainArray,
	isPlainObject,
	last,
	replaceEqualDeep,
	shallow,
} from "./utils";
export type {
	AnySchema,
	AnyStandardSchemaValidate,
	AnyStandardSchemaValidateFailure,
	AnyStandardSchemaValidateInput,
	AnyStandardSchemaValidateIssue,
	AnyStandardSchemaValidateSuccess,
	AnyStandardSchemaValidator,
	AnyValidator,
	AnyValidatorAdapter,
	AnyValidatorFn,
	AnyValidatorObj,
	DefaultValidator,
	ResolveSearchValidatorInput,
	ResolveSearchValidatorInputFn,
	ResolveValidatorInput,
	ResolveValidatorInputFn,
	ResolveValidatorOutput,
	ResolveValidatorOutputFn,
	StandardSchemaValidator,
	StandardSchemaValidatorProps,
	StandardSchemaValidatorTypes,
	Validator,
	ValidatorAdapter,
	ValidatorFn,
	ValidatorObj,
} from "./validators";
