// TraceRTM gRPC Service Definitions
// Phase 4: Inter-Service Communication
//
// This file defines the gRPC services for TraceRTM's unified infrastructure:
// - GraphService: Provided by Go backend, consumed by Python
// - AIService: Provided by Python backend, consumed by Go

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: tracertm/v1/tracertm.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphService_AnalyzeImpact_FullMethodName      = "/tracertm.v1.GraphService/AnalyzeImpact"
	GraphService_FindCycles_FullMethodName         = "/tracertm.v1.GraphService/FindCycles"
	GraphService_CalculatePath_FullMethodName      = "/tracertm.v1.GraphService/CalculatePath"
	GraphService_StreamGraphUpdates_FullMethodName = "/tracertm.v1.GraphService/StreamGraphUpdates"
)

// GraphServiceClient is the client API for GraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GraphService provides graph analysis and traversal operations
type GraphServiceClient interface {
	// AnalyzeImpact performs impact analysis for a given item
	AnalyzeImpact(ctx context.Context, in *AnalyzeImpactRequest, opts ...grpc.CallOption) (*AnalyzeImpactResponse, error)
	// FindCycles detects circular dependencies in the graph
	FindCycles(ctx context.Context, in *FindCyclesRequest, opts ...grpc.CallOption) (*FindCyclesResponse, error)
	// CalculatePath finds the shortest path between two items
	CalculatePath(ctx context.Context, in *CalculatePathRequest, opts ...grpc.CallOption) (*CalculatePathResponse, error)
	// StreamGraphUpdates streams real-time graph changes
	StreamGraphUpdates(ctx context.Context, in *StreamGraphUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamGraphUpdatesResponse], error)
}

type graphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphServiceClient(cc grpc.ClientConnInterface) GraphServiceClient {
	return &graphServiceClient{cc}
}

func (c *graphServiceClient) AnalyzeImpact(ctx context.Context, in *AnalyzeImpactRequest, opts ...grpc.CallOption) (*AnalyzeImpactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeImpactResponse)
	err := c.cc.Invoke(ctx, GraphService_AnalyzeImpact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) FindCycles(ctx context.Context, in *FindCyclesRequest, opts ...grpc.CallOption) (*FindCyclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindCyclesResponse)
	err := c.cc.Invoke(ctx, GraphService_FindCycles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) CalculatePath(ctx context.Context, in *CalculatePathRequest, opts ...grpc.CallOption) (*CalculatePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePathResponse)
	err := c.cc.Invoke(ctx, GraphService_CalculatePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) StreamGraphUpdates(ctx context.Context, in *StreamGraphUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamGraphUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GraphService_ServiceDesc.Streams[0], GraphService_StreamGraphUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamGraphUpdatesRequest, StreamGraphUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_StreamGraphUpdatesClient = grpc.ServerStreamingClient[StreamGraphUpdatesResponse]

// GraphServiceServer is the server API for GraphService service.
// All implementations must embed UnimplementedGraphServiceServer
// for forward compatibility.
//
// GraphService provides graph analysis and traversal operations
type GraphServiceServer interface {
	// AnalyzeImpact performs impact analysis for a given item
	AnalyzeImpact(context.Context, *AnalyzeImpactRequest) (*AnalyzeImpactResponse, error)
	// FindCycles detects circular dependencies in the graph
	FindCycles(context.Context, *FindCyclesRequest) (*FindCyclesResponse, error)
	// CalculatePath finds the shortest path between two items
	CalculatePath(context.Context, *CalculatePathRequest) (*CalculatePathResponse, error)
	// StreamGraphUpdates streams real-time graph changes
	StreamGraphUpdates(*StreamGraphUpdatesRequest, grpc.ServerStreamingServer[StreamGraphUpdatesResponse]) error
	mustEmbedUnimplementedGraphServiceServer()
}

// UnimplementedGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphServiceServer struct{}

func (UnimplementedGraphServiceServer) AnalyzeImpact(context.Context, *AnalyzeImpactRequest) (*AnalyzeImpactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeImpact not implemented")
}
func (UnimplementedGraphServiceServer) FindCycles(context.Context, *FindCyclesRequest) (*FindCyclesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindCycles not implemented")
}
func (UnimplementedGraphServiceServer) CalculatePath(context.Context, *CalculatePathRequest) (*CalculatePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculatePath not implemented")
}
func (UnimplementedGraphServiceServer) StreamGraphUpdates(*StreamGraphUpdatesRequest, grpc.ServerStreamingServer[StreamGraphUpdatesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamGraphUpdates not implemented")
}
func (UnimplementedGraphServiceServer) mustEmbedUnimplementedGraphServiceServer() {}
func (UnimplementedGraphServiceServer) testEmbeddedByValue()                      {}

// UnsafeGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphServiceServer will
// result in compilation errors.
type UnsafeGraphServiceServer interface {
	mustEmbedUnimplementedGraphServiceServer()
}

func RegisterGraphServiceServer(s grpc.ServiceRegistrar, srv GraphServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphService_ServiceDesc, srv)
}

func _GraphService_AnalyzeImpact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeImpactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).AnalyzeImpact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_AnalyzeImpact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).AnalyzeImpact(ctx, req.(*AnalyzeImpactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_FindCycles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCyclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).FindCycles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_FindCycles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).FindCycles(ctx, req.(*FindCyclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_CalculatePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).CalculatePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_CalculatePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).CalculatePath(ctx, req.(*CalculatePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_StreamGraphUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamGraphUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphServiceServer).StreamGraphUpdates(m, &grpc.GenericServerStream[StreamGraphUpdatesRequest, StreamGraphUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_StreamGraphUpdatesServer = grpc.ServerStreamingServer[StreamGraphUpdatesResponse]

// GraphService_ServiceDesc is the grpc.ServiceDesc for GraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracertm.v1.GraphService",
	HandlerType: (*GraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeImpact",
			Handler:    _GraphService_AnalyzeImpact_Handler,
		},
		{
			MethodName: "FindCycles",
			Handler:    _GraphService_FindCycles_Handler,
		},
		{
			MethodName: "CalculatePath",
			Handler:    _GraphService_CalculatePath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGraphUpdates",
			Handler:       _GraphService_StreamGraphUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tracertm/v1/tracertm.proto",
}

const (
	AIService_AnalyzeRequirement_FullMethodName  = "/tracertm.v1.AIService/AnalyzeRequirement"
	AIService_GenerateSuggestions_FullMethodName = "/tracertm.v1.AIService/GenerateSuggestions"
	AIService_DetectEquivalences_FullMethodName  = "/tracertm.v1.AIService/DetectEquivalences"
	AIService_ExtractEntities_FullMethodName     = "/tracertm.v1.AIService/ExtractEntities"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIService provides AI-powered analysis and suggestions
type AIServiceClient interface {
	// AnalyzeRequirement performs NLP analysis on a requirement
	AnalyzeRequirement(ctx context.Context, in *AnalyzeRequirementRequest, opts ...grpc.CallOption) (*AnalyzeRequirementResponse, error)
	// GenerateSuggestions streams AI-generated suggestions
	GenerateSuggestions(ctx context.Context, in *GenerateSuggestionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateSuggestionsResponse], error)
	// DetectEquivalences finds semantically equivalent items
	DetectEquivalences(ctx context.Context, in *DetectEquivalencesRequest, opts ...grpc.CallOption) (*DetectEquivalencesResponse, error)
	// ExtractEntities extracts named entities from text
	ExtractEntities(ctx context.Context, in *ExtractEntitiesRequest, opts ...grpc.CallOption) (*ExtractEntitiesResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) AnalyzeRequirement(ctx context.Context, in *AnalyzeRequirementRequest, opts ...grpc.CallOption) (*AnalyzeRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeRequirementResponse)
	err := c.cc.Invoke(ctx, AIService_AnalyzeRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GenerateSuggestions(ctx context.Context, in *GenerateSuggestionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateSuggestionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], AIService_GenerateSuggestions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateSuggestionsRequest, GenerateSuggestionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_GenerateSuggestionsClient = grpc.ServerStreamingClient[GenerateSuggestionsResponse]

func (c *aIServiceClient) DetectEquivalences(ctx context.Context, in *DetectEquivalencesRequest, opts ...grpc.CallOption) (*DetectEquivalencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectEquivalencesResponse)
	err := c.cc.Invoke(ctx, AIService_DetectEquivalences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ExtractEntities(ctx context.Context, in *ExtractEntitiesRequest, opts ...grpc.CallOption) (*ExtractEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractEntitiesResponse)
	err := c.cc.Invoke(ctx, AIService_ExtractEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
//
// AIService provides AI-powered analysis and suggestions
type AIServiceServer interface {
	// AnalyzeRequirement performs NLP analysis on a requirement
	AnalyzeRequirement(context.Context, *AnalyzeRequirementRequest) (*AnalyzeRequirementResponse, error)
	// GenerateSuggestions streams AI-generated suggestions
	GenerateSuggestions(*GenerateSuggestionsRequest, grpc.ServerStreamingServer[GenerateSuggestionsResponse]) error
	// DetectEquivalences finds semantically equivalent items
	DetectEquivalences(context.Context, *DetectEquivalencesRequest) (*DetectEquivalencesResponse, error)
	// ExtractEntities extracts named entities from text
	ExtractEntities(context.Context, *ExtractEntitiesRequest) (*ExtractEntitiesResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) AnalyzeRequirement(context.Context, *AnalyzeRequirementRequest) (*AnalyzeRequirementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeRequirement not implemented")
}
func (UnimplementedAIServiceServer) GenerateSuggestions(*GenerateSuggestionsRequest, grpc.ServerStreamingServer[GenerateSuggestionsResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateSuggestions not implemented")
}
func (UnimplementedAIServiceServer) DetectEquivalences(context.Context, *DetectEquivalencesRequest) (*DetectEquivalencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectEquivalences not implemented")
}
func (UnimplementedAIServiceServer) ExtractEntities(context.Context, *ExtractEntitiesRequest) (*ExtractEntitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractEntities not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_AnalyzeRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AnalyzeRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AnalyzeRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AnalyzeRequirement(ctx, req.(*AnalyzeRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GenerateSuggestions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateSuggestionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).GenerateSuggestions(m, &grpc.GenericServerStream[GenerateSuggestionsRequest, GenerateSuggestionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_GenerateSuggestionsServer = grpc.ServerStreamingServer[GenerateSuggestionsResponse]

func _AIService_DetectEquivalences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectEquivalencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DetectEquivalences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DetectEquivalences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DetectEquivalences(ctx, req.(*DetectEquivalencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ExtractEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ExtractEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ExtractEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ExtractEntities(ctx, req.(*ExtractEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracertm.v1.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeRequirement",
			Handler:    _AIService_AnalyzeRequirement_Handler,
		},
		{
			MethodName: "DetectEquivalences",
			Handler:    _AIService_DetectEquivalences_Handler,
		},
		{
			MethodName: "ExtractEntities",
			Handler:    _AIService_ExtractEntities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateSuggestions",
			Handler:       _AIService_GenerateSuggestions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tracertm/v1/tracertm.proto",
}

const (
	SpecAnalyticsService_AnalyzeSpec_FullMethodName       = "/tracertm.v1.SpecAnalyticsService/AnalyzeSpec"
	SpecAnalyticsService_BatchAnalyzeSpecs_FullMethodName = "/tracertm.v1.SpecAnalyticsService/BatchAnalyzeSpecs"
	SpecAnalyticsService_ValidateISO29148_FullMethodName  = "/tracertm.v1.SpecAnalyticsService/ValidateISO29148"
	SpecAnalyticsService_GetEARSPatterns_FullMethodName   = "/tracertm.v1.SpecAnalyticsService/GetEARSPatterns"
)

// SpecAnalyticsServiceClient is the client API for SpecAnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpecAnalyticsService provides requirement/spec analytics from the Python backend
type SpecAnalyticsServiceClient interface {
	// AnalyzeSpec performs a single spec analysis
	AnalyzeSpec(ctx context.Context, in *AnalyzeSpecRequest, opts ...grpc.CallOption) (*AnalyzeSpecResponse, error)
	// BatchAnalyzeSpecs analyzes multiple specs in one call
	BatchAnalyzeSpecs(ctx context.Context, in *BatchAnalyzeSpecsRequest, opts ...grpc.CallOption) (*BatchAnalyzeSpecsResponse, error)
	// ValidateISO29148 checks ISO 29148 compliance
	ValidateISO29148(ctx context.Context, in *ValidateISO29148Request, opts ...grpc.CallOption) (*ValidateISO29148Response, error)
	// GetEARSPatterns extracts EARS patterns
	GetEARSPatterns(ctx context.Context, in *GetEARSPatternsRequest, opts ...grpc.CallOption) (*GetEARSPatternsResponse, error)
}

type specAnalyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecAnalyticsServiceClient(cc grpc.ClientConnInterface) SpecAnalyticsServiceClient {
	return &specAnalyticsServiceClient{cc}
}

func (c *specAnalyticsServiceClient) AnalyzeSpec(ctx context.Context, in *AnalyzeSpecRequest, opts ...grpc.CallOption) (*AnalyzeSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeSpecResponse)
	err := c.cc.Invoke(ctx, SpecAnalyticsService_AnalyzeSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specAnalyticsServiceClient) BatchAnalyzeSpecs(ctx context.Context, in *BatchAnalyzeSpecsRequest, opts ...grpc.CallOption) (*BatchAnalyzeSpecsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchAnalyzeSpecsResponse)
	err := c.cc.Invoke(ctx, SpecAnalyticsService_BatchAnalyzeSpecs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specAnalyticsServiceClient) ValidateISO29148(ctx context.Context, in *ValidateISO29148Request, opts ...grpc.CallOption) (*ValidateISO29148Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateISO29148Response)
	err := c.cc.Invoke(ctx, SpecAnalyticsService_ValidateISO29148_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specAnalyticsServiceClient) GetEARSPatterns(ctx context.Context, in *GetEARSPatternsRequest, opts ...grpc.CallOption) (*GetEARSPatternsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEARSPatternsResponse)
	err := c.cc.Invoke(ctx, SpecAnalyticsService_GetEARSPatterns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpecAnalyticsServiceServer is the server API for SpecAnalyticsService service.
// All implementations must embed UnimplementedSpecAnalyticsServiceServer
// for forward compatibility.
//
// SpecAnalyticsService provides requirement/spec analytics from the Python backend
type SpecAnalyticsServiceServer interface {
	// AnalyzeSpec performs a single spec analysis
	AnalyzeSpec(context.Context, *AnalyzeSpecRequest) (*AnalyzeSpecResponse, error)
	// BatchAnalyzeSpecs analyzes multiple specs in one call
	BatchAnalyzeSpecs(context.Context, *BatchAnalyzeSpecsRequest) (*BatchAnalyzeSpecsResponse, error)
	// ValidateISO29148 checks ISO 29148 compliance
	ValidateISO29148(context.Context, *ValidateISO29148Request) (*ValidateISO29148Response, error)
	// GetEARSPatterns extracts EARS patterns
	GetEARSPatterns(context.Context, *GetEARSPatternsRequest) (*GetEARSPatternsResponse, error)
	mustEmbedUnimplementedSpecAnalyticsServiceServer()
}

// UnimplementedSpecAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpecAnalyticsServiceServer struct{}

func (UnimplementedSpecAnalyticsServiceServer) AnalyzeSpec(context.Context, *AnalyzeSpecRequest) (*AnalyzeSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeSpec not implemented")
}
func (UnimplementedSpecAnalyticsServiceServer) BatchAnalyzeSpecs(context.Context, *BatchAnalyzeSpecsRequest) (*BatchAnalyzeSpecsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchAnalyzeSpecs not implemented")
}
func (UnimplementedSpecAnalyticsServiceServer) ValidateISO29148(context.Context, *ValidateISO29148Request) (*ValidateISO29148Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateISO29148 not implemented")
}
func (UnimplementedSpecAnalyticsServiceServer) GetEARSPatterns(context.Context, *GetEARSPatternsRequest) (*GetEARSPatternsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEARSPatterns not implemented")
}
func (UnimplementedSpecAnalyticsServiceServer) mustEmbedUnimplementedSpecAnalyticsServiceServer() {}
func (UnimplementedSpecAnalyticsServiceServer) testEmbeddedByValue()                              {}

// UnsafeSpecAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpecAnalyticsServiceServer will
// result in compilation errors.
type UnsafeSpecAnalyticsServiceServer interface {
	mustEmbedUnimplementedSpecAnalyticsServiceServer()
}

func RegisterSpecAnalyticsServiceServer(s grpc.ServiceRegistrar, srv SpecAnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedSpecAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpecAnalyticsService_ServiceDesc, srv)
}

func _SpecAnalyticsService_AnalyzeSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecAnalyticsServiceServer).AnalyzeSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecAnalyticsService_AnalyzeSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecAnalyticsServiceServer).AnalyzeSpec(ctx, req.(*AnalyzeSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecAnalyticsService_BatchAnalyzeSpecs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAnalyzeSpecsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecAnalyticsServiceServer).BatchAnalyzeSpecs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecAnalyticsService_BatchAnalyzeSpecs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecAnalyticsServiceServer).BatchAnalyzeSpecs(ctx, req.(*BatchAnalyzeSpecsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecAnalyticsService_ValidateISO29148_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateISO29148Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecAnalyticsServiceServer).ValidateISO29148(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecAnalyticsService_ValidateISO29148_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecAnalyticsServiceServer).ValidateISO29148(ctx, req.(*ValidateISO29148Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecAnalyticsService_GetEARSPatterns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEARSPatternsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecAnalyticsServiceServer).GetEARSPatterns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecAnalyticsService_GetEARSPatterns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecAnalyticsServiceServer).GetEARSPatterns(ctx, req.(*GetEARSPatternsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpecAnalyticsService_ServiceDesc is the grpc.ServiceDesc for SpecAnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpecAnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracertm.v1.SpecAnalyticsService",
	HandlerType: (*SpecAnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeSpec",
			Handler:    _SpecAnalyticsService_AnalyzeSpec_Handler,
		},
		{
			MethodName: "BatchAnalyzeSpecs",
			Handler:    _SpecAnalyticsService_BatchAnalyzeSpecs_Handler,
		},
		{
			MethodName: "ValidateISO29148",
			Handler:    _SpecAnalyticsService_ValidateISO29148_Handler,
		},
		{
			MethodName: "GetEARSPatterns",
			Handler:    _SpecAnalyticsService_GetEARSPatterns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracertm/v1/tracertm.proto",
}
