// TraceRTM gRPC Service Definitions
// Phase 4: Inter-Service Communication
//
// This file defines the gRPC services for TraceRTM's unified infrastructure:
// - GraphService: Provided by Go backend, consumed by Python
// - AIService: Provided by Python backend, consumed by Go

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: tracertm/v1/tracertm.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to analyze impact of changes to an item
type AnalyzeImpactRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ItemId    string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ProjectId string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Direction: "upstream" (what depends on this), "downstream" (what this depends on), "both"
	Direction     string   `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	MaxDepth      int32    `protobuf:"varint,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`   // Maximum traversal depth (0 = unlimited)
	LinkTypes     []string `protobuf:"bytes,5,rep,name=link_types,json=linkTypes,proto3" json:"link_types,omitempty"` // Filter by link types (empty = all types)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeImpactRequest) Reset() {
	*x = AnalyzeImpactRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeImpactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImpactRequest) ProtoMessage() {}

func (x *AnalyzeImpactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImpactRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeImpactRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeImpactRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AnalyzeImpactRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AnalyzeImpactRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *AnalyzeImpactRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *AnalyzeImpactRequest) GetLinkTypes() []string {
	if x != nil {
		return x.LinkTypes
	}
	return nil
}

// Response containing impact analysis results
type AnalyzeImpactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ImpactedItems []*ImpactedItem        `protobuf:"bytes,2,rep,name=impacted_items,json=impactedItems,proto3" json:"impacted_items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	ItemsByType   map[string]int32       `protobuf:"bytes,4,rep,name=items_by_type,json=itemsByType,proto3" json:"items_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`    // Count of impacted items by type
	ItemsByDepth  map[string]int32       `protobuf:"bytes,5,rep,name=items_by_depth,json=itemsByDepth,proto3" json:"items_by_depth,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Count of items at each depth level
	CriticalPaths []string               `protobuf:"bytes,6,rep,name=critical_paths,json=criticalPaths,proto3" json:"critical_paths,omitempty"`                                                                           // IDs of items on critical paths
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeImpactResponse) Reset() {
	*x = AnalyzeImpactResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeImpactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImpactResponse) ProtoMessage() {}

func (x *AnalyzeImpactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImpactResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeImpactResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeImpactResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AnalyzeImpactResponse) GetImpactedItems() []*ImpactedItem {
	if x != nil {
		return x.ImpactedItems
	}
	return nil
}

func (x *AnalyzeImpactResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *AnalyzeImpactResponse) GetItemsByType() map[string]int32 {
	if x != nil {
		return x.ItemsByType
	}
	return nil
}

func (x *AnalyzeImpactResponse) GetItemsByDepth() map[string]int32 {
	if x != nil {
		return x.ItemsByDepth
	}
	return nil
}

func (x *AnalyzeImpactResponse) GetCriticalPaths() []string {
	if x != nil {
		return x.CriticalPaths
	}
	return nil
}

// An item impacted by changes
type ImpactedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Depth         int32                  `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`                                 // Distance from source item
	LinkType      string                 `protobuf:"bytes,5,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`            // Type of link connecting to this item
	ImpactScore   float64                `protobuf:"fixed64,6,opt,name=impact_score,json=impactScore,proto3" json:"impact_score,omitempty"` // Calculated impact score (0.0-1.0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactedItem) Reset() {
	*x = ImpactedItem{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactedItem) ProtoMessage() {}

func (x *ImpactedItem) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactedItem.ProtoReflect.Descriptor instead.
func (*ImpactedItem) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{2}
}

func (x *ImpactedItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImpactedItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ImpactedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImpactedItem) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *ImpactedItem) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

func (x *ImpactedItem) GetImpactScore() float64 {
	if x != nil {
		return x.ImpactScore
	}
	return 0
}

// Request to find circular dependencies
type FindCyclesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	LinkTypes      []string               `protobuf:"bytes,2,rep,name=link_types,json=linkTypes,proto3" json:"link_types,omitempty"`                   // Filter by link types
	MaxCycleLength int32                  `protobuf:"varint,3,opt,name=max_cycle_length,json=maxCycleLength,proto3" json:"max_cycle_length,omitempty"` // Maximum cycle size to detect
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindCyclesRequest) Reset() {
	*x = FindCyclesRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCyclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCyclesRequest) ProtoMessage() {}

func (x *FindCyclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCyclesRequest.ProtoReflect.Descriptor instead.
func (*FindCyclesRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{3}
}

func (x *FindCyclesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FindCyclesRequest) GetLinkTypes() []string {
	if x != nil {
		return x.LinkTypes
	}
	return nil
}

func (x *FindCyclesRequest) GetMaxCycleLength() int32 {
	if x != nil {
		return x.MaxCycleLength
	}
	return 0
}

// Response containing detected cycles
type FindCyclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cycles        []*Cycle               `protobuf:"bytes,1,rep,name=cycles,proto3" json:"cycles,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasCycles     bool                   `protobuf:"varint,3,opt,name=has_cycles,json=hasCycles,proto3" json:"has_cycles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCyclesResponse) Reset() {
	*x = FindCyclesResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCyclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCyclesResponse) ProtoMessage() {}

func (x *FindCyclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCyclesResponse.ProtoReflect.Descriptor instead.
func (*FindCyclesResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{4}
}

func (x *FindCyclesResponse) GetCycles() []*Cycle {
	if x != nil {
		return x.Cycles
	}
	return nil
}

func (x *FindCyclesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *FindCyclesResponse) GetHasCycles() bool {
	if x != nil {
		return x.HasCycles
	}
	return false
}

// A circular dependency in the graph
type Cycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`       // Items forming the cycle (first == last)
	LinkTypes     []string               `protobuf:"bytes,2,rep,name=link_types,json=linkTypes,proto3" json:"link_types,omitempty"` // Link types in the cycle
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`                       // Number of items in cycle
	Severity      float64                `protobuf:"fixed64,4,opt,name=severity,proto3" json:"severity,omitempty"`                  // Severity score (0.0-1.0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cycle) Reset() {
	*x = Cycle{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cycle) ProtoMessage() {}

func (x *Cycle) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cycle.ProtoReflect.Descriptor instead.
func (*Cycle) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{5}
}

func (x *Cycle) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *Cycle) GetLinkTypes() []string {
	if x != nil {
		return x.LinkTypes
	}
	return nil
}

func (x *Cycle) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Cycle) GetSeverity() float64 {
	if x != nil {
		return x.Severity
	}
	return 0
}

// Request to calculate shortest path
type CalculatePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SourceItemId  string                 `protobuf:"bytes,2,opt,name=source_item_id,json=sourceItemId,proto3" json:"source_item_id,omitempty"`
	TargetItemId  string                 `protobuf:"bytes,3,opt,name=target_item_id,json=targetItemId,proto3" json:"target_item_id,omitempty"`
	LinkTypes     []string               `protobuf:"bytes,4,rep,name=link_types,json=linkTypes,proto3" json:"link_types,omitempty"` // Filter by link types
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePathRequest) Reset() {
	*x = CalculatePathRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePathRequest) ProtoMessage() {}

func (x *CalculatePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePathRequest.ProtoReflect.Descriptor instead.
func (*CalculatePathRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{6}
}

func (x *CalculatePathRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CalculatePathRequest) GetSourceItemId() string {
	if x != nil {
		return x.SourceItemId
	}
	return ""
}

func (x *CalculatePathRequest) GetTargetItemId() string {
	if x != nil {
		return x.TargetItemId
	}
	return ""
}

func (x *CalculatePathRequest) GetLinkTypes() []string {
	if x != nil {
		return x.LinkTypes
	}
	return nil
}

// Response containing path information
type CalculatePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`       // Items in the path (source to target)
	LinkTypes     []string               `protobuf:"bytes,2,rep,name=link_types,json=linkTypes,proto3" json:"link_types,omitempty"` // Link types connecting the path
	PathLength    int32                  `protobuf:"varint,3,opt,name=path_length,json=pathLength,proto3" json:"path_length,omitempty"`
	PathExists    bool                   `protobuf:"varint,4,opt,name=path_exists,json=pathExists,proto3" json:"path_exists,omitempty"`
	PathWeight    float64                `protobuf:"fixed64,5,opt,name=path_weight,json=pathWeight,proto3" json:"path_weight,omitempty"` // Total weight/cost of path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePathResponse) Reset() {
	*x = CalculatePathResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePathResponse) ProtoMessage() {}

func (x *CalculatePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePathResponse.ProtoReflect.Descriptor instead.
func (*CalculatePathResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{7}
}

func (x *CalculatePathResponse) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *CalculatePathResponse) GetLinkTypes() []string {
	if x != nil {
		return x.LinkTypes
	}
	return nil
}

func (x *CalculatePathResponse) GetPathLength() int32 {
	if x != nil {
		return x.PathLength
	}
	return 0
}

func (x *CalculatePathResponse) GetPathExists() bool {
	if x != nil {
		return x.PathExists
	}
	return false
}

func (x *CalculatePathResponse) GetPathWeight() float64 {
	if x != nil {
		return x.PathWeight
	}
	return 0
}

// Request to stream graph updates
type StreamGraphUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // Filter: "item_created", "item_updated", "link_created", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamGraphUpdatesRequest) Reset() {
	*x = StreamGraphUpdatesRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamGraphUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGraphUpdatesRequest) ProtoMessage() {}

func (x *StreamGraphUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGraphUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamGraphUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{8}
}

func (x *StreamGraphUpdatesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StreamGraphUpdatesRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// Real-time graph update event
type StreamGraphUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamGraphUpdatesResponse) Reset() {
	*x = StreamGraphUpdatesResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamGraphUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGraphUpdatesResponse) ProtoMessage() {}

func (x *StreamGraphUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGraphUpdatesResponse.ProtoReflect.Descriptor instead.
func (*StreamGraphUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{9}
}

func (x *StreamGraphUpdatesResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StreamGraphUpdatesResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *StreamGraphUpdatesResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StreamGraphUpdatesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamGraphUpdatesResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request to analyze a requirement
type AnalyzeRequirementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ItemType      string                 `protobuf:"bytes,3,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // "requirement", "story", "task", etc.
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequirementRequest) Reset() {
	*x = AnalyzeRequirementRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequirementRequest) ProtoMessage() {}

func (x *AnalyzeRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequirementRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequirementRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeRequirementRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AnalyzeRequirementRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnalyzeRequirementRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *AnalyzeRequirementRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Response containing requirement analysis
type AnalyzeRequirementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quality       *QualityMetrics        `protobuf:"bytes,2,opt,name=quality,proto3" json:"quality,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                                     // Auto-generated tags
	RelatedItems  []string               `protobuf:"bytes,4,rep,name=related_items,json=relatedItems,proto3" json:"related_items,omitempty"` // IDs of semantically related items
	Sentiment     string                 `protobuf:"bytes,5,opt,name=sentiment,proto3" json:"sentiment,omitempty"`                           // "positive", "neutral", "negative"
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`                       // Confidence score (0.0-1.0)
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequirementResponse) Reset() {
	*x = AnalyzeRequirementResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequirementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequirementResponse) ProtoMessage() {}

func (x *AnalyzeRequirementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequirementResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeRequirementResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{11}
}

func (x *AnalyzeRequirementResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AnalyzeRequirementResponse) GetQuality() *QualityMetrics {
	if x != nil {
		return x.Quality
	}
	return nil
}

func (x *AnalyzeRequirementResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AnalyzeRequirementResponse) GetRelatedItems() []string {
	if x != nil {
		return x.RelatedItems
	}
	return nil
}

func (x *AnalyzeRequirementResponse) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

func (x *AnalyzeRequirementResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeRequirementResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Quality metrics for a requirement
type QualityMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Completeness    float64                `protobuf:"fixed64,1,opt,name=completeness,proto3" json:"completeness,omitempty"`     // 0.0-1.0
	Clarity         float64                `protobuf:"fixed64,2,opt,name=clarity,proto3" json:"clarity,omitempty"`               // 0.0-1.0
	Testability     float64                `protobuf:"fixed64,3,opt,name=testability,proto3" json:"testability,omitempty"`       // 0.0-1.0
	Consistency     float64                `protobuf:"fixed64,4,opt,name=consistency,proto3" json:"consistency,omitempty"`       // 0.0-1.0
	Issues          []string               `protobuf:"bytes,5,rep,name=issues,proto3" json:"issues,omitempty"`                   // Detected quality issues
	Recommendations []string               `protobuf:"bytes,6,rep,name=recommendations,proto3" json:"recommendations,omitempty"` // Improvement recommendations
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QualityMetrics) Reset() {
	*x = QualityMetrics{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityMetrics) ProtoMessage() {}

func (x *QualityMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityMetrics.ProtoReflect.Descriptor instead.
func (*QualityMetrics) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{12}
}

func (x *QualityMetrics) GetCompleteness() float64 {
	if x != nil {
		return x.Completeness
	}
	return 0
}

func (x *QualityMetrics) GetClarity() float64 {
	if x != nil {
		return x.Clarity
	}
	return 0
}

func (x *QualityMetrics) GetTestability() float64 {
	if x != nil {
		return x.Testability
	}
	return 0
}

func (x *QualityMetrics) GetConsistency() float64 {
	if x != nil {
		return x.Consistency
	}
	return 0
}

func (x *QualityMetrics) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *QualityMetrics) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// Request for AI suggestions
type GenerateSuggestionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // Context for suggestions
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SuggestionType string                 `protobuf:"bytes,3,opt,name=suggestion_type,json=suggestionType,proto3" json:"suggestion_type,omitempty"` // "links", "tags", "related_items", "improvements"
	MaxSuggestions int32                  `protobuf:"varint,4,opt,name=max_suggestions,json=maxSuggestions,proto3" json:"max_suggestions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateSuggestionsRequest) Reset() {
	*x = GenerateSuggestionsRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSuggestionsRequest) ProtoMessage() {}

func (x *GenerateSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*GenerateSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateSuggestionsRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *GenerateSuggestionsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GenerateSuggestionsRequest) GetSuggestionType() string {
	if x != nil {
		return x.SuggestionType
	}
	return ""
}

func (x *GenerateSuggestionsRequest) GetMaxSuggestions() int32 {
	if x != nil {
		return x.MaxSuggestions
	}
	return 0
}

// A single AI-generated suggestion
type GenerateSuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Reasoning     string                 `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"` // Explanation for the suggestion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSuggestionsResponse) Reset() {
	*x = GenerateSuggestionsResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSuggestionsResponse) ProtoMessage() {}

func (x *GenerateSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*GenerateSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateSuggestionsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GenerateSuggestionsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateSuggestionsResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GenerateSuggestionsResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GenerateSuggestionsResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

// Request to detect equivalences
type DetectEquivalencesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ItemId              string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Text                string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ProjectId           string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SimilarityThreshold float64                `protobuf:"fixed64,4,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"` // Minimum similarity (0.0-1.0)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DetectEquivalencesRequest) Reset() {
	*x = DetectEquivalencesRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectEquivalencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectEquivalencesRequest) ProtoMessage() {}

func (x *DetectEquivalencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectEquivalencesRequest.ProtoReflect.Descriptor instead.
func (*DetectEquivalencesRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{15}
}

func (x *DetectEquivalencesRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DetectEquivalencesRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DetectEquivalencesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DetectEquivalencesRequest) GetSimilarityThreshold() float64 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

// Response containing detected equivalences
type DetectEquivalencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Equivalents   []*EquivalentItem      `protobuf:"bytes,2,rep,name=equivalents,proto3" json:"equivalents,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectEquivalencesResponse) Reset() {
	*x = DetectEquivalencesResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectEquivalencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectEquivalencesResponse) ProtoMessage() {}

func (x *DetectEquivalencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectEquivalencesResponse.ProtoReflect.Descriptor instead.
func (*DetectEquivalencesResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{16}
}

func (x *DetectEquivalencesResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DetectEquivalencesResponse) GetEquivalents() []*EquivalentItem {
	if x != nil {
		return x.Equivalents
	}
	return nil
}

func (x *DetectEquivalencesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// An equivalent item
type EquivalentItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	SimilarityScore float64                `protobuf:"fixed64,4,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"` // 0.0-1.0
	MatchingPhrases []string               `protobuf:"bytes,5,rep,name=matching_phrases,json=matchingPhrases,proto3" json:"matching_phrases,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EquivalentItem) Reset() {
	*x = EquivalentItem{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquivalentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquivalentItem) ProtoMessage() {}

func (x *EquivalentItem) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquivalentItem.ProtoReflect.Descriptor instead.
func (*EquivalentItem) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{17}
}

func (x *EquivalentItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EquivalentItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EquivalentItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EquivalentItem) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *EquivalentItem) GetMatchingPhrases() []string {
	if x != nil {
		return x.MatchingPhrases
	}
	return nil
}

// Request to extract entities
type ExtractEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EntityTypes   []string               `protobuf:"bytes,3,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"` // Filter: "person", "organization", "technology", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractEntitiesRequest) Reset() {
	*x = ExtractEntitiesRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractEntitiesRequest) ProtoMessage() {}

func (x *ExtractEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ExtractEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{18}
}

func (x *ExtractEntitiesRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExtractEntitiesRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ExtractEntitiesRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

// Response containing extracted entities
type ExtractEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractEntitiesResponse) Reset() {
	*x = ExtractEntitiesResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractEntitiesResponse) ProtoMessage() {}

func (x *ExtractEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ExtractEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{19}
}

func (x *ExtractEntitiesResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ExtractEntitiesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request to analyze a specification
type AnalyzeSpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecId        string                 `protobuf:"bytes,1,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSpecRequest) Reset() {
	*x = AnalyzeSpecRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSpecRequest) ProtoMessage() {}

func (x *AnalyzeSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSpecRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeSpecRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{20}
}

func (x *AnalyzeSpecRequest) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

func (x *AnalyzeSpecRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnalyzeSpecRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Response containing spec analysis
type AnalyzeSpecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *SpecAnalysisResult    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSpecResponse) Reset() {
	*x = AnalyzeSpecResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSpecResponse) ProtoMessage() {}

func (x *AnalyzeSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSpecResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeSpecResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{21}
}

func (x *AnalyzeSpecResponse) GetResult() *SpecAnalysisResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// Batch analyze request
type BatchAnalyzeSpecsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*AnalyzeSpecRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnalyzeSpecsRequest) Reset() {
	*x = BatchAnalyzeSpecsRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnalyzeSpecsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnalyzeSpecsRequest) ProtoMessage() {}

func (x *BatchAnalyzeSpecsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnalyzeSpecsRequest.ProtoReflect.Descriptor instead.
func (*BatchAnalyzeSpecsRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{22}
}

func (x *BatchAnalyzeSpecsRequest) GetRequests() []*AnalyzeSpecRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// Batch analyze response
type BatchAnalyzeSpecsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SpecAnalysisResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnalyzeSpecsResponse) Reset() {
	*x = BatchAnalyzeSpecsResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnalyzeSpecsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnalyzeSpecsResponse) ProtoMessage() {}

func (x *BatchAnalyzeSpecsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnalyzeSpecsResponse.ProtoReflect.Descriptor instead.
func (*BatchAnalyzeSpecsResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{23}
}

func (x *BatchAnalyzeSpecsResponse) GetResults() []*SpecAnalysisResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Validate ISO 29148 request
type ValidateISO29148Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecId        string                 `protobuf:"bytes,1,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateISO29148Request) Reset() {
	*x = ValidateISO29148Request{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateISO29148Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateISO29148Request) ProtoMessage() {}

func (x *ValidateISO29148Request) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateISO29148Request.ProtoReflect.Descriptor instead.
func (*ValidateISO29148Request) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{24}
}

func (x *ValidateISO29148Request) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

func (x *ValidateISO29148Request) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ValidateISO29148Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Validate ISO 29148 response
type ValidateISO29148Response struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompliantWithIso bool                   `protobuf:"varint,1,opt,name=compliant_with_iso,json=compliantWithIso,proto3" json:"compliant_with_iso,omitempty"`
	Recommendations  []string               `protobuf:"bytes,2,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateISO29148Response) Reset() {
	*x = ValidateISO29148Response{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateISO29148Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateISO29148Response) ProtoMessage() {}

func (x *ValidateISO29148Response) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateISO29148Response.ProtoReflect.Descriptor instead.
func (*ValidateISO29148Response) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{25}
}

func (x *ValidateISO29148Response) GetCompliantWithIso() bool {
	if x != nil {
		return x.CompliantWithIso
	}
	return false
}

func (x *ValidateISO29148Response) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// Get EARS patterns request
type GetEARSPatternsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecId        string                 `protobuf:"bytes,1,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEARSPatternsRequest) Reset() {
	*x = GetEARSPatternsRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEARSPatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEARSPatternsRequest) ProtoMessage() {}

func (x *GetEARSPatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEARSPatternsRequest.ProtoReflect.Descriptor instead.
func (*GetEARSPatternsRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{26}
}

func (x *GetEARSPatternsRequest) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

func (x *GetEARSPatternsRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetEARSPatternsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Get EARS patterns response
type GetEARSPatternsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EarsPatterns  []*EARSPattern         `protobuf:"bytes,1,rep,name=ears_patterns,json=earsPatterns,proto3" json:"ears_patterns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEARSPatternsResponse) Reset() {
	*x = GetEARSPatternsResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEARSPatternsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEARSPatternsResponse) ProtoMessage() {}

func (x *GetEARSPatternsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEARSPatternsResponse.ProtoReflect.Descriptor instead.
func (*GetEARSPatternsResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{27}
}

func (x *GetEARSPatternsResponse) GetEarsPatterns() []*EARSPattern {
	if x != nil {
		return x.EarsPatterns
	}
	return nil
}

// Spec analysis result
type SpecAnalysisResult struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	SpecId             string                    `protobuf:"bytes,1,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	CompliantWithIso   bool                      `protobuf:"varint,2,opt,name=compliant_with_iso,json=compliantWithIso,proto3" json:"compliant_with_iso,omitempty"`
	EarsPatterns       []*EARSPattern            `protobuf:"bytes,3,rep,name=ears_patterns,json=earsPatterns,proto3" json:"ears_patterns,omitempty"`
	OdcClassification  *ODCClassification        `protobuf:"bytes,4,opt,name=odc_classification,json=odcClassification,proto3" json:"odc_classification,omitempty"`
	FormalVerification *FormalVerificationResult `protobuf:"bytes,5,opt,name=formal_verification,json=formalVerification,proto3" json:"formal_verification,omitempty"`
	Recommendations    []string                  `protobuf:"bytes,6,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	QualityScore       float64                   `protobuf:"fixed64,7,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	QualityGrade       string                    `protobuf:"bytes,8,opt,name=quality_grade,json=qualityGrade,proto3" json:"quality_grade,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SpecAnalysisResult) Reset() {
	*x = SpecAnalysisResult{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecAnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecAnalysisResult) ProtoMessage() {}

func (x *SpecAnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecAnalysisResult.ProtoReflect.Descriptor instead.
func (*SpecAnalysisResult) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{28}
}

func (x *SpecAnalysisResult) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

func (x *SpecAnalysisResult) GetCompliantWithIso() bool {
	if x != nil {
		return x.CompliantWithIso
	}
	return false
}

func (x *SpecAnalysisResult) GetEarsPatterns() []*EARSPattern {
	if x != nil {
		return x.EarsPatterns
	}
	return nil
}

func (x *SpecAnalysisResult) GetOdcClassification() *ODCClassification {
	if x != nil {
		return x.OdcClassification
	}
	return nil
}

func (x *SpecAnalysisResult) GetFormalVerification() *FormalVerificationResult {
	if x != nil {
		return x.FormalVerification
	}
	return nil
}

func (x *SpecAnalysisResult) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *SpecAnalysisResult) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *SpecAnalysisResult) GetQualityGrade() string {
	if x != nil {
		return x.QualityGrade
	}
	return ""
}

// EARSPattern represents an EARS (Easy Approach to Requirements Syntax) pattern match
type EARSPattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // UBIQUITOUS, EVENT_DRIVEN, UNWANTED_BEHAVIOR, STATE_DRIVEN, OPTIONAL_FEATURE, etc.
	Matched       bool                   `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EARSPattern) Reset() {
	*x = EARSPattern{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EARSPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EARSPattern) ProtoMessage() {}

func (x *EARSPattern) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EARSPattern.ProtoReflect.Descriptor instead.
func (*EARSPattern) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{29}
}

func (x *EARSPattern) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EARSPattern) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *EARSPattern) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Formal verification result
type FormalVerificationResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsVerifiable   bool                   `protobuf:"varint,1,opt,name=is_verifiable,json=isVerifiable,proto3" json:"is_verifiable,omitempty"`
	LogicalFormula string                 `protobuf:"bytes,2,opt,name=logical_formula,json=logicalFormula,proto3" json:"logical_formula,omitempty"`
	Contradictions []string               `protobuf:"bytes,3,rep,name=contradictions,proto3" json:"contradictions,omitempty"`
	Ambiguities    []string               `protobuf:"bytes,4,rep,name=ambiguities,proto3" json:"ambiguities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FormalVerificationResult) Reset() {
	*x = FormalVerificationResult{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormalVerificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormalVerificationResult) ProtoMessage() {}

func (x *FormalVerificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormalVerificationResult.ProtoReflect.Descriptor instead.
func (*FormalVerificationResult) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{30}
}

func (x *FormalVerificationResult) GetIsVerifiable() bool {
	if x != nil {
		return x.IsVerifiable
	}
	return false
}

func (x *FormalVerificationResult) GetLogicalFormula() string {
	if x != nil {
		return x.LogicalFormula
	}
	return ""
}

func (x *FormalVerificationResult) GetContradictions() []string {
	if x != nil {
		return x.Contradictions
	}
	return nil
}

func (x *FormalVerificationResult) GetAmbiguities() []string {
	if x != nil {
		return x.Ambiguities
	}
	return nil
}

// ODC classification result
type ODCClassification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectType    string                 `protobuf:"bytes,1,opt,name=defect_type,json=defectType,proto3" json:"defect_type,omitempty"`
	Trigger       string                 `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Impact        string                 `protobuf:"bytes,3,opt,name=impact,proto3" json:"impact,omitempty"`
	Qualifier     string                 `protobuf:"bytes,4,opt,name=qualifier,proto3" json:"qualifier,omitempty"`
	Age           string                 `protobuf:"bytes,5,opt,name=age,proto3" json:"age,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ODCClassification) Reset() {
	*x = ODCClassification{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ODCClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ODCClassification) ProtoMessage() {}

func (x *ODCClassification) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ODCClassification.ProtoReflect.Descriptor instead.
func (*ODCClassification) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{31}
}

func (x *ODCClassification) GetDefectType() string {
	if x != nil {
		return x.DefectType
	}
	return ""
}

func (x *ODCClassification) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *ODCClassification) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *ODCClassification) GetQualifier() string {
	if x != nil {
		return x.Qualifier
	}
	return ""
}

func (x *ODCClassification) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *ODCClassification) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ODCClassification) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// An extracted entity
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "person", "organization", "technology", "concept", etc.
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	StartPos      int32                  `protobuf:"varint,4,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"` // Character position in text
	EndPos        int32                  `protobuf:"varint,5,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{32}
}

func (x *Entity) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Entity) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *Entity) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

// Standard error details
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{33}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Health check request/response
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{34}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "serving", "not_serving", "unknown"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracertm_v1_tracertm_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_tracertm_v1_tracertm_proto_rawDescGZIP(), []int{35}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_tracertm_v1_tracertm_proto protoreflect.FileDescriptor

const file_tracertm_v1_tracertm_proto_rawDesc = "" +
	"\n" +
	"\x1atracertm/v1/tracertm.proto\x12\vtracertm.v1\"\xa8\x01\n" +
	"\x14AnalyzeImpactRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1b\n" +
	"\tmax_depth\x18\x04 \x01(\x05R\bmaxDepth\x12\x1d\n" +
	"\n" +
	"link_types\x18\x05 \x03(\tR\tlinkTypes\"\xf0\x03\n" +
	"\x15AnalyzeImpactResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12@\n" +
	"\x0eimpacted_items\x18\x02 \x03(\v2\x19.tracertm.v1.ImpactedItemR\rimpactedItems\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12W\n" +
	"\ritems_by_type\x18\x04 \x03(\v23.tracertm.v1.AnalyzeImpactResponse.ItemsByTypeEntryR\vitemsByType\x12Z\n" +
	"\x0eitems_by_depth\x18\x05 \x03(\v24.tracertm.v1.AnalyzeImpactResponse.ItemsByDepthEntryR\fitemsByDepth\x12%\n" +
	"\x0ecritical_paths\x18\x06 \x03(\tR\rcriticalPaths\x1a>\n" +
	"\x10ItemsByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11ItemsByDepthEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9e\x01\n" +
	"\fImpactedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12\x1b\n" +
	"\tlink_type\x18\x05 \x01(\tR\blinkType\x12!\n" +
	"\fimpact_score\x18\x06 \x01(\x01R\vimpactScore\"{\n" +
	"\x11FindCyclesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"link_types\x18\x02 \x03(\tR\tlinkTypes\x12(\n" +
	"\x10max_cycle_length\x18\x03 \x01(\x05R\x0emaxCycleLength\"\x80\x01\n" +
	"\x12FindCyclesResponse\x12*\n" +
	"\x06cycles\x18\x01 \x03(\v2\x12.tracertm.v1.CycleR\x06cycles\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"has_cycles\x18\x03 \x01(\bR\thasCycles\"u\n" +
	"\x05Cycle\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\tR\aitemIds\x12\x1d\n" +
	"\n" +
	"link_types\x18\x02 \x03(\tR\tlinkTypes\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\x01R\bseverity\"\xa0\x01\n" +
	"\x14CalculatePathRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12$\n" +
	"\x0esource_item_id\x18\x02 \x01(\tR\fsourceItemId\x12$\n" +
	"\x0etarget_item_id\x18\x03 \x01(\tR\ftargetItemId\x12\x1d\n" +
	"\n" +
	"link_types\x18\x04 \x03(\tR\tlinkTypes\"\xb4\x01\n" +
	"\x15CalculatePathResponse\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\tR\aitemIds\x12\x1d\n" +
	"\n" +
	"link_types\x18\x02 \x03(\tR\tlinkTypes\x12\x1f\n" +
	"\vpath_length\x18\x03 \x01(\x05R\n" +
	"pathLength\x12\x1f\n" +
	"\vpath_exists\x18\x04 \x01(\bR\n" +
	"pathExists\x12\x1f\n" +
	"\vpath_weight\x18\x05 \x01(\x01R\n" +
	"pathWeight\"[\n" +
	"\x19StreamGraphUpdatesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\"\xa1\x02\n" +
	"\x1aStreamGraphUpdatesResponse\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12Q\n" +
	"\bmetadata\x18\x05 \x03(\v25.tracertm.v1.StreamGraphUpdatesResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x19AnalyzeRequirementRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\titem_type\x18\x03 \x01(\tR\bitemType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\"\xf3\x02\n" +
	"\x1aAnalyzeRequirementResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x125\n" +
	"\aquality\x18\x02 \x01(\v2\x1b.tracertm.v1.QualityMetricsR\aquality\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12#\n" +
	"\rrelated_items\x18\x04 \x03(\tR\frelatedItems\x12\x1c\n" +
	"\tsentiment\x18\x05 \x01(\tR\tsentiment\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12Q\n" +
	"\bmetadata\x18\a \x03(\v25.tracertm.v1.AnalyzeRequirementResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x0eQualityMetrics\x12\"\n" +
	"\fcompleteness\x18\x01 \x01(\x01R\fcompleteness\x12\x18\n" +
	"\aclarity\x18\x02 \x01(\x01R\aclarity\x12 \n" +
	"\vtestability\x18\x03 \x01(\x01R\vtestability\x12 \n" +
	"\vconsistency\x18\x04 \x01(\x01R\vconsistency\x12\x16\n" +
	"\x06issues\x18\x05 \x03(\tR\x06issues\x12(\n" +
	"\x0frecommendations\x18\x06 \x03(\tR\x0frecommendations\"\xa7\x01\n" +
	"\x1aGenerateSuggestionsRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12'\n" +
	"\x0fsuggestion_type\x18\x03 \x01(\tR\x0esuggestionType\x12'\n" +
	"\x0fmax_suggestions\x18\x04 \x01(\x05R\x0emaxSuggestions\"\x9a\x02\n" +
	"\x1bGenerateSuggestionsResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12R\n" +
	"\bmetadata\x18\x04 \x03(\v26.tracertm.v1.GenerateSuggestionsResponse.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\treasoning\x18\x05 \x01(\tR\treasoning\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x19DetectEquivalencesRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x121\n" +
	"\x14similarity_threshold\x18\x04 \x01(\x01R\x13similarityThreshold\"\x95\x01\n" +
	"\x1aDetectEquivalencesResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12=\n" +
	"\vequivalents\x18\x02 \x03(\v2\x1b.tracertm.v1.EquivalentItemR\vequivalents\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xa0\x01\n" +
	"\x0eEquivalentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12)\n" +
	"\x10similarity_score\x18\x04 \x01(\x01R\x0fsimilarityScore\x12)\n" +
	"\x10matching_phrases\x18\x05 \x03(\tR\x0fmatchingPhrases\"h\n" +
	"\x16ExtractEntitiesRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12!\n" +
	"\fentity_types\x18\x03 \x03(\tR\ventityTypes\"k\n" +
	"\x17ExtractEntitiesResponse\x12/\n" +
	"\bentities\x18\x01 \x03(\v2\x13.tracertm.v1.EntityR\bentities\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"f\n" +
	"\x12AnalyzeSpecRequest\x12\x17\n" +
	"\aspec_id\x18\x01 \x01(\tR\x06specId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\"N\n" +
	"\x13AnalyzeSpecResponse\x127\n" +
	"\x06result\x18\x01 \x01(\v2\x1f.tracertm.v1.SpecAnalysisResultR\x06result\"W\n" +
	"\x18BatchAnalyzeSpecsRequest\x12;\n" +
	"\brequests\x18\x01 \x03(\v2\x1f.tracertm.v1.AnalyzeSpecRequestR\brequests\"V\n" +
	"\x19BatchAnalyzeSpecsResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.tracertm.v1.SpecAnalysisResultR\aresults\"k\n" +
	"\x17ValidateISO29148Request\x12\x17\n" +
	"\aspec_id\x18\x01 \x01(\tR\x06specId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\"r\n" +
	"\x18ValidateISO29148Response\x12,\n" +
	"\x12compliant_with_iso\x18\x01 \x01(\bR\x10compliantWithIso\x12(\n" +
	"\x0frecommendations\x18\x02 \x03(\tR\x0frecommendations\"j\n" +
	"\x16GetEARSPatternsRequest\x12\x17\n" +
	"\aspec_id\x18\x01 \x01(\tR\x06specId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\"X\n" +
	"\x17GetEARSPatternsResponse\x12=\n" +
	"\rears_patterns\x18\x01 \x03(\v2\x18.tracertm.v1.EARSPatternR\fearsPatterns\"\xb5\x03\n" +
	"\x12SpecAnalysisResult\x12\x17\n" +
	"\aspec_id\x18\x01 \x01(\tR\x06specId\x12,\n" +
	"\x12compliant_with_iso\x18\x02 \x01(\bR\x10compliantWithIso\x12=\n" +
	"\rears_patterns\x18\x03 \x03(\v2\x18.tracertm.v1.EARSPatternR\fearsPatterns\x12M\n" +
	"\x12odc_classification\x18\x04 \x01(\v2\x1e.tracertm.v1.ODCClassificationR\x11odcClassification\x12V\n" +
	"\x13formal_verification\x18\x05 \x01(\v2%.tracertm.v1.FormalVerificationResultR\x12formalVerification\x12(\n" +
	"\x0frecommendations\x18\x06 \x03(\tR\x0frecommendations\x12#\n" +
	"\rquality_score\x18\a \x01(\x01R\fqualityScore\x12#\n" +
	"\rquality_grade\x18\b \x01(\tR\fqualityGrade\"[\n" +
	"\vEARSPattern\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\"\xb2\x01\n" +
	"\x18FormalVerificationResult\x12#\n" +
	"\ris_verifiable\x18\x01 \x01(\bR\fisVerifiable\x12'\n" +
	"\x0flogical_formula\x18\x02 \x01(\tR\x0elogicalFormula\x12&\n" +
	"\x0econtradictions\x18\x03 \x03(\tR\x0econtradictions\x12 \n" +
	"\vambiguities\x18\x04 \x03(\tR\vambiguities\"\xce\x01\n" +
	"\x11ODCClassification\x12\x1f\n" +
	"\vdefect_type\x18\x01 \x01(\tR\n" +
	"defectType\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\x12\x16\n" +
	"\x06impact\x18\x03 \x01(\tR\x06impact\x12\x1c\n" +
	"\tqualifier\x18\x04 \x01(\tR\tqualifier\x12\x10\n" +
	"\x03age\x18\x05 \x01(\tR\x03age\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\"\x86\x01\n" +
	"\x06Entity\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1b\n" +
	"\tstart_pos\x18\x04 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x05 \x01(\x05R\x06endPos\"\xac\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\adetails\x18\x03 \x03(\v2\x1f.tracertm.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xf7\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..tracertm.v1.HealthCheckResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf6\x02\n" +
	"\fGraphService\x12V\n" +
	"\rAnalyzeImpact\x12!.tracertm.v1.AnalyzeImpactRequest\x1a\".tracertm.v1.AnalyzeImpactResponse\x12M\n" +
	"\n" +
	"FindCycles\x12\x1e.tracertm.v1.FindCyclesRequest\x1a\x1f.tracertm.v1.FindCyclesResponse\x12V\n" +
	"\rCalculatePath\x12!.tracertm.v1.CalculatePathRequest\x1a\".tracertm.v1.CalculatePathResponse\x12g\n" +
	"\x12StreamGraphUpdates\x12&.tracertm.v1.StreamGraphUpdatesRequest\x1a'.tracertm.v1.StreamGraphUpdatesResponse0\x012\xa3\x03\n" +
	"\tAIService\x12e\n" +
	"\x12AnalyzeRequirement\x12&.tracertm.v1.AnalyzeRequirementRequest\x1a'.tracertm.v1.AnalyzeRequirementResponse\x12j\n" +
	"\x13GenerateSuggestions\x12'.tracertm.v1.GenerateSuggestionsRequest\x1a(.tracertm.v1.GenerateSuggestionsResponse0\x01\x12e\n" +
	"\x12DetectEquivalences\x12&.tracertm.v1.DetectEquivalencesRequest\x1a'.tracertm.v1.DetectEquivalencesResponse\x12\\\n" +
	"\x0fExtractEntities\x12#.tracertm.v1.ExtractEntitiesRequest\x1a$.tracertm.v1.ExtractEntitiesResponse2\x8b\x03\n" +
	"\x14SpecAnalyticsService\x12P\n" +
	"\vAnalyzeSpec\x12\x1f.tracertm.v1.AnalyzeSpecRequest\x1a .tracertm.v1.AnalyzeSpecResponse\x12b\n" +
	"\x11BatchAnalyzeSpecs\x12%.tracertm.v1.BatchAnalyzeSpecsRequest\x1a&.tracertm.v1.BatchAnalyzeSpecsResponse\x12_\n" +
	"\x10ValidateISO29148\x12$.tracertm.v1.ValidateISO29148Request\x1a%.tracertm.v1.ValidateISO29148Response\x12\\\n" +
	"\x0fGetEARSPatterns\x12#.tracertm.v1.GetEARSPatternsRequest\x1a$.tracertm.v1.GetEARSPatternsResponseB>Z<github.com/kooshapari/tracertm-backend/pkg/proto/tracertm/v1b\x06proto3"

var (
	file_tracertm_v1_tracertm_proto_rawDescOnce sync.Once
	file_tracertm_v1_tracertm_proto_rawDescData []byte
)

func file_tracertm_v1_tracertm_proto_rawDescGZIP() []byte {
	file_tracertm_v1_tracertm_proto_rawDescOnce.Do(func() {
		file_tracertm_v1_tracertm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracertm_v1_tracertm_proto_rawDesc), len(file_tracertm_v1_tracertm_proto_rawDesc)))
	})
	return file_tracertm_v1_tracertm_proto_rawDescData
}

var file_tracertm_v1_tracertm_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_tracertm_v1_tracertm_proto_goTypes = []any{
	(*AnalyzeImpactRequest)(nil),        // 0: tracertm.v1.AnalyzeImpactRequest
	(*AnalyzeImpactResponse)(nil),       // 1: tracertm.v1.AnalyzeImpactResponse
	(*ImpactedItem)(nil),                // 2: tracertm.v1.ImpactedItem
	(*FindCyclesRequest)(nil),           // 3: tracertm.v1.FindCyclesRequest
	(*FindCyclesResponse)(nil),          // 4: tracertm.v1.FindCyclesResponse
	(*Cycle)(nil),                       // 5: tracertm.v1.Cycle
	(*CalculatePathRequest)(nil),        // 6: tracertm.v1.CalculatePathRequest
	(*CalculatePathResponse)(nil),       // 7: tracertm.v1.CalculatePathResponse
	(*StreamGraphUpdatesRequest)(nil),   // 8: tracertm.v1.StreamGraphUpdatesRequest
	(*StreamGraphUpdatesResponse)(nil),  // 9: tracertm.v1.StreamGraphUpdatesResponse
	(*AnalyzeRequirementRequest)(nil),   // 10: tracertm.v1.AnalyzeRequirementRequest
	(*AnalyzeRequirementResponse)(nil),  // 11: tracertm.v1.AnalyzeRequirementResponse
	(*QualityMetrics)(nil),              // 12: tracertm.v1.QualityMetrics
	(*GenerateSuggestionsRequest)(nil),  // 13: tracertm.v1.GenerateSuggestionsRequest
	(*GenerateSuggestionsResponse)(nil), // 14: tracertm.v1.GenerateSuggestionsResponse
	(*DetectEquivalencesRequest)(nil),   // 15: tracertm.v1.DetectEquivalencesRequest
	(*DetectEquivalencesResponse)(nil),  // 16: tracertm.v1.DetectEquivalencesResponse
	(*EquivalentItem)(nil),              // 17: tracertm.v1.EquivalentItem
	(*ExtractEntitiesRequest)(nil),      // 18: tracertm.v1.ExtractEntitiesRequest
	(*ExtractEntitiesResponse)(nil),     // 19: tracertm.v1.ExtractEntitiesResponse
	(*AnalyzeSpecRequest)(nil),          // 20: tracertm.v1.AnalyzeSpecRequest
	(*AnalyzeSpecResponse)(nil),         // 21: tracertm.v1.AnalyzeSpecResponse
	(*BatchAnalyzeSpecsRequest)(nil),    // 22: tracertm.v1.BatchAnalyzeSpecsRequest
	(*BatchAnalyzeSpecsResponse)(nil),   // 23: tracertm.v1.BatchAnalyzeSpecsResponse
	(*ValidateISO29148Request)(nil),     // 24: tracertm.v1.ValidateISO29148Request
	(*ValidateISO29148Response)(nil),    // 25: tracertm.v1.ValidateISO29148Response
	(*GetEARSPatternsRequest)(nil),      // 26: tracertm.v1.GetEARSPatternsRequest
	(*GetEARSPatternsResponse)(nil),     // 27: tracertm.v1.GetEARSPatternsResponse
	(*SpecAnalysisResult)(nil),          // 28: tracertm.v1.SpecAnalysisResult
	(*EARSPattern)(nil),                 // 29: tracertm.v1.EARSPattern
	(*FormalVerificationResult)(nil),    // 30: tracertm.v1.FormalVerificationResult
	(*ODCClassification)(nil),           // 31: tracertm.v1.ODCClassification
	(*Entity)(nil),                      // 32: tracertm.v1.Entity
	(*Error)(nil),                       // 33: tracertm.v1.Error
	(*HealthCheckRequest)(nil),          // 34: tracertm.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 35: tracertm.v1.HealthCheckResponse
	nil,                                 // 36: tracertm.v1.AnalyzeImpactResponse.ItemsByTypeEntry
	nil,                                 // 37: tracertm.v1.AnalyzeImpactResponse.ItemsByDepthEntry
	nil,                                 // 38: tracertm.v1.StreamGraphUpdatesResponse.MetadataEntry
	nil,                                 // 39: tracertm.v1.AnalyzeRequirementResponse.MetadataEntry
	nil,                                 // 40: tracertm.v1.GenerateSuggestionsResponse.MetadataEntry
	nil,                                 // 41: tracertm.v1.Error.DetailsEntry
	nil,                                 // 42: tracertm.v1.HealthCheckResponse.MetadataEntry
}
var file_tracertm_v1_tracertm_proto_depIdxs = []int32{
	2,  // 0: tracertm.v1.AnalyzeImpactResponse.impacted_items:type_name -> tracertm.v1.ImpactedItem
	36, // 1: tracertm.v1.AnalyzeImpactResponse.items_by_type:type_name -> tracertm.v1.AnalyzeImpactResponse.ItemsByTypeEntry
	37, // 2: tracertm.v1.AnalyzeImpactResponse.items_by_depth:type_name -> tracertm.v1.AnalyzeImpactResponse.ItemsByDepthEntry
	5,  // 3: tracertm.v1.FindCyclesResponse.cycles:type_name -> tracertm.v1.Cycle
	38, // 4: tracertm.v1.StreamGraphUpdatesResponse.metadata:type_name -> tracertm.v1.StreamGraphUpdatesResponse.MetadataEntry
	12, // 5: tracertm.v1.AnalyzeRequirementResponse.quality:type_name -> tracertm.v1.QualityMetrics
	39, // 6: tracertm.v1.AnalyzeRequirementResponse.metadata:type_name -> tracertm.v1.AnalyzeRequirementResponse.MetadataEntry
	40, // 7: tracertm.v1.GenerateSuggestionsResponse.metadata:type_name -> tracertm.v1.GenerateSuggestionsResponse.MetadataEntry
	17, // 8: tracertm.v1.DetectEquivalencesResponse.equivalents:type_name -> tracertm.v1.EquivalentItem
	32, // 9: tracertm.v1.ExtractEntitiesResponse.entities:type_name -> tracertm.v1.Entity
	28, // 10: tracertm.v1.AnalyzeSpecResponse.result:type_name -> tracertm.v1.SpecAnalysisResult
	20, // 11: tracertm.v1.BatchAnalyzeSpecsRequest.requests:type_name -> tracertm.v1.AnalyzeSpecRequest
	28, // 12: tracertm.v1.BatchAnalyzeSpecsResponse.results:type_name -> tracertm.v1.SpecAnalysisResult
	29, // 13: tracertm.v1.GetEARSPatternsResponse.ears_patterns:type_name -> tracertm.v1.EARSPattern
	29, // 14: tracertm.v1.SpecAnalysisResult.ears_patterns:type_name -> tracertm.v1.EARSPattern
	31, // 15: tracertm.v1.SpecAnalysisResult.odc_classification:type_name -> tracertm.v1.ODCClassification
	30, // 16: tracertm.v1.SpecAnalysisResult.formal_verification:type_name -> tracertm.v1.FormalVerificationResult
	41, // 17: tracertm.v1.Error.details:type_name -> tracertm.v1.Error.DetailsEntry
	42, // 18: tracertm.v1.HealthCheckResponse.metadata:type_name -> tracertm.v1.HealthCheckResponse.MetadataEntry
	0,  // 19: tracertm.v1.GraphService.AnalyzeImpact:input_type -> tracertm.v1.AnalyzeImpactRequest
	3,  // 20: tracertm.v1.GraphService.FindCycles:input_type -> tracertm.v1.FindCyclesRequest
	6,  // 21: tracertm.v1.GraphService.CalculatePath:input_type -> tracertm.v1.CalculatePathRequest
	8,  // 22: tracertm.v1.GraphService.StreamGraphUpdates:input_type -> tracertm.v1.StreamGraphUpdatesRequest
	10, // 23: tracertm.v1.AIService.AnalyzeRequirement:input_type -> tracertm.v1.AnalyzeRequirementRequest
	13, // 24: tracertm.v1.AIService.GenerateSuggestions:input_type -> tracertm.v1.GenerateSuggestionsRequest
	15, // 25: tracertm.v1.AIService.DetectEquivalences:input_type -> tracertm.v1.DetectEquivalencesRequest
	18, // 26: tracertm.v1.AIService.ExtractEntities:input_type -> tracertm.v1.ExtractEntitiesRequest
	20, // 27: tracertm.v1.SpecAnalyticsService.AnalyzeSpec:input_type -> tracertm.v1.AnalyzeSpecRequest
	22, // 28: tracertm.v1.SpecAnalyticsService.BatchAnalyzeSpecs:input_type -> tracertm.v1.BatchAnalyzeSpecsRequest
	24, // 29: tracertm.v1.SpecAnalyticsService.ValidateISO29148:input_type -> tracertm.v1.ValidateISO29148Request
	26, // 30: tracertm.v1.SpecAnalyticsService.GetEARSPatterns:input_type -> tracertm.v1.GetEARSPatternsRequest
	1,  // 31: tracertm.v1.GraphService.AnalyzeImpact:output_type -> tracertm.v1.AnalyzeImpactResponse
	4,  // 32: tracertm.v1.GraphService.FindCycles:output_type -> tracertm.v1.FindCyclesResponse
	7,  // 33: tracertm.v1.GraphService.CalculatePath:output_type -> tracertm.v1.CalculatePathResponse
	9,  // 34: tracertm.v1.GraphService.StreamGraphUpdates:output_type -> tracertm.v1.StreamGraphUpdatesResponse
	11, // 35: tracertm.v1.AIService.AnalyzeRequirement:output_type -> tracertm.v1.AnalyzeRequirementResponse
	14, // 36: tracertm.v1.AIService.GenerateSuggestions:output_type -> tracertm.v1.GenerateSuggestionsResponse
	16, // 37: tracertm.v1.AIService.DetectEquivalences:output_type -> tracertm.v1.DetectEquivalencesResponse
	19, // 38: tracertm.v1.AIService.ExtractEntities:output_type -> tracertm.v1.ExtractEntitiesResponse
	21, // 39: tracertm.v1.SpecAnalyticsService.AnalyzeSpec:output_type -> tracertm.v1.AnalyzeSpecResponse
	23, // 40: tracertm.v1.SpecAnalyticsService.BatchAnalyzeSpecs:output_type -> tracertm.v1.BatchAnalyzeSpecsResponse
	25, // 41: tracertm.v1.SpecAnalyticsService.ValidateISO29148:output_type -> tracertm.v1.ValidateISO29148Response
	27, // 42: tracertm.v1.SpecAnalyticsService.GetEARSPatterns:output_type -> tracertm.v1.GetEARSPatternsResponse
	31, // [31:43] is the sub-list for method output_type
	19, // [19:31] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_tracertm_v1_tracertm_proto_init() }
func file_tracertm_v1_tracertm_proto_init() {
	if File_tracertm_v1_tracertm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracertm_v1_tracertm_proto_rawDesc), len(file_tracertm_v1_tracertm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_tracertm_v1_tracertm_proto_goTypes,
		DependencyIndexes: file_tracertm_v1_tracertm_proto_depIdxs,
		MessageInfos:      file_tracertm_v1_tracertm_proto_msgTypes,
	}.Build()
	File_tracertm_v1_tracertm_proto = out.File
	file_tracertm_v1_tracertm_proto_goTypes = nil
	file_tracertm_v1_tracertm_proto_depIdxs = nil
}
