/**
 * CSF 3.0 Story Template Generator for TraceRTM
 * Generates type-safe Storybook stories with design integration
 */

import type { PropInfo, StoryTemplateConfig, VariantInfo } from '../config';

/**
 * Generate a complete story file content
 */
export function generateStoryTemplate(config: StoryTemplateConfig): string {
  const {
    componentName,
    importPath,
    title,
    componentId,
    storyId,
    figmaUrl,
    variants = [],
    props = [],
  } = config;

  return `// Auto-generated by TraceRTM Storybook Generator
// Do not edit manually - regenerate using: bun run generate:stories
import type { Meta, StoryObj } from '@storybook/react-vite'
import { ${componentName} } from '${importPath}'

const meta: Meta<typeof ${componentName}> = {
  title: '${title}',
  component: ${componentName},
  tags: ['autodocs'],${generateArgTypes(variants, props)}${generateParameters(componentId, storyId, figmaUrl)}
}

export default meta
type Story = StoryObj<typeof meta>

${generateVariantStories(componentName, variants)}
${generateShowcaseStory(componentName, variants)}
`.trim();
}

/**
 * Generate argTypes configuration for controls
 */
function generateArgTypes(variants: VariantInfo[], props: PropInfo[]): string {
  const controls: string[] = [];

  // Add variant controls
  for (const variant of variants) {
    if (variant.options.length > 0) {
      controls.push(`    ${variant.name}: {
      control: 'select',
      options: [${variant.options.map((opt) => `'${opt}'`).join(', ')}],
    }`);
    }
  }

  // Add prop controls
  for (const prop of props) {
    if (prop.type === 'boolean') {
      controls.push(`    ${prop.name}: { control: 'boolean' }`);
    } else if (prop.type === 'string') {
      controls.push(`    ${prop.name}: { control: 'text' }`);
    } else if (prop.type === 'number') {
      controls.push(`    ${prop.name}: { control: 'number' }`);
    }
  }

  if (controls.length === 0) {
    return '';
  }

  return `
  argTypes: {
${controls.join(',\n')}
  },`;
}

/**
 * Generate parameters for design integration and traceability
 */
function generateParameters(componentId?: string, storyId?: string, figmaUrl?: string): string {
  const params: string[] = [];

  if (figmaUrl) {
    params.push(`    design: {
      type: 'figma',
      url: '${figmaUrl}',
    }`);
  }

  if (componentId || storyId) {
    params.push(`    trace: {${
      componentId
        ? `
      componentId: '${componentId}',`
        : ''
    }${
      storyId
        ? `
      storyId: '${storyId}',`
        : ''
    }
    }`);
  }

  if (params.length === 0) {
    return '';
  }

  return `
  parameters: {
${params.join(',\n')}
  },`;
}

/**
 * Generate stories for each variant option
 */
function generateVariantStories(componentName: string, variants: VariantInfo[]): string {
  const stories: string[] = [];
  const generatedNames = new Set<string>();

  for (const variant of variants) {
    for (const option of variant.options) {
      const storyName = capitalize(option);

      // Skip if this story name was already generated (e.g., from default value)
      if (generatedNames.has(storyName)) {
        continue;
      }
      generatedNames.add(storyName);

      const childrenText = getChildrenText(componentName, option);

      stories.push(`export const ${storyName}: Story = {
  args: {${
    childrenText
      ? `
    children: '${childrenText}',`
      : ''
  }
    ${variant.name}: '${option}',
  },
}`);
    }
  }

  return stories.join('\n\n');
}

/**
 * Generate showcase story with all variants
 */
function generateShowcaseStory(componentName: string, variants: VariantInfo[]): string {
  if (variants.length === 0) {
    return '';
  }

  const mainVariant = variants[0];
  if (!mainVariant || mainVariant.options.length === 0) {
    return '';
  }

  const elements = mainVariant.options
    .map((option) => {
      const childrenText = getChildrenText(componentName, option);
      return `      <${componentName} ${mainVariant.name}="${option}">${childrenText}</${componentName}>`;
    })
    .join('\n');

  return `
export const AllVariants: Story = {
  render: () => (
    <div className="flex flex-wrap gap-4">
${elements}
    </div>
  ),
}
`;
}

/**
 * Get appropriate children text for a component variant
 */
function getChildrenText(componentName: string, option: string): string {
  // Components that don't typically have children
  if (['Input', 'Card', 'Avatar', 'Skeleton', 'Progress'].includes(componentName)) {
    return '';
  }

  return capitalize(option);
}

/**
 * Capitalize first letter of a string
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Generate story title from component path
 */
export function generateStoryTitle(componentPath: string, componentName: string): string {
  if (componentPath.includes('packages/ui')) {
    return `Components/${componentName}`;
  }

  if (componentPath.includes('layout')) {
    return `Layout/${componentName}`;
  }

  if (componentPath.includes('forms')) {
    return `Forms/${componentName}`;
  }

  return `Components/${componentName}`;
}
