# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
# type: ignore[attr-defined,unresolved-attribute]  # Generated; _pb2 and grpc.experimental vary by proto/grpcio version

import grpc

from tracertm.proto.proto import tracertm_pb2 as proto_dot_tracertm__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in proto/tracertm_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GraphServiceStub:
    """============================================================================
    GraphService - Provided by Go, Consumed by Python
    ============================================================================

    GraphService provides graph analysis and traversal operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeImpact = channel.unary_unary(
            "/tracertm.GraphService/AnalyzeImpact",
            request_serializer=proto_dot_tracertm__pb2.ImpactRequest.SerializeToString,
            response_deserializer=proto_dot_tracertm__pb2.ImpactResponse.FromString,
            _registered_method=True,
        )
        self.FindCycles = channel.unary_unary(
            "/tracertm.GraphService/FindCycles",
            request_serializer=proto_dot_tracertm__pb2.CycleRequest.SerializeToString,
            response_deserializer=proto_dot_tracertm__pb2.CycleResponse.FromString,
            _registered_method=True,
        )
        self.CalculatePath = channel.unary_unary(
            "/tracertm.GraphService/CalculatePath",
            request_serializer=proto_dot_tracertm__pb2.PathRequest.SerializeToString,
            response_deserializer=proto_dot_tracertm__pb2.PathResponse.FromString,
            _registered_method=True,
        )
        self.StreamGraphUpdates = channel.unary_stream(
            "/tracertm.GraphService/StreamGraphUpdates",
            request_serializer=proto_dot_tracertm__pb2.GraphStreamRequest.SerializeToString,
            response_deserializer=proto_dot_tracertm__pb2.GraphUpdate.FromString,
            _registered_method=True,
        )


class GraphServiceServicer:
    """============================================================================
    GraphService - Provided by Go, Consumed by Python
    ============================================================================

    GraphService provides graph analysis and traversal operations
    """

    def AnalyzeImpact(self, request, context):
        """AnalyzeImpact performs impact analysis for a given item"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FindCycles(self, request, context):
        """FindCycles detects circular dependencies in the graph"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CalculatePath(self, request, context):
        """CalculatePath finds the shortest path between two items"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamGraphUpdates(self, request, context):
        """StreamGraphUpdates streams real-time graph changes"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AnalyzeImpact": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeImpact,
            request_deserializer=proto_dot_tracertm__pb2.ImpactRequest.FromString,
            response_serializer=proto_dot_tracertm__pb2.ImpactResponse.SerializeToString,
        ),
        "FindCycles": grpc.unary_unary_rpc_method_handler(
            servicer.FindCycles,
            request_deserializer=proto_dot_tracertm__pb2.CycleRequest.FromString,
            response_serializer=proto_dot_tracertm__pb2.CycleResponse.SerializeToString,
        ),
        "CalculatePath": grpc.unary_unary_rpc_method_handler(
            servicer.CalculatePath,
            request_deserializer=proto_dot_tracertm__pb2.PathRequest.FromString,
            response_serializer=proto_dot_tracertm__pb2.PathResponse.SerializeToString,
        ),
        "StreamGraphUpdates": grpc.unary_stream_rpc_method_handler(
            servicer.StreamGraphUpdates,
            request_deserializer=proto_dot_tracertm__pb2.GraphStreamRequest.FromString,
            response_serializer=proto_dot_tracertm__pb2.GraphUpdate.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("tracertm.GraphService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("tracertm.GraphService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.


class GraphService:
    """============================================================================
    GraphService - Provided by Go, Consumed by Python
    ============================================================================

    GraphService provides graph analysis and traversal operations
    """

    @staticmethod
    def AnalyzeImpact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tracertm.GraphService/AnalyzeImpact",
            proto_dot_tracertm__pb2.ImpactRequest.SerializeToString,
            proto_dot_tracertm__pb2.ImpactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FindCycles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tracertm.GraphService/FindCycles",
            proto_dot_tracertm__pb2.CycleRequest.SerializeToString,
            proto_dot_tracertm__pb2.CycleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CalculatePath(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tracertm.GraphService/CalculatePath",
            proto_dot_tracertm__pb2.PathRequest.SerializeToString,
            proto_dot_tracertm__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamGraphUpdates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/tracertm.GraphService/StreamGraphUpdates",
            proto_dot_tracertm__pb2.GraphStreamRequest.SerializeToString,
            proto_dot_tracertm__pb2.GraphUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class AIServiceStub:
    """============================================================================
    AIService - Provided by Python, Consumed by Go
    ============================================================================

    AIService provides AI-powered analysis and suggestions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeRequirement = channel.unary_unary(
            "/tracertm.AIService/AnalyzeRequirement",
            request_serializer=proto_dot_tracertm__pb2.RequirementRequest.SerializeToString,
            response_deserializer=proto_dot_tracertm__pb2.RequirementResponse.FromString,
            _registered_method=True,
        )
        self.GenerateSuggestions = channel.unary_stream(
            "/tracertm.AIService/GenerateSuggestions",
            request_serializer=proto_dot_tracertm__pb2.SuggestionRequest.SerializeToString,
            response_deserializer=proto_dot_tracertm__pb2.Suggestion.FromString,
            _registered_method=True,
        )
        self.DetectEquivalences = channel.unary_unary(
            "/tracertm.AIService/DetectEquivalences",
            request_serializer=proto_dot_tracertm__pb2.EquivalenceRequest.SerializeToString,
            response_deserializer=proto_dot_tracertm__pb2.EquivalenceResponse.FromString,
            _registered_method=True,
        )
        self.ExtractEntities = channel.unary_unary(
            "/tracertm.AIService/ExtractEntities",
            request_serializer=proto_dot_tracertm__pb2.EntityRequest.SerializeToString,
            response_deserializer=proto_dot_tracertm__pb2.EntityResponse.FromString,
            _registered_method=True,
        )


class AIServiceServicer:
    """============================================================================
    AIService - Provided by Python, Consumed by Go
    ============================================================================

    AIService provides AI-powered analysis and suggestions
    """

    def AnalyzeRequirement(self, request, context):
        """AnalyzeRequirement performs NLP analysis on a requirement"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateSuggestions(self, request, context):
        """GenerateSuggestions streams AI-generated suggestions"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DetectEquivalences(self, request, context):
        """DetectEquivalences finds semantically equivalent items"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExtractEntities(self, request, context):
        """ExtractEntities extracts named entities from text"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AnalyzeRequirement": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeRequirement,
            request_deserializer=proto_dot_tracertm__pb2.RequirementRequest.FromString,
            response_serializer=proto_dot_tracertm__pb2.RequirementResponse.SerializeToString,
        ),
        "GenerateSuggestions": grpc.unary_stream_rpc_method_handler(
            servicer.GenerateSuggestions,
            request_deserializer=proto_dot_tracertm__pb2.SuggestionRequest.FromString,
            response_serializer=proto_dot_tracertm__pb2.Suggestion.SerializeToString,
        ),
        "DetectEquivalences": grpc.unary_unary_rpc_method_handler(
            servicer.DetectEquivalences,
            request_deserializer=proto_dot_tracertm__pb2.EquivalenceRequest.FromString,
            response_serializer=proto_dot_tracertm__pb2.EquivalenceResponse.SerializeToString,
        ),
        "ExtractEntities": grpc.unary_unary_rpc_method_handler(
            servicer.ExtractEntities,
            request_deserializer=proto_dot_tracertm__pb2.EntityRequest.FromString,
            response_serializer=proto_dot_tracertm__pb2.EntityResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("tracertm.AIService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("tracertm.AIService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.


class AIService:
    """============================================================================
    AIService - Provided by Python, Consumed by Go
    ============================================================================

    AIService provides AI-powered analysis and suggestions
    """

    @staticmethod
    def AnalyzeRequirement(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tracertm.AIService/AnalyzeRequirement",
            proto_dot_tracertm__pb2.RequirementRequest.SerializeToString,
            proto_dot_tracertm__pb2.RequirementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateSuggestions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/tracertm.AIService/GenerateSuggestions",
            proto_dot_tracertm__pb2.SuggestionRequest.SerializeToString,
            proto_dot_tracertm__pb2.Suggestion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DetectEquivalences(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tracertm.AIService/DetectEquivalences",
            proto_dot_tracertm__pb2.EquivalenceRequest.SerializeToString,
            proto_dot_tracertm__pb2.EquivalenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExtractEntities(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tracertm.AIService/ExtractEntities",
            proto_dot_tracertm__pb2.EntityRequest.SerializeToString,
            proto_dot_tracertm__pb2.EntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
