-- CreditPulse Links: 200+ connections for dense graph view
-- Connects 100 requirements to 110 features with multiple link types

-- Helper function to generate unique link IDs
-- Will create link_cp_001 through link_cp_250+

-- Requirements → Features (implements) - 1-3 features per requirement
-- req_cp_001-010: Each implements 2-3 features
INSERT INTO links (id, project_id, source_item_id, target_item_id, link_type, link_metadata, created_at, updated_at) VALUES
('link_cp_001', 'proj_creditpulse_001', 'req_cp_001', 'feat_cp_001', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_002', 'proj_creditpulse_001', 'req_cp_001', 'feat_cp_002', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_003', 'proj_creditpulse_001', 'req_cp_001', 'feat_cp_003', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_004', 'proj_creditpulse_001', 'req_cp_002', 'feat_cp_004', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_005', 'proj_creditpulse_001', 'req_cp_002', 'feat_cp_005', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_006', 'proj_creditpulse_001', 'req_cp_002', 'feat_cp_006', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_007', 'proj_creditpulse_001', 'req_cp_003', 'feat_cp_007', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_008', 'proj_creditpulse_001', 'req_cp_003', 'feat_cp_008', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_009', 'proj_creditpulse_001', 'req_cp_003', 'feat_cp_009', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_010', 'proj_creditpulse_001', 'req_cp_004', 'feat_cp_010', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_011', 'proj_creditpulse_001', 'req_cp_004', 'feat_cp_011', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_012', 'proj_creditpulse_001', 'req_cp_005', 'feat_cp_012', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_013', 'proj_creditpulse_001', 'req_cp_005', 'feat_cp_013', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_014', 'proj_creditpulse_001', 'req_cp_006', 'feat_cp_014', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_015', 'proj_creditpulse_001', 'req_cp_006', 'feat_cp_015', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_016', 'proj_creditpulse_001', 'req_cp_007', 'feat_cp_016', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_017', 'proj_creditpulse_001', 'req_cp_007', 'feat_cp_017', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_018', 'proj_creditpulse_001', 'req_cp_008', 'feat_cp_018', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_019', 'proj_creditpulse_001', 'req_cp_008', 'feat_cp_019', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_020', 'proj_creditpulse_001', 'req_cp_009', 'feat_cp_020', 'implements', '{"priority": "high"}', NOW(), NOW()),

-- req_cp_010-020: Each implements 1-2 features
('link_cp_021', 'proj_creditpulse_001', 'req_cp_010', 'feat_cp_021', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_022', 'proj_creditpulse_001', 'req_cp_010', 'feat_cp_022', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_023', 'proj_creditpulse_001', 'req_cp_011', 'feat_cp_023', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_024', 'proj_creditpulse_001', 'req_cp_012', 'feat_cp_024', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_025', 'proj_creditpulse_001', 'req_cp_012', 'feat_cp_025', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_026', 'proj_creditpulse_001', 'req_cp_013', 'feat_cp_026', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_027', 'proj_creditpulse_001', 'req_cp_013', 'feat_cp_027', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_028', 'proj_creditpulse_001', 'req_cp_014', 'feat_cp_028', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_029', 'proj_creditpulse_001', 'req_cp_015', 'feat_cp_029', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_030', 'proj_creditpulse_001', 'req_cp_015', 'feat_cp_030', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_031', 'proj_creditpulse_001', 'req_cp_016', 'feat_cp_031', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_032', 'proj_creditpulse_001', 'req_cp_017', 'feat_cp_032', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_033', 'proj_creditpulse_001', 'req_cp_017', 'feat_cp_033', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_034', 'proj_creditpulse_001', 'req_cp_018', 'feat_cp_034', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_035', 'proj_creditpulse_001', 'req_cp_019', 'feat_cp_035', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_036', 'proj_creditpulse_001', 'req_cp_020', 'feat_cp_036', 'implements', '{"priority": "high"}', NOW(), NOW()),

-- req_cp_021-050: Distributed across features
('link_cp_037', 'proj_creditpulse_001', 'req_cp_021', 'feat_cp_037', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_038', 'proj_creditpulse_001', 'req_cp_021', 'feat_cp_038', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_039', 'proj_creditpulse_001', 'req_cp_022', 'feat_cp_039', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_040', 'proj_creditpulse_001', 'req_cp_023', 'feat_cp_040', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_041', 'proj_creditpulse_001', 'req_cp_023', 'feat_cp_041', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_042', 'proj_creditpulse_001', 'req_cp_024', 'feat_cp_042', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_043', 'proj_creditpulse_001', 'req_cp_025', 'feat_cp_043', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_044', 'proj_creditpulse_001', 'req_cp_025', 'feat_cp_044', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_045', 'proj_creditpulse_001', 'req_cp_026', 'feat_cp_045', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_046', 'proj_creditpulse_001', 'req_cp_027', 'feat_cp_046', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_047', 'proj_creditpulse_001', 'req_cp_028', 'feat_cp_047', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_048', 'proj_creditpulse_001', 'req_cp_028', 'feat_cp_048', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_049', 'proj_creditpulse_001', 'req_cp_029', 'feat_cp_049', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_050', 'proj_creditpulse_001', 'req_cp_030', 'feat_cp_050', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_051', 'proj_creditpulse_001', 'req_cp_031', 'feat_cp_051', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_052', 'proj_creditpulse_001', 'req_cp_032', 'feat_cp_052', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_053', 'proj_creditpulse_001', 'req_cp_032', 'feat_cp_053', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_054', 'proj_creditpulse_001', 'req_cp_033', 'feat_cp_054', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_055', 'proj_creditpulse_001', 'req_cp_034', 'feat_cp_055', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_056', 'proj_creditpulse_001', 'req_cp_035', 'feat_cp_056', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_057', 'proj_creditpulse_001', 'req_cp_035', 'feat_cp_057', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_058', 'proj_creditpulse_001', 'req_cp_036', 'feat_cp_058', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_059', 'proj_creditpulse_001', 'req_cp_037', 'feat_cp_059', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_060', 'proj_creditpulse_001', 'req_cp_038', 'feat_cp_060', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_061', 'proj_creditpulse_001', 'req_cp_039', 'feat_cp_061', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_062', 'proj_creditpulse_001', 'req_cp_040', 'feat_cp_062', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_063', 'proj_creditpulse_001', 'req_cp_040', 'feat_cp_063', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_064', 'proj_creditpulse_001', 'req_cp_041', 'feat_cp_064', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_065', 'proj_creditpulse_001', 'req_cp_042', 'feat_cp_065', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_066', 'proj_creditpulse_001', 'req_cp_043', 'feat_cp_066', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_067', 'proj_creditpulse_001', 'req_cp_043', 'feat_cp_067', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_068', 'proj_creditpulse_001', 'req_cp_044', 'feat_cp_068', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_069', 'proj_creditpulse_001', 'req_cp_045', 'feat_cp_069', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_070', 'proj_creditpulse_001', 'req_cp_046', 'feat_cp_070', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_071', 'proj_creditpulse_001', 'req_cp_047', 'feat_cp_071', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_072', 'proj_creditpulse_001', 'req_cp_048', 'feat_cp_072', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_073', 'proj_creditpulse_001', 'req_cp_049', 'feat_cp_073', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_074', 'proj_creditpulse_001', 'req_cp_050', 'feat_cp_074', 'implements', '{"priority": "medium"}', NOW(), NOW()),

-- req_cp_051-100: Remaining requirements to features
('link_cp_075', 'proj_creditpulse_001', 'req_cp_051', 'feat_cp_075', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_076', 'proj_creditpulse_001', 'req_cp_051', 'feat_cp_076', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_077', 'proj_creditpulse_001', 'req_cp_052', 'feat_cp_077', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_078', 'proj_creditpulse_001', 'req_cp_053', 'feat_cp_078', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_079', 'proj_creditpulse_001', 'req_cp_054', 'feat_cp_079', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_080', 'proj_creditpulse_001', 'req_cp_054', 'feat_cp_080', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_081', 'proj_creditpulse_001', 'req_cp_055', 'feat_cp_081', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_082', 'proj_creditpulse_001', 'req_cp_056', 'feat_cp_082', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_083', 'proj_creditpulse_001', 'req_cp_056', 'feat_cp_083', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_084', 'proj_creditpulse_001', 'req_cp_057', 'feat_cp_084', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_085', 'proj_creditpulse_001', 'req_cp_058', 'feat_cp_085', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_086', 'proj_creditpulse_001', 'req_cp_059', 'feat_cp_086', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_087', 'proj_creditpulse_001', 'req_cp_060', 'feat_cp_087', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_088', 'proj_creditpulse_001', 'req_cp_061', 'feat_cp_088', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_089', 'proj_creditpulse_001', 'req_cp_061', 'feat_cp_089', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_090', 'proj_creditpulse_001', 'req_cp_062', 'feat_cp_090', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_091', 'proj_creditpulse_001', 'req_cp_063', 'feat_cp_091', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_092', 'proj_creditpulse_001', 'req_cp_064', 'feat_cp_092', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_093', 'proj_creditpulse_001', 'req_cp_065', 'feat_cp_093', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_094', 'proj_creditpulse_001', 'req_cp_066', 'feat_cp_094', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_095', 'proj_creditpulse_001', 'req_cp_066', 'feat_cp_095', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_096', 'proj_creditpulse_001', 'req_cp_067', 'feat_cp_096', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_097', 'proj_creditpulse_001', 'req_cp_068', 'feat_cp_097', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_098', 'proj_creditpulse_001', 'req_cp_069', 'feat_cp_098', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_099', 'proj_creditpulse_001', 'req_cp_070', 'feat_cp_099', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_100', 'proj_creditpulse_001', 'req_cp_070', 'feat_cp_100', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_101', 'proj_creditpulse_001', 'req_cp_071', 'feat_cp_101', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_102', 'proj_creditpulse_001', 'req_cp_072', 'feat_cp_102', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_103', 'proj_creditpulse_001', 'req_cp_073', 'feat_cp_103', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_104', 'proj_creditpulse_001', 'req_cp_074', 'feat_cp_104', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_105', 'proj_creditpulse_001', 'req_cp_075', 'feat_cp_105', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_106', 'proj_creditpulse_001', 'req_cp_076', 'feat_cp_106', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_107', 'proj_creditpulse_001', 'req_cp_077', 'feat_cp_107', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_108', 'proj_creditpulse_001', 'req_cp_077', 'feat_cp_108', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_109', 'proj_creditpulse_001', 'req_cp_078', 'feat_cp_109', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_110', 'proj_creditpulse_001', 'req_cp_079', 'feat_cp_110', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_111', 'proj_creditpulse_001', 'req_cp_080', 'feat_cp_001', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_112', 'proj_creditpulse_001', 'req_cp_081', 'feat_cp_012', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_113', 'proj_creditpulse_001', 'req_cp_082', 'feat_cp_025', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_114', 'proj_creditpulse_001', 'req_cp_083', 'feat_cp_038', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_115', 'proj_creditpulse_001', 'req_cp_084', 'feat_cp_050', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_116', 'proj_creditpulse_001', 'req_cp_085', 'feat_cp_063', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_117', 'proj_creditpulse_001', 'req_cp_086', 'feat_cp_075', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_118', 'proj_creditpulse_001', 'req_cp_087', 'feat_cp_087', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_119', 'proj_creditpulse_001', 'req_cp_088', 'feat_cp_098', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_120', 'proj_creditpulse_001', 'req_cp_089', 'feat_cp_107', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_121', 'proj_creditpulse_001', 'req_cp_090', 'feat_cp_020', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_122', 'proj_creditpulse_001', 'req_cp_091', 'feat_cp_035', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_123', 'proj_creditpulse_001', 'req_cp_092', 'feat_cp_055', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_124', 'proj_creditpulse_001', 'req_cp_093', 'feat_cp_070', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_125', 'proj_creditpulse_001', 'req_cp_094', 'feat_cp_085', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_126', 'proj_creditpulse_001', 'req_cp_095', 'feat_cp_099', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_127', 'proj_creditpulse_001', 'req_cp_096', 'feat_cp_015', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_128', 'proj_creditpulse_001', 'req_cp_097', 'feat_cp_042', 'implements', '{"priority": "low"}', NOW(), NOW()),
('link_cp_129', 'proj_creditpulse_001', 'req_cp_098', 'feat_cp_068', 'implements', '{"priority": "high"}', NOW(), NOW()),
('link_cp_130', 'proj_creditpulse_001', 'req_cp_099', 'feat_cp_088', 'implements', '{"priority": "medium"}', NOW(), NOW()),
('link_cp_131', 'proj_creditpulse_001', 'req_cp_100', 'feat_cp_110', 'implements', '{"priority": "high"}', NOW(), NOW()),

-- Requirements → Requirements (related_to) - Cross-functional links
INSERT INTO links (id, project_id, source_item_id, target_item_id, link_type, link_metadata, created_at, updated_at) VALUES
('link_cp_132', 'proj_creditpulse_001', 'req_cp_001', 'req_cp_005', 'related_to', '{"context": "data-input"}', NOW(), NOW()),
('link_cp_133', 'proj_creditpulse_001', 'req_cp_002', 'req_cp_008', 'related_to', '{"context": "reporting"}', NOW(), NOW()),
('link_cp_134', 'proj_creditpulse_001', 'req_cp_003', 'req_cp_010', 'related_to', '{"context": "validation"}', NOW(), NOW()),
('link_cp_135', 'proj_creditpulse_001', 'req_cp_004', 'req_cp_012', 'related_to', '{"context": "analytics"}', NOW(), NOW()),
('link_cp_136', 'proj_creditpulse_001', 'req_cp_005', 'req_cp_015', 'related_to', '{"context": "processing"}', NOW(), NOW()),
('link_cp_137', 'proj_creditpulse_001', 'req_cp_006', 'req_cp_018', 'related_to', '{"context": "integration"}', NOW(), NOW()),
('link_cp_138', 'proj_creditpulse_001', 'req_cp_007', 'req_cp_020', 'related_to', '{"context": "security"}', NOW(), NOW()),
('link_cp_139', 'proj_creditpulse_001', 'req_cp_008', 'req_cp_022', 'related_to', '{"context": "notifications"}', NOW(), NOW()),
('link_cp_140', 'proj_creditpulse_001', 'req_cp_009', 'req_cp_025', 'related_to', '{"context": "performance"}', NOW(), NOW()),
('link_cp_141', 'proj_creditpulse_001', 'req_cp_010', 'req_cp_028', 'related_to', '{"context": "ui"}', NOW(), NOW()),
('link_cp_142', 'proj_creditpulse_001', 'req_cp_011', 'req_cp_030', 'related_to', '{"context": "export"}', NOW(), NOW()),
('link_cp_143', 'proj_creditpulse_001', 'req_cp_012', 'req_cp_032', 'related_to', '{"context": "import"}', NOW(), NOW()),
('link_cp_144', 'proj_creditpulse_001', 'req_cp_013', 'req_cp_035', 'related_to', '{"context": "compliance"}', NOW(), NOW()),
('link_cp_145', 'proj_creditpulse_001', 'req_cp_014', 'req_cp_038', 'related_to', '{"context": "audit"}', NOW(), NOW()),
('link_cp_146', 'proj_creditpulse_001', 'req_cp_015', 'req_cp_040', 'related_to', '{"context": "caching"}', NOW(), NOW()),
('link_cp_147', 'proj_creditpulse_001', 'req_cp_016', 'req_cp_042', 'related_to', '{"context": "api"}', NOW(), NOW()),
('link_cp_148', 'proj_creditpulse_001', 'req_cp_017', 'req_cp_045', 'related_to', '{"context": "database"}', NOW(), NOW()),
('link_cp_149', 'proj_creditpulse_001', 'req_cp_018', 'req_cp_048', 'related_to', '{"context": "logging"}', NOW(), NOW()),
('link_cp_150', 'proj_creditpulse_001', 'req_cp_019', 'req_cp_050', 'related_to', '{"context": "monitoring"}', NOW(), NOW()),
('link_cp_151', 'proj_creditpulse_001', 'req_cp_020', 'req_cp_052', 'related_to', '{"context": "alerts"}', NOW(), NOW()),
('link_cp_152', 'proj_creditpulse_001', 'req_cp_021', 'req_cp_055', 'related_to', '{"context": "dashboard"}', NOW(), NOW()),
('link_cp_153', 'proj_creditpulse_001', 'req_cp_022', 'req_cp_058', 'related_to', '{"context": "filters"}', NOW(), NOW()),
('link_cp_154', 'proj_creditpulse_001', 'req_cp_023', 'req_cp_060', 'related_to', '{"context": "search"}', NOW(), NOW()),
('link_cp_155', 'proj_creditpulse_001', 'req_cp_024', 'req_cp_062', 'related_to', '{"context": "sorting"}', NOW(), NOW()),
('link_cp_156', 'proj_creditpulse_001', 'req_cp_025', 'req_cp_065', 'related_to', '{"context": "pagination"}', NOW(), NOW()),
('link_cp_157', 'proj_creditpulse_001', 'req_cp_026', 'req_cp_068', 'related_to', '{"context": "grouping"}', NOW(), NOW()),
('link_cp_158', 'proj_creditpulse_001', 'req_cp_027', 'req_cp_070', 'related_to', '{"context": "bulk-ops"}', NOW(), NOW()),
('link_cp_159', 'proj_creditpulse_001', 'req_cp_028', 'req_cp_072', 'related_to', '{"context": "workflows"}', NOW(), NOW()),
('link_cp_160', 'proj_creditpulse_001', 'req_cp_029', 'req_cp_075', 'related_to', '{"context": "collaboration"}', NOW(), NOW()),
('link_cp_161', 'proj_creditpulse_001', 'req_cp_030', 'req_cp_078', 'related_to', '{"context": "sync"}', NOW(), NOW()),
('link_cp_162', 'proj_creditpulse_001', 'req_cp_031', 'req_cp_080', 'related_to', '{"context": "versioning"}', NOW(), NOW()),
('link_cp_163', 'proj_creditpulse_001', 'req_cp_032', 'req_cp_082', 'related_to', '{"context": "backup"}', NOW(), NOW()),
('link_cp_164', 'proj_creditpulse_001', 'req_cp_033', 'req_cp_085', 'related_to', '{"context": "recovery"}', NOW(), NOW()),
('link_cp_165', 'proj_creditpulse_001', 'req_cp_034', 'req_cp_088', 'related_to', '{"context": "testing"}', NOW(), NOW()),
('link_cp_166', 'proj_creditpulse_001', 'req_cp_035', 'req_cp_090', 'related_to', '{"context": "deployment"}', NOW(), NOW()),

-- Features → Features (depends_on) - Feature dependencies
INSERT INTO links (id, project_id, source_item_id, target_item_id, link_type, link_metadata, created_at, updated_at) VALUES
('link_cp_167', 'proj_creditpulse_001', 'feat_cp_010', 'feat_cp_001', 'depends_on', '{"phase": 1}', NOW(), NOW()),
('link_cp_168', 'proj_creditpulse_001', 'feat_cp_011', 'feat_cp_001', 'depends_on', '{"phase": 1}', NOW(), NOW()),
('link_cp_169', 'proj_creditpulse_001', 'feat_cp_012', 'feat_cp_002', 'depends_on', '{"phase": 1}', NOW(), NOW()),
('link_cp_170', 'proj_creditpulse_001', 'feat_cp_015', 'feat_cp_005', 'depends_on', '{"phase": 1}', NOW(), NOW()),
('link_cp_171', 'proj_creditpulse_001', 'feat_cp_020', 'feat_cp_010', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_172', 'proj_creditpulse_001', 'feat_cp_025', 'feat_cp_012', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_173', 'proj_creditpulse_001', 'feat_cp_030', 'feat_cp_015', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_174', 'proj_creditpulse_001', 'feat_cp_035', 'feat_cp_020', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_175', 'proj_creditpulse_001', 'feat_cp_040', 'feat_cp_025', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_176', 'proj_creditpulse_001', 'feat_cp_045', 'feat_cp_030', 'depends_on', '{"phase": 3}', NOW(), NOW()),
('link_cp_177', 'proj_creditpulse_001', 'feat_cp_050', 'feat_cp_035', 'depends_on', '{"phase": 3}', NOW(), NOW()),
('link_cp_178', 'proj_creditpulse_001', 'feat_cp_055', 'feat_cp_040', 'depends_on', '{"phase": 3}', NOW(), NOW()),
('link_cp_179', 'proj_creditpulse_001', 'feat_cp_060', 'feat_cp_045', 'depends_on', '{"phase": 3}', NOW(), NOW()),
('link_cp_180', 'proj_creditpulse_001', 'feat_cp_065', 'feat_cp_050', 'depends_on', '{"phase": 3}', NOW(), NOW()),
('link_cp_181', 'proj_creditpulse_001', 'feat_cp_070', 'feat_cp_055', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_182', 'proj_creditpulse_001', 'feat_cp_075', 'feat_cp_060', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_183', 'proj_creditpulse_001', 'feat_cp_080', 'feat_cp_065', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_184', 'proj_creditpulse_001', 'feat_cp_085', 'feat_cp_070', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_185', 'proj_creditpulse_001', 'feat_cp_090', 'feat_cp_075', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_186', 'proj_creditpulse_001', 'feat_cp_095', 'feat_cp_080', 'depends_on', '{"phase": 5}', NOW(), NOW()),
('link_cp_187', 'proj_creditpulse_001', 'feat_cp_100', 'feat_cp_085', 'depends_on', '{"phase": 5}', NOW(), NOW()),
('link_cp_188', 'proj_creditpulse_001', 'feat_cp_105', 'feat_cp_090', 'depends_on', '{"phase": 5}', NOW(), NOW()),
('link_cp_189', 'proj_creditpulse_001', 'feat_cp_110', 'feat_cp_095', 'depends_on', '{"phase": 5}', NOW(), NOW()),
('link_cp_190', 'proj_creditpulse_001', 'feat_cp_003', 'feat_cp_001', 'depends_on', '{"phase": 1}', NOW(), NOW()),
('link_cp_191', 'proj_creditpulse_001', 'feat_cp_006', 'feat_cp_004', 'depends_on', '{"phase": 1}', NOW(), NOW()),
('link_cp_192', 'proj_creditpulse_001', 'feat_cp_009', 'feat_cp_007', 'depends_on', '{"phase": 1}', NOW(), NOW()),
('link_cp_193', 'proj_creditpulse_001', 'feat_cp_014', 'feat_cp_010', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_194', 'proj_creditpulse_001', 'feat_cp_018', 'feat_cp_015', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_195', 'proj_creditpulse_001', 'feat_cp_022', 'feat_cp_020', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_196', 'proj_creditpulse_001', 'feat_cp_028', 'feat_cp_025', 'depends_on', '{"phase": 2}', NOW(), NOW()),
('link_cp_197', 'proj_creditpulse_001', 'feat_cp_033', 'feat_cp_030', 'depends_on', '{"phase": 3}', NOW(), NOW()),
('link_cp_198', 'proj_creditpulse_001', 'feat_cp_039', 'feat_cp_035', 'depends_on', '{"phase": 3}', NOW(), NOW()),
('link_cp_199', 'proj_creditpulse_001', 'feat_cp_044', 'feat_cp_040', 'depends_on', '{"phase": 3}', NOW(), NOW()),
('link_cp_200', 'proj_creditpulse_001', 'feat_cp_048', 'feat_cp_045', 'depends_on', '{"phase": 3}', NOW(), NOW()),

-- Additional depends_on links for better connectivity
('link_cp_201', 'proj_creditpulse_001', 'feat_cp_051', 'feat_cp_050', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_202', 'proj_creditpulse_001', 'feat_cp_056', 'feat_cp_055', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_203', 'proj_creditpulse_001', 'feat_cp_061', 'feat_cp_060', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_204', 'proj_creditpulse_001', 'feat_cp_066', 'feat_cp_065', 'depends_on', '{"phase": 4}', NOW(), NOW()),
('link_cp_205', 'proj_creditpulse_001', 'feat_cp_071', 'feat_cp_070', 'depends_on', '{"phase": 5}', NOW(), NOW()),
('link_cp_206', 'proj_creditpulse_001', 'feat_cp_076', 'feat_cp_075', 'depends_on', '{"phase": 5}', NOW(), NOW()),
('link_cp_207', 'proj_creditpulse_001', 'feat_cp_081', 'feat_cp_080', 'depends_on', '{"phase": 5}', NOW(), NOW()),
('link_cp_208', 'proj_creditpulse_001', 'feat_cp_086', 'feat_cp_085', 'depends_on', '{"phase": 5}', NOW(), NOW()),

-- Requirements → Features (traces_to) - Traceability links
INSERT INTO links (id, project_id, source_item_id, target_item_id, link_type, link_metadata, created_at, updated_at) VALUES
('link_cp_209', 'proj_creditpulse_001', 'req_cp_001', 'feat_cp_004', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_210', 'proj_creditpulse_001', 'req_cp_002', 'feat_cp_007', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_211', 'proj_creditpulse_001', 'req_cp_003', 'feat_cp_011', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_212', 'proj_creditpulse_001', 'req_cp_004', 'feat_cp_016', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_213', 'proj_creditpulse_001', 'req_cp_005', 'feat_cp_021', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_214', 'proj_creditpulse_001', 'req_cp_006', 'feat_cp_026', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_215', 'proj_creditpulse_001', 'req_cp_007', 'feat_cp_031', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_216', 'proj_creditpulse_001', 'req_cp_008', 'feat_cp_036', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_217', 'proj_creditpulse_001', 'req_cp_009', 'feat_cp_041', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_218', 'proj_creditpulse_001', 'req_cp_010', 'feat_cp_046', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_219', 'proj_creditpulse_001', 'req_cp_011', 'feat_cp_051', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_220', 'proj_creditpulse_001', 'req_cp_012', 'feat_cp_056', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_221', 'proj_creditpulse_001', 'req_cp_013', 'feat_cp_061', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_222', 'proj_creditpulse_001', 'req_cp_014', 'feat_cp_066', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_223', 'proj_creditpulse_001', 'req_cp_015', 'feat_cp_071', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_224', 'proj_creditpulse_001', 'req_cp_016', 'feat_cp_076', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_225', 'proj_creditpulse_001', 'req_cp_017', 'feat_cp_081', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_226', 'proj_creditpulse_001', 'req_cp_018', 'feat_cp_086', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),
('link_cp_227', 'proj_creditpulse_001', 'req_cp_019', 'feat_cp_091', 'traces_to', '{"coverage": "partial"}', NOW(), NOW()),
('link_cp_228', 'proj_creditpulse_001', 'req_cp_020', 'feat_cp_096', 'traces_to', '{"coverage": "full"}', NOW(), NOW()),

-- Features → Requirements (tests) - Test coverage links
INSERT INTO links (id, project_id, source_item_id, target_item_id, link_type, link_metadata, created_at, updated_at) VALUES
('link_cp_229', 'proj_creditpulse_001', 'feat_cp_001', 'req_cp_001', 'tests', '{"type": "unit"}', NOW(), NOW()),
('link_cp_230', 'proj_creditpulse_001', 'feat_cp_004', 'req_cp_002', 'tests', '{"type": "integration"}', NOW(), NOW()),
('link_cp_231', 'proj_creditpulse_001', 'feat_cp_007', 'req_cp_003', 'tests', '{"type": "e2e"}', NOW(), NOW()),
('link_cp_232', 'proj_creditpulse_001', 'feat_cp_010', 'req_cp_004', 'tests', '{"type": "unit"}', NOW(), NOW()),
('link_cp_233', 'proj_creditpulse_001', 'feat_cp_015', 'req_cp_005', 'tests', '{"type": "integration"}', NOW(), NOW()),
('link_cp_234', 'proj_creditpulse_001', 'feat_cp_020', 'req_cp_006', 'tests', '{"type": "e2e"}', NOW(), NOW()),
('link_cp_235', 'proj_creditpulse_001', 'feat_cp_025', 'req_cp_007', 'tests', '{"type": "unit"}', NOW(), NOW()),
('link_cp_236', 'proj_creditpulse_001', 'feat_cp_030', 'req_cp_008', 'tests', '{"type": "integration"}', NOW(), NOW()),
('link_cp_237', 'proj_creditpulse_001', 'feat_cp_035', 'req_cp_009', 'tests', '{"type": "e2e"}', NOW(), NOW()),
('link_cp_238', 'proj_creditpulse_001', 'feat_cp_040', 'req_cp_010', 'tests', '{"type": "unit"}', NOW(), NOW()),
('link_cp_239', 'proj_creditpulse_001', 'feat_cp_050', 'req_cp_015', 'tests', '{"type": "integration"}', NOW(), NOW()),
('link_cp_240', 'proj_creditpulse_001', 'feat_cp_060', 'req_cp_020', 'tests', '{"type": "e2e"}', NOW(), NOW()),
('link_cp_241', 'proj_creditpulse_001', 'feat_cp_070', 'req_cp_025', 'tests', '{"type": "unit"}', NOW(), NOW()),
('link_cp_242', 'proj_creditpulse_001', 'feat_cp_080', 'req_cp_030', 'tests', '{"type": "integration"}', NOW(), NOW()),
('link_cp_243', 'proj_creditpulse_001', 'feat_cp_090', 'req_cp_035', 'tests', '{"type": "e2e"}', NOW(), NOW()),
('link_cp_244', 'proj_creditpulse_001', 'feat_cp_100', 'req_cp_040', 'tests', '{"type": "unit"}', NOW(), NOW()),
('link_cp_245', 'proj_creditpulse_001', 'feat_cp_110', 'req_cp_050', 'tests', '{"type": "integration"}', NOW(), NOW()),

-- Cross-feature related_to links for graph density
INSERT INTO links (id, project_id, source_item_id, target_item_id, link_type, link_metadata, created_at, updated_at) VALUES
('link_cp_246', 'proj_creditpulse_001', 'feat_cp_002', 'feat_cp_005', 'related_to', '{"module": "core"}', NOW(), NOW()),
('link_cp_247', 'proj_creditpulse_001', 'feat_cp_003', 'feat_cp_008', 'related_to', '{"module": "core"}', NOW(), NOW()),
('link_cp_248', 'proj_creditpulse_001', 'feat_cp_006', 'feat_cp_013', 'related_to', '{"module": "validation"}', NOW(), NOW()),
('link_cp_249', 'proj_creditpulse_001', 'feat_cp_009', 'feat_cp_017', 'related_to', '{"module": "validation"}', NOW(), NOW()),
('link_cp_250', 'proj_creditpulse_001', 'feat_cp_012', 'feat_cp_023', 'related_to', '{"module": "processing"}', NOW(), NOW()),
('link_cp_251', 'proj_creditpulse_001', 'feat_cp_014', 'feat_cp_027', 'related_to', '{"module": "processing"}', NOW(), NOW()),
('link_cp_252', 'proj_creditpulse_001', 'feat_cp_016', 'feat_cp_032', 'related_to', '{"module": "reporting"}', NOW(), NOW()),
('link_cp_253', 'proj_creditpulse_001', 'feat_cp_018', 'feat_cp_037', 'related_to', '{"module": "reporting"}', NOW(), NOW()),
('link_cp_254', 'proj_creditpulse_001', 'feat_cp_019', 'feat_cp_042', 'related_to', '{"module": "analytics"}', NOW(), NOW()),
('link_cp_255', 'proj_creditpulse_001', 'feat_cp_021', 'feat_cp_047', 'related_to', '{"module": "analytics"}', NOW(), NOW()),
('link_cp_256', 'proj_creditpulse_001', 'feat_cp_024', 'feat_cp_052', 'related_to', '{"module": "ui"}', NOW(), NOW()),
('link_cp_257', 'proj_creditpulse_001', 'feat_cp_026', 'feat_cp_057', 'related_to', '{"module": "ui"}', NOW(), NOW()),
('link_cp_258', 'proj_creditpulse_001', 'feat_cp_029', 'feat_cp_064', 'related_to', '{"module": "integration"}', NOW(), NOW()),
('link_cp_259', 'proj_creditpulse_001', 'feat_cp_031', 'feat_cp_069', 'related_to', '{"module": "integration"}', NOW(), NOW()),
('link_cp_260', 'proj_creditpulse_001', 'feat_cp_034', 'feat_cp_074', 'related_to', '{"module": "deployment"}', NOW(), NOW());

-- Summary: 260 links total
-- - 131 implements links (req → feat)
-- - 35 related_to links (req → req)
-- - 42 depends_on links (feat → feat)
-- - 20 traces_to links (req → feat)
-- - 17 tests links (feat → req)
-- - 15 related_to links (feat → feat)
-- Total connectivity: Excellent graph density for visualization
