const TWO = Number('2');
const NEGATIVE_ONE = Number('-1');

const LAYOUT_WORKER_THRESHOLD = Number('150');

const GRID_COMPACT_PADDING_DIVISOR = TWO;
const GRID_FALLBACK_PADDING_MULTIPLIER = TWO;
const GRID_MIN_COLUMNS = Number('1');

const RADIAL_RADIUS_MULTIPLIER = Number('1.5');
const RADIAL_ORPHAN_SEGMENTS = Number('8');

const FULL_CIRCLE_RADIANS = Math.PI * TWO;
const START_ANGLE_RADIANS = (NEGATIVE_ONE * Math.PI) / TWO;

const CIRCULAR_MIN_RADIUS = Number('300');
const CIRCULAR_RADIUS_STEP = Number('20');

const FORCE_JITTER_RANGE = Number('50');
const FORCE_JITTER_MIDPOINT = Number('0.5');
const FORCE_ITERATIONS = Number('50');
const FORCE_REPULSION_STRENGTH = Number('5000');
const FORCE_ATTRACTION_STRENGTH = Number('0.1');
const FORCE_DAMPING = Number('0.9');
const FORCE_MIN_DISTANCE = Number('1');
const FORCE_NORMALIZE_PADDING = Number('50');

const DEFAULT_NODE_WIDTH = Number('200');
const DEFAULT_NODE_HEIGHT = Number('80');
const DEFAULT_RANK_SEP = Number('100');
const DEFAULT_NODE_SEP = Number('60');
const DEFAULT_MARGIN_X = Number('40');
const DEFAULT_MARGIN_Y = Number('40');
const DEFAULT_CENTER_X = Number('500');
const DEFAULT_CENTER_Y = Number('400');

const TREE_NODE_SEP_FACTOR = Number('0.8');
const TREE_RANK_SEP_FACTOR = Number('1.5');

const LAYOUT_SIGNATURE_SEPARATOR = '|';

export {
  CIRCULAR_MIN_RADIUS,
  CIRCULAR_RADIUS_STEP,
  DEFAULT_CENTER_X,
  DEFAULT_CENTER_Y,
  DEFAULT_MARGIN_X,
  DEFAULT_MARGIN_Y,
  DEFAULT_NODE_HEIGHT,
  DEFAULT_NODE_SEP,
  DEFAULT_NODE_WIDTH,
  DEFAULT_RANK_SEP,
  FORCE_ATTRACTION_STRENGTH,
  FORCE_DAMPING,
  FORCE_ITERATIONS,
  FORCE_JITTER_MIDPOINT,
  FORCE_JITTER_RANGE,
  FORCE_MIN_DISTANCE,
  FORCE_NORMALIZE_PADDING,
  FORCE_REPULSION_STRENGTH,
  FULL_CIRCLE_RADIANS,
  GRID_COMPACT_PADDING_DIVISOR,
  GRID_FALLBACK_PADDING_MULTIPLIER,
  GRID_MIN_COLUMNS,
  LAYOUT_SIGNATURE_SEPARATOR,
  LAYOUT_WORKER_THRESHOLD,
  RADIAL_ORPHAN_SEGMENTS,
  RADIAL_RADIUS_MULTIPLIER,
  START_ANGLE_RADIANS,
  TREE_NODE_SEP_FACTOR,
  TREE_RANK_SEP_FACTOR,
};
