// Auto-generated by TraceRTM Storybook Generator
// Do not edit manually - regenerate using: bun run generate:stories
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Alert } from "@tracertm/ui";

const meta: Meta<typeof Alert> = {
	argTypes: {
		variant: {
			control: "select",
			options: ["default", "destructive", "success", "warning"],
		},
	},
	component: Alert,
	tags: ["autodocs"],
	title: "Components/Alert",
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	args: {
		children: "Default",
		variant: "default",
	},
};

export const Destructive: Story = {
	args: {
		children: "Destructive",
		variant: "destructive",
	},
};

export const Success: Story = {
	args: {
		children: "Success",
		variant: "success",
	},
};

export const Warning: Story = {
	args: {
		children: "Warning",
		variant: "warning",
	},
};

export const AllVariants: Story = {
	render: () => (
		<div className="flex flex-wrap gap-4">
			<Alert variant="default">Default</Alert>
			<Alert variant="destructive">Destructive</Alert>
			<Alert variant="success">Success</Alert>
			<Alert variant="warning">Warning</Alert>
		</div>
	),
};
