// Auto-generated by TraceRTM Storybook Generator
// Do not edit manually - regenerate using: bun run generate:stories
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button } from "@tracertm/ui";

const meta: Meta<typeof Button> = {
	argTypes: {
		variant: {
			control: "select",
			options: [
				"default",
				"destructive",
				"outline",
				"secondary",
				"ghost",
				"link",
			],
		},
		size: {
			control: "select",
			options: ["default", "sm", "lg", "icon"],
		},
	},
	component: Button,
	parameters: {
		design: {
			type: "figma",
			url: "https://www.figma.com/file/xxx/Design-System?node-id=123",
		},
		trace: {
			componentId: "comp-button-001",
			storyId: "story-button-001",
		},
	},
	tags: ["autodocs"],
	title: "Components/Button",
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	args: {
		children: "Default",
		variant: "default",
	},
};

export const Destructive: Story = {
	args: {
		children: "Destructive",
		variant: "destructive",
	},
};

export const Outline: Story = {
	args: {
		children: "Outline",
		variant: "outline",
	},
};

export const Secondary: Story = {
	args: {
		children: "Secondary",
		variant: "secondary",
	},
};

export const Ghost: Story = {
	args: {
		children: "Ghost",
		variant: "ghost",
	},
};

export const Link: Story = {
	args: {
		children: "Link",
		variant: "link",
	},
};

export const Sm: Story = {
	args: {
		children: "Sm",
		size: "sm",
	},
};

export const Lg: Story = {
	args: {
		children: "Lg",
		size: "lg",
	},
};

export const Icon: Story = {
	args: {
		children: "Icon",
		size: "icon",
	},
};

export const AllVariants: Story = {
	render: () => (
		<div className="flex flex-wrap gap-4">
			<Button variant="default">Default</Button>
			<Button variant="destructive">Destructive</Button>
			<Button variant="outline">Outline</Button>
			<Button variant="secondary">Secondary</Button>
			<Button variant="ghost">Ghost</Button>
			<Button variant="link">Link</Button>
		</div>
	),
};
