// Auto-generated by TraceRTM Storybook Generator
// Do not edit manually - regenerate using: bun run generate:stories
import type { Meta, StoryObj } from "@storybook/react-vite";
import { DialogOverlay } from "@tracertm/ui";

const meta: Meta<typeof DialogOverlay> = {
	title: "Components/DialogOverlay",
	component: DialogOverlay,
	tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	args: {
		children: "Default",
	},
};
