// Auto-generated by TraceRTM Storybook Generator
// Do not edit manually - regenerate using: bun run generate:stories
import type { Meta, StoryObj } from "@storybook/react-vite";
import { DropdownMenuContent } from "@tracertm/ui";

const meta: Meta<typeof DropdownMenuContent> = {
	title: "Components/DropdownMenuContent",
	component: DropdownMenuContent,
	tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	args: {
		children: "Default",
	},
};
