// Auto-generated by TraceRTM Storybook Generator
// Do not edit manually - regenerate using: bun run generate:stories
import type { Meta, StoryObj } from '@storybook/react-vite'
import { Input } from '@tracertm/ui'

const meta: Meta<typeof Input> = {
  title: 'Components/Input',
  component: Input,
  tags: ['autodocs'],
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/file/xxx/Design-System?node-id=456',
    },
    trace: {
      componentId: 'comp-input-001',
      storyId: 'story-input-001',
    },
  },
}

export default meta
type Story = StoryObj<typeof meta>
