// Auto-generated by TraceRTM Storybook Generator
// Do not edit manually - regenerate using: bun run generate:stories
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Progress } from "@tracertm/ui";

const meta: Meta<typeof Progress> = {
	component: Progress,
	tags: ["autodocs"],
	title: "Components/Progress",
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	args: {
		children: "Default",
	},
};
