// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Agent struct {
	ID             pgtype.UUID      `db:"id" json:"id"`
	ProjectID      pgtype.UUID      `db:"project_id" json:"project_id"`
	Name           string           `db:"name" json:"name"`
	Status         string           `db:"status" json:"status"`
	Metadata       []byte           `db:"metadata" json:"metadata"`
	LastActivityAt pgtype.Timestamp `db:"last_activity_at" json:"last_activity_at"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type AgentTask struct {
	ID        string           `db:"id" json:"id"`
	ProjectID string           `db:"project_id" json:"project_id"`
	Status    string           `db:"status" json:"status"`
	Priority  int32            `db:"priority" json:"priority"`
	Data      []byte           `db:"data" json:"data"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type BurndownDatum struct {
	ID              pgtype.UUID      `db:"id" json:"id"`
	SprintID        pgtype.UUID      `db:"sprint_id" json:"sprint_id"`
	RecordedDate    pgtype.Timestamp `db:"recorded_date" json:"recorded_date"`
	RemainingPoints int32            `db:"remaining_points" json:"remaining_points"`
	IdealPoints     int32            `db:"ideal_points" json:"ideal_points"`
	CompletedPoints int32            `db:"completed_points" json:"completed_points"`
	AddedPoints     pgtype.Int4      `db:"added_points" json:"added_points"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ChangeLog struct {
	ID         pgtype.UUID      `db:"id" json:"id"`
	EntityType string           `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID      `db:"entity_id" json:"entity_id"`
	Action     string           `db:"action" json:"action"`
	Changes    []byte           `db:"changes" json:"changes"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Documentation struct {
	ID              pgtype.UUID      `db:"id" json:"id"`
	ProjectID       pgtype.UUID      `db:"project_id" json:"project_id"`
	Title           string           `db:"title" json:"title"`
	Slug            pgtype.Text      `db:"slug" json:"slug"`
	Format          string           `db:"format" json:"format"`
	Content         string           `db:"content" json:"content"`
	Summary         pgtype.Text      `db:"summary" json:"summary"`
	ParsedStructure []byte           `db:"parsed_structure" json:"parsed_structure"`
	Tags            []string         `db:"tags" json:"tags"`
	Version         pgtype.Int4      `db:"version" json:"version"`
	SourceUrl       pgtype.Text      `db:"source_url" json:"source_url"`
	FilePath        pgtype.Text      `db:"file_path" json:"file_path"`
	FullTextSearch  interface{}      `db:"full_text_search" json:"full_text_search"`
	Metadata        []byte           `db:"metadata" json:"metadata"`
	CreatedBy       pgtype.UUID      `db:"created_by" json:"created_by"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type DocumentationLink struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	SourceDocID  pgtype.UUID      `db:"source_doc_id" json:"source_doc_id"`
	TargetDocID  pgtype.UUID      `db:"target_doc_id" json:"target_doc_id"`
	TargetItemID pgtype.UUID      `db:"target_item_id" json:"target_item_id"`
	LinkType     pgtype.Text      `db:"link_type" json:"link_type"`
	Url          pgtype.Text      `db:"url" json:"url"`
	Title        pgtype.Text      `db:"title" json:"title"`
	Description  pgtype.Text      `db:"description" json:"description"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type DocumentationSearchIndex struct {
	ID             pgtype.UUID      `db:"id" json:"id"`
	DocID          pgtype.UUID      `db:"doc_id" json:"doc_id"`
	DocTitle       pgtype.Text      `db:"doc_title" json:"doc_title"`
	SectionTitle   pgtype.Text      `db:"section_title" json:"section_title"`
	ContentSnippet pgtype.Text      `db:"content_snippet" json:"content_snippet"`
	SearchVector   interface{}      `db:"search_vector" json:"search_vector"`
	Rank           pgtype.Float8    `db:"rank" json:"rank"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type DocumentationSection struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	DocID         pgtype.UUID      `db:"doc_id" json:"doc_id"`
	Level         int32            `db:"level" json:"level"`
	Title         string           `db:"title" json:"title"`
	Content       pgtype.Text      `db:"content" json:"content"`
	SectionNumber pgtype.Text      `db:"section_number" json:"section_number"`
	Position      pgtype.Int4      `db:"position" json:"position"`
	CodeBlocks    []string         `db:"code_blocks" json:"code_blocks"`
	Links         []string         `db:"links" json:"links"`
	Metadata      []byte           `db:"metadata" json:"metadata"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type DocumentationVersion struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	DocID         pgtype.UUID      `db:"doc_id" json:"doc_id"`
	VersionNumber int32            `db:"version_number" json:"version_number"`
	Content       string           `db:"content" json:"content"`
	ChangeSummary pgtype.Text      `db:"change_summary" json:"change_summary"`
	ChangedBy     pgtype.UUID      `db:"changed_by" json:"changed_by"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Event struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	ProjectID     pgtype.UUID      `db:"project_id" json:"project_id"`
	EntityType    string           `db:"entity_type" json:"entity_type"`
	EntityID      pgtype.UUID      `db:"entity_id" json:"entity_id"`
	EventType     string           `db:"event_type" json:"event_type"`
	Data          []byte           `db:"data" json:"data"`
	Metadata      []byte           `db:"metadata" json:"metadata"`
	Version       int32            `db:"version" json:"version"`
	CausationID   pgtype.UUID      `db:"causation_id" json:"causation_id"`
	CorrelationID pgtype.UUID      `db:"correlation_id" json:"correlation_id"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Item struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	ProjectID    pgtype.UUID      `db:"project_id" json:"project_id"`
	Title        string           `db:"title" json:"title"`
	Description  pgtype.Text      `db:"description" json:"description"`
	Type         string           `db:"type" json:"type"`
	Status       string           `db:"status" json:"status"`
	Priority     pgtype.Int4      `db:"priority" json:"priority"`
	Metadata     []byte           `db:"metadata" json:"metadata"`
	SearchVector interface{}      `db:"search_vector" json:"search_vector"`
	Embedding    pgvector.Vector  `db:"embedding" json:"embedding"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type ItemAlternative struct {
	ID                pgtype.UUID      `db:"id" json:"id"`
	ProjectID         pgtype.UUID      `db:"project_id" json:"project_id"`
	BaseItemID        pgtype.UUID      `db:"base_item_id" json:"base_item_id"`
	AlternativeItemID pgtype.UUID      `db:"alternative_item_id" json:"alternative_item_id"`
	Relationship      string           `db:"relationship" json:"relationship"`
	Description       pgtype.Text      `db:"description" json:"description"`
	IsChosen          bool             `db:"is_chosen" json:"is_chosen"`
	ChosenAt          pgtype.Timestamp `db:"chosen_at" json:"chosen_at"`
	ChosenBy          pgtype.Text      `db:"chosen_by" json:"chosen_by"`
	ChosenReason      pgtype.Text      `db:"chosen_reason" json:"chosen_reason"`
	Metrics           []byte           `db:"metrics" json:"metrics"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type ItemVersion struct {
	ID                      pgtype.UUID      `db:"id" json:"id"`
	ItemID                  pgtype.UUID      `db:"item_id" json:"item_id"`
	VersionID               pgtype.UUID      `db:"version_id" json:"version_id"`
	BranchID                pgtype.UUID      `db:"branch_id" json:"branch_id"`
	ProjectID               pgtype.UUID      `db:"project_id" json:"project_id"`
	State                   []byte           `db:"state" json:"state"`
	Lifecycle               pgtype.Text      `db:"lifecycle" json:"lifecycle"`
	IntroducedInVersionID   pgtype.UUID      `db:"introduced_in_version_id" json:"introduced_in_version_id"`
	LastModifiedInVersionID pgtype.UUID      `db:"last_modified_in_version_id" json:"last_modified_in_version_id"`
	CreatedAt               pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Link struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	SourceID  pgtype.UUID      `db:"source_id" json:"source_id"`
	TargetID  pgtype.UUID      `db:"target_id" json:"target_id"`
	Type      string           `db:"type" json:"type"`
	Metadata  []byte           `db:"metadata" json:"metadata"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type MergeRequest struct {
	ID              pgtype.UUID      `db:"id" json:"id"`
	ProjectID       pgtype.UUID      `db:"project_id" json:"project_id"`
	SourceBranchID  pgtype.UUID      `db:"source_branch_id" json:"source_branch_id"`
	TargetBranchID  pgtype.UUID      `db:"target_branch_id" json:"target_branch_id"`
	SourceVersionID pgtype.UUID      `db:"source_version_id" json:"source_version_id"`
	BaseVersionID   pgtype.UUID      `db:"base_version_id" json:"base_version_id"`
	Status          string           `db:"status" json:"status"`
	Title           string           `db:"title" json:"title"`
	Description     pgtype.Text      `db:"description" json:"description"`
	Diff            []byte           `db:"diff" json:"diff"`
	Conflicts       []byte           `db:"conflicts" json:"conflicts"`
	Reviewers       []byte           `db:"reviewers" json:"reviewers"`
	ApprovedBy      []byte           `db:"approved_by" json:"approved_by"`
	CreatedBy       string           `db:"created_by" json:"created_by"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	MergedAt        pgtype.Timestamp `db:"merged_at" json:"merged_at"`
	MergedBy        pgtype.Text      `db:"merged_by" json:"merged_by"`
	ClosedAt        pgtype.Timestamp `db:"closed_at" json:"closed_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Milestone struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	ProjectID   pgtype.UUID      `db:"project_id" json:"project_id"`
	ParentID    pgtype.UUID      `db:"parent_id" json:"parent_id"`
	Name        string           `db:"name" json:"name"`
	Slug        string           `db:"slug" json:"slug"`
	Description pgtype.Text      `db:"description" json:"description"`
	Objective   pgtype.Text      `db:"objective" json:"objective"`
	StartDate   pgtype.Timestamp `db:"start_date" json:"start_date"`
	TargetDate  pgtype.Timestamp `db:"target_date" json:"target_date"`
	ActualDate  pgtype.Timestamp `db:"actual_date" json:"actual_date"`
	Status      string           `db:"status" json:"status"`
	Health      string           `db:"health" json:"health"`
	RiskScore   int32            `db:"risk_score" json:"risk_score"`
	RiskFactors []byte           `db:"risk_factors" json:"risk_factors"`
	OwnerID     pgtype.UUID      `db:"owner_id" json:"owner_id"`
	Tags        []byte           `db:"tags" json:"tags"`
	Metadata    []byte           `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type MilestoneDependency struct {
	DependentID      pgtype.UUID      `db:"dependent_id" json:"dependent_id"`
	DependencyID     pgtype.UUID      `db:"dependency_id" json:"dependency_id"`
	RelationshipType string           `db:"relationship_type" json:"relationship_type"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type MilestoneItem struct {
	MilestoneID pgtype.UUID      `db:"milestone_id" json:"milestone_id"`
	ItemID      pgtype.UUID      `db:"item_id" json:"item_id"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Profile struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	AuthID       pgtype.UUID      `db:"auth_id" json:"auth_id"`
	WorkosUserID string           `db:"workos_user_id" json:"workos_user_id"`
	WorkosOrgID  pgtype.Text      `db:"workos_org_id" json:"workos_org_id"`
	WorkosIDs    []byte           `db:"workos_ids" json:"workos_ids"`
	Email        string           `db:"email" json:"email"`
	FullName     pgtype.Text      `db:"full_name" json:"full_name"`
	AvatarUrl    pgtype.Text      `db:"avatar_url" json:"avatar_url"`
	Metadata     []byte           `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type ProgressSnapshot struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	ProjectID    pgtype.UUID      `db:"project_id" json:"project_id"`
	SnapshotDate pgtype.Timestamp `db:"snapshot_date" json:"snapshot_date"`
	Metrics      []byte           `db:"metrics" json:"metrics"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	Metadata    []byte           `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type Snapshot struct {
	ID         pgtype.UUID      `db:"id" json:"id"`
	ProjectID  pgtype.UUID      `db:"project_id" json:"project_id"`
	EntityType string           `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID      `db:"entity_id" json:"entity_id"`
	Version    int32            `db:"version" json:"version"`
	State      []byte           `db:"state" json:"state"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Sprint struct {
	ID              pgtype.UUID      `db:"id" json:"id"`
	ProjectID       pgtype.UUID      `db:"project_id" json:"project_id"`
	Name            string           `db:"name" json:"name"`
	Slug            string           `db:"slug" json:"slug"`
	Goal            pgtype.Text      `db:"goal" json:"goal"`
	StartDate       pgtype.Timestamp `db:"start_date" json:"start_date"`
	EndDate         pgtype.Timestamp `db:"end_date" json:"end_date"`
	Status          string           `db:"status" json:"status"`
	Health          string           `db:"health" json:"health"`
	PlannedCapacity pgtype.Int4      `db:"planned_capacity" json:"planned_capacity"`
	ActualCapacity  pgtype.Int4      `db:"actual_capacity" json:"actual_capacity"`
	PlannedPoints   int32            `db:"planned_points" json:"planned_points"`
	CompletedPoints int32            `db:"completed_points" json:"completed_points"`
	RemainingPoints int32            `db:"remaining_points" json:"remaining_points"`
	AddedPoints     int32            `db:"added_points" json:"added_points"`
	RemovedPoints   int32            `db:"removed_points" json:"removed_points"`
	Metadata        []byte           `db:"metadata" json:"metadata"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	CompletedAt     pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	DeletedAt       pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}

type SprintItem struct {
	SprintID  pgtype.UUID      `db:"sprint_id" json:"sprint_id"`
	ItemID    pgtype.UUID      `db:"item_id" json:"item_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type VelocityHistory struct {
	ID              pgtype.UUID      `db:"id" json:"id"`
	ProjectID       pgtype.UUID      `db:"project_id" json:"project_id"`
	PeriodStart     pgtype.Timestamp `db:"period_start" json:"period_start"`
	PeriodEnd       pgtype.Timestamp `db:"period_end" json:"period_end"`
	PeriodLabel     string           `db:"period_label" json:"period_label"`
	PlannedPoints   int32            `db:"planned_points" json:"planned_points"`
	CompletedPoints int32            `db:"completed_points" json:"completed_points"`
	Velocity        int32            `db:"velocity" json:"velocity"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Version struct {
	ID              pgtype.UUID      `db:"id" json:"id"`
	BranchID        pgtype.UUID      `db:"branch_id" json:"branch_id"`
	ProjectID       pgtype.UUID      `db:"project_id" json:"project_id"`
	VersionNumber   int32            `db:"version_number" json:"version_number"`
	ParentVersionID pgtype.UUID      `db:"parent_version_id" json:"parent_version_id"`
	SnapshotID      pgtype.UUID      `db:"snapshot_id" json:"snapshot_id"`
	ChangesetID     pgtype.UUID      `db:"changeset_id" json:"changeset_id"`
	Tag             pgtype.Text      `db:"tag" json:"tag"`
	Message         string           `db:"message" json:"message"`
	ItemCount       int32            `db:"item_count" json:"item_count"`
	ChangeCount     int32            `db:"change_count" json:"change_count"`
	Status          string           `db:"status" json:"status"`
	ApprovedBy      pgtype.Text      `db:"approved_by" json:"approved_by"`
	ApprovedAt      pgtype.Timestamp `db:"approved_at" json:"approved_at"`
	RejectionReason pgtype.Text      `db:"rejection_reason" json:"rejection_reason"`
	Metadata        []byte           `db:"metadata" json:"metadata"`
	CreatedBy       string           `db:"created_by" json:"created_by"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type VersionBranch struct {
	ID             pgtype.UUID      `db:"id" json:"id"`
	ProjectID      pgtype.UUID      `db:"project_id" json:"project_id"`
	Name           string           `db:"name" json:"name"`
	Slug           string           `db:"slug" json:"slug"`
	Description    pgtype.Text      `db:"description" json:"description"`
	BranchType     string           `db:"branch_type" json:"branch_type"`
	ParentBranchID pgtype.UUID      `db:"parent_branch_id" json:"parent_branch_id"`
	BaseVersionID  pgtype.UUID      `db:"base_version_id" json:"base_version_id"`
	Status         string           `db:"status" json:"status"`
	IsDefault      bool             `db:"is_default" json:"is_default"`
	IsProtected    bool             `db:"is_protected" json:"is_protected"`
	MergedAt       pgtype.Timestamp `db:"merged_at" json:"merged_at"`
	MergedInto     pgtype.UUID      `db:"merged_into" json:"merged_into"`
	MergedBy       pgtype.Text      `db:"merged_by" json:"merged_by"`
	VersionCount   int32            `db:"version_count" json:"version_count"`
	ItemCount      int32            `db:"item_count" json:"item_count"`
	Metadata       []byte           `db:"metadata" json:"metadata"`
	CreatedBy      string           `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
