// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Milestone Items (join table)
	AddItemToMilestone(ctx context.Context, arg AddItemToMilestoneParams) error
	// Sprint Items (join table)
	AddItemToSprint(ctx context.Context, arg AddItemToSprintParams) error
	// Agents
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	// Burndown Data
	CreateBurndownData(ctx context.Context, arg CreateBurndownDataParams) (BurndownDatum, error)
	// Change Log
	CreateChangeLog(ctx context.Context, arg CreateChangeLogParams) (ChangeLog, error)
	// Documentation
	CreateDocumentation(ctx context.Context, arg CreateDocumentationParams) (Documentation, error)
	// Events
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// Items
	CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error)
	// Item Alternatives
	CreateItemAlternative(ctx context.Context, arg CreateItemAlternativeParams) (ItemAlternative, error)
	// Item Versions
	CreateItemVersion(ctx context.Context, arg CreateItemVersionParams) (ItemVersion, error)
	// Links
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	// Merge Requests
	CreateMergeRequest(ctx context.Context, arg CreateMergeRequestParams) (MergeRequest, error)
	// Milestones
	CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error)
	// Profiles
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	// Progress Snapshots
	CreateProgressSnapshot(ctx context.Context, arg CreateProgressSnapshotParams) (ProgressSnapshot, error)
	// sqlc queries for TraceRTM
	// Run: sqlc generate
	// Projects
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// Snapshots
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error)
	// Sprints
	CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error)
	// Velocity History
	CreateVelocityHistory(ctx context.Context, arg CreateVelocityHistoryParams) (VelocityHistory, error)
	// Versions
	CreateVersion(ctx context.Context, arg CreateVersionParams) (Version, error)
	// Version Branches
	CreateVersionBranch(ctx context.Context, arg CreateVersionBranchParams) (VersionBranch, error)
	DeleteAgent(ctx context.Context, id pgtype.UUID) error
	DeleteBurndownData(ctx context.Context, id pgtype.UUID) error
	DeleteDocumentation(ctx context.Context, id pgtype.UUID) error
	DeleteItem(ctx context.Context, id pgtype.UUID) error
	DeleteItemAlternative(ctx context.Context, id pgtype.UUID) error
	DeleteItemVersion(ctx context.Context, id pgtype.UUID) error
	DeleteLink(ctx context.Context, id pgtype.UUID) error
	DeleteMergeRequest(ctx context.Context, id pgtype.UUID) error
	DeleteMilestone(ctx context.Context, id pgtype.UUID) error
	DeleteProfile(ctx context.Context, id pgtype.UUID) error
	DeleteProgressSnapshot(ctx context.Context, id pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteSprint(ctx context.Context, id pgtype.UUID) error
	DeleteVelocityHistory(ctx context.Context, id pgtype.UUID) error
	DeleteVersion(ctx context.Context, id pgtype.UUID) error
	DeleteVersionBranch(ctx context.Context, id pgtype.UUID) error
	GetAgent(ctx context.Context, id pgtype.UUID) (Agent, error)
	GetAncestors(ctx context.Context, targetID pgtype.UUID) ([]GetAncestorsRow, error)
	GetBurndownData(ctx context.Context, id pgtype.UUID) (BurndownDatum, error)
	GetChangeLog(ctx context.Context, id pgtype.UUID) (ChangeLog, error)
	// Graph Queries (Recursive CTEs for traversal)
	GetDescendants(ctx context.Context, sourceID pgtype.UUID) ([]GetDescendantsRow, error)
	GetDocumentation(ctx context.Context, id pgtype.UUID) (Documentation, error)
	GetEvent(ctx context.Context, id pgtype.UUID) (Event, error)
	GetImpactAnalysis(ctx context.Context, sourceID pgtype.UUID) ([]GetImpactAnalysisRow, error)
	GetItem(ctx context.Context, id pgtype.UUID) (GetItemRow, error)
	GetItemAlternative(ctx context.Context, id pgtype.UUID) (ItemAlternative, error)
	GetItemVersion(ctx context.Context, id pgtype.UUID) (ItemVersion, error)
	GetLink(ctx context.Context, id pgtype.UUID) (Link, error)
	GetLinkBySourceAndTarget(ctx context.Context, arg GetLinkBySourceAndTargetParams) (Link, error)
	GetMergeRequest(ctx context.Context, id pgtype.UUID) (MergeRequest, error)
	GetMilestone(ctx context.Context, id pgtype.UUID) (Milestone, error)
	GetOrphanItems(ctx context.Context, projectID pgtype.UUID) ([]GetOrphanItemsRow, error)
	GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error)
	GetProfileByEmail(ctx context.Context, email string) (Profile, error)
	GetProfileByWorkOSUserID(ctx context.Context, workosUserID string) (Profile, error)
	GetProgressSnapshot(ctx context.Context, id pgtype.UUID) (ProgressSnapshot, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetSnapshot(ctx context.Context, id pgtype.UUID) (Snapshot, error)
	GetSnapshotByEntityVersion(ctx context.Context, arg GetSnapshotByEntityVersionParams) (Snapshot, error)
	GetSprint(ctx context.Context, id pgtype.UUID) (Sprint, error)
	GetVelocityHistory(ctx context.Context, id pgtype.UUID) (VelocityHistory, error)
	GetVersion(ctx context.Context, id pgtype.UUID) (Version, error)
	GetVersionBranch(ctx context.Context, id pgtype.UUID) (VersionBranch, error)
	ListAgentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Agent, error)
	ListBurndownDataBySprint(ctx context.Context, sprintID pgtype.UUID) ([]BurndownDatum, error)
	ListChangeLogByEntity(ctx context.Context, arg ListChangeLogByEntityParams) ([]ChangeLog, error)
	ListDocumentationByProject(ctx context.Context, arg ListDocumentationByProjectParams) ([]Documentation, error)
	ListEventsByEntity(ctx context.Context, arg ListEventsByEntityParams) ([]Event, error)
	ListEventsByProject(ctx context.Context, arg ListEventsByProjectParams) ([]Event, error)
	ListItemAlternativesByBase(ctx context.Context, baseItemID pgtype.UUID) ([]ItemAlternative, error)
	ListItemVersionsByItem(ctx context.Context, itemID pgtype.UUID) ([]ItemVersion, error)
	ListItemVersionsByVersion(ctx context.Context, versionID pgtype.UUID) ([]ItemVersion, error)
	ListItemsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListItemsByIDsRow, error)
	ListItemsByMilestone(ctx context.Context, milestoneID pgtype.UUID) ([]ListItemsByMilestoneRow, error)
	ListItemsByProject(ctx context.Context, arg ListItemsByProjectParams) ([]ListItemsByProjectRow, error)
	ListItemsByProjectAndType(ctx context.Context, arg ListItemsByProjectAndTypeParams) ([]ListItemsByProjectAndTypeRow, error)
	// Graph Queries - Additional operations
	ListItemsByProjectIDs(ctx context.Context, projectID pgtype.UUID) ([]ListItemsByProjectIDsRow, error)
	ListItemsBySprint(ctx context.Context, sprintID pgtype.UUID) ([]ListItemsBySprintRow, error)
	ListLinksBetweenItems(ctx context.Context, dollar_1 []pgtype.UUID) ([]Link, error)
	ListLinksBySource(ctx context.Context, sourceID pgtype.UUID) ([]Link, error)
	ListLinksBySourceIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Link, error)
	ListLinksByTarget(ctx context.Context, targetID pgtype.UUID) ([]Link, error)
	ListLinksByTargetIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Link, error)
	ListMergeRequestsByProject(ctx context.Context, arg ListMergeRequestsByProjectParams) ([]MergeRequest, error)
	ListMilestonesByItem(ctx context.Context, itemID pgtype.UUID) ([]Milestone, error)
	ListMilestonesByProject(ctx context.Context, projectID pgtype.UUID) ([]Milestone, error)
	ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error)
	ListProgressSnapshotsByProject(ctx context.Context, arg ListProgressSnapshotsByProjectParams) ([]ProgressSnapshot, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListSnapshotsByEntity(ctx context.Context, arg ListSnapshotsByEntityParams) ([]Snapshot, error)
	ListSprintsByProject(ctx context.Context, projectID pgtype.UUID) ([]Sprint, error)
	ListVelocityHistoryByProject(ctx context.Context, arg ListVelocityHistoryByProjectParams) ([]VelocityHistory, error)
	ListVersionBranchesByProject(ctx context.Context, projectID pgtype.UUID) ([]VersionBranch, error)
	ListVersionsByBranch(ctx context.Context, branchID pgtype.UUID) ([]Version, error)
	RemoveItemFromMilestone(ctx context.Context, arg RemoveItemFromMilestoneParams) error
	RemoveItemFromSprint(ctx context.Context, arg RemoveItemFromSprintParams) error
	// Full-Text Search Queries
	SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error)
	// Vector Search Queries (Semantic Search)
	SearchItemsByEmbedding(ctx context.Context, arg SearchItemsByEmbeddingParams) ([]SearchItemsByEmbeddingRow, error)
	SearchItemsByType(ctx context.Context, arg SearchItemsByTypeParams) ([]SearchItemsByTypeRow, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateDocumentation(ctx context.Context, arg UpdateDocumentationParams) (Documentation, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error)
	UpdateItemAlternative(ctx context.Context, arg UpdateItemAlternativeParams) (ItemAlternative, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpdateMergeRequest(ctx context.Context, arg UpdateMergeRequestParams) (MergeRequest, error)
	UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error)
	UpdateVersion(ctx context.Context, arg UpdateVersionParams) (Version, error)
	UpdateVersionBranch(ctx context.Context, arg UpdateVersionBranchParams) (VersionBranch, error)
}

var _ Querier = (*Queries)(nil)
