"""Pydantic schemas for TraceRTM."""

from tracertm.schemas.account import (
    AccountCreate,
    AccountListResponse,
    AccountResponse,
    AccountUpdate,
    AccountUserResponse,
)
from tracertm.schemas.auth import (
    AccountSwitchRequest,
    AuthResponse,
    LoginRequest,
    SignupRequest,
    UserResponse,
)
from tracertm.schemas.event import EventCreate, EventResponse
from tracertm.schemas.execution import (
    CodexAgentTaskCreate,
    CodexAgentTaskListResponse,
    CodexAgentTaskResponse,
    ExecutionArtifactCreate,
    ExecutionArtifactListResponse,
    ExecutionArtifactResponse,
    ExecutionComplete,
    ExecutionCreate,
    ExecutionEnvironmentConfigCreate,
    ExecutionEnvironmentConfigResponse,
    ExecutionEnvironmentConfigUpdate,
    ExecutionListResponse,
    ExecutionResponse,
    ExecutionStart,
    ExecutionStats,
    ExecutionUpdate,
    VHSTapeGenerateRequest,
    VHSTapeResponse,
)
from tracertm.schemas.integration import (
    ConflictResolutionRequest,
    ConflictResolutionResponse,
    ConflictResolutionStatus,
    ConflictResolutionStrategy,
    CredentialStatus,
    CredentialType,
    CredentialValidationResult,
    ExternalItemSearchRequest,
    ExternalItemSearchResponse,
    GitHubIssue,
    GitHubPullRequest,
    GitHubRepo,
    GitHubRepoList,
    IntegrationCredentialCreate,
    IntegrationCredentialList,
    IntegrationCredentialResponse,
    IntegrationCredentialUpdate,
    IntegrationMappingCreate,
    IntegrationMappingList,
    IntegrationMappingResponse,
    IntegrationMappingUpdate,
    IntegrationProvider,
    IntegrationStats,
    LinearIssue,
    LinearTeam,
    LinearTeamList,
    MappingDirection,
    MappingStatus,
    OAuthCallbackRequest,
    OAuthStartRequest,
    OAuthStartResponse,
    SyncConflictList,
    SyncConflictResponse,
    SyncDirection,
    SyncEventType,
    SyncLogList,
    SyncLogResponse,
    SyncQueueItemResponse,
    SyncQueueList,
    SyncQueueStatus,
    SyncStatusResponse,
    SyncStatusSummary,
    TriggerSyncRequest,
    TriggerSyncResponse,
)
from tracertm.schemas.item import ItemCreate, ItemResponse, ItemUpdate
from tracertm.schemas.item_spec import (
    AcceptanceCriterion,
    BlockerEntry,
    ChangeHistoryEntry,
    ChecklistItem,
    ConstraintType,
    DefectHealthStats,
    # Defect Spec Schemas
    DefectSpecCreate,
    DefectSpecListResponse,
    DefectSpecResponse,
    DefectSpecUpdate,
    EpicProgressStats,
    # Epic Spec Schemas
    EpicSpecCreate,
    EpicSpecListResponse,
    EpicSpecResponse,
    EpicSpecUpdate,
    ImpactAssessment,
    Invariant,
    # Bulk Operation Schemas
    ItemSpecBulkCreateRequest,
    ItemSpecBulkOperationResponse,
    ItemSpecBulkUpdateRequest,
    ItemSpecStats,
    QualityDimension,
    # Nested types
    QualityIssue,
    # Statistics Schemas
    RequirementQualityStats,
    # Requirement Spec Schemas
    RequirementSpecCreate,
    RequirementSpecListResponse,
    RequirementSpecResponse,
    RequirementSpecUpdate,
    # Item Spec Enums
    RequirementType,
    RiskLevel,
    SemanticSimilarity,
    SubtaskEntry,
    TaskProgressStats,
    # Task Spec Schemas
    TaskSpecCreate,
    TaskSpecListResponse,
    TaskSpecResponse,
    TaskSpecUpdate,
    TestHealthStats,
    TestResultStatus,
    TestRunSummary,
    # Test Spec Schemas
    TestSpecCreate,
    TestSpecListResponse,
    TestSpecResponse,
    TestSpecUpdate,
    TestType,
    TimeEntry,
    UserStoryHealthStats,
    # User Story Spec Schemas
    UserStorySpecCreate,
    UserStorySpecListResponse,
    UserStorySpecResponse,
    UserStorySpecUpdate,
    VerificationEvidence,
    VerificationStatus,
)
from tracertm.schemas.link import LinkCreate, LinkResponse
from tracertm.schemas.problem import (
    FishboneAnalysis,
    FiveWhysAnalysis,
    PermanentFixUpdate,
    ProblemActivityResponse,
    ProblemClosure,
    ProblemCreate,
    ProblemListResponse,
    ProblemResponse,
    ProblemStatusTransition,
    ProblemUpdate,
    RCARequest,
    WorkaroundUpdate,
)
from tracertm.schemas.process import (
    ProcessActivation,
    ProcessCreate,
    ProcessDeprecation,
    ProcessExecutionComplete,
    ProcessExecutionCreate,
    ProcessExecutionResponse,
    ProcessExecutionUpdate,
    ProcessListResponse,
    ProcessResponse,
    ProcessUpdate,
    ProcessVersionCreate,
)
from tracertm.schemas.specification import (
    ADRActivityListResponse,
    ADRActivityResponse,
    ADRCreate,
    ADRListResponse,
    ADROption,
    ADRResponse,
    # ADR Enums & Schemas
    ADRStatus,
    ADRUpdate,
    BDDStep,
    ContractActivityListResponse,
    ContractActivityResponse,
    ContractCondition,
    ContractCreate,
    ContractListResponse,
    ContractResponse,
    # Contract Enums & Schemas
    ContractStatus,
    ContractType,
    ContractUpdate,
    FeatureActivityListResponse,
    FeatureActivityResponse,
    FeatureCreate,
    FeatureListResponse,
    FeatureResponse,
    # Feature & Scenario Enums & Schemas
    FeatureStatus,
    FeatureUpdate,
    # Requirement Quality Schemas
    RequirementQualityRead,
    ScenarioActivityListResponse,
    ScenarioActivityResponse,
    ScenarioCreate,
    ScenarioExample,
    ScenarioListResponse,
    ScenarioResponse,
    ScenarioStatus,
    ScenarioUpdate,
    StateTransition,
    StepDefinitionCreate,
    StepDefinitionImplementation,
    StepDefinitionLanguage,
    StepDefinitionListResponse,
    StepDefinitionResponse,
    # Step Definition Enums & Schemas
    StepDefinitionType,
    StepDefinitionUpdate,
)
from tracertm.schemas.test_case import (
    TestCaseActivityResponse,
    TestCaseCreate,
    TestCaseDeprecation,
    TestCaseListResponse,
    TestCaseResponse,
    TestCaseReview,
    TestCaseStats,
    TestCaseStatusTransition,
    TestCaseUpdate,
    TestStep,
)
from tracertm.schemas.test_coverage import (
    CoverageActivityResponse,
    CoverageGapItem,
    CoverageGapsResponse,
    CoverageStats,
    TestCaseCoverageSummary,
    TestCoverageCreate,
    TestCoverageListResponse,
    TestCoverageResponse,
    TestCoverageUpdate,
    TestCoverageVerify,
    TraceabilityMatrixItem,
    TraceabilityMatrixResponse,
)
from tracertm.schemas.test_run import (
    BulkTestResultsSubmit,
    TestResultCreate,
    TestResultResponse,
    TestRunActivitiesResponse,
    TestRunActivityResponse,
    TestRunComplete,
    TestRunCreate,
    TestRunListResponse,
    TestRunResponse,
    TestRunStart,
    TestRunStats,
    TestRunUpdate,
)
from tracertm.schemas.test_suite import (
    TestSuiteActivitiesResponse,
    TestSuiteActivityResponse,
    TestSuiteCreate,
    TestSuiteListResponse,
    TestSuiteResponse,
    TestSuiteStats,
    TestSuiteStatusTransition,
    TestSuiteTestCaseCreate,
    TestSuiteTestCaseResponse,
    TestSuiteUpdate,
)
from tracertm.schemas.webhook import (
    InboundWebhookPayload,
    InboundWebhookResponse,
    WebhookCreate,
    WebhookListResponse,
    WebhookLogResponse,
    WebhookLogsResponse,
    WebhookResponse,
    WebhookStats,
    WebhookStatusUpdate,
    WebhookUpdate,
)

__all__ = [
    "ADRActivityListResponse",
    "ADRActivityResponse",
    "ADRCreate",
    "ADRListResponse",
    "ADROption",
    "ADRResponse",
    # Specification schemas
    # ADR Enums & Schemas
    "ADRStatus",
    "ADRUpdate",
    "AcceptanceCriterion",
    # Account schemas
    "AccountCreate",
    "AccountListResponse",
    "AccountResponse",
    "AccountSwitchRequest",
    "AccountUpdate",
    "AccountUserResponse",
    "AuthResponse",
    "BDDStep",
    "BlockerEntry",
    "BulkTestResultsSubmit",
    "ChangeHistoryEntry",
    "ChecklistItem",
    "CodexAgentTaskCreate",
    "CodexAgentTaskListResponse",
    "CodexAgentTaskResponse",
    "ConflictResolutionRequest",
    "ConflictResolutionResponse",
    "ConflictResolutionStatus",
    "ConflictResolutionStrategy",
    "ConstraintType",
    "ContractActivityListResponse",
    "ContractActivityResponse",
    "ContractCondition",
    "ContractCreate",
    "ContractListResponse",
    "ContractResponse",
    # Contract Enums & Schemas
    "ContractStatus",
    "ContractType",
    "ContractUpdate",
    "CoverageActivityResponse",
    "CoverageGapItem",
    "CoverageGapsResponse",
    "CoverageStats",
    "CredentialStatus",
    "CredentialType",
    "CredentialValidationResult",
    "DefectHealthStats",
    # Defect Spec Schemas
    "DefectSpecCreate",
    "DefectSpecListResponse",
    "DefectSpecResponse",
    "DefectSpecUpdate",
    "EpicProgressStats",
    # Epic Spec Schemas
    "EpicSpecCreate",
    "EpicSpecListResponse",
    "EpicSpecResponse",
    "EpicSpecUpdate",
    "EventCreate",
    "EventResponse",
    "ExecutionArtifactCreate",
    "ExecutionArtifactListResponse",
    "ExecutionArtifactResponse",
    "ExecutionComplete",
    # Execution schemas
    "ExecutionCreate",
    "ExecutionEnvironmentConfigCreate",
    "ExecutionEnvironmentConfigResponse",
    "ExecutionEnvironmentConfigUpdate",
    "ExecutionListResponse",
    "ExecutionResponse",
    "ExecutionStart",
    "ExecutionStats",
    "ExecutionUpdate",
    "ExternalItemSearchRequest",
    "ExternalItemSearchResponse",
    "FeatureActivityListResponse",
    "FeatureActivityResponse",
    "FeatureCreate",
    "FeatureListResponse",
    "FeatureResponse",
    # Feature & Scenario Enums & Schemas
    "FeatureStatus",
    "FeatureUpdate",
    "FishboneAnalysis",
    "FiveWhysAnalysis",
    "GitHubIssue",
    "GitHubPullRequest",
    "GitHubRepo",
    "GitHubRepoList",
    "ImpactAssessment",
    "InboundWebhookPayload",
    "InboundWebhookResponse",
    "IntegrationCredentialCreate",
    "IntegrationCredentialList",
    "IntegrationCredentialResponse",
    "IntegrationCredentialUpdate",
    "IntegrationMappingCreate",
    "IntegrationMappingList",
    "IntegrationMappingResponse",
    "IntegrationMappingUpdate",
    # Integration schemas
    "IntegrationProvider",
    "IntegrationStats",
    "Invariant",
    "ItemCreate",
    "ItemResponse",
    # Bulk Operation Schemas
    "ItemSpecBulkCreateRequest",
    "ItemSpecBulkOperationResponse",
    "ItemSpecBulkUpdateRequest",
    "ItemSpecStats",
    "ItemUpdate",
    "LinearIssue",
    "LinearTeam",
    "LinearTeamList",
    "LinkCreate",
    "LinkResponse",
    "LoginRequest",
    "MappingDirection",
    "MappingStatus",
    "OAuthCallbackRequest",
    "OAuthStartRequest",
    "OAuthStartResponse",
    "PermanentFixUpdate",
    "ProblemActivityResponse",
    "ProblemClosure",
    # Problem schemas
    "ProblemCreate",
    "ProblemListResponse",
    "ProblemResponse",
    "ProblemStatusTransition",
    "ProblemUpdate",
    "ProcessActivation",
    # Process schemas
    "ProcessCreate",
    "ProcessDeprecation",
    "ProcessExecutionComplete",
    "ProcessExecutionCreate",
    "ProcessExecutionResponse",
    "ProcessExecutionUpdate",
    "ProcessListResponse",
    "ProcessResponse",
    "ProcessUpdate",
    "ProcessVersionCreate",
    "QualityDimension",
    # Item Spec Nested Types
    "QualityIssue",
    "RCARequest",
    # Requirement Quality Schemas
    "RequirementQualityRead",
    # Statistics Schemas
    "RequirementQualityStats",
    # Requirement Spec Schemas
    "RequirementSpecCreate",
    "RequirementSpecListResponse",
    "RequirementSpecResponse",
    "RequirementSpecUpdate",
    # Item Spec Enums
    "RequirementType",
    "RiskLevel",
    "ScenarioActivityListResponse",
    "ScenarioActivityResponse",
    "ScenarioCreate",
    "ScenarioExample",
    "ScenarioListResponse",
    "ScenarioResponse",
    "ScenarioStatus",
    "ScenarioUpdate",
    "SemanticSimilarity",
    # Auth schemas
    "SignupRequest",
    "StateTransition",
    "StepDefinitionCreate",
    "StepDefinitionImplementation",
    "StepDefinitionLanguage",
    "StepDefinitionListResponse",
    "StepDefinitionResponse",
    # Step Definition Enums & Schemas
    "StepDefinitionType",
    "StepDefinitionUpdate",
    "SubtaskEntry",
    "SyncConflictList",
    "SyncConflictResponse",
    "SyncDirection",
    "SyncEventType",
    "SyncLogList",
    "SyncLogResponse",
    "SyncQueueItemResponse",
    "SyncQueueList",
    "SyncQueueStatus",
    "SyncStatusResponse",
    "SyncStatusSummary",
    "TaskProgressStats",
    # Task Spec Schemas
    "TaskSpecCreate",
    "TaskSpecListResponse",
    "TaskSpecResponse",
    "TaskSpecUpdate",
    "TestCaseActivityResponse",
    "TestCaseCoverageSummary",
    # Test Case schemas
    "TestCaseCreate",
    "TestCaseDeprecation",
    "TestCaseListResponse",
    "TestCaseResponse",
    "TestCaseReview",
    "TestCaseStats",
    "TestCaseStatusTransition",
    "TestCaseUpdate",
    # Test Coverage schemas
    "TestCoverageCreate",
    "TestCoverageListResponse",
    "TestCoverageResponse",
    "TestCoverageUpdate",
    "TestCoverageVerify",
    "TestHealthStats",
    "TestResultCreate",
    "TestResultResponse",
    "TestResultStatus",
    "TestRunActivitiesResponse",
    "TestRunActivityResponse",
    "TestRunComplete",
    # Test Run schemas
    "TestRunCreate",
    "TestRunListResponse",
    "TestRunResponse",
    "TestRunStart",
    "TestRunStats",
    "TestRunSummary",
    "TestRunUpdate",
    # Test Spec Schemas
    "TestSpecCreate",
    "TestSpecListResponse",
    "TestSpecResponse",
    "TestSpecUpdate",
    "TestStep",
    "TestSuiteActivitiesResponse",
    "TestSuiteActivityResponse",
    # Test Suite schemas
    "TestSuiteCreate",
    "TestSuiteListResponse",
    "TestSuiteResponse",
    "TestSuiteStats",
    "TestSuiteStatusTransition",
    "TestSuiteTestCaseCreate",
    "TestSuiteTestCaseResponse",
    "TestSuiteUpdate",
    "TestType",
    "TimeEntry",
    "TraceabilityMatrixItem",
    "TraceabilityMatrixResponse",
    "TriggerSyncRequest",
    "TriggerSyncResponse",
    "UserResponse",
    "UserStoryHealthStats",
    # User Story Spec Schemas
    "UserStorySpecCreate",
    "UserStorySpecListResponse",
    "UserStorySpecResponse",
    "UserStorySpecUpdate",
    "VHSTapeGenerateRequest",
    "VHSTapeResponse",
    "VerificationEvidence",
    "VerificationStatus",
    # Webhook schemas
    "WebhookCreate",
    "WebhookListResponse",
    "WebhookLogResponse",
    "WebhookLogsResponse",
    "WebhookResponse",
    "WebhookStats",
    "WebhookStatusUpdate",
    "WebhookUpdate",
    "WorkaroundUpdate",
]
