-- Business Objectives Batch 2 (Items 9-30)

INSERT INTO tracertm.items (id, project_id, type, title, description, status, priority, metadata, tags, created_at, updated_at)
VALUES

-- Growth & Expansion Objectives
('d1e1f1a1-0001-4001-a001-000000000009', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Launch in 15 New Cities by Q2 2026',
'Expand SwiftRide''s geographic footprint by launching operations in 15 new tier-2 and tier-3 cities across North America by the end of Q2 2026. This expansion will focus on mid-sized markets with populations between 200,000-500,000 that show strong demand for ride-sharing services but limited competition. Each launch will include a 90-day market entry plan covering driver recruitment (minimum 200 drivers per city), rider acquisition campaigns (targeting 5,000 active riders per city in first 60 days), local partnership development, and regulatory compliance. Success will be measured by achieving profitability in each new city within 180 days of launch.',
'ACTIVE', 1,
'{"owner": "VP of Expansion", "target_date": "2026-06-30", "success_metrics": ["15 cities launched", "200+ drivers per city", "5000+ riders per city within 60 days", "Profitability within 180 days"], "dependencies": ["Driver recruitment infrastructure", "Regulatory compliance team", "Local marketing budget"], "stakeholders": ["CEO", "CFO", "VP Expansion", "Regional Managers"], "budget": "$12M", "risk_level": "HIGH"}'::jsonb,
ARRAY['business', 'strategy', 'expansion', 'growth', 'geographic'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000010', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Achieve 30% Month-over-Month Rider Growth',
'Drive aggressive rider acquisition to achieve 30% month-over-month growth in active riders across all markets for 6 consecutive months (Q1-Q2 2026). This objective requires a multi-channel marketing approach including digital advertising, referral programs, corporate partnerships, and strategic promotions. Focus areas include: optimizing customer acquisition cost (target CAC <$25), improving first-ride completion rate (target >85%), and maximizing rider retention after first ride (target 40% retention at 30 days). Growth strategies will be tailored per market segment with dedicated campaigns for commuters, airport travelers, and late-night users.',
'ACTIVE', 1,
'{"owner": "Chief Marketing Officer", "target_date": "2026-06-30", "success_metrics": ["30% MoM growth", "CAC <$25", "85% first ride completion", "40% 30-day retention"], "dependencies": ["Marketing budget increase", "Referral program enhancement", "Corporate sales team"], "stakeholders": ["CMO", "VP Growth", "Product Marketing", "Data Analytics"], "budget": "$8M quarterly", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'strategy', 'growth', 'marketing', 'acquisition'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000011', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Reduce Driver Churn to Below 12%',
'Lower monthly driver churn rate from current 18% to below 12% by implementing comprehensive driver retention programs throughout 2026. This initiative addresses the primary drivers of churn including income volatility, lack of benefits, poor support experience, and limited career advancement. Key programs include: guaranteed earnings floor during slow periods, tiered driver rewards program, dedicated driver support hotline with <2 minute response time, driver appreciation events, and pathway to fleet ownership. Success requires collaboration across Operations, Driver Experience, and Finance teams. Expected impact includes $15M annual savings in recruitment and training costs.',
'ACTIVE', 2,
'{"owner": "VP Driver Experience", "target_date": "2026-12-31", "success_metrics": ["<12% monthly churn", "80% driver satisfaction", "<2 min support response", "$15M cost savings"], "dependencies": ["Guaranteed earnings fund", "Driver support team expansion", "Rewards platform"], "stakeholders": ["VP Driver Experience", "CFO", "Head of Operations"], "budget": "$5M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'strategy', 'retention', 'driver-experience', 'operations'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000012', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Establish Enterprise B2B Revenue Stream at $50M ARR',
'Build and scale enterprise B2B business line targeting corporate clients, healthcare providers, and educational institutions to generate $50M in annual recurring revenue by end of 2026. This new revenue stream will provide ride services under bulk contracts with features including: centralized billing, custom approval workflows, department-level reporting, expense integration, and dedicated account management. Initial target segments include Fortune 1000 companies (employee transportation), hospital systems (patient/staff transport), and universities (student/staff mobility). Success metrics include signing 200+ enterprise clients with average contract value of $250K.',
'ACTIVE', 1,
'{"owner": "VP Enterprise Sales", "target_date": "2026-12-31", "success_metrics": ["$50M ARR", "200+ enterprise clients", "$250K average contract value", "90% contract renewal rate"], "dependencies": ["Enterprise sales team", "B2B platform features", "Account management team"], "stakeholders": ["CEO", "VP Enterprise Sales", "Product", "Finance"], "budget": "$10M", "risk_level": "HIGH"}'::jsonb,
ARRAY['business', 'strategy', 'b2b', 'enterprise', 'revenue'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000013', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Launch Subscription Service with 100K Subscribers',
'Introduce SwiftRide Premium subscription service and acquire 100,000 paying subscribers by Q4 2026. Premium membership ($29.99/month) offers unlimited rides up to $15 value each, priority matching, no surge pricing, free cancellations, and exclusive support. This recurring revenue model provides predictable cash flow and increases rider lifetime value from $180 to projected $450+. Launch strategy includes: beta testing with 5,000 high-frequency riders, phased rollout by market, referral incentives, and corporate bulk purchase options. Financial modeling projects subscription revenue of $36M annually at 100K subscriber target.',
'ACTIVE', 1,
'{"owner": "VP Product", "target_date": "2026-10-31", "success_metrics": ["100K subscribers", "$29.99 ARPU", "60% retention after 3 months", "$36M annual revenue"], "dependencies": ["Subscription billing system", "Premium feature development", "Customer segmentation"], "stakeholders": ["VP Product", "CFO", "Engineering", "Marketing"], "budget": "$4M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'strategy', 'subscription', 'revenue-model', 'product'],
NOW(), NOW()),

-- Operational Excellence Objectives
('d1e1f1a1-0001-4001-a001-000000000014', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Reduce Average Pickup Time to Under 3 Minutes',
'Optimize matching algorithms and driver positioning to reduce average rider pickup time from current 4.5 minutes to under 3 minutes across all markets by Q3 2026. This improvement directly impacts rider satisfaction (target NPS +15 points) and driver efficiency (target 20% more rides per shift). Implementation includes: predictive demand modeling for driver pre-positioning, enhanced real-time routing algorithms, incentive zones during high-demand periods, and machine learning for pickup time estimation. Technical requirements include infrastructure scaling to process 100K+ matches per minute and <100ms matching latency.',
'ACTIVE', 2,
'{"owner": "VP Operations", "target_date": "2026-09-30", "success_metrics": ["<3 min avg pickup", "+15 NPS points", "20% more rides per shift", "<100ms match latency"], "dependencies": ["ML algorithm enhancement", "Infrastructure scaling", "Driver incentive system"], "stakeholders": ["VP Operations", "CTO", "Data Science", "Product"], "budget": "$6M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'operations', 'efficiency', 'technology', 'customer-experience'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000015', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Achieve 99.9% Platform Uptime',
'Establish world-class platform reliability with 99.9% uptime (max 8.76 hours downtime annually) across all core services including rider app, driver app, matching system, and payment processing. This objective requires comprehensive infrastructure modernization including: multi-region active-active deployment, automated failover systems, comprehensive monitoring and alerting, chaos engineering practices, and incident response procedures with <5 minute time to detection and <15 minute time to resolution. Implementation includes migration to Kubernetes, implementation of circuit breakers, and establishment of SRE team. Downtime currently costs estimated $50K per hour in lost revenue.',
'ACTIVE', 1,
'{"owner": "CTO", "target_date": "2026-06-30", "success_metrics": ["99.9% uptime", "<5 min incident detection", "<15 min resolution time", "Zero critical incidents >1 hour"], "dependencies": ["Infrastructure migration", "SRE team hiring", "Monitoring tools"], "stakeholders": ["CTO", "VP Engineering", "DevOps", "Product"], "budget": "$8M", "risk_level": "HIGH"}'::jsonb,
ARRAY['business', 'technology', 'reliability', 'infrastructure', 'operations'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000016', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Improve First-Ride Completion Rate to 90%',
'Increase the percentage of first-time riders who successfully complete their initial ride from current 78% to 90% by Q2 2026. First-ride completion is critical for long-term retention and lifetime value. This initiative addresses primary drop-off points: app onboarding (currently 8% abandon), payment setup (6% abandon), driver no-show (5% fail), and pickup confusion (3% fail). Solutions include: simplified onboarding flow, pre-authorized payment options, first-ride guarantee (refund if driver no-show), live chat support during first ride, and step-by-step pickup guidance. Expected revenue impact: $12M annually from improved new rider retention.',
'ACTIVE', 2,
'{"owner": "VP Product", "target_date": "2026-06-30", "success_metrics": ["90% first ride completion", "95% onboarding completion", "98% payment setup", "<1% driver no-show"], "dependencies": ["Onboarding redesign", "Live chat system", "First-ride guarantee fund"], "stakeholders": ["VP Product", "Design", "Engineering", "Customer Support"], "budget": "$3M", "risk_level": "LOW"}'::jsonb,
ARRAY['business', 'product', 'onboarding', 'retention', 'ux'],
NOW(), NOW()),

-- Financial Objectives
('d1e1f1a1-0001-4001-a001-000000000017', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Achieve Positive EBITDA in Top 10 Markets',
'Reach positive EBITDA (earnings before interest, taxes, depreciation, and amortization) in our top 10 metropolitan markets by Q3 2026, representing 70% of total ride volume. This milestone demonstrates path to profitability while maintaining aggressive growth in emerging markets. Key strategies include: optimizing market-specific pricing models, reducing customer acquisition cost through organic growth and referrals, improving driver utilization rates to 45%+ active time, and implementing dynamic cost management. Target consolidated EBITDA margin of 12% in mature markets. This achievement critical for Series D funding round.',
'ACTIVE', 1,
'{"owner": "CFO", "target_date": "2026-09-30", "success_metrics": ["Positive EBITDA top 10 markets", "12% EBITDA margin", "45% driver utilization", "70% volume coverage"], "dependencies": ["Pricing optimization", "Cost management system", "Market analytics"], "stakeholders": ["CFO", "CEO", "VP Operations", "Board"], "budget": "N/A - cost reduction", "risk_level": "HIGH"}'::jsonb,
ARRAY['business', 'finance', 'profitability', 'strategy', 'metrics'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000018', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Reduce Customer Acquisition Cost by 40%',
'Lower blended customer acquisition cost (CAC) from current $42 to $25 by Q4 2026 through optimization of marketing channels, enhanced referral programs, and organic growth initiatives. Current CAC breakdown: paid digital advertising (45%), referral incentives (25%), partnerships (15%), traditional marketing (10%), other (5%). Strategy focuses on: increasing referral program effectiveness (target 35% of new riders from referrals vs current 18%), improving SEO/content marketing for organic discovery, developing strategic partnerships with complementary services, and optimizing paid channel ROI through better targeting and creative testing. At 1M new riders annually, this represents $17M in cost savings.',
'ACTIVE', 1,
'{"owner": "CMO", "target_date": "2026-12-31", "success_metrics": ["$25 CAC", "35% referral-driven signups", "50% paid channel efficiency improvement", "$17M cost savings"], "dependencies": ["Referral program redesign", "SEO/content strategy", "Partnership development"], "stakeholders": ["CMO", "CFO", "VP Growth", "Analytics"], "budget": "$2M for optimization", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'marketing', 'finance', 'efficiency', 'growth'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000019', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Increase Average Revenue Per Ride by 15%',
'Grow average revenue per ride from $18.50 to $21.30 by Q4 2026 through product enhancements, service tier optimization, and value-added offerings. This will be achieved without compromising rider satisfaction (maintain NPS >70) through: introducing premium vehicle options (SUV, luxury), implementing dynamic pricing 2.0 with better demand prediction, offering in-ride commerce (food delivery pickup, package delivery), adding scheduled ride premium, and creating ride bundles/packages. Additionally, focus on increasing ride distance through better matching and reducing discount dependency from 35% of rides to <20%.',
'ACTIVE', 2,
'{"owner": "VP Revenue", "target_date": "2026-12-31", "success_metrics": ["$21.30 avg revenue per ride", "15% revenue increase", "NPS >70 maintained", "<20% rides with discounts"], "dependencies": ["Premium vehicle program", "Dynamic pricing v2", "In-ride commerce platform"], "stakeholders": ["VP Revenue", "Product", "Operations", "Finance"], "budget": "$5M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'revenue', 'pricing', 'product', 'strategy'],
NOW(), NOW()),

-- Customer Experience Objectives
('d1e1f1a1-0001-4001-a001-000000000020', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Achieve Net Promoter Score of 75+',
'Improve rider Net Promoter Score from current 68 to 75+ by Q3 2026, placing SwiftRide in top quartile of ride-sharing services globally. NPS improvement driven by: reducing average pickup time (<3 min), improving driver quality (95% 4.5+ star rating), enhancing app experience (4.8+ app store rating), resolving support issues faster (<4 hour average resolution), and reducing ride cancellations (<2% cancellation rate). Implementation includes comprehensive driver training program, app UX redesign, customer support team expansion, and proactive issue resolution. Each NPS point improvement correlates with 3% increase in rider retention.',
'ACTIVE', 2,
'{"owner": "Chief Customer Officer", "target_date": "2026-09-30", "success_metrics": ["NPS 75+", "4.8+ app rating", "<3 min pickup", "95% drivers rated 4.5+", "<4 hr support resolution"], "dependencies": ["Driver training program", "App redesign", "Support team expansion"], "stakeholders": ["CCO", "Product", "Operations", "Support"], "budget": "$6M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'customer-experience', 'satisfaction', 'quality', 'retention'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000021', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Reduce Support Ticket Volume by 50%',
'Decrease monthly support ticket volume from 250,000 to 125,000 by Q4 2026 through proactive issue prevention, self-service improvements, and product quality enhancements. Root cause analysis shows top ticket drivers: payment issues (22%), trip fare disputes (18%), driver no-shows (15%), app technical issues (12%), account access (10%), other (23%). Solutions include: automated payment issue resolution, transparent pricing calculator in-app, driver accountability system with auto-compensation for no-shows, bug reduction through improved testing, and enhanced FAQ/help center. Cost savings from reduced support staff needs: $8M annually.',
'ACTIVE', 2,
'{"owner": "VP Customer Support", "target_date": "2026-12-31", "success_metrics": ["125K monthly tickets", "50% volume reduction", "80% self-service resolution", "$8M cost savings"], "dependencies": ["Self-service tools", "Payment automation", "App quality improvements"], "stakeholders": ["VP Support", "Product", "Engineering", "Finance"], "budget": "$4M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'customer-support', 'efficiency', 'operations', 'cost-reduction'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000022', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Launch Accessibility Features for All Riders',
'Develop and launch comprehensive accessibility features making SwiftRide usable for riders with disabilities, targeting full ADA compliance and 50,000 monthly rides for riders using accessibility features by Q4 2026. Features include: wheelchair-accessible vehicle option in all major markets (minimum 10% of fleet), screen reader optimization for vision-impaired riders, hearing assistance integration, cognitive accessibility improvements, and service animal accommodation. Additionally, implement driver training for accessibility needs, priority matching for accessibility rides, and partnership with disability advocacy organizations. This initiative addresses 61M Americans with disabilities.',
'ACTIVE', 1,
'{"owner": "VP Product", "target_date": "2026-12-31", "success_metrics": ["Full ADA compliance", "10% wheelchair-accessible fleet", "50K monthly accessibility rides", "4.5+ star accessibility rating"], "dependencies": ["WAV driver recruitment", "App accessibility audit", "Training program"], "stakeholders": ["VP Product", "Legal", "Operations", "Advocacy Groups"], "budget": "$7M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'accessibility', 'compliance', 'social-responsibility', 'product'],
NOW(), NOW()),

-- Technology & Innovation Objectives
('d1e1f1a1-0001-4001-a001-000000000023', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Deploy AI-Powered Demand Prediction System',
'Implement machine learning-based demand prediction system achieving 90%+ accuracy in forecasting rider demand 15-30 minutes ahead across all markets by Q2 2026. This system will enable: proactive driver positioning reducing pickup time by 25%, dynamic pricing optimization increasing revenue by 12%, surge prevention through better supply distribution, and improved driver earnings through high-demand area recommendations. Technical requirements include: processing 50M+ location data points daily, real-time inference <50ms, integration with external data (weather, events, traffic), and automated retraining pipeline. Expected annual revenue impact: $45M.',
'ACTIVE', 1,
'{"owner": "VP Data Science", "target_date": "2026-06-30", "success_metrics": ["90% prediction accuracy", "25% pickup time reduction", "12% revenue increase", "<50ms inference time"], "dependencies": ["ML infrastructure", "Data pipeline", "Integration with matching system"], "stakeholders": ["VP Data Science", "CTO", "Operations", "Product"], "budget": "$10M", "risk_level": "HIGH"}'::jsonb,
ARRAY['business', 'technology', 'ai-ml', 'innovation', 'operations'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000024', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Implement Real-Time Fraud Detection',
'Deploy comprehensive fraud detection and prevention system reducing fraudulent transactions by 90% and preventing $20M in annual fraud losses by Q3 2026. Current fraud categories: stolen payment methods (35%), fake driver accounts (25%), promo code abuse (20%), rider collusion (10%), GPS spoofing (10%). Solution includes: ML-based transaction risk scoring (<100ms evaluation), biometric driver verification, device fingerprinting, network analysis for collusion detection, and automated account suspension workflows. System will process 10M+ daily transactions with <0.1% false positive rate to avoid legitimate user friction.',
'ACTIVE', 1,
'{"owner": "VP Risk & Compliance", "target_date": "2026-09-30", "success_metrics": ["90% fraud reduction", "$20M loss prevention", "<0.1% false positives", "<100ms transaction scoring"], "dependencies": ["ML fraud models", "Biometric verification", "Risk decisioning engine"], "stakeholders": ["VP Risk", "CTO", "Finance", "Legal"], "budget": "$6M", "risk_level": "HIGH"}'::jsonb,
ARRAY['business', 'technology', 'security', 'fraud-prevention', 'risk'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000025', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Launch Driver Mobile App 3.0',
'Release next-generation driver mobile app with redesigned UX, offline capabilities, and advanced earnings tools by Q2 2026, achieving 4.7+ app store rating and 85%+ driver adoption within 90 days. Key features include: offline mode for core functions in low-connectivity areas, real-time earnings tracker with hourly/daily/weekly views, intelligent route recommendations, in-app training modules, voice-activated controls for hands-free operation, and battery optimization extending device usage by 40%. App must support iOS 14+ and Android 10+ with <50MB download size and <2 second cold start time.',
'ACTIVE', 2,
'{"owner": "VP Engineering", "target_date": "2026-06-30", "success_metrics": ["4.7+ app rating", "85% adoption in 90 days", "40% battery improvement", "<2s cold start"], "dependencies": ["Mobile team scaling", "UX research", "Offline sync architecture"], "stakeholders": ["VP Engineering", "Product", "Driver Experience", "Design"], "budget": "$8M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'technology', 'mobile', 'driver-experience', 'product'],
NOW(), NOW()),

-- Safety & Security Objectives
('d1e1f1a1-0001-4001-a001-000000000026', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Achieve Zero Critical Safety Incidents',
'Establish industry-leading safety record with zero critical safety incidents (fatalities, serious injuries from preventable causes) across platform by implementing comprehensive safety program throughout 2026. Multi-layered approach includes: enhanced driver background checks (annual re-screening), continuous motor vehicle record monitoring, in-app safety features (emergency button, trip sharing, route verification), driver fatigue detection and prevention, safety training certification, insurance verification, and 24/7 safety response team. Success metrics include incident rate <0.5 per million rides, 100% driver safety certification, and <2 minute emergency response time.',
'ACTIVE', 1,
'{"owner": "VP Safety", "target_date": "2026-12-31", "success_metrics": ["Zero critical incidents", "<0.5 incidents per million rides", "100% driver certification", "<2 min emergency response"], "dependencies": ["Background check system", "Safety features development", "Response team"], "stakeholders": ["VP Safety", "Legal", "Operations", "Product"], "budget": "$15M", "risk_level": "CRITICAL"}'::jsonb,
ARRAY['business', 'safety', 'security', 'compliance', 'risk'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000027', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Implement Advanced Driver Verification System',
'Deploy multi-factor driver identity verification system preventing fraudulent driver accounts and ensuring only approved drivers provide rides, targeting 99.95% verification accuracy by Q3 2026. System combines: government ID verification with liveness detection, facial recognition matching (photo to real-time), biometric authentication before each shift, random selfie checks during shifts, vehicle photo verification, background check integration, and anomaly detection for account sharing. This addresses critical safety and regulatory requirements while reducing identity fraud by 95%. Implementation includes mobile SDK integration and backend verification infrastructure.',
'ACTIVE', 1,
'{"owner": "VP Trust & Safety", "target_date": "2026-09-30", "success_metrics": ["99.95% verification accuracy", "95% fraud reduction", "100% driver biometric enrollment", "<10s verification time"], "dependencies": ["Biometric SDK", "ID verification service", "Facial recognition system"], "stakeholders": ["VP Trust & Safety", "Engineering", "Legal", "Operations"], "budget": "$5M", "risk_level": "HIGH"}'::jsonb,
ARRAY['business', 'security', 'verification', 'trust-safety', 'compliance'],
NOW(), NOW()),

-- Partnership & Ecosystem Objectives
('d1e1f1a1-0001-4001-a001-000000000028', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Establish Strategic Partnerships with 100 Major Venues',
'Build dedicated venue partnership program covering 100 major airports, stadiums, convention centers, and entertainment venues by Q4 2026, generating incremental 200K+ rides monthly. Partnership benefits include: dedicated pickup zones with preferential positioning, venue-specific promotions, co-marketing opportunities, employee commute programs, and event-based surge pricing collaboration. Target venues: 25 major airports, 30 sports stadiums, 20 convention centers, 15 universities, 10 theme parks. Each partnership projected to generate $500K-$2M annual revenue. Program includes venue relationship management team and dedicated venue integration features in driver/rider apps.',
'ACTIVE', 2,
'{"owner": "VP Partnerships", "target_date": "2026-12-31", "success_metrics": ["100 venue partnerships", "200K monthly incremental rides", "$75M annual partnership revenue", "95% partnership renewal"], "dependencies": ["Partnership team", "Venue integration features", "Dedicated pickup zones"], "stakeholders": ["VP Partnerships", "Business Development", "Product", "Operations"], "budget": "$4M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'partnerships', 'b2b', 'revenue', 'growth'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000029', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Launch White-Label Platform for Regional Operators',
'Develop and launch white-label ride-sharing platform enabling regional transportation companies to operate branded services powered by SwiftRide technology, targeting 20 white-label partners by Q4 2026. Platform includes: fully customizable mobile apps (iOS/Android), driver management system, dispatch and routing technology, payment processing, customer support tools, analytics dashboard, and API integrations. Revenue model: $50K implementation fee + $0.25 per ride platform fee. Target markets: municipal transit authorities, taxi cooperatives, corporate campuses, and resort destinations. Projected annual recurring revenue: $15M at 20 partners processing 5M rides monthly.',
'ACTIVE', 2,
'{"owner": "VP Platform Services", "target_date": "2026-12-31", "success_metrics": ["20 white-label partners", "5M monthly white-label rides", "$15M ARR", "95% platform uptime"], "dependencies": ["White-label platform development", "Partner success team", "Multi-tenant architecture"], "stakeholders": ["VP Platform", "CTO", "Business Development", "Finance"], "budget": "$12M", "risk_level": "HIGH"}'::jsonb,
ARRAY['business', 'platform', 'b2b', 'technology', 'revenue-diversification'],
NOW(), NOW()),

('d1e1f1a1-0001-4001-a001-000000000030', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'business_objective',
'Integrate with 50 Travel & Hospitality Platforms',
'Establish deep integrations with 50 major travel booking platforms, hotel chains, airline apps, and destination apps by Q3 2026, enabling seamless ride booking as part of travel experiences and generating 15% rider growth from integrated channels. Integrations include: flight tracking for airport pickups, hotel checkout ride booking, restaurant reservation transportation, event ticketing ride bundling, and travel itinerary synchronization. Technical implementation via REST APIs, OAuth authentication, webhook notifications, and white-label booking widgets. Revenue sharing: 5-10% commission to partners. Target 500K monthly bookings through integrated channels.',
'ACTIVE', 2,
'{"owner": "VP Business Development", "target_date": "2026-09-30", "success_metrics": ["50 platform integrations", "500K monthly integrated bookings", "15% rider growth from channels", "$8M incremental revenue"], "dependencies": ["Integration API development", "Partner SDK", "Revenue sharing system"], "stakeholders": ["VP BD", "Product", "Engineering", "Finance"], "budget": "$5M", "risk_level": "MEDIUM"}'::jsonb,
ARRAY['business', 'partnerships', 'integrations', 'growth', 'distribution'],
NOW(), NOW());
