-- KPI Batch 2 (Items 21-60) - 40 additional KPIs

INSERT INTO tracertm.items (id, project_id, type, title, description, status, priority, metadata, tags, created_at, updated_at)
VALUES

-- Driver Metrics
('e1e1f1a1-0002-4002-a002-000000000021', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Driver Earnings Per Hour',
'Measures average driver earnings per active hour on the platform, critical metric for driver satisfaction and retention. Formula: (Total driver payouts + tips) / Total active hours. Active hours defined as time from first ride acceptance to last ride completion in a session. Target: $25/hour minimum across all markets to remain competitive. Current performance: $22.50/hour overall, varies by market ($18 in small cities to $28 in major metros). Tracking frequency: Real-time dashboard, weekly trending, monthly market comparison. Below $20/hour triggers driver incentive programs and demand generation campaigns.',
'ACTIVE', 1,
'{"current_value": 22.50, "target_value": 25.00, "unit": "$/hour", "formula": "(Total Payouts + Tips) / Active Hours", "tracking_frequency": "Real-time", "data_source": "Payments DB, Driver Sessions", "thresholds": {"red": "<$20", "yellow": "$20-$23", "green": ">$23"}, "trend": "increasing", "owner": "VP Operations", "related_objectives": ["Reduce Driver Churn to Below 12%"]}'::jsonb,
ARRAY['kpi', 'driver', 'earnings', 'operations', 'financial'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000022', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Driver Utilization Rate',
'Percentage of time drivers are actively transporting riders versus total time online. Formula: (Time on trip / Time online) × 100. Higher utilization = better driver earnings and platform efficiency. Target: 55% utilization (industry best-in-class 60%, average 45%). Current: 48%. Key drivers: match efficiency, demand density, driver positioning. Tracking: Real-time by market/time/driver segment. Improvement strategies: predictive positioning, hotspot recommendations, reduced wait times between rides. Critical for driver satisfaction (directly impacts $/hour) and operational efficiency.',
'ACTIVE', 1,
'{"current_value": 48.0, "target_value": 55.0, "unit": "%", "formula": "(Time on Trip / Time Online) × 100", "tracking_frequency": "Real-time", "data_source": "Driver Activity Logs", "thresholds": {"red": "<40%", "yellow": "40-50%", "green": ">50%"}, "trend": "increasing", "owner": "VP Operations", "benchmarks": {"industry_average": 45, "best_in_class": 60}}'::jsonb,
ARRAY['kpi', 'driver', 'utilization', 'efficiency', 'operations'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000023', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Driver Monthly Active Retention',
'Percentage of active drivers in month M who remain active in month M+1. Formula: (Active drivers in both M and M+1) / (Active drivers in M) × 100. Active defined as completing ≥4 rides per month. Target: 88% monthly retention. Current: 82%. Primary churn reasons: insufficient earnings (40%), flexibility of gig economy (25%), vehicle issues (15%), platform issues (10%), other (10%). High-value driver segment (>40 rides/month) retention: 94%. Tracking: Monthly cohort analysis. Retention improvements: earnings guarantees, rewards programs, vehicle maintenance support.',
'ACTIVE', 1,
'{"current_value": 82.0, "target_value": 88.0, "unit": "%", "formula": "(Drivers Active in M and M+1) / (Drivers Active in M) × 100", "tracking_frequency": "Monthly", "data_source": "Driver Activity DB", "thresholds": {"red": "<75%", "yellow": "75-85%", "green": ">85%"}, "segment_performance": {"high_value": 94, "medium_value": 84, "low_value": 65}, "owner": "VP Driver Experience"}'::jsonb,
ARRAY['kpi', 'driver', 'retention', 'churn', 'operations'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000024', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Driver Acceptance Rate',
'Percentage of ride requests accepted by drivers. Formula: (Accepted requests / Total requests sent to drivers) × 100. Target: 90% acceptance (indicates sufficient driver supply, attractive ride economics). Current: 85%. Low acceptance causes: unprofitable rides (long pickup distance, low fare), undesirable destinations, driver availability misclassification. Tracking: Real-time, segmented by driver tier, time of day, location. Impacts rider wait time and match efficiency. Minimum 80% to maintain service levels. Premium driver segment: 95% acceptance.',
'ACTIVE', 2,
'{"current_value": 85.0, "target_value": 90.0, "unit": "%", "formula": "(Accepted Requests / Total Sent Requests) × 100", "tracking_frequency": "Real-time", "data_source": "Matching System", "thresholds": {"red": "<80%", "yellow": "80-88%", "green": ">88%"}, "decline_reasons": {"long_pickup": 35, "low_fare": 30, "bad_destination": 20, "other": 15}, "owner": "VP Operations"}'::jsonb,
ARRAY['kpi', 'driver', 'acceptance', 'matching', 'supply'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000025', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Driver Cancellation Rate',
'Percentage of accepted rides that drivers cancel before pickup. Formula: (Driver cancellations / Accepted rides) × 100. Target: <2% cancellation. Current: 3.2%. Cancellation reasons: rider location issues (30%), better ride opportunity (25%), traffic/routing (20%), rider communication issues (15%), other (10%). High cancellation rates harm rider experience and increase costs. Driver penalties: <95% completion rate = temporary deactivation. Premium drivers: <1% cancellation. Tracking: Real-time with automatic penalties.',
'ACTIVE', 1,
'{"current_value": 3.2, "target_value": 2.0, "unit": "%", "formula": "(Driver Cancellations / Accepted Rides) × 100", "tracking_frequency": "Real-time", "data_source": "Ride Records", "thresholds": {"red": ">5%", "yellow": "2-5%", "green": "<2%"}, "cancellation_reasons": {"location_issues": 30, "better_ride": 25, "traffic": 20, "communication": 15, "other": 10}, "owner": "VP Operations", "penalties": "Completion rate <95% = deactivation"}'::jsonb,
ARRAY['kpi', 'driver', 'cancellation', 'reliability', 'quality'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000026', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Driver Rating Average',
'Average star rating (1-5 scale) given to drivers by riders. Formula: Sum(all driver ratings) / Count(ratings). Target: ≥4.85 platform average. Current: 4.82. Drivers below 4.6 receive coaching; below 4.4 for 30 days = deactivation. Rating distribution: 5-star (70%), 4-star (20%), 3-star (7%), <3-star (3%). Premium tier drivers average 4.92. Tracking: Real-time per driver, aggregated daily. Key drivers of rating: vehicle cleanliness, driving safety, route efficiency, friendliness. Rating included in match priority algorithm.',
'ACTIVE', 1,
'{"current_value": 4.82, "target_value": 4.85, "unit": "stars (1-5)", "formula": "AVG(all driver ratings)", "tracking_frequency": "Real-time", "data_source": "Rating System", "thresholds": {"red": "<4.6", "yellow": "4.6-4.8", "green": ">4.8"}, "distribution": {"5_star": 70, "4_star": 20, "3_star": 7, "below_3": 3}, "premium_tier": 4.92, "owner": "VP Quality"}'::jsonb,
ARRAY['kpi', 'driver', 'quality', 'rating', 'satisfaction'],
NOW(), NOW()),

-- Rider Metrics
('e1e1f1a1-0002-4002-a002-000000000027', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Rider Acquisition Cost (CAC)',
'Average cost to acquire one new rider. Formula: Total marketing & sales expenses / New riders acquired. Target: $25 CAC. Current: $42. Includes paid advertising, referral incentives, partnerships, promotions. CAC varies by channel: organic ($8), referrals ($15), paid social ($38), paid search ($52), outdoor/TV ($75). Tracking: Weekly by channel. LTV:CAC ratio target 6:1 (current 4.3:1). Optimization focus: increase organic and referral percentages. High-value rider CAC acceptable up to $60 if predicted LTV >$400.',
'ACTIVE', 1,
'{"current_value": 42.0, "target_value": 25.0, "unit": "$", "formula": "Marketing Expenses / New Riders", "tracking_frequency": "Weekly", "data_source": "Marketing Analytics", "thresholds": {"red": ">$50", "yellow": "$35-$50", "green": "<$35"}, "by_channel": {"organic": 8, "referral": 15, "paid_social": 38, "paid_search": 52, "traditional": 75}, "ltv_cac_ratio": 4.3, "target_ratio": 6.0, "owner": "CMO"}'::jsonb,
ARRAY['kpi', 'marketing', 'acquisition', 'financial', 'rider'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000028', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Rider Retention Rate (30-Day)',
'Percentage of riders who take another ride within 30 days of their first ride. Formula: (Riders with 2+ rides in 30 days / New riders) × 100. Target: 40% 30-day retention. Current: 32%. Retention critical for positive unit economics (CAC payback requires 4+ rides). Retention drivers: ride quality (4.5+ rating = 55% retention), pricing satisfaction, pickup speed, first-ride experience. Cohort analysis by acquisition channel shows referrals highest retention (48%) vs paid ads (28%). Tracking: Daily cohort monitoring.',
'ACTIVE', 1,
'{"current_value": 32.0, "target_value": 40.0, "unit": "%", "formula": "(Riders with 2+ rides in 30d / New Riders) × 100", "tracking_frequency": "Daily", "data_source": "Ride Analytics", "thresholds": {"red": "<25%", "yellow": "25-35%", "green": ">35%"}, "by_channel": {"referral": 48, "organic": 42, "paid_social": 30, "paid_search": 28}, "drivers": "Ride quality, pricing, speed", "owner": "VP Growth"}'::jsonb,
ARRAY['kpi', 'rider', 'retention', 'growth', 'engagement'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000029', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Rider Lifetime Value (LTV)',
'Predicted total net revenue from a rider over their lifetime. Formula: (Average revenue per ride × Rides per year × Average customer lifespan) - CAC. Target: $250 LTV. Current: $180. Components: rides per year (avg 28, target 40), revenue per ride ($18.50), lifespan (2.3 years, target 3.5 years), retention rate (60% year-over-year). High-value segment (business travelers): $520 LTV. Tracking: Quarterly cohort analysis with predictive models. LTV improvement strategies: loyalty program, subscription, ride frequency campaigns.',
'ACTIVE', 1,
'{"current_value": 180.0, "target_value": 250.0, "unit": "$", "formula": "(Revenue/Ride × Rides/Year × Lifespan) - CAC", "tracking_frequency": "Quarterly", "data_source": "Financial Analytics", "components": {"rides_per_year": 28, "revenue_per_ride": 18.50, "lifespan_years": 2.3, "retention_rate": 60}, "segments": {"high_value": 520, "medium_value": 180, "low_value": 85}, "owner": "CFO"}'::jsonb,
ARRAY['kpi', 'rider', 'ltv', 'financial', 'value'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000030', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Rider Cancellation Rate',
'Percentage of requested rides cancelled by riders before driver arrival. Formula: (Rider cancellations / Total ride requests) × 100. Target: <5% cancellation. Current: 7.2%. Cancellation reasons: long wait time (45%), price shock (25%), changed plans (15%), driver rating concerns (10%), other (5%). Cancellations after driver dispatched incur $5 fee (after 2 min grace period). High cancellation rates indicate poor ETA estimation or pricing transparency. Tracking: Real-time with automated alerts >10%.',
'ACTIVE', 2,
'{"current_value": 7.2, "target_value": 5.0, "unit": "%", "formula": "(Rider Cancellations / Total Requests) × 100", "tracking_frequency": "Real-time", "data_source": "Ride Records", "thresholds": {"red": ">10%", "yellow": "5-10%", "green": "<5%"}, "cancellation_reasons": {"long_wait": 45, "price": 25, "changed_plans": 15, "driver_concerns": 10, "other": 5}, "cancellation_fee": "$5 after 2min", "owner": "VP Product"}'::jsonb,
ARRAY['kpi', 'rider', 'cancellation', 'experience', 'pricing'],
NOW(), NOW()),

-- Financial Metrics
('e1e1f1a1-0002-4002-a002-000000000031', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Gross Merchandise Value (GMV)',
'Total dollar value of all rides completed on the platform before fees. Formula: Sum(Ride base fare + Distance charge + Time charge + Surge + Tips). Target: $1.2B annually ($100M monthly). Current: $900M annually ($75M monthly), growing 25% YoY. GMV is top-line growth indicator but not revenue (take rate averages 25%). Tracking: Real-time, daily rollup, monthly/quarterly reporting. Segmentation: market, service tier, rider type. GMV per active rider target: $450 annually (current $360).',
'ACTIVE', 1,
'{"current_value": 75000000, "target_value": 100000000, "unit": "$ monthly", "formula": "Sum(all ride charges)", "tracking_frequency": "Real-time", "data_source": "Payments DB", "annual_current": 900000000, "annual_target": 1200000000, "yoy_growth": 25, "take_rate": 25, "gmv_per_rider": 360, "owner": "CFO"}'::jsonb,
ARRAY['kpi', 'financial', 'gmv', 'revenue', 'growth'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000032', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Take Rate',
'Percentage of GMV retained as platform revenue. Formula: (Platform revenue / GMV) × 100. Target: 26% blended take rate. Current: 25%. Breakdown: base commission (20%), service fee (3%), booking fee ($2.50 flat), surge markup (2% avg). Varies by service: standard rides (24%), premium (30%), subscription discounted (18%), enterprise (22%). Higher take rate improves unit economics but must balance driver earnings. Tracking: Daily by service type and market. Top quartile markets achieve 28% through optimization.',
'ACTIVE', 1,
'{"current_value": 25.0, "target_value": 26.0, "unit": "%", "formula": "(Platform Revenue / GMV) × 100", "tracking_frequency": "Daily", "data_source": "Financial Analytics", "breakdown": {"base_commission": 20, "service_fee": 3, "booking_fee": 2, "surge": 2}, "by_service": {"standard": 24, "premium": 30, "subscription": 18, "enterprise": 22}, "owner": "CFO"}'::jsonb,
ARRAY['kpi', 'financial', 'revenue', 'take-rate', 'margin'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000033', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Contribution Margin',
'Profit margin after variable costs (driver payments, payment processing, insurance per ride). Formula: (Revenue - Variable costs) / Revenue × 100. Target: 45% contribution margin. Current: 38%. Variable costs breakdown: driver payout (75% of rider charge), payment processing (2.5%), insurance (3%), other (1.5%). Contribution margin funds fixed costs (technology, marketing, overhead). Positive contribution margin required for path to profitability. Premium tier achieves 52% margin. Tracking: Real-time per ride type.',
'ACTIVE', 1,
'{"current_value": 38.0, "target_value": 45.0, "unit": "%", "formula": "(Revenue - Variable Costs) / Revenue × 100", "tracking_frequency": "Real-time", "data_source": "Financial Analytics", "cost_breakdown": {"driver_payout": 75, "payment_processing": 2.5, "insurance": 3, "other": 1.5}, "by_tier": {"standard": 38, "premium": 52, "subscription": 28}, "owner": "CFO"}'::jsonb,
ARRAY['kpi', 'financial', 'margin', 'profitability', 'unit-economics'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000034', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Monthly Burn Rate',
'Net cash consumed per month before financing activities. Formula: Operating expenses - Operating revenue. Target: $8M monthly burn (path to breakeven). Current: $15M monthly burn. Burn funds growth investments: marketing ($5M), engineering ($4M), operations ($3M), G&A ($3M). Runway at current burn: 18 months with $270M cash. Burn rate reduction strategies: improve take rate, reduce CAC, increase operational efficiency. Break-even target: Q3 2027. Tracking: Monthly with board reporting.',
'ACTIVE', 1,
'{"current_value": 15000000, "target_value": 8000000, "unit": "$ monthly", "formula": "Operating Expenses - Operating Revenue", "tracking_frequency": "Monthly", "data_source": "Finance", "burn_breakdown": {"marketing": 5000000, "engineering": 4000000, "operations": 3000000, "gna": 3000000}, "cash_position": 270000000, "runway_months": 18, "breakeven_target": "Q3 2027", "owner": "CFO"}'::jsonb,
ARRAY['kpi', 'financial', 'burn-rate', 'cash', 'runway'],
NOW(), NOW()),

-- Operational Metrics
('e1e1f1a1-0002-4002-a002-000000000035', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Average Pickup Time (ETA)',
'Average time from ride request to driver arrival at pickup location. Formula: AVG(Driver arrival time - Request time). Target: <3 minutes. Current: 4.5 minutes. Pickup time most important factor for rider satisfaction (correlation 0.85 with NPS). Variation by market: urban core (3.2 min), suburban (5.8 min), rural (8.5 min). Peak hour vs off-peak: 5.2 min vs 3.8 min. Improvement strategies: predictive positioning, supply optimization, demand smoothing. Tracking: Real-time per ride, market aggregation.',
'ACTIVE', 1,
'{"current_value": 4.5, "target_value": 3.0, "unit": "minutes", "formula": "AVG(arrival_time - request_time)", "tracking_frequency": "Real-time", "data_source": "Matching System", "thresholds": {"red": ">6min", "yellow": "4-6min", "green": "<4min"}, "by_area": {"urban": 3.2, "suburban": 5.8, "rural": 8.5}, "by_time": {"peak": 5.2, "off_peak": 3.8}, "nps_correlation": 0.85, "owner": "VP Operations"}'::jsonb,
ARRAY['kpi', 'operations', 'pickup-time', 'eta', 'experience'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000036', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Surge Pricing Frequency',
'Percentage of rides with surge pricing applied. Formula: (Rides with surge / Total rides) × 100. Target: <15% of rides (minimize surge while maintaining supply). Current: 22%. Surge triggers when demand exceeds supply by 20%+. Surge multiplier: 1.2x - 3.0x (capped). High surge frequency indicates supply issues or poor demand prediction. Surge revenue represents 8% of total GMV but causes rider dissatisfaction (NPS -12 points during surge). Tracking: Real-time with automated supply incentives when surge threshold reached.',
'ACTIVE', 2,
'{"current_value": 22.0, "target_value": 15.0, "unit": "% of rides", "formula": "(Surged Rides / Total Rides) × 100", "tracking_frequency": "Real-time", "data_source": "Pricing Engine", "surge_range": "1.2x - 3.0x", "surge_trigger": "Demand > Supply by 20%", "revenue_contribution": 8, "nps_impact": -12, "owner": "VP Operations"}'::jsonb,
ARRAY['kpi', 'operations', 'surge', 'pricing', 'supply-demand'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000037', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Ride Completion Rate',
'Percentage of requested rides that complete successfully. Formula: (Completed rides / Total ride requests) × 100. Target: >92% completion. Current: 88%. Incomplete reasons: rider cancellation (7.2%), driver cancellation (3.2%), no driver available (1.2%), technical issues (0.4%). Completion rate varies by time: late night (82%), rush hour (90%), midday (91%). Premium service: 96% completion. Tracking: Real-time with automated interventions for low-supply conditions. Critical metric for service reliability.',
'ACTIVE', 1,
'{"current_value": 88.0, "target_value": 92.0, "unit": "%", "formula": "(Completed Rides / Total Requests) × 100", "tracking_frequency": "Real-time", "data_source": "Ride Records", "incomplete_reasons": {"rider_cancel": 7.2, "driver_cancel": 3.2, "no_driver": 1.2, "technical": 0.4}, "by_time": {"late_night": 82, "rush_hour": 90, "midday": 91}, "premium": 96, "owner": "VP Operations"}'::jsonb,
ARRAY['kpi', 'operations', 'completion', 'reliability', 'quality'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000038', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Platform Uptime',
'Percentage of time core platform services are operational. Formula: (Total time - Downtime) / Total time × 100. Target: 99.9% uptime (max 43.2 min downtime monthly). Current: 99.7% (130 min monthly downtime). Critical services: rider app, driver app, matching system, payment processing. Downtime cost: ~$50K per hour in lost GMV plus reputation damage. Incidents: planned maintenance (20%), infrastructure failures (40%), code deployments (25%), third-party dependencies (15%). Tracking: Real-time monitoring with PagerDuty alerts.',
'ACTIVE', 1,
'{"current_value": 99.7, "target_value": 99.9, "unit": "%", "formula": "(Uptime / Total Time) × 100", "tracking_frequency": "Real-time", "data_source": "Monitoring Systems", "monthly_downtime_current": 130, "monthly_downtime_target": 43.2, "downtime_cost_per_hour": 50000, "incident_causes": {"infrastructure": 40, "deployments": 25, "planned": 20, "third_party": 15}, "owner": "CTO"}'::jsonb,
ARRAY['kpi', 'technology', 'uptime', 'reliability', 'infrastructure'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000039', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Fraudulent Transaction Rate',
'Percentage of transactions flagged as fraudulent. Formula: (Fraudulent transactions / Total transactions) × 100. Target: <0.3%. Current: 0.8%. Fraud types: stolen payment methods (45%), promo abuse (30%), driver-rider collusion (15%), GPS spoofing (10%). Current annual fraud loss: $7.2M (0.8% of GMV). Fraud detection: ML models (92% accuracy), manual review for edge cases. False positive rate: 0.5% (flagged but legitimate). Tracking: Real-time transaction scoring with daily fraud review. Chargeback rate target: <0.4%.',
'ACTIVE', 1,
'{"current_value": 0.8, "target_value": 0.3, "unit": "%", "formula": "(Fraudulent Txns / Total Txns) × 100", "tracking_frequency": "Real-time", "data_source": "Fraud Detection System", "fraud_types": {"stolen_payment": 45, "promo_abuse": 30, "collusion": 15, "gps_spoofing": 10}, "annual_loss": 7200000, "detection_accuracy": 92, "false_positive_rate": 0.5, "owner": "VP Risk"}'::jsonb,
ARRAY['kpi', 'security', 'fraud', 'risk', 'financial'],
NOW(), NOW()),

-- Customer Experience Metrics
('e1e1f1a1-0002-4002-a002-000000000040', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Net Promoter Score (NPS)',
'Measures rider likelihood to recommend SwiftRide. Formula: % Promoters (9-10) - % Detractors (0-6). Target: 75 NPS. Current: 68 NPS. Distribution: Promoters 58%, Passives 27%, Detractors 15%. NPS drivers: pickup speed (weight 30%), ride quality (25%), pricing fairness (20%), app experience (15%), customer service (10%). Premium tier NPS: 82. Competitor benchmarks: Uber 71, Lyft 69. Survey: post-ride for 10% of riders. Tracking: Daily aggregation, monthly trending. NPS correlates strongly with organic growth and retention.',
'ACTIVE', 1,
'{"current_value": 68, "target_value": 75, "unit": "score (-100 to 100)", "formula": "% Promoters - % Detractors", "tracking_frequency": "Daily", "data_source": "Post-Ride Surveys", "distribution": {"promoters": 58, "passives": 27, "detractors": 15}, "drivers": {"pickup_speed": 30, "ride_quality": 25, "pricing": 20, "app_ux": 15, "support": 10}, "benchmarks": {"uber": 71, "lyft": 69}, "owner": "Chief Customer Officer"}'::jsonb,
ARRAY['kpi', 'customer-experience', 'nps', 'satisfaction', 'quality'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000041', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Customer Support Resolution Time',
'Average time to resolve customer support tickets. Formula: AVG(Resolution time - Ticket creation time). Target: <4 hours average resolution. Current: 6.5 hours. Resolution by priority: Critical (<1 hr target, 2 hrs actual), High (<4 hr target, 5 hrs actual), Medium (<24 hr target, 18 hrs actual), Low (<48 hr target, 36 hrs actual). Ticket volume: 250K monthly. First response time: 12 minutes (target <5 min). Resolution channels: automated (35%), chat (40%), email (20%), phone (5%). Tracking: Real-time ticketing system.',
'ACTIVE', 2,
'{"current_value": 6.5, "target_value": 4.0, "unit": "hours", "formula": "AVG(resolution_time - creation_time)", "tracking_frequency": "Real-time", "data_source": "Support Ticketing System", "by_priority": {"critical": {"target": 1, "actual": 2}, "high": {"target": 4, "actual": 5}, "medium": {"target": 24, "actual": 18}, "low": {"target": 48, "actual": 36}}, "monthly_volume": 250000, "first_response_time": 12, "owner": "VP Customer Support"}'::jsonb,
ARRAY['kpi', 'customer-support', 'resolution-time', 'service', 'quality'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000042', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'App Store Rating',
'Average star rating on iOS App Store and Google Play. Formula: AVG(all platform ratings). Target: 4.7+ on both platforms. Current: iOS 4.5, Android 4.4. Rating distribution critical for app discovery (4.5+ threshold for featuring). Ratings impact download conversion by 20-30%. Recent review themes: pickup time (30% of reviews), pricing (25%), driver quality (20%), app crashes (15%), other (10%). 1-star review response time <24 hours. Version-over-version tracking shows app quality improvements. Rating recovery campaign targeting 4.7 by Q3 2026.',
'ACTIVE', 1,
'{"current_value": 4.45, "target_value": 4.7, "unit": "stars (1-5)", "formula": "AVG(all app ratings)", "tracking_frequency": "Daily", "data_source": "App Store APIs", "by_platform": {"ios": 4.5, "android": 4.4}, "review_themes": {"pickup_time": 30, "pricing": 25, "driver_quality": 20, "app_issues": 15, "other": 10}, "conversion_impact": "20-30% on downloads", "owner": "VP Product"}'::jsonb,
ARRAY['kpi', 'product', 'app-rating', 'quality', 'mobile'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000043', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'First Ride Completion Rate',
'Percentage of new riders who successfully complete their first requested ride. Formula: (First rides completed / First ride requests) × 100. Target: 90%. Current: 78%. Drop-off points: app download but no account (5%), account created but no ride request (12%), request but payment fails (6%), request but no driver match (3%), matched but driver/rider cancel (6%). First ride critical for retention (completers have 3.5x higher LTV). Solutions: streamlined onboarding, payment validation, first-ride guarantee, live support. Tracking: Real-time funnel analysis.',
'ACTIVE', 1,
'{"current_value": 78.0, "target_value": 90.0, "unit": "%", "formula": "(First Rides Completed / First Ride Requests) × 100", "tracking_frequency": "Real-time", "data_source": "Onboarding Analytics", "drop_off_points": {"no_account": 5, "no_request": 12, "payment_fail": 6, "no_match": 3, "cancellation": 6}, "ltv_impact": "3.5x higher for completers", "owner": "VP Product"}'::jsonb,
ARRAY['kpi', 'onboarding', 'completion', 'retention', 'funnel'],
NOW(), NOW()),

-- Growth & Marketing Metrics
('e1e1f1a1-0002-4002-a002-000000000044', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Referral Conversion Rate',
'Percentage of referred users who complete their first ride. Formula: (Referred users who ride / Total referrals sent) × 100. Target: 25% conversion. Current: 18%. Referral program: Referrer gets $10 credit after referee completes first ride; referee gets $5 off first ride. Current referral volume: 50K monthly referrals generating 9K new riders (18% of total acquisition). Top referrers: 100+ referrals each. Conversion optimization: personalized referral messages, timing optimization, incentive testing. Goal: increase referrals to 35% of acquisition by improving conversion.',
'ACTIVE', 2,
'{"current_value": 18.0, "target_value": 25.0, "unit": "%", "formula": "(Referred Riders / Total Referrals) × 100", "tracking_frequency": "Daily", "data_source": "Referral System", "monthly_referrals": 50000, "monthly_new_riders": 9000, "incentives": {"referrer": "$10 credit", "referee": "$5 off"}, "acquisition_percentage": 18, "target_percentage": 35, "owner": "VP Growth"}'::jsonb,
ARRAY['kpi', 'growth', 'referral', 'acquisition', 'viral'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000045', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Monthly Active Riders (MAR)',
'Count of unique riders who completed at least one ride in the month. Formula: COUNT(DISTINCT rider_id with completed ride in month). Target: 3M MAR. Current: 2.5M MAR. Growth: 15% YoY, 2-3% MoM. MAR composition: heavy users (10+ rides) 12%, medium (4-9 rides) 28%, light (1-3 rides) 60%. Reactivation of dormant users (no ride in 90+ days) represents 8% of MAR. Seasonal variation: Summer peak (+15%), winter trough (-10%). MAR per market varies: Top market 800K, small markets 5K-20K. Tracking: Daily active riders also tracked.',
'ACTIVE', 1,
'{"current_value": 2500000, "target_value": 3000000, "unit": "riders", "formula": "COUNT(DISTINCT riders with ride in month)", "tracking_frequency": "Daily", "data_source": "Ride Analytics", "growth_yoy": 15, "growth_mom": 2.5, "composition": {"heavy": 12, "medium": 28, "light": 60}, "reactivation_rate": 8, "seasonal_variation": {"summer": 15, "winter": -10}, "owner": "VP Growth"}'::jsonb,
ARRAY['kpi', 'growth', 'riders', 'active-users', 'engagement'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000046', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Market Share by Geography',
'SwiftRide percentage of total ride-sharing rides in each market. Formula: SwiftRide rides / Total market rides × 100 (from industry data). Target: #2 position in all markets, #1 in 10+ markets. Current average market share: 18%. Leading markets: City A (32%), City B (28%). Lagging markets: City X (8%), City Y (5%). Primary competitors: Uber (62% average share), Lyft (20%). Market share tracking: Quarterly via third-party data, monthly estimates via surveying. Growth strategy: Focus on lagging markets with targeted campaigns.',
'ACTIVE', 2,
'{"current_value": 18.0, "target_value": 25.0, "unit": "% of market", "formula": "SwiftRide Rides / Total Market Rides × 100", "tracking_frequency": "Quarterly", "data_source": "Industry Reports + Surveys", "leader_markets": {"cityA": 32, "cityB": 28}, "lagging_markets": {"cityX": 8, "cityY": 5}, "competitors": {"uber": 62, "lyft": 20}, "owner": "VP Strategy"}'::jsonb,
ARRAY['kpi', 'market-share', 'competition', 'strategy', 'growth'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000047', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Brand Awareness (Unaided)',
'Percentage of target audience who name SwiftRide when asked about ride-sharing services (unaided recall). Formula: Respondents mentioning SwiftRide / Total respondents × 100. Target: 85% awareness in operating markets. Current: 68%. Top-of-mind awareness (first mention): 22%. Aided awareness (recognition when prompted): 92%. Awareness varies by market: Established (85%), New (<50%). Competitor awareness: Uber 94%, Lyft 89%. Awareness correlates with market share (+0.72 correlation). Tracking: Quarterly brand study (n=5000 nationally). Awareness campaigns targeting +5 points per quarter.',
'ACTIVE', 2,
'{"current_value": 68.0, "target_value": 85.0, "unit": "%", "formula": "SwiftRide mentions / Total respondents × 100", "tracking_frequency": "Quarterly", "data_source": "Brand Studies", "top_of_mind": 22, "aided_awareness": 92, "by_market": {"established": 85, "new": 45}, "competitors": {"uber": 94, "lyft": 89}, "market_share_correlation": 0.72, "owner": "CMO"}'::jsonb,
ARRAY['kpi', 'marketing', 'brand', 'awareness', 'perception'],
NOW(), NOW()),

-- Safety & Compliance Metrics
('e1e1f1a1-0002-4002-a002-000000000048', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Safety Incident Rate',
'Number of safety incidents per million rides. Formula: (Total safety incidents / Total rides) × 1,000,000. Target: <2 incidents per million rides. Current: 3.8 per million. Incident categories: Minor accidents (60%), Serious accidents (25%), Safety concerns (10%), Harassment (5%). Critical incidents (hospitalization/fatality): <0.1 per million (current 0.08). Industry average: 4-5 per million. Premium tier: <1 per million. Tracking: Real-time incident reporting, monthly safety review. Every incident investigated, patterns analyzed for prevention.',
'ACTIVE', 1,
'{"current_value": 3.8, "target_value": 2.0, "unit": "per million rides", "formula": "(Incidents / Rides) × 1,000,000", "tracking_frequency": "Real-time", "data_source": "Safety Incident System", "categories": {"minor_accidents": 60, "serious_accidents": 25, "safety_concerns": 10, "harassment": 5}, "critical_rate": 0.08, "industry_average": 4.5, "premium_tier": 0.9, "owner": "VP Safety"}'::jsonb,
ARRAY['kpi', 'safety', 'incidents', 'risk', 'compliance'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000049', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Driver Background Check Compliance',
'Percentage of active drivers with valid, up-to-date background checks. Formula: (Drivers with valid checks / Total active drivers) × 100. Target: 100% compliance. Current: 99.8% (50 drivers pending renewal). Background check components: Criminal records (federal, state, local), Sex offender registry, Motor vehicle records, SSN verification. Renewal frequency: Annual for all drivers. Processing time: 3-5 days average. Non-compliance results in immediate deactivation. Tracking: Real-time compliance dashboard with automated renewal reminders 30 days before expiration.',
'ACTIVE', 1,
'{"current_value": 99.8, "target_value": 100.0, "unit": "%", "formula": "(Valid Checks / Active Drivers) × 100", "tracking_frequency": "Real-time", "data_source": "Background Check System", "pending_renewals": 50, "check_components": ["Criminal", "Sex offender", "MVR", "SSN"], "renewal_frequency": "Annual", "processing_time_days": 4, "owner": "VP Trust & Safety"}'::jsonb,
ARRAY['kpi', 'compliance', 'safety', 'background-check', 'regulatory'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000050', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Insurance Claim Rate',
'Percentage of rides resulting in insurance claim. Formula: (Rides with claims / Total rides) × 100. Target: <0.15%. Current: 0.22%. Claim types: Vehicle damage (55%), Injury (25%), Property damage (15%), Other (5%). Average claim cost: $3,500. Total annual claim costs: $18M. Claim resolution time: 14 days average (target <10 days). Claims prevented through safety programs: Estimated 15% reduction from driver training, vehicle inspections, real-time safety monitoring. Tracking: Monthly claims analysis, quarterly actuarial review.',
'ACTIVE', 1,
'{"current_value": 0.22, "target_value": 0.15, "unit": "%", "formula": "(Rides with Claims / Total Rides) × 100", "tracking_frequency": "Monthly", "data_source": "Insurance System", "claim_types": {"vehicle_damage": 55, "injury": 25, "property_damage": 15, "other": 5}, "avg_claim_cost": 3500, "annual_cost": 18000000, "resolution_time_days": 14, "prevention_rate": 15, "owner": "VP Risk Management"}'::jsonb,
ARRAY['kpi', 'insurance', 'claims', 'risk', 'financial'],
NOW(), NOW()),

-- Technology & Product Metrics
('e1e1f1a1-0002-4002-a002-000000000051', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'App Crash Rate',
'Percentage of app sessions ending in crash. Formula: (Crashed sessions / Total sessions) × 100. Target: <0.5% crash rate. Current: 1.2%. Crash rate by platform: iOS 0.9%, Android 1.5%. Critical crash scenarios: During ride booking (30%), During active ride (25%), Payment processing (20%), App launch (15%), Other (10%). Crashes impact conversion (10% of users uninstall after crash), ratings (crashes mentioned in 15% of negative reviews). Tracking: Real-time crash analytics (Firebase/Crashlytics), daily developer review, weekly crash triage.',
'ACTIVE', 1,
'{"current_value": 1.2, "target_value": 0.5, "unit": "%", "formula": "(Crashed Sessions / Total Sessions) × 100", "tracking_frequency": "Real-time", "data_source": "Crash Analytics", "by_platform": {"ios": 0.9, "android": 1.5}, "crash_scenarios": {"booking": 30, "active_ride": 25, "payment": 20, "launch": 15, "other": 10}, "uninstall_rate": 10, "owner": "VP Engineering"}'::jsonb,
ARRAY['kpi', 'technology', 'mobile', 'quality', 'stability'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000052', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'API Response Time (P95)',
'95th percentile API response time for critical endpoints. Formula: 95th percentile of response times. Target: <200ms P95. Current: 350ms P95. Critical endpoints: Ride matching (<100ms target), Pricing calculation (<150ms), Payment processing (<300ms), Location updates (<50ms). Slow responses impact: User experience (perceived lag), Match efficiency (drivers move during slow match), Timeout errors (>5s = failure). Infrastructure: Multi-region deployment, CDN, database optimization, caching. Tracking: Real-time APM (Datadog), hourly aggregation, alerts at >500ms P95.',
'ACTIVE', 1,
'{"current_value": 350, "target_value": 200, "unit": "ms", "formula": "P95(all API response times)", "tracking_frequency": "Real-time", "data_source": "APM System", "by_endpoint": {"matching": {"target": 100, "actual": 180}, "pricing": {"target": 150, "actual": 220}, "payment": {"target": 300, "actual": 420}, "location": {"target": 50, "actual": 85}}, "timeout_threshold": 5000, "owner": "CTO"}'::jsonb,
ARRAY['kpi', 'technology', 'performance', 'api', 'latency'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000053', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Feature Adoption Rate',
'Percentage of users using newly launched features within 30 days. Formula: (Users using feature / Total active users) × 100. Target: >40% adoption for major features. Current average: 28%. Recent features: Scheduled rides (35% adoption), Ride sharing (22%), Favorites (45%), In-app chat (18%). Adoption drivers: Onboarding prompts (2x lift), In-app messaging (1.5x lift), Email campaigns (1.3x lift), Organic discovery (baseline). Low adoption indicates poor feature discovery or value proposition. Tracking: Daily feature usage analytics, cohort analysis, A/B testing of discovery mechanisms.',
'ACTIVE', 2,
'{"current_value": 28.0, "target_value": 40.0, "unit": "%", "formula": "(Feature Users / Total Users) × 100", "tracking_frequency": "Daily", "data_source": "Product Analytics", "recent_features": {"scheduled_rides": 35, "ride_sharing": 22, "favorites": 45, "in_app_chat": 18}, "adoption_drivers": {"onboarding": 2.0, "in_app_msg": 1.5, "email": 1.3, "organic": 1.0}, "owner": "VP Product"}'::jsonb,
ARRAY['kpi', 'product', 'adoption', 'features', 'engagement'],
NOW(), NOW()),

-- Enterprise & B2B Metrics
('e1e1f1a1-0002-4002-a002-000000000054', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Enterprise Contract Value (ACV)',
'Average annual contract value for enterprise B2B clients. Formula: Total B2B annual contract values / Number of B2B contracts. Target: $250K ACV. Current: $180K ACV. Enterprise clients: 85 active (target 200+). ACV by segment: Fortune 1000 ($400K avg), Healthcare ($220K), Universities ($150K), SMB ($80K). Contract terms: 1-3 year commitments, volume discounts (15-25% below retail), dedicated account management, custom billing/reporting. Total B2B ARR: $15.3M (current), target $50M. Tracking: Monthly sales pipeline, quarterly contract renewals.',
'ACTIVE', 2,
'{"current_value": 180000, "target_value": 250000, "unit": "$", "formula": "Total B2B Contract Value / Count(Contracts)", "tracking_frequency": "Monthly", "data_source": "Enterprise Sales CRM", "active_clients": 85, "target_clients": 200, "by_segment": {"fortune_1000": 400000, "healthcare": 220000, "universities": 150000, "smb": 80000}, "total_arr": 15300000, "target_arr": 50000000, "owner": "VP Enterprise Sales"}'::jsonb,
ARRAY['kpi', 'b2b', 'enterprise', 'revenue', 'contracts'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000055', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'B2B Customer Retention (ARR)',
'Percentage of B2B annual recurring revenue retained year-over-year. Formula: (Retained ARR / Prior year ARR) × 100. Target: 95% gross retention, 110% net retention (with expansion). Current: 88% gross, 102% net. Churn reasons: Budget cuts (35%), Competitor switch (30%), Went in-house (20%), Poor experience (15%). Expansion through: Additional employee seats, New departments, Premium features, Multi-location rollout. Average account grows 15% annually. Tracking: Quarterly business reviews, monthly usage monitoring for early churn signals.',
'ACTIVE', 1,
'{"current_value": 88.0, "target_value": 95.0, "unit": "% gross retention", "formula": "(Retained ARR / Prior Year ARR) × 100", "tracking_frequency": "Quarterly", "data_source": "Enterprise Analytics", "net_retention": 102, "net_target": 110, "churn_reasons": {"budget": 35, "competitor": 30, "in_house": 20, "experience": 15}, "expansion_rate": 15, "owner": "VP Enterprise Sales"}'::jsonb,
ARRAY['kpi', 'b2b', 'retention', 'revenue', 'expansion'],
NOW(), NOW()),

-- Environmental & Sustainability Metrics
('e1e1f1a1-0002-4002-a002-000000000056', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Carbon Emissions Per Ride',
'Average CO2 emissions per completed ride in kg. Formula: Total fleet emissions / Total rides. Target: <2.5kg CO2/ride. Current: 4.2kg/ride. Baseline gasoline vehicles: 5.8kg/ride. Reduction strategies: EV fleet transition (target 40% EVs, current 8%), Ride pooling/sharing (35% emission reduction), Route optimization (10% reduction), Carbon offsets (purchased for all rides). EV rides: 1.2kg CO2/ride. Hybrid: 3.1kg/ride. Tracking: Monthly emission calculations, quarterly sustainability reporting. Supports ESG goals and climate commitments (carbon neutral by 2030).',
'ACTIVE', 2,
'{"current_value": 4.2, "target_value": 2.5, "unit": "kg CO2 per ride", "formula": "Total Emissions / Total Rides", "tracking_frequency": "Monthly", "data_source": "Fleet Analytics", "baseline_gasoline": 5.8, "by_vehicle_type": {"ev": 1.2, "hybrid": 3.1, "gasoline": 5.8}, "fleet_composition": {"ev": 8, "hybrid": 22, "gasoline": 70}, "carbon_neutral_target": "2030", "owner": "VP Sustainability"}'::jsonb,
ARRAY['kpi', 'sustainability', 'environment', 'carbon', 'esg'],
NOW(), NOW()),

-- Payment & Billing Metrics
('e1e1f1a1-0002-4002-a002-000000000057', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Payment Success Rate',
'Percentage of payment transactions that complete successfully on first attempt. Formula: (Successful payments / Total payment attempts) × 100. Target: 97% success rate. Current: 94.5%. Failure reasons: Insufficient funds (40%), Expired card (25%), Fraud blocks (20%), Technical errors (10%), Other (5%). Failed payments result in: Ride cancellation if pre-auth, debt collection if post-ride. Payment retry logic: 2 automatic retries, alternative payment method prompt. Tracking: Real-time payment monitoring, daily reconciliation. Each 1% improvement = $2.5M additional revenue annually.',
'ACTIVE', 1,
'{"current_value": 94.5, "target_value": 97.0, "unit": "%", "formula": "(Successful Payments / Payment Attempts) × 100", "tracking_frequency": "Real-time", "data_source": "Payment Gateway", "failure_reasons": {"insufficient_funds": 40, "expired_card": 25, "fraud_block": 20, "technical": 10, "other": 5}, "retry_logic": "2 automatic retries", "revenue_impact_per_percent": 2500000, "owner": "VP Finance"}'::jsonb,
ARRAY['kpi', 'payments', 'financial', 'conversion', 'revenue'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000058', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Days Sales Outstanding (DSO)',
'Average days to collect payment from enterprise B2B clients. Formula: (Accounts receivable / Total credit sales) × Days in period. Target: <30 days DSO. Current: 42 days. Enterprise payment terms: Net 30 standard, Net 60 for large clients. Collection efficiency: 85% on-time (within terms), 12% late (<60 days), 3% very late (>60 days). Impact on cash flow: 12-day reduction in DSO frees ~$6M working capital. Collection process: Automated reminders at day 20, account manager outreach day 35, collections team day 45. Bad debt rate: 0.5% of AR.',
'ACTIVE', 2,
'{"current_value": 42, "target_value": 30, "unit": "days", "formula": "(AR / Credit Sales) × Days", "tracking_frequency": "Monthly", "data_source": "Accounts Receivable", "payment_terms": "Net 30 (standard), Net 60 (large)", "collection_efficiency": {"on_time": 85, "late": 12, "very_late": 3}, "working_capital_impact": 6000000, "bad_debt_rate": 0.5, "owner": "CFO"}'::jsonb,
ARRAY['kpi', 'financial', 'ar', 'collections', 'cash-flow'],
NOW(), NOW()),

-- Data & Analytics Metrics
('e1e1f1a1-0002-4002-a002-000000000059', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'Data Pipeline Latency',
'Time delay between event occurrence and data availability for analysis. Formula: Event processing timestamp - Event occurrence timestamp. Target: <5 minute latency for real-time data. Current: 12 minutes. Data categories: Critical operational (target <1 min, actual 8 min), Analytics (target <5 min, actual 12 min), Reporting (target <30 min, actual 45 min). Use cases requiring real-time data: Surge pricing, Fraud detection, Matching optimization, Operational dashboards. Pipeline: Event ingestion → Kafka → Stream processing → Data warehouse. Tracking: Pipeline monitoring with latency SLAs.',
'ACTIVE', 2,
'{"current_value": 12, "target_value": 5, "unit": "minutes", "formula": "Processing Timestamp - Event Timestamp", "tracking_frequency": "Real-time", "data_source": "Data Pipeline Monitoring", "by_category": {"operational": {"target": 1, "actual": 8}, "analytics": {"target": 5, "actual": 12}, "reporting": {"target": 30, "actual": 45}}, "critical_uses": ["Surge pricing", "Fraud detection", "Matching"], "owner": "VP Data"}'::jsonb,
ARRAY['kpi', 'data', 'latency', 'infrastructure', 'analytics'],
NOW(), NOW()),

('e1e1f1a1-0002-4002-a002-000000000060', 'cd6d847c-0f2e-4ccc-bf1a-c96b08c97d4e', 'kpi',
'ML Model Prediction Accuracy',
'Accuracy of machine learning models in production. Formula: Varies by model type. Target: >90% for critical models. Current models: Demand prediction (87% accuracy target 90%), Fraud detection (92% accuracy target 95%), ETA prediction (81% accuracy target 85%), Driver churn prediction (76% accuracy target 80%). Model performance degradation: 2-5% accuracy drop per quarter without retraining. Retraining frequency: Weekly for critical models, monthly for others. Tracking: Continuous model monitoring, A/B testing of model versions, automated retraining pipelines.',
'ACTIVE', 1,
'{"current_value": 84.0, "target_value": 90.0, "unit": "% average accuracy", "formula": "Model-specific metrics", "tracking_frequency": "Real-time", "data_source": "ML Platform", "by_model": {"demand_prediction": {"current": 87, "target": 90}, "fraud_detection": {"current": 92, "target": 95}, "eta_prediction": {"current": 81, "target": 85}, "churn_prediction": {"current": 76, "target": 80}}, "degradation_rate": 3.5, "retraining": "Weekly (critical), Monthly (others)", "owner": "VP Data Science"}'::jsonb,
ARRAY['kpi', 'ml', 'ai', 'accuracy', 'technology'],
NOW(), NOW());
